### ISSUE TITLE
Investigate linking image assets from WYSIWYG

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#104]
In Drupal 7, editors were able to wrap an image in a link by selecting the image and then using the Link button in the WYSIWYG toolbar. Similar functionality is currently not available or working in our Drupal 8 WYSIWYG.

Looks like there may be a few issues out on D.O. for this:
- https://www.drupal.org/project/entity_embed/issues/2511404

**Comment by cory-skeers** [comment]
Links can be added separately, then edited in the source to surround the image, but the next time the editor window is opened the link gets stripped out.

One workaround is to use a card and its link wrapper, but this limits formatting options for the image. 

https://www.drupal.org/project/entity_embed_link was started, but has since been abandoned. Looking into other options, but may need custom work to some degree.
