### ISSUE TITLE
Paragraphs: editor-friendly names for Views and Blocks bundles

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#117]
The terms "Views" and "Blocks" don't hold much if any meaning to content contributors. Are there more editor-friendly names we could use for these Paragraph bundles?

**Comment by joewhitsitt** [comment]
On D7 sites, I have saying "Content Displays" for views when talking to clients. Additionally, I have some Paragraph "view" bundles that provide an option of grid or list.

I don't have a strong preference, but because of the grid/list option, i'd be wary of "listing" for all views.

I'd vote "Custom Block" over "Box."

**Comment by richardbporter** [comment]
I think we should stick with core's naming conventions.
