### ISSUE TITLE
Bug in Sitenow - D8 for character counts in MetaDescription field.

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1238]
Also, description box in Article schema should be sized for multi-line entry and not single field.

**Comment by mjoneill** [comment]
meta-desc-char-count-SN-D8

Here's a video that explains it.

**Comment by mjoneill** [comment]
Description and video of issues available here: https://iowa-my.sharepoint.com/:v:/g/personal/mjoneill_uiowa_edu/EQxvXRSmBdFOggJG8AJ3Y7gBM-92R3okqkWE_2umEEbFbA?e=fre4Tq

**Comment by joewhitsitt** [comment]
So, i took a peek at this. There is definitely a discrepancy between the help text and what the fields actually allow. There is an issue out there that fixed this, we just haven't updated the module yet because a new stable version has not been released. https://www.drupal.org/project/metatag/issues/3106609

## Proposed Solution
Update the metatag module to the latest dev.

## Workaround

Short term workaround or general tip: For each of the content types, we have "Content Description (page), Article Summary (article), Short Biography (person)" which is called field_teaser behind the scenes. This field_teaser value which is not limited is the default short code in the meta description field and will let you enter a longer description and serve as teaser text if the homepage ever uses them for cards or something down the road. The short code could be used for the article schema field since that one won't get fixed probably due to the difference in field type (textfield versus long text)

## Additional Note

As an aside, our SEO documentation on the SiteNow website is out of date: https://sitenow.uiowa.edu/documentation/search-engine-optimization
