### ISSUE TITLE
Views paragraph embed

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#124]
Related to #125, #174 and #175 

A common use-case is to display a View within a Paragraph bundle (for example, so that an editor can put a list of People or Articles on any page).

Is there a generic way (with one Paragraph bundle) this could be handled for multiple views? Does it make sense to handle this in a generic way?

**Comment by joewhitsitt** [comment]
So as of right now, we don't have a view that is a good use case for this. There are separate events (not a view) and articles bundles and we are working on a similar but not view based Featured content #220 bundle (not a view) due to the need for arbitrary sorting (e.g. people). I could see the Articles bundle being replaced by a "do-all" view bundle but contextual filtering would have to be standardized.

**Comment by richardbporter** [comment]
No use case for this right now.
