### ISSUE TITLE
How to configure Remote Video size using Media Library with uids_base?

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1240]
# Problem

On https://uiowa.stage.drupal.uiowa.edu/ you can't set a width for an embedded YouTube video. 

# Proposed Solution

The oEmbed module on SiteNow wraps each video in a responsive wrapper.

<img width="1315" alt="Screen Shot 2020-03-23 at 10 00 53 AM" src="https://user-images.githubusercontent.com/1036433/77330747-c5373500-6ced-11ea-9732-27a153c8fef4.png">

On https://uiowa.stage.drupal.uiowa.edu/  The media library embed shows all of the responsive image options when embedding YouTube video:

<img width="1222" alt="Screen Shot 2020-03-23 at 10 02 23 AM" src="https://user-images.githubusercontent.com/1036433/77330824-df711300-6ced-11ea-9bc0-d607eeb2fb3a.png">

It adds a wrapper class based on the image style like `media--view-mode-large__ultrawide`.  

Ideally, I would like to add responsive image styles for all YouTube videos using a responsive approach within uids_base like https://getbootstrap.com/docs/4.0/utilities/embed/.

**Comment by bspeare** [comment]
Here is the css that we would need to accomplish this:
 ```
.embed-responsive {
    position: relative;
    display: block;
    width: 100%;
    padding: 0;
    overflow: hidden;
}
.embed-responsive embed, .embed-responsive iframe, .embed-responsive object, .embed-responsive video {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: 0;
}
.embed-responsive-1by1 {
  padding-bottom: 100%;
}
.embed-responsive-4by3 {
  padding-bottom: 75%;
}
.embed-responsive-16by9 {
  padding-bottom: 56.25%;
}
.embed-responsive-21by9 {
  padding-bottom: 42.85714286%;
}
 ```

**Comment by pyrello** [comment]
This is trickier than just styling with the correct CSS. On uiowa.edu we have the WYSIWYG editor configured to use the Media Library embed button, which was a new feature that was stabilized in Drupal 8.8. This introduced the ability to insert a `<drupal-media>` tag into a WYSIWYG-controlled area. One of the downsides to this approach is that there is no way (that I am aware of) to create a second Media Library embed button with different settings. Since there can be only one, it has to work for all our media types that might be added via WYSIWYG. That also means that all media inserts have to share the same settings and configuration. That is why all the view modes that were created for responsive image show up, even when you add a remote video.

The reason that it works differently on SiteNow is because they are still using Entity Embed. This inserts a `<drupal-entity>` tag into the WYSIWYG text area. These two tags are not interchangeable. 

We decided a while back to go the Media Library embed route because it would be the most forward-compatible, but it came at the expense of the flexibility of Entity Embed.

Ideally, we would probably like to have either:
* Two buttons, one for images, one for videos, each with their own options/config.
* One button that intelligently swaps out options/config based on the type of media selected.

I'm honestly not sure how to accomplish the above and retain using the `<drupal-media>` tag.

**Comment by bspeare** [comment]
@pyrello I think that we can map the `media--type-remote-video` class to the responsive image styles to apply to different video ratios.  Are you ok with proceeding with that direction?

**Comment by pyrello** [comment]
Sure. I think that is probably the thing that we can do the most immediately and without having to do a lot of research and/or writing a lot of custom code.
