### ISSUE TITLE
No feedback form built into site.

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#134]
It would be nice to have a form to collect feedback.

**Comment by briand44** [comment]
I think the thought behind this was an easy way for customers to provide feedback on the service directly through their site. So this would be some kind of form that is only available on the admin side that would email its-web. Other options could be just to have a feedback form on the sitenow site and direct customers to that.

**Comment by richardbporter** [comment]
This could be as simple as a link to a workflow form.

**Comment by richardbporter** [comment]
But we should evaluate all our methods of communication so that we are not making life harder for ourselves.

**Comment by joewhitsitt** [comment]
We talked about this a bit today. Without knowing what the current Standard form is doing or any usage stats here are my thoughts.

For this form if implemented, we need to make sure it is going to one place and even for custom sites, removing the responsibility of the project developer. If that means it goes to the helpdesk/sharewell or workflow I don't know. Ultimately, this won't solve the "i can't login" issue or prevent customers from reaching out to a developer they know directly.

If we go the helpdesk/sccm/sharewell method, we should revisit how we are using that system. pinging slack about taking on a group issue has not be very efficient/effective. We should explore how other groups are handling it and/or experimenting with assigning tasks individually.

Should we coordinate with the rest of CSI in where these are routed/picked up so that we can continue to integrate with the rest CSI where it makes sense?

In the past, Romy has stressed the importance of individual contacts for custom sites and we can keep that going as we work on sites but support after go-live should go through this method. Customers are redirected around after someone leaves, is on leave or is no longer responsible for the project. It also allows students or folks with free time to jump in and assist when they can without forwarding emails/attachments/contact-info.

We should capture as much information as we can from the start (contact info, role, website URL, screenshots, affected URL(s)).

I am not very familiar with Workflow but it sounds like a good tool for site requests. A site request is a multi-step process that may need to go backwards (more info, denied, approved) before it branches out in several directions (hostmaster, developer). Support requests are often more linear and often require a more informal approach.

**Comment by cory-skeers** [comment]
The current D7 SiteNow Standard contact form sends its email to its-hd-sm@uiowa.edu. It also creates a log in the watchdog, which could be used to find overall usage numbers--not sure if/how the email might get logged, to see what kinds of issues are being raised through it.

    watchdog('SiteNow Support', 'Support request sent by %hawkid', array('%hawkid' => $form_state['values']['hawkid']));

**Comment by richardbporter** [comment]
The SiteNow v2 site is live with a contact form for submitting feedback. Logged in users will see a link to the SiteNow site v2 docs and can find their way to the form.
