### ISSUE TITLE
Investigate organizing media library solutions.

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa#137]
Feedback stated it would be nice to organize the media library using an arbitrary user structure.

**Comment by joewhitsitt** [comment]
Postponing this for now. Ideally it would be great to have something before the sites become littered with files, but we don't have this in D7 except for a few sites using media browser plus. I think we should keep our ear to the ground though to see how others are handing core media organization.

**Comment by joewhitsitt** [comment]
Since we are moving forward with tags on all the content types, this would be a simple way to categorize media as well. #720 , #598 , #781

**Comment by joewhitsitt** [comment]
If we were to go this way, extending field_tags from #598 would be the path forward

**Comment by joewhitsitt** [comment]
Since "OneDrupal" are all using or plan to use the media types in scope, we should get input before moving forward with this.

**Comment by pyrello** [comment]
@joewhitsitt Am I understanding this issue correctly? This is about how to organize what you are shown when selecting media?

**Comment by joewhitsitt** [comment]
correct. we have tags on all content types for "internal organizing" and we thought about extending this to media to help organize it.

**Comment by pyrello** [comment]
So, this would mean adding a tags field to all the media types? And the user would be responsible for adding tags when they create the media item?

**Comment by joewhitsitt** [comment]
Yes. optional but yes.

**Comment by pyrello** [comment]
My concern with this is that people just wouldn't use it and so most media items would be "uncategorized".

**Comment by joewhitsitt** [comment]
I agree that a good number of sites won't use this functionality, but we identified the use-case for something like this back in D7. Larger sites like education implemented media browser plus to create "folders" for this type of media organization. This would offer the same organization paired with tag autocomplete filtering on the media overview and media library dialogs.

If you don't think this lightweight solution serves the 80% I could be persuaded. We could wait to hear from more sites about this. If/when this does come up more, I worry about the sustainability of managing a feature split for media types where we are trying to align more closely overall (types, responsive images, etc.).

**Comment by pyrello** [comment]
I think that this is a good idea and I don't have another idea about how to make it work, so I'm for it :)

**Comment by pyrello** [comment]
I'm wondering how this intersects with providing tools for users to provide lists of embedded videos without having to specifically curate the list every time. The use case has come up where IWP would like to have a bunch of videos posted to a page on their site that represents a series. Individually posting each video on the page is hard to manage and doesn't scale very well. It would be nice to potentially have a way for people to post lists of embedded videos similar to how we allow this for people or articles.

I think for such a thing to be workable, the tags would be necessary, as otherwise, there really wouldn't be a great way to filter out videos that are unrelated. And the way that media is used, there is almost always stuff that is going to be posted to the site that you wouldn't want to show up in a list like this.
