### ISSUE TITLE
CKEditor - Tableresize doesn't work

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#139]
The tableresize (dragging width/height of table/cells) works in the editor but is stripped with filtered_html because it uses the style attribute which is a known XSS vulnerability.

It is added in `core/assets/vendor/ckeditor/build-config.js`

I haven't found a way to disable it without touching core.

**Comment by richardbporter** [comment]
We probably should since we're implementing BS responsive tables for all tables.

https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uiowa_bootstrap/assets/js/bootstrap_table_responsive.behavior.js

~~Should we stop doing that?~~ No.

Also, the table resize plugin doesn't work in Chrome (https://www.drupal.org/project/wysiwyg/issues/2880679). It doesn't display, so kind-of a non-issue.

**Comment by richardbporter** [comment]
Ended up reverting this. Not worth forking it and tracking all that code for an issue with one browser.

**Comment by richardbporter** [comment]
Possibly related: https://www.drupal.org/project/drupal/issues/3050111
