### ISSUE TITLE
Adjust layout builder flexbox styles so that components will stack by default

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1457]
# Problem

Cards will not wrap if placed into the same layout column. 

<img width="1034" alt="Screen Shot 2020-04-22 at 4 02 37 PM" src="https://user-images.githubusercontent.com/1036433/80033810-f6548200-84b2-11ea-98c5-b3011da5653f.png">

# Proposed Solution

Adjust container settings on layout for `flex-wrap`.

**Comment by mark-bennett-uiowa** [comment]
I encountered this yesterday. I assumed we had to enter a second row in another section. Should we be able to create a 3x2 grid in one section with this update?

**Comment by bspeare** [comment]
@mark-bennett-uiowa I might need a little more info about what you are trying to do for this one.  Screenshots?

**Comment by mark-bennett-uiowa** [comment]
@bspeare yeah, sorry. I was trying to create a 3 column by 2 row grid for the front page of the Policy site. When I used one section and entered them so that they looked correct on the preview, when saved it looked exactly like that top row in your problem image above. So I took the second row of three blocks and moved them into their own new section. My screenshots would look just like yours above.

**Comment by bspeare** [comment]
@mark-bennett-uiowa The 3x2 grid style is only for use on https://uiowa.github.io/uids/components/detail/stat-block.html.  Unfortunately, it's hard to know that since it is not documented anywhere yet.

**Comment by mark-bennett-uiowa** [comment]
@bspeare sounds good, thanks bud.

**Comment by bspeare** [comment]
@mark-bennett-uiowa I would just use two sections using three columns for each layout to accomplish that.
