### ISSUE TITLE
Program/Degree/Certificate block component for departmental sites

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#1550]
My goal is to have a reusable component for adding program/degree/certificate to departmental sites under Undergraduate and Graduate Program pages. Majors, minors and certificates will be entered on these pages using this component.

<img width="1364" alt="Screen Shot 2020-05-07 at 1 42 51 PM" src="https://user-images.githubusercontent.com/3067017/81333283-f7b4ab80-9069-11ea-9088-13aa6bea148b.png">

As the above image shows, there are three sections of this component with separation borders that contain the following information:
**Top:**

- The title of the program/degree/certificate.
- A brief description of the program/degree/certificate.

**Bottom Left:**

- A heading to this section.
- An unordered list of various features of this program/degree/certificate.

**Bottom Right:**

- A heading to this section.
- A text area.
- A button with link attached.

**Comment by mark-bennett-uiowa** [comment]
This is to be a template for each program on the site. And these will only be used on the Undergraduate Programs and Graduate Programs pages. They will be stacked on top of each other in a “list” of sorts, one for each Major, one for each Minor, and one for each Certificate. So on the UG Programs page, it will be B.S. in X, B.S. in Y, B.A. in Z, Minor in X, Minor in Y, Certificate in Z, with each one having its own block like this. Its like a splash screen for degrees/certificates, that will then allow them to go to an interior major/minor/certificate specific page or directly to the General Catalog.

**Comment by pyrello** [comment]
Just adding some notes here:
@mark-bennett-uiowa and I talked about the possibility of using the Layout builder library module (https://www.drupal.org/project/layout_library), which allows admins to create multiple layout templates for a given entity/bundle. A content editor can select the layout type and it is applied to that node.

The way in which this module fails to be a good solution for the problem is that there is no way to use the selected layout to override the node's layout. If you attempt to modify the node's layout, you'll get a generated layout based on the default layout for the node type. This is documented in this issue: https://www.drupal.org/project/layout_library/issues/3082434

It looks like there is a potential patch that would create the more helpful and intuitive behavior. It, however, relies on another patch (https://www.drupal.org/project/drupal/issues/3143635)~~, which moves LB's pre-rendering to use the event system and requires modules that alter layout preparation to use an event subscriber. This directly impacts the Layout Builder Direct Add module - which I maintain - that we are using. I have also added an issue to that module's queue to update the module to be compatible with the patched version of layout builder: https://www.drupal.org/project/lb_direct_add/issues/3153511~~

So, this could be a potential solution, but we would need to make a few moves ahead of this for it to be truly useful.

**Comment by pyrello** [comment]
It turns out that the pre_render and prepare layout event do not overlap and therefore doesn't affect the LB Direct Add module after all.

**Comment by pyrello** [comment]
Just discussed this with @mark-bennett-uiowa and I was misunderstanding the use case of this a bit. These are going to be listed on a page, but they don't really need to be content. In addition to the idea of a custom block, I also suggested taking a look at the [fragments](https://www.drupal.org/project/fragments) module. I've considered this module related to #1503.

**Comment by mark-bennett-uiowa** [comment]
@pyrello What if we called this "Carat Content", "Pyramid Content", "Conical Content", or "Funnel Content" (because of the shape) rather than a Program block? Have this setup as follows:
- h2 title and text block in the top section.
- h3 title and text block in the two lower sub-sections, with available link buttons similar to banners/CTA/etc
- keep styling as described above with thin, light-colored borders between the three sections. Handle slight style changes for White/Grey/Black/Gold backgrounds similar to other blocks.

**Comment by bspeare** [comment]
I think this issue was created before the replicate functionality existed.    At this point, I think it would be more useful to improve the replicate functionality with an issue like https://github.com/uiowa/uiowa/issues/5301 or reconsider/revisit the layout template issues like https://github.com/uiowa/uiowa/issues/2378.    

We can create this design (https://user-images.githubusercontent.com/3067017/81333283-f7b4ab80-9069-11ea-9088-13aa6bea148b.png) in layout builder.  The only thing that we would need to add is the ability to add dividing lines in between sections.     

- Improve replicate functionality https://github.com/uiowa/uiowa/issues/5301 
- Create an issue to add a layout builder style for adding borders to blocks.  There are plans to add the border style to blocks like https://github.com/uiowa/uiowa/issues/5179, we could just extend that work to include individual border properties.

**Comment by bspeare** [comment]
Chatted with @mark-bennett-uiowa about this.   It sounds like it might be worth investigating layout builder section cloning and adding the ability to set borders on sections/blocks. 

- Something like https://www.drupal.org/project/layout_builder_clone
- Adding border options on text area blocks or layout builder sections

**Comment by mark-bennett-uiowa** [comment]
Tested out the latest #5855 PR that @bspeare created. With Ben's PR, the addition of the button block, and updates to the text area blocks (since this issue was created years ago), we can now create something nearly identical for the original idea of this issue. Here is a screenshot of an existing "program" block with the new updates to widgets, and the #5855 PR:
![Screen Shot 2022-10-12 at 2 51 19 PM](https://user-images.githubusercontent.com/3067017/195442800-71808c77-76cf-46d5-a852-d552db950167.png)
This alone would be able to close this issue as completed without having to create a custom layout block option for LB.

Ben and I did talk about the cloning feature, which would be nice to speed up the content creation process, but these blocks reside on two pages for each department site, and once created (and set) they rarely get changed unless a curriculum change happens. I have already created several example blocks that are created via the CLAS Template content copy, which in turn can be edited by a content manager during site creation. While the cloning feature would be fantastic to have, I am not sure that this needs to be a priority for this project.
