### ISSUE TITLE
As a content editor/webmaster, I can create different categories of people content

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1553]
- [x] Add person type selection field
- [x] Add additional fields for students and faculty
- [x] Add logic to conditionally show fields based on person type selection.

**Comment by pyrello** [comment]
> Add person type selection field

_Should this field be a static list? Or should it be a taxonomical list that can be augmented with additional types of people as the need arises?_

The problem with using a taxonomical list is that the taxonomy items would be content, we would have to provision default content for them, and then the conditional field logic would depend on content. Either the terms could be deleted or we would have to protect them from deletion somehow. At that point, it seems like it might have just been more logical to define a static list.

_Should we allow multiple selections? Are there any cases where we can imagine a person that fits into 2 categories?_

If we don't allow the selection of multiple categories, then if there is someone who should be listed in multiple categories, are we going to require they are entered twice?

On the other hand, making this a multiple selection widget, when that is almost certainly an edge case, is going to mean there is a lot of potential for misuse.

> Add additional fields for students and faculty

Additional faculty fields that have been requested for immuno.grad.uiowa.edu:
* Office Room
* Office Building
* Office Phone
* Lab Room
* Lab Building
* Lab Phone
* Department
* Faculty Type - Examples in immuno: Program, Resource
* Research Area

All of these, with the possible exception of Faculty Type, seem like they might be useful campus-wide.

Additional student fields that have been requested for immuno.grad.uiowa.edu:
* Lab Address
* Lab Phone
* __* Advisor__
* __* Program Start Date__
* Dissertation
* __* Former Student__ (Yes/No) – this indicates if they are alumni

I have highlighted the items in the student fields list that seem broadly relevant. The rest seem like they may be more specific to this site or program sites where lab work is a part of what the student is involved in.

> Add logic to conditionally show fields based on person type selection.

I'm thinking this can maybe be accomplished generically, where a field is named something like `field_person_faculty_department` and the form is altered to add #states for any fields with **`field_person_faculty`** to show when the type selection matches **`faculty`**.

**Comment by joewhitsitt** [comment]
First off, just to pass on Todd's requests from the last week or so until a better issue is created to address the service wide additions: 
- pronouns
- additional roles/[positions]

I had the same debate with myself when we were considering adding the person type back in for our feature parity sprint. I was leaning towards a taxonomy with protected defaults that align with the APR person types along with prevent deletion functionality allowing site owners to add to the list and make it their own.

The problem now with the protected defaults is we can't just target the same tids across the service as some sites have been creating tags, etc from day one. At this point, I see some kind of boolean to mark tids and figure out the best way to add and mark these for new and existing sites (default content and/or massive update hook).

I could also get behind a default select list and then a developer hook to add more similar to allowed_classes (prevents misuse, but increases developer responsibility)

Multi select is going to come up sooner than later (student worker aka student and staff), so I would just start with it.

I am resistant to dive into further discussions about what fields could be created and merged back into the default install profile. I would audit all the schema and apr fields, etc. when planning and naming your new ones.

**Comment by pyrello** [comment]
@joewhitsitt It sounds like you are saying, by deigning to discuss specific fields for the default install profile that you would prefer if I just add these to a split. I guess I'm not sure where a better place to start this discussion is. @mark-bennett-uiowa and I are going to be needing this functionality sooner rather than later, so I would prefer to get the process underway. 

Here is a comparison of the Entity Types Person type to the SiteNow person type: https://gist.github.com/pyrello/3c33f78d96574bb359a17797ed7d18fc

**Comment by pyrello** [comment]
@mark-bennett-uiowa Can you speak to whether the person type you built maps to the field names in APR?

**Comment by joewhitsitt** [comment]
Yeah, i am interested in the APR comparison because i had been previously told that was the best chance at a campus wide solution.

**Comment by mark-bennett-uiowa** [comment]
This is a discussion that may take extensive discussion outside of this board. To answer your question above @pyrello for the most part yes. However, there are some fields and field names that are slightly different in APR. The APR system changed quite a bit during the time I was working on it. If Suzanne and Denny have changed things since they have been working on it, I am unaware of changes to field names.

When I was working on the project (before, during and after Mark Ahrens was working on it), the system read the feed data and stored various levels of that data at the Drupal level. With each passing year, the amount that was stored at the Drupal level decreased. At this point now, nothing is stored at the Drupal level. But that causes its own issue. Developers cannot use stored Drupal level data to create additional lists/views/pages that utilize this APR data. This could be a major problem if we are planning on using the APR data outside of People lists/pages. Are we going to ask Denny to create us new feeds with every request we may have? Are we prepared to tell our clients they cant have something because it isnt possible with the APR setup?

At this point, Im still up in the air between APR and Drupal site solution. We've been talking to our clients about APR for years (its coming, you have to keep it updated, our Dean requires it, etc) and they are expecting it. We've been talking about how this is the solution, and this is all that it will display. If you want something above and beyond that, you can create your own portfolio/personal site. Unfortunately, we have the following issues:

- The Dean that was pushing APR left.
- There are sites that will require non-APR people to display.
- There are sites that contain mixed populations (creating them will require grouping on a field other than College/Department, i.e. Affiliation).
- The APR system is not widely accepted or appreciated.

Now, to the topic of categories of people. In CLAS, it seems that we have always created one content type that was used for all types of people. Whether we created additional fields that were left blank (if a person type didnt use it), or conditional fields that only worked if a certain person type was chosen, we had one content type for all people on the site. Between the two options, it seemed that the additional fields that were left unused was the easier option. However, there were issues with this also:

- Data input was confusing and overwhelming for some departments (see Biology - way too MANY fields).
- Every department had their own ideas of how this should look (no two solutions are the same).
- Where is the line drawn for adding fields to this? Don't we want this to resemble the APR solution?

At this point, I feel we should create one person type:

- Have it resemble the display of APR as much as possible.
- Have it contain similar fields, and ONLY add additional fields at the site level if truly necessary.
- Have it contain a non-taxonomy based person type field (editable select options that can be changed in the content type).
- Suggest that the people create their own SiteNow or thrid-party personal site if they want above and beyond.

Hope this makes sense.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Thanks for this write-up. I think this helps illuminate the dimensions of what we are up against in this challenge very nicely.

How do we go about acquiring a list of the fields in APR?

Who is currently in charge of the APR implementation in Drupal? It seems to me that, as the people tasked with developing how people records from APR are shown in a Drupal site, that we should be able to determine for ourselves whether the records are stored locally, how often they are refreshed, and how local modifications to the authoritative records are handled.

In the limited conversations that I have had with my clients in this regard, I have been hearing a repeated message that they want standardization. I think we can adopt a reasonable standard model that may not work for everyone, but will work well enough for most people. If people want more than that, they will have to justify why it is necessary, as it will incur additional development time and technical debt. I think this is a reality of our limited resources. We are not going to be able to accommodate every request. And I think most people will accept that.

**Comment by pyrello** [comment]
Related to #598
