### ISSUE TITLE
Create Articles/People functionality in layout builder using custom block types

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1789]
# Problem 

Provide a way to add view of People, Articles.

# Proposed Solution

Recreate the paragraph bundles in v2 as custom block types in v3, keeping things to a list style only for now.

Create a separate issue offer more layout/style options to display articles, people and possibly events in the future.

**Comment by pyrello** [comment]
So, it looks like both of the listed module address how to display views in the formats listed, but not how to go about making them available to attach in LB. I think just creating a view blocks will make them show up?

**Comment by joewhitsitt** [comment]
You folks don't like my programmatic view renders?!

**Comment by bspeare** [comment]
I do like them! I just added the items above to start the conversation.

**Comment by bspeare** [comment]
@GaryRidgway  It looks like these are the current views available via layout builder:

<img width="372" alt="Screen Shot 2020-07-02 at 10 01 20 AM" src="https://user-images.githubusercontent.com/1036433/86375446-4dad6600-bc4b-11ea-82bd-c6ba94b9147b.png">


- Is this the correct list of views? 
- Do we need to add more or remove any?  
- Do we want to provide style variants of these views?  
- If so, what are the style variants? Grid, Masonry, List?
- Are the views currently styled if they are placed within a layout section?
- Are there layout sections where we would want to limit the placement of these views?

**Comment by GaryRidgway** [comment]
are there any sites with layout builder that actually have people or articles for me to test with? the three I pulled don't have any.

In addition, are the "who's online" and "recent Content" views useful? I don't think i have seen people use those. recent content maybe if we can filter with it but definitely not "Who's online"

**Comment by joewhitsitt** [comment]
Restricting blocks is in https://github.com/uiowa/uiowa/issues/1889

I am not sure we want to use these same views for articles/people unless we implement them via custom block types. These were crafted with paragraphs and view pages in mind.

**Comment by pyrello** [comment]
Here are my notes from investigating this:

* I think that an approach similar to what was done with the paragraph implementation (spaghetti code) is likely our best bet at this point.
* I also looked at the [EVA](https://www.drupal.org/project/eva) module as a possible way to solve this. EVA allows you to create a view that can be attached to an entity type. However when attached view is added, it doesn't provide any options that get passed through to the block entity, so it doesn't really seem like it provides much advantage over just manually defining the block that gets attached. 
* The [Views Layout](https://www.drupal.org/project/views_layout) module provides the ability to use layouts defined in the system to display the results of a view. You can select a 3-column layout and have the view's results display one item in each column. This is potentially useful to us because we won't be able to accomplish something like that directly through the LB UI, so being able to mimic it and provide that as an option for styling will be the closest we can get, I think.
* Also just checked to see how different displays of the same view show up in the LB UI. If you create multiple displays for a view, they all show up individually as separate options to place in LB.

**Comment by bspeare** [comment]
@joewhitsitt I think rolling our own implementation (spaghetti code) sounds good to me.   I just mentioned the modules above as possible enhancements like the Views layout.   

> Also just checked to see how different displays of the same view show up in the LB UI. If you create multiple displays for a view, they all show up individually as separate options to place in LB.

@pyrello Is that a good thing?  Is there a way to expose a filter to select the displays for one view?

**Comment by joewhitsitt** [comment]
Sounds like custom block types similar to the paragraph bundles without closing the door on incorporating views layout somehow?

We used https://www.drupal.org/project/viewfield in the past for D7. I think even with this module we had custom code to get it to work the way we wanted so for D8, I just decided to do all custom code.

I worry about maintaining a list of view displays. Right now as it stands there are view displays that shouldn't be placed via layout builder. I think you can restrict by default and add individuals

I could try the custom block type method and see if I can find a way to add the views layout features as POC.

**Comment by pyrello** [comment]
@joewhitsitt I think this sounds like a good approach for now. Let's see what it turns up!

@bspeare I don't think that is a good thing. Ideally, how I think it would work is that the user would select the view block (articles view delivered through custom code attaching it to a custom block type for that purpose), then have a list of options for how it would display. Maybe this is done via LB styles. Maybe this is done via multiple view displays with the correct one be handled by the custom processing code.
