### ISSUE TITLE
Permissions for a role between webmaster and administrator?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1905]
This is to document permissions that may require an additional role for users who have a higher technical ability but are not considered developers.

- [ ] Global Metatags?
- [ ] Workbench Access
- [ ] Sitemap https://github.com/uiowa/uiowa/issues/1258

**Comment by joewhitsitt** [comment]
I am starting to see the need for "Web Admin" as I work on #2549 / #748 . Someone to manage content ownership permissions for the whole site...

**Comment by pyrello** [comment]
@joewhitsitt Is there a reason that this wouldn't just be the webmaster role?

**Comment by joewhitsitt** [comment]
@pyrello For grad (2 webmasters) in #2607, it probably doesn't have to be, but as I was tinkering, either an individual or a role needs to be assigned to the top-level editorial groups to effectively manage the groups underneath. If webmaster was that role and there was several webmasters on the site, the whole access control functionality IMO wouldn't be very useful as they could bypass restrictions.

In the future I think we want to stay away from the site ownership designation stuff in v1 standard because nobody used it and it became out of date. Another role (used sparingly, though I am not sure it will be) which has a bit more permissions than a webmaster seemed to make sense for this content access stuff. Webmaster was supposed to be used sparingly so we might just be repeating history with another role.

**Comment by richardbporter** [comment]
It might make sense to rename administrator to developer to denote that access to all features and functionality require knowledge of the application workflow and participation in our team. If that was done, administrator might fit between webmaster and developer.

**Comment by joewhitsitt** [comment]
should webmaster become "administrator" and administrator become "developer" so we can make a move away from the term webmaster?

**Comment by richardbporter** [comment]
Something else to consider, which may be better suited for a separate issue but wanted to jot down before forgetting, is whether or not the administrator role should be available for manual assignment. That is, do we want to only grant the administrator role to those in the appropriate AD group?

**Comment by briand44** [comment]
Created a separate issue for ^^. https://github.com/uiowa/uiowa/issues/4845

**Comment by pyrello** [comment]
Wondering if there is still any need for this? I don't think so from my end. I'm inclined to close it.

**Comment by briand44** [comment]
I'm in favor of closing.

**Comment by joewhitsitt** [comment]
heads up we still have https://github.com/uiowa/uiowa/issues/859 and i do like the idea of moving away from webmaster when it aligns with other work (https://github.com/uiowa/uiowa/issues/1905#issuecomment-1040446018)

**Comment by pyrello** [comment]
I'm closing this in favor of #859 and #5448. Please re-open if you think this specific issue needs to stay open.
