### ISSUE TITLE
Additional Default Content - Person, Article, Homepage content blocks

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#196]
### Problem
The students didn't know /news existed. We should highlight this functionality out of the box so people know about it.

### Proposed Solution
- [ ] Create Herky Hawk (first name, last name)
- [ ] Create article with Herky Hawk as the author. See comments below for ideal article content.
- [ ] Create an article listing on the homepage showing the one article and a more link.
- [ ] Create an events listing (grid three items, no images, no descriptions). The events filter should be on something that always has events but specific enough that it will always have appropriate events (arts?).
- [ ] Change the /about page to two real (not Latin filler) paragraghs with a blockquote (center) separating it.

There is a wiki article about creating default content. Make sure you follow it closely.

### Test
- On a new site install, make sure all the new content is added correctly.
- Proofread for spelling, bad links, etc.
- Accessibility scan (proper heading structure, alt text, no redundant links, etc.)
- We should have the rights to any photos used (UI Photoshelter) and attribution should be added similar to the homepage section background image.

**Comment by briand44** [comment]
https://wiki.uiowa.edu/display/sitenow/Creating+Default+Content

Thanks @joewhitsitt for the docs.

**Comment by joewhitsitt** [comment]
I think once we have a MVP date, we should date an article by Herky Hawk that talks generally about the launch of the service, Drupal 8 and the base of the of the SiteNow service. Maybe we can pull Nicole into this as something similar will probably be written for oneit. I don't think we should pull out specifics like content blocks but instead talk about "Page building tools", SEO, Mobile performance, accessibility, etc.

**Comment by joewhitsitt** [comment]
Without approaching the ITS communication folks, how is this for an article draft? @briand44 @richardbporter @dnkemper @GaryRidgway 

Some of this was pulled from the current SiteNow site.

```
University of Iowa's Information Technology Services (ITS) is pleased to announce their improved SiteNow service, which has been rebuilt from the ground up using the latest from the open-source community to be more stable and secure than ever before.

SiteNow still offers a lot of the same functionality that made it popular on campus while sprinkling in new features site owners have been asking for:

- An intuitive content management experience right in your browser, no additional software required.
- Highly customizable page content and layout tools.
- Secure login with user management and permissions handling.
- Content workflow and moderation.
- Form generation, allowing the collection user submitted data.
- Configurable search engine optimization (SEO).
- Integration with the University of Iowa's event promotion system.
- Hosted audio, image and document support.
- Embedded video from third-party providers.
- Mobile and cross-browser friendly responsive design.
- WCAG compliant accessibility.
- User support and documentation.
- More features/updates to come!

Need more?
The SiteNow service is now built with the ability to extend and scale to fit your needs. Need something extra or unique to your site? Contact ITS to learn more about our SiteNow custom development services.
```

**Comment by joewhitsitt** [comment]
@dnkemper was this done in the 196b branch? Ready to turn it into a PR? I can review it in a bit.

**Comment by joewhitsitt** [comment]
I took a look at this. Here are my initial thoughts:

- Homepage section background image is not displaying on a new site install.
- IMO I think articles and events should be together on the homepage.
- The more filters on the events, the less will be available to show. We want to make sure we are always getting upcoming events. Maybe just use "Arts Iowa" as the general interest.
- The issue description mentions a few things that are missing:
 - Articles more link (blocked by #171, sorry)
 - Centered blockquote

I have a higher res sitenow logo you can use for this and the new sitenow website.

I think the about page goes off-topic quickly. Here is something simple:

Established in 2012, Information Technology Services's SiteNow provides website solutions based on the Drupal open-source content management system (CMS).

> 71% of the top 100 universities use Drupal - [drupal.org](https://www.drupal.org/industries/education)

Since then, the SiteNow service has provided hosting, development and support to hundreds of sites to customers across campus. SiteNow strives to offer websites that are secure, accessible and that ultimately meet their customers' needs.

**Comment by dnkemper** [comment]
Okay, before I start again, I believe this is what you want it to say. Is that correct? @joewhitsitt 

# About Page
### Text
#### SiteNow Services
Established in 2012, Information Technology Services's SiteNow provides website solutions based on the Drupal open-source content management system (CMS).

> 71% of the top 100 universities use Drupal - drupal.org

Since then, the SiteNow service has provided hosting, development and support to hundreds of sites to customers across campus. SiteNow strives to offer websites that are secure, accessible and that ultimately meet their customers' needs.

### Blockquote
**Content:** Need help? Checkout our SiteNow documentation for guidance. If you still have questions or issues, feel free to email our SiteNow development team at: its-web@uiowa.edu for more information.

**URL:** https://docs.sitenow.uiowa.edu/
**Link text:** SiteNow Documentation

### Text
#### Search Engine Optimization (SEO)
There's more to SEO than increasing the visibility of a site on a search engine. Great SEO practice will ensure good user experiences and usability of your site. When editing a page, be sure to utilize the SEO settings located in the sidebar menu. We have also provided some SiteNow SEO information docs.

### Accordion
**Title:** SEO tips and pointers
**Body:** 	

- Make use of Google’s SEO tools

- Be unique with your content, titles, descriptions, URLs, etc.

- Add a content description to every page (dropdown provided in side menu)

- Add an article summary for every article (dropdown provided in side menu)

- Add a short biography for every person (dropdown provided in side menu)

- Add a title and alt text to every image

- Look for broken URLs in your site

- If embedding custom YouTube videos, make sure your video has a descriptive title, description and tags

# Article
### Keep Moving Forward! 
University of Iowa's Information Technology Services (ITS) is pleased to announce their improved SiteNow service, which has been rebuilt from the ground up using the latest from the open-source community to be more stable and secure than ever before. SiteNow offers much of the same functionality that made it popular on campus while sprinkling in new features site owners have been asking for.

- An intuitive content management experience right in your browser, no additional software required.

- Highly customizable page content and layout tools.

- Secure login with user management and permissions handling.

- Content workflow and moderation.

- Form generation, allowing the collection user submitted data.

- Configurable search engine optimization (SEO).

- Integration with the University of Iowa's event promotion system.

- Hosted audio, image and document support.

- Embedded video from third-party providers.

- Mobile and cross-browser friendly responsive design.

- WCAG compliant accessibility.

- User support and documentation.

- More features/updates to come!

#### Need more?
The SiteNow service is now built with the ability to extend and scale to fit your needs. Need something extra or unique to your site? Contact ITS to learn more about our SiteNow custom development services.

**Short Summary:** University of Iowa's Information Technology Services (ITS) is pleased to announce their improved SiteNow service, which has been rebuilt from the ground up using the latest from the open-source community to be more stable and secure than ever before.

# Person/Author
**First Name:** Herky
**Last Name:** the Hawk
**Position:** University of Iowa Mascot
**Phone:** (319) 335-3500
**Office:** Kinnick Stadium

**Short Bio:** Add a short biography for every person. It's important for SEO and will be referenced on the /people page. To hide a specific person, go to the 'Promotion Options' and select 'Hide on lists'.

**Bio:** Herky the Hawk has been the symbol of the University of Iowa and its intercollegiate athletics teams for more than 60 years. The Hawkeye nickname came to life in 1948 when a cartoon character, later to be named Herky the Hawk, was hatched. The creator was Richard Spencer III, an instructor of journalism at the UI. The impish hawk was an immediate hit and he acquired his name through a statewide contest staged by the UI Athletics Department. John Franklin, a Belle Plaine alumnus, was the man who suggested Herky.

Since his birth 60 years ago, Herky has symbolized intercollegiate athletics at the UI and epitomized University life in Iowa City. He even donned a military uniform during the Korean War and became the insignia of the 124th Fighting Squadron.

During the mid-1950s, Herky came to life at a football game as the Iowa mascot with a black leather head and gold felt feathers. Herky represents not only the University of Iowa, but also the entire state of Iowa...hence the state's nickname, the Hawkeye State. Herky can be seen at all home and away football games, home basketball games, home volleyball games, home wrestling meets and many other home athletics events. Herky travels when the team goes to bowl games and post season basketball tournaments and the annual wrestling national championship. He can be seen at events throughout Iowa during the year, including the Iowa State Fair, parades, grand openings, charity events, weddings and various other events.

**Comment by joewhitsitt** [comment]
I only have language edits for the about page:
About
Text
Established in 2012, Information Technology Services's SiteNow provide website solutions based on the Drupal open-source content management system (CMS).

Blockquote
71% of the top 100 universities use Drupal

URL: https://www.drupal.org/industries/education
Link text: Drupal.org
Style: Center

Text
Since then, the SiteNow service has provided hosting, development and support to hundreds of sites to customers across campus. SiteNow strives to offer websites that are secure, accessible and that ultimately meet their customers' needs.


---

I am working on #171 and hope to have that available to you shortly.

**Comment by briand44** [comment]
I would make some edits to the first sentence:

Established in 2012, ITS Custom Solutions & Integrations' SiteNow service provides...

**Comment by briand44** [comment]
A few edits in the article as well:

Refer to our group as CSI throughout rather than just ITS, same as my edit for the about page.

Form generation, allowing the collection `of` user submitted data

**Comment by joewhitsitt** [comment]
This has been merged.
