### ISSUE TITLE
'Formatter' options don't all work for the 'Title' content field block (More... block option)

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#2002]
For the ‘Title’ content field block (More… block option), the title doesn’t display with the following formats: ‘Twitter embed’, ‘Instagram embed’, ‘Imagecache External Image’ and ‘Imagecache External Responsive Image’ 

Suggestion: remove the formats since the title is a text field

**Comment by richardbporter** [comment]
I've no clue why those formatters are available or what controls them but this seems like another field that should not be available for placement. It renders as an h1 and messes up the heading structure of a page. Plus its visually hidden anyway so there is not much value for placing it.

**Comment by dnkemper** [comment]
DAMN DAMN DAMN hahahaha

**Comment by dnkemper** [comment]
Thank you for looking into this, @richardbporter

**Comment by joewhitsitt** [comment]
Pulling from a Slack conversation about this: "Unconfirmed but I think the page title block is necessary for the default template."

So we either need to confirm this or restrict what folks can do with it (restrict view modes and/or region placement)

**Comment by richardbporter** [comment]
It's necessary to place on the default template initially, which it already is. I think it could be restricted after that.

**Comment by pyrello** [comment]
This goes back to a conversation we had when we were talking about restriction on certain types of layouts. We have constructed a standard page header layout that uses the featured image field, the title block, and the breadcrumbs in a specialized layout that renders in the style of a hero (soon to be banner). Removing the ability to access these blocks shouldn't have any impact on that default layout. But if for any reason, that header needs to be removed to customize a page, then there will not be any straightforward way of restoring those fields. The idea in leaving these fields available in the first place was to provide a way for the page to be customized, then later restored to a similar state.

I'm okay with making these restrictions now because they can easily be added back in later, but I wanted to explain the thinking in them being there.
