### ISSUE TITLE
Adjust use of default margins in layout builder sections

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2059]
# Problem

Each section in layout builder is given default `margin-bottom: 3rem;` and to remove this default margin there is a layout builder style to remove it.  The default margin has been set to provide better spacing so that content editors don't create pages with components on top of each other. 

<img width="786" alt="Screen Shot 2020-08-20 at 3 32 35 PM" src="https://user-images.githubusercontent.com/1036433/90822944-d31fcf00-e2fa-11ea-9b04-4731d73ab0b0.png">

# Proposed Solution

Create a more robust solution for adding default margins based on proximity of sections with a background color.  

Do we want to:

- Remove all margins and only add them by default using adjacent selectors (https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator) if section with a background color is next to a section with a background color?
- Continue with current strategy?
- Other suggestions?

**Comment by bspeare** [comment]
**Additional plans for this issue:**

Remove `Padding` and `Margin` style options on the Section and replace it with a `Container` Dropdown. 
- Each section will have default padding added to it. 
- Default margins will be removed from sections. 

Options inside the `Container` dropdown:
- Edge to Edge container
- Extended width container
- Fixed width container (default)
- Remove default column spacing
- Add additional top spacing
- Add additional bottom spacing
- Remove default spacing
- Remove default top spacing
- Remove default bottom spacing

**Comment by pyrello** [comment]
And to clarify, this would mean removing all the existing Padding and Margin options that are not listed above.

@mark-bennett-uiowa Do you have sites with LB pages that are making use of the padding/margin options?

**Comment by mark-bennett-uiowa** [comment]
@pyrello yes, many are using the remove default margins, default padding, or adding top and bottom padding. Check any of the sites, and usually frontpage or undergraduate/graduate pages are using LB.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Probably we are going to have to update these manually. I'm not sure if we can create a set of rules for creating an update hook, since in some cases, the solution will be to add padding to the section directly before the one being operated on. Also, I think the number of sites is still small enough that it would be more straightforward to just do it manually.

Can you provide an example or two of pages where this is the case?

**Comment by mark-bennett-uiowa** [comment]
@pyrello https://globalhealthstudies.prod.drupal.uiowa.edu/undergraduate
https://globalhealthstudies.prod.drupal.uiowa.edu/graduate
https://americanstudies.prod.drupal.uiowa.edu/
https://americanstudies.prod.drupal.uiowa.edu/undergraduate
the list is quite long...

**Comment by pyrello** [comment]
So, here are the options that are being removed as part of the process and may require some adjustments:

**Padding**
* Top/bottom - vertical padding will be added by default
* Left and right - The most common use case for using these is together. We have the extended width container to provide a container that is slightly inset from the edges. If there is a need for something similar, but inset from the fixed width container, we could create a "narrow" container option to handle that.

**Margin**
Top/bottom - we're going to be using padding instead of margin. This is where the scenario comes up where it might be necessary to add padding to the preceding section when the margin is removed from the current one.

**Comment by bspeare** [comment]
Here's what the Container section looks like at this point:

<img width="745" alt="Screen Shot 2020-08-25 at 1 27 51 PM" src="https://user-images.githubusercontent.com/1036433/91213221-e48c2100-e6d6-11ea-8180-795c8be57e0b.png">

**Edge to Edge Container:** used in Hero/Banner implementations

<img width="1776" alt="Screen Shot 2020-08-25 at 1 30 02 PM" src="https://user-images.githubusercontent.com/1036433/91213452-3cc32300-e6d7-11ea-8c83-c47a407bd837.png">

**Fixed width container:** default setting for the theme - do we need this to set default content settings for install?

<img width="1718" alt="Screen Shot 2020-08-25 at 1 30 13 PM" src="https://user-images.githubusercontent.com/1036433/91213500-4e0c2f80-e6d7-11ea-9702-d0235bf9ee60.png">

**Full width container with side spacing:** used on the home page for the vertical videos. 

<img width="1775" alt="Screen Shot 2020-08-25 at 1 29 52 PM" src="https://user-images.githubusercontent.com/1036433/91213431-32088e00-e6d7-11ea-9a20-d2fa6195b47b.png">

**Extended width container:** container that extends outside of the default container

<img width="1749" alt="Screen Shot 2020-08-25 at 1 30 25 PM" src="https://user-images.githubusercontent.com/1036433/91213533-5b291e80-e6d7-11ea-8c91-973ff14fc1ea.png">

**Comment by pyrello** [comment]
@bspeare, thanks for putting this together. After seeing it, I think the "Container" group should only contain the following options:
* Edge-to-edge
* Extended width
* Full width

That way we can make it force it to be a single select group and the person can only select one option.

I'm not sure what the best label is for the remaining items, but maybe just calling it 'Padding', since that is what is being changed.

**Comment by bspeare** [comment]
@pyrello Should we call it "Spacing" since that is the terminology that we are using for the padding options?

**Comment by pyrello** [comment]
Sounds good to me.
