### ISSUE TITLE
uiowa_bootstrap CSS is massive

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#208]
With absurd selectors. This is causing performance issues and needs to be reduced.

**Comment by richardbporter** [comment]
This is due to the use of `@extend` everywhere. I'm not sure if there is a quick fix since BS partials don't ship with placeholders.

**Comment by richardbporter** [comment]
Probably the best course of action is to implement the BS classes at the template/preprocess level and then remove the `@extend`s and avoid using them going forward.

**Comment by richardbporter** [comment]
Example in #225: https://github.com/uiowa/uiowa/pull/225/commits/23d3d720ffda89e005d54c131156dd089ef83467

**Comment by joewhitsitt** [comment]
If the activity by OSC and CLAS morphs this issue into a re-write with components we should look into some CSS via libraries performance: https://www.previousnext.com.au/blog/performance-improvements-drupal-8-libraries

The main key being to load the 90% used CSS as aggregated/compressed and the one off components separately. Otherwise a one-time component being loaded would throw out the entire aggregated/compressed/cached css file.

**Comment by joewhitsitt** [comment]
As of right now, it sounds like uiowa_bootstrap is not going away any time soon (HR), but majority of theming resources will be going towards a new HDS/UDS based theme and adapting uiowa_bootstrap to work with the result of #260. Will anymore work be done on optimizing/reducing size of this theme?

**Comment by richardbporter** [comment]
Not if its going away eventually.
