### ISSUE TITLE
Section background adds 1.25rem margin to Left/Right under 1300px wide

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2082]
This may already be a known issue or already posted as an issue, so I apologize for the addition if that is the case.

This can be seen on multiple sites, but the example below uses [https://interdisciplinaryprograms.prod.drupal.uiowa.edu/](https://interdisciplinaryprograms.prod.drupal.uiowa.edu/).

A single-column section with one CTA block placed within, adds a 1.25rem margin when the section is under 1300(?)px. Here is an image above 1300(?)px:
<img width="1660" alt="Screen Shot 2020-08-24 at 7 03 24 PM" src="https://user-images.githubusercontent.com/3067017/91108312-5dd73580-e63d-11ea-8e91-173b1d2fa45b.png">
Here is the same section/block when the viewing window size is reduced below 1300(?)px:
<img width="1341" alt="Screen Shot 2020-08-24 at 7 03 46 PM" src="https://user-images.githubusercontent.com/3067017/91108353-747d8c80-e63d-11ea-8e4b-581b49f573ed.png">

**Comment by bspeare** [comment]
@mark-bennett-uiowa This is happening because you have specified "Fixed width container" in the layout builder styles.  I have removed that on https://americanstudies.prod.drupal.uiowa.edu/ and the spacing disappears.   Feel free to open this back up if this is still an issue. 

Before:

<img width="1295" alt="Screen Shot 2020-08-25 at 8 26 11 AM" src="https://user-images.githubusercontent.com/1036433/91179947-cdd0d480-e6ac-11ea-9833-c23d4260cc4b.png">

After:

<img width="926" alt="Screen Shot 2020-08-25 at 8 26 45 AM" src="https://user-images.githubusercontent.com/1036433/91180067-f789fb80-e6ac-11ea-8262-369378e3850f.png">

**Comment by mark-bennett-uiowa** [comment]
@bspeare thanks bud. I need to remember that by default those sections have a fixed width. I was putting that in to ensure they didnt try to stretch to full width. I have updated the remaining sites.
