### ISSUE TITLE
Views table style scoping issue

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2118]
## Problem

The recent PR #2093 introduced table styles for all views. This is causing a border style issue with the People manual sort table `draggableviews-table-people-page-people-table`

Example: https://gis.sites.uiowa.edu/people

## Proposed Solution

- Create a :not(.draggableviews-table-people-page-people-table) exception on that style since I believe that is the only table affected.

**Comment by GaryRidgway** [comment]
So, i think this is a little more complicated than originally stated. because of the  way that styles are being applied i think it would be more effective if there was an option per table view for something like `no-styles` and that would not apply the `is-striped` styles on the table. this would be a more everlasting solution but it will almost definitively change the point value of the card.

**Comment by joewhitsitt** [comment]
we realized that we could just target draggableviews view tables for now instead of create a custom class, adding that to default view config, writing an update hook to add it to existing (ignored config), and then logic to see if class exists

so still a round about 1-2 pointer
