### ISSUE TITLE
[Admissions Redesign - Core] Scholarships

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#2214]
Scholarship content type and display (search?)

**Comment by briand44** [comment]
Desired Fields:

- Title
- Short Description - Body/Summary
- Value - value of the scholarship - probably text area.
- Minimum Requirements - minimum requirements that need to be met to qualify - probably text area
- Application - Information on how to apply or if no application is needed - probably text area
- Deadline - Information regarding deadlines - probably text area
- Renewal - Information on renewal - probably text area
- Contact - currently link field with required title - used mainly for mailto links.
- Scholarship Type - need more info here. (first Year, transfer, International)
- Resident/Non-Resident - need more info here.

**Comment by scottfi** [comment]
- Title (title)
- Short Description - (Body/Summary)
- Value - value of the scholarship - (text area short - will list an amount of money $X,000 - X,000 or $X,000)
- Minimum Requirements - minimum requirements that need to be met to qualify - (text area)
- Application - Information on how to apply or if no application is needed - (text area)
- Deadline - Information regarding deadlines - (text area)
- Renewal - Information on renewal - (text area)
- Contact - (email address, so it can be a mailto: link)
- Scholarship Type - First-year, Transfer, International. (see below)
- Resident/Non-Resident - If First-year or Transfer than need to choose if resident of Non-resident when creating a scholarship (see below)

The text area fields should have WYSIWYG to allow for paragraphs, bold, etc.

The last two are for sorting the types of scholarships.
Scholarship Type is mainly used for the student type and that could be: First-year, Transfer, International
Resident/Non-resident is mainly used for first-year students, but determines whether a scholarship is for resident or nonresident students (we have different scholarships for people from Iowa or outside of Iowa).

We display different scholarships for the student type, but also different scholarships for first-year resident or nonresident students. You can see how this is used here: https://admissions.uiowa.edu/finances/scholarships
There is essentially a simple decision tree to get you to the right scholarship listings. What student type? If you select first-year, are you resident or nonresident?

**Comment by briand44** [comment]
On the scholarships page, at a minimum, they need the ability to have an image and editable text on that page. Their preference would be after choosing a student type and resident/non-resident (if First-year) that it takes you to a separate page to display the results. The reason for this is to provide somewhat of a barrier for a specific student type to view scholarships available for other student types. 

As far as design they are ok with us taking an initial stab at it and providing feedback once we have something for them to react to. When displaying scholarships of a specific type they would prefer to be able to get all information about a specific scholarship without having to go to separate pages for each.

**Comment by joewhitsitt** [comment]
I forgot that I am out today. Pushing up what I have.

I am unsure though on now best to proceed with the [jump menu](https://admissions.uiowa.edu/finances/scholarships) and the [view displays](https://admissions.uiowa.edu/finances/scholarships-first-year-students). Thought about a text area block full HTML (content) that has a one-off jump form to user created pages.

The existing site has separate view pages for each argument combination and I want to avoid that. I believe this was done to provide different page content per argument. Admissions won't have direct access to views ui this time around.

I tried setting up a contextual filter view block with "allow settings" that would show on the block config. That functionality is not in core yet beyond number of items and required a patch and two ctools contrib sub modules to be enabled. In the end the UX on the block config was very rough around the edges.

Leaning towards a custom block type that provides drop downs for the two fields and will allow webmasters to place them wherever. Programmatic view (noodle) similar to how we do articles/people. This would have the best UX would be the most custom.

Otherwise, leaning towards a generic custom block plugin that limits allowed views/displays via admin interface but allows a webmaster to select the view/display and provide arguments based on how the view accepts them. Help text for arguments can change based on how the view is setup. In this case I think it would be "type/resident."

Looking for other thoughts on how this should be built. @uiowa/developer

**Comment by cory-skeers** [comment]
> Leaning towards a custom block type that provides drop downs for the two fields and will allow webmasters to place them wherever. Programmatic view (noodle) similar to how we do articles/people. This would have the best UX would be the most custom.

This would be my gut-check choice, being the most easily flexible within the world of admissions.

> Otherwise, leaning towards a generic custom block plugin that limits allowed views/displays via admin interface but allows a webmaster to select the view/display and provide arguments based on how the view accepts them. Help text for arguments can change based on how the view is setup. In this case I think it would be "type/resident."

In trying to think more through the lens of possible Drupal contributions, I'm intrigued by taking a more abstract plugin approach to giving a role-restrictable way to embed a pre-filtered view via inline block (if I understood your description accurately).

**Comment by bspeare** [comment]
How important is having this in a select list or jump menu?  Do we want to create more of a designed experience with expanding cards decision tree or just have the user use a select list?

![screenshot-01](https://user-images.githubusercontent.com/1036433/95919420-277f8200-0d73-11eb-8c3b-96fb60f15a75.png)

**Comment by scottfi** [comment]
I'm OK with a more designed experience. While what we want to do is a bit anti-user, we'd like to make sure that a student is getting dropped on the right page when they make it through the selections. We're trying to prevent a student from easily selecting all student types and residency and easily jumping around comparing scholarships for different types/residency. I know it's impossible to totally prevent that, but we say "who are you?" and then drop you on a page for your stuff without an easy way back to the beginning. The drop-downs hide a bit of that currently.

How does your example work when you're a first year student and have the 2nd question of residency?

**Comment by bspeare** [comment]
My thought would be that clicking or hovering on the first year student card would reveal options to click on "From Iowa" or "Outside Iowa" within the card drawer.   But you are right, the jump menu would slow the user down more from comparing each of them.

**Comment by joewhitsitt** [comment]
So far, I am constructing it like this:
<img width="695" alt="Screen Shot 2020-10-13 at 8 47 24 PM" src="https://user-images.githubusercontent.com/4663676/96016298-349d7f00-0e0e-11eb-9487-9edfc0e6c310.png">

I think what @bspeare suggested looks nice and I wouldn't be opposed to pursuing it further beyond this issue. I am using the Forms API to construct this now, so for my own sanity and accessibility, I'd like to keep it based as a form. Thankfully there are form elements that can be used instead to potentially pull something like this off. https://api.drupal.org/api/drupal/elements/8.9.x
