### ISSUE TITLE
Determine if using person content type or separate content type for counselors.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2317]
Relates to https://github.com/uiowa/uiowa/issues/2212

**Comment by joewhitsitt** [comment]
So, I think we can move faster with the original requirements if this is a separate content type, but I think long term, this content will come back to the person content type as a person type term we target #2289. We went separate content type for IGHN because of their special fields and the fact that they had view filtering around those.

I also think we should push back on some of these fields. The questions in my mind could easily be part of the biography field or if we are talking about layout, the ability to place collections. Degrees I feel like could be captured in "Education." Hometown I could see being a field on the default person content type (optional of course).

**Comment by bspeare** [comment]
I think it does make sense to keep this within the person content type.   I agree with @joewhitsitt that a lot of the info could go in the biography field.  Perhaps we might want to develop a dynamic layout template that could have options for how to display the profile suitable for academics and counselors.

**Comment by pyrello** [comment]
Here is what I would recommend as a solution for this:

Use person content type for this:
Name - currently using title field - needs to be a text field
Job Title - currently text field
Email - email field
Degree(s) - text field
Profile Image - image with focal point

Add a content type called Counselor profile to contain these fields:
Hometown - text field
What would people be surprised to know about you? - long text - no WYSIWYG
My favorite thing about working in Admissions - long text - no WYSIWYG
Iowa City “Must Do and Must See” Locations - long text - no WYSIWYG??
What makes Iowa such a great place? - long text - no WYSIWYG
Counselor - reference field back to person record

Add this field to person content type via admissions site split:
Territory - select list of states but does have "international recruitment" as an option.

**Comment by joewhitsitt** [comment]
Another use-case was mentioned where using person for counselors would be beneficial. There will be a local event content type in the future (#2396) and Admissions needs to be able to relate a counselor to an event. If this event functionality grows in usage, it would be easier to offer that relationship piece using a content type every site already has.

**Comment by joewhitsitt** [comment]
Hearing no objections, as it relates to #2212, extending the person content type for Admissions' Counselor is the step forward. How it is implemented on the person content type should be addressed in #2212 and special consideration for #2291  should be taken.
