### ISSUE TITLE
Config split admin page not rendering select lists with Chosen

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2385]
### Problem
The config split admin UI is no longer rendering multiple select lists with Chosen. This makes it difficult to find config entities and mark them for a complete or conditional split.

### Proposed solution
Investigate why this happening now and if it is affecting other admin UI select lists. Refactor our sitenow chosen library to fix it. This may be a good time to investigate a chosen.js replacement sine it is deprecated.

**Comment by cory-skeers** [comment]
Couple things:

It looks like the specific issue is related to a change in config_split, which is set to automatically switch to a checkbox form unless drupal/chosen or drupal/select2_all is installed. This check can be overridden in a state variable `\Drupal::state()->get('config_split_use_select')`, which is annoying, because it's a state variable and not config.

Quick fix could be something to set the state variable, or even hook into the form to force it back to select instead of checkboxes. Longer fix could be looking into using drupal/select2_all, which fixes the form here, and replaces the deprecated chosen library with select2 (https://select2.org/).
