### ISSUE TITLE
Allow users to add a class or icon to the last item in their main menus

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2407]
# Problem 

There is a lack of CTA options within the current website header. 

# Proposed Solution

Allow users to add a class and/or icon to the last item in their main menu in order to create a button style for important links. 

<img width="1267" alt="Screen Shot 2020-10-21 at 12 16 17 PM" src="https://user-images.githubusercontent.com/1036433/97223934-729b8b00-179e-11eb-922d-6532c89c80ec.png">

**Comment by pyrello** [comment]
Here are some ideas that were discussed for how to handle this:
* We could enable a module such as https://www.drupal.org/project/menu_link_attributes, set the permissions so that only Admins are able to add a class. This would allow us to limit usage. This could be done pretty rapidly and allow us to meet the request for Admissions without having to figure out a more complicated solution right away.
* We could create a custom UI that allows the user to set a single link that gets appended to the main menu and adds the special class that way.
* We could create an administration UI form that allows people to make the last link in the main menu a button. This could be a wrapper around the functionality implemented in the first idea.
* Move the top links to sit at the end of the main navigation area.

**Comment by GaryRidgway** [comment]
My preference would be to option two, so that users(with high perms potentially) can perform the function if they desire and we don't have to do any work after the functionality is created. I think it would be valuable to make it as hands off as possible.

**Comment by bspeare** [comment]
Closing and using https://github.com/uiowa/uiowa/issues/2537 instead to accomplish this feature.
