### ISSUE TITLE
PHP warning on basic page manage display settings admin page

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2470]
# Problem
There is a PHP warning showing when administering display settings for basic page:
```
Warning: array_rand(): Array is empty in Drupal\options\Plugin\Field\FieldType\ListItemBase::generateSampleValue() (line 70 of core/modules/options/src/Plugin/Field/FieldType/ListItemBase.php).
```

# Steps to reproduce
 - As an admin locally, go to admin/structure/types/manage/page/display.
- See warning.

# Proposed solution
Investigate cause and fix! Didn't do much digging yet...

**Comment by mattlt** [comment]
Hello, I just received the same error. Navigated away from the page, and went back and the page loaded as expected. Not sure what happened, but thought I'd report in case it helped your investigation.

Thanks,

•• matt

**Comment by richardbporter** [comment]
Thanks. Yea it doesn't seem to cause any noticeable issues and goes away after saving like you mentioned.

**Comment by richardbporter** [comment]
Look for d.o issue related to this.

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/drupal/issues/2960714#comment-12570257

> ListItemBase (options) - Needs further investigation (probably more of an issue on fields that extend this)

**Comment by pyrello** [comment]
Also potentially related: https://www.drupal.org/project/drupal/issues/3208480

I would argue that we should close this as `wontfix` since this is an issue that only affects us as developers. Even if there was a patch for it, I'm not sure that it would be worth the time implementing it. I'd be fine waiting for the fix to make it into core and not continuing to track it in an open issue.
