### ISSUE TITLE
Migrate Areas of Study content

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#2501]
# Motivation
As part of #2365, "Migrate areas of study content from existing site into new site."

# Story

As a site owner of the Admissions site,
I want an automated migration solution to move existing Areas of Study content into the new website
so that the new content is available with minimal chance of human error that may otherwise occur during a manual migration.

# Proposed solution

Investigate a custom migration option for Areas of Study content.
If applicable, implement said migration option.

Blocked until Areas of Study content type is finalized.

**Comment by pyrello** [comment]
With the inclusion of #3229, there is a change in the logic of how the Pretty (alternate) title is being used. Previously, the alternate title was used for display on the details page and the PDF page and was always filled in. In the D9 implementation, the regular title will be used for display on the details page and the PDF and the pretty title field is optional. The implications for this migration are:
* Map Alternate title => title
* If D7 title is different than Alternate title, map title => pretty title. Otherwise, pretty title should be left blank.

**Comment by richardbporter** [comment]
Some content cannot be imported or has been deemed unnecessary by client.
- Academic Groups
  - Image field
  - Video field
- Colleges
  - Image field 
- Areas of Study
  - Some degree abbreviations could not be determined.

**Comment by joewhitsitt** [comment]
Program Types field, if approved/merged will need to be accounted for in the migration. Key mapping as they have changed.

https://github.com/uiowa/uiowa/pull/3253

**Comment by richardbporter** [comment]
> With the inclusion of #3229, there is a change in the logic of how the Pretty (alternate) title is being used. Previously, the alternate title was used for display on the details page and the PDF page and was always filled in. In the D9 implementation, the regular title will be used for display on the details page and the PDF and the pretty title field is optional. The implications for this migration are:
> 
> * Map Alternate title => title
> * If D7 title is different than Alternate title, map title => pretty title. Otherwise, pretty title should be left blank.

The D7 alt title is a multi-value field. Should we just use the first value?

**Comment by pyrello** [comment]
> The D7 alt title is a multi-value field. Should we just use the first value?

Yes

**Comment by richardbporter** [comment]
> Program Types field, if approved/merged will need to be accounted for in the migration. Key mapping as they have changed.
> 
> #3253

I added this to the PR. Thanks.
