### ISSUE TITLE
Allow person type/former filtering on People View Block

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2524]
# Story

As a webmaster, I want to be able to filter people by person type/statuses when creating my pages with paragraphs or layout block content.

# Proposed solution

- [ ] Add the person types and person types status fields to the Person list view filters and expose them.
- [ ] Need to figure out a way to generalize the solution that was put in place to improve the UX of the person types field.
- [ ] Update preprocess_paragraph in SiteNow People to account new view contextual filter options.

**Comment by mark-bennett-uiowa** [comment]
Adding this from the duplicate issue I created recently:
For instance, lets say I want to create the following structure within all CLAS sites:
<img width="464" alt="Screen Shot 2021-03-31 at 4 39 22 PM" src="https://user-images.githubusercontent.com/3067017/113214859-adb75400-923f-11eb-979c-9d9739c2dfd2.png">

I could create a site split specific to the site, and add additional person types for Professional Advisory Board, Hall of Fame, etc. Then I could create individual pages, edit the layout of the page, and create a filtered block of People based on these Person Types.

As of right now, we enter a Person, and then check the checkbox based on their type. However, if we want to create a filtered list of Faculty, I also have to add a 'Faculty' relationship to each person. I see Relationships as additional filtering beyond Person Types. For instance, Biology has iBio Graduate Students and Genomics Graduate Students. Both types could be checked as Students, but then iBio Graduate Students could have an 'iBio' relationship and Genomics Graduate Students could have a 'Genomics' relationship. Then I could create a list of all Students, a list of iBio students, and a list of Genomics students.

**Comment by joewhitsitt** [comment]
Ideally we would make progress with https://github.com/uiowa/uiowa/pull/2702 before adding additional functionality to the existing solution

**Comment by pyrello** [comment]
The work in #2702 should allow doing this via the view directly, at least for V3. I think that it will still need to be added to V2 using the steps outlined above.

- Enable the Person block list view.
- Add the person types and person types status fields to the view filters and expose them.
- Need to figure out a way to generalize the solution that was put in place to improve the UX of the person types field.
- Update hook to replace existing people blocks with the views-based alternative.

**Comment by pyrello** [comment]
This is now blocked by #3489.

**Comment by pyrello** [comment]
This is no longer blocked. Also changed the scope of this to not include adding it to V2, since we are no longer adding new features there and doing so would add additional time and complication.

**Comment by pyrello** [comment]
I'm starting to work on this.

**Comment by pyrello** [comment]
Started working on this in #3587 and ran into a snag with generalizing the approach that was taken to change the filter widget in #3269. The problem is that the views exposed form alter doesn't trigger with the block form. Also, in `HOOK_form_alter` the form ID is too general and there is nothing to allow us to limit the modifications we would make to just the view block. I started down the path of using a custom process function on the add/update block form to allow us to get access to the specific block plugin ID, but we don't seem to have access to the form in that function, so there is no way to pass it to the new helper function.

I'm a bit stumped as to how to continue. @cory-skeers I know you have worked with the process functions a bit before, so if you have any insight that would be appreciated. We may have to revisit the solution from #3269 and see if there is something that affects the render of the filter widget in every case.
