### ISSUE TITLE
As a content editor, I can set Zilla headings and Zilla underline styles in the WYSIWYG toolbar rather than in HTML source

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2532]
# Story

As a content editor, I can set Zilla headings and Zilla underline styles in the WYSIWYG toolbar rather than in HTML source 

Previous solution:

<details>
As a content editor, I can adjust font styling in WYSIWYG toolbar rather than in HTML source.

Could we get font styles or options to set font to the following options:

- [ ] Smaller text
- [ ] Headline text in Serif font
- [ ] Headline text in Serif font with underline
- [x] uids-component--light-intro
- [x] uids-component--bold-intro
- [ ] more?

Currently we have to edit the HTML in source to get the headline font to change.

<img width="848" alt="Screen Shot 2020-11-12 at 4 48 49 PM" src="https://user-images.githubusercontent.com/3067017/99005878-35a5f700-2507-11eb-878b-802c17b111d4.png">
</details>

# Proposed solution

- Add styling options to WYSIWYG for the Zilla serif and Zilla serif underline heading styles. 
- https://github.com/uiowa/uiowa/issues/2532#issuecomment-1040864388

**Comment by joewhitsitt** [comment]
This is what I kind of demonstrated in the tables discussion today, using the styles dropdown for block and inline elements instead of the paragraph dropdown. I think the paragraph dropdown would be used for `<small>` but everything else in the original issue description would be a style class applied based on element selected.

Unfortunately, the styles dropdown doesn't append to but removes/replace existing classes on the element so we might have to generate popular combinations for some of these.

- [ ] Compile a list and combinations of classes that can be applied to inline and block html elements that are available in filtered_html
  - [ ] Table classes #2748, uiowa/uids#468 (comment)
  - [ ] Heading classes
  - [x] Linkit Buttons replacement?
- [ ] Per #2195, add these items to the filtered_html text format configuration for use similar to alert styles.
- [x] Deprecate .lead and replace with a uids_base replacement and scope it to inline elements instead of div.

This could replace the need for https://github.com/uiowa/uiowa/issues/2047

**Comment by bspeare** [comment]
I think adding `Zilla` to the WYSIWYG as an alternative to `Roboto` makes sense.   I think I would still want to keep the remaining headline styles limited to use in the Headline field: https://github.com/uiowa/uiowa/issues/2960.  This question and https://github.com/uiowa/uiowa/issues/2107 might be good to revisit at the next design meeting.

**Comment by bspeare** [comment]
My impression on this is that brand would like to keep Zilla out of the WYSIWYG as an option for heading tags for maintaining consistency and hierarchy.   Flipping back and forth between the thick serif Zilla and Roboto within a content area would definitely create visual hierarchy issues.   Of course, you can create those issues by using multiple text areas and headline fields, but that is a lot of extra work.   My suggestion is that if we dislike the Roboto heading styles, what if we adjusted the Roboto styles to a weight/style that is more appealing or offered additional Roboto styles in the WYSIWYG?  There are a lot of options: https://fonts.google.com/specimen/Roboto#standard-styles.

**Comment by mark-bennett-uiowa** [comment]
Thats fine, then brand needs to remove Zilla as an option for anything below the h1 level. By giving us the option, it gave all the editors/departments/units the option, and at least I tried to standardize the headings for all CLAS departments/units. At this point, I cant monitor each and every editor to make sure they are keeping the Zilla standard heading styling, let alone knowledgable enough to edit the HTML to add the classes.

I remember bringing this up in 2020, at a brand meeting, and nothing was ever done about it.

If brand wants to remove Zilla as an option, can we consider making the default as Bold for Roboto sans-serif headings? I'm not thrilled with this necessarily either, and it's something about the standard Roboto unboldened headings that irks me.
![headings](https://user-images.githubusercontent.com/3067017/150431447-5ea37b03-3324-4725-8843-1216c77222b5.jpg)

**Comment by bspeare** [comment]
@mark-bennett-uiowa Yes, I think removing Zilla from anything below `<h1>` makes sense.   And yes, we should revisit the weights of Roboto to make them look better like in your screenshot.

**Comment by bspeare** [comment]
After talking with the brand team about this, I think we should move forward with offering Zilla as a heading style for the WYSIWYG.   There are mixins for most of the headline styles (https://github.com/uiowa/uids/blob/main/src/components/headline/_headline-mixins.scss) so we shouldn't be limited by trying to apply the multiple `headline headline--serif` classes at once if that is a blocker for integrating these headings into the WYSIWYG.
