### ISSUE TITLE
Create college config entities

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#2551]
# Story

As a site visitor, I want to see information on colleges which are related to the content I'm viewing, so that I can understand the full context of the content, as well as choose to learn more about the college from their webpages.

As a site owner I want a field list from which to select individual colleges so that I can easily connect content to relevant colleges.

As a SiteNow administrator, I want to manage a list of colleges in a shareable manner, so that I can maintain and update the list for all SiteNow users with minimal service disruption.

# Proposed solution

Create a custom config entity for colleges with a label, description, and homepage (link). Content fields can reference these entities, and they can be managed through config and shared across sites.

Work was originally started on this in #2465. Can be pulled out of there and into its own home, and then referenced by the area of study content type in that PR.

**Comment by cory-skeers** [comment]
@pyrello I'm wondering about namespacing for this, and where a good home for it could be.

The current setup in the AoS split has it in a `sitenow_area_of_study` module, with the entities as `sitenow_area_of_study.college.*`. Wondering if it should be something like `sitenow_colleges` and `sitenow_colleges.college.*`, or if there's a good middle-ground to move into an existing module.

**Comment by joewhitsitt** [comment]
Can this be expanded to "Colleges and Units"? I see a great use for capturing these beyond AoS as defined by the provost https://provost.uiowa.edu/organization

I see this being available to all sites to tap into some day (person content type for one) so a separate module makes sense to me and makes it easier to install the entity in the first place (oops with person types). I'd also like to leave the door open and have this data be managed by someone else in the future (we maintain the config entity foundation, entities are imported from somewhere else)

uiowa_units?


One thing to think about, just in case. What happens when a unit goes away. Shudder to think, but something to think about. What happens to data using the now missing unit.

**Comment by cory-skeers** [comment]
Interesting--I think including units along with colleges makes a lot of sense. We could include a marker to differentiate colleges from units.

The quick(ish) and dirty solution to a unit going away can be to it to disabled, and make sure any field displays, views, etc are conditioned on the entity being enabled. Past that, more thorough cleanup = update hook?

**Comment by pyrello** [comment]
I don't have a problem with expanding this, although so far, I haven't seen any fields that referenced the non-collegiate units. Maybe we can figure out a way to exclude them from the field per site or per feature?

I'm not sure about `uiowa_units`. Its not a bad place to put them, but I'm wondering if we need a better overall warehouse of available stuff not broken out into individual pieces. I don't have a strong feeling about it, so I'm definitely persuadable to using individual modules to house all the specific discrete pieces of configuration we're creating. Putting the person types in with SiteNow People made sense, since it was relevant to that.

Some question applies to the person types. I think it is our responsibility after we introduce them that we have to write an update hook if one ever is removed. I'm not sure what that looks like in terms of existing field values.

**Comment by cory-skeers** [comment]
One option could be one step back for a `uiowa_entities`, starting with `uiowa_entities.college.*` and `uiowa_entities.academic_unit.*` as starters, based on the provost organization.

A plus for separate modules would be the option to turn on some, but not all, based on split--but not sure that that's desirable or necessary, as on any site either a) they're available and needed for a field or b) they're "available" but not referenced by any field, and so not accessible by site owners. For that, I'd lean toward a single module for any cases like this of config entities that may be used by more than one type of content (as opposed to Person Types, which are more specific in their use).

**Comment by cory-skeers** [comment]
@pyrello @joewhitsitt Have a POC PR in #2562 that goes with a `uiowa_entities` module with separate `academic unit` and `college` entities (as well as base entities for each). They both share the same `unit` entity base.
