### ISSUE TITLE
Add option for former students or faculty

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2582]
# Story

As a site owner I want to be able to indicate that a person is no longer in the group (person type) that they formerly occupied (e.g. past faculty, former students) so that I can distinguish between them in lists.

## Examples of how this would be used
* https://www.amcs.uiowa.edu/students/all-graduates
* https://toxicology.grad.uiowa.edu/program-alumni
* https://toxicology.grad.uiowa.edu/faculty/past

# Proposed solution

- [x] Add a boolean "Allow status" property to person type config entity.
- [x] Add an allowed values function that gets all person types with allow status set and prepends "Former " to the beginning of them.
- [x] Add new person type statuses text list field to the person content type which references the allowed values function. (This happens after the field config is exported).
- [x] Write an update hook targeting any site with the `person_extended` split and for any people content items where the student person type is selected and the "Current student" flag is not set, set the "Former student" person type status.
- [ ] BONUS: Add `#states` behavior to type status checkboxes to only show when their corresponding person type option is checked.

Please check with Sean if any of these items are unclear.

**Comment by joewhitsitt** [comment]
Could this be an allowed options type deal (multiple checkboxes) where the options are populated by the allowed person types? Trying to think of the most flexible route as the number of person types fluctuates.

**Comment by pyrello** [comment]
To make sure I understand, would it be something like, if they select a person type, then there is a corresponding checkbox to mark whether they are a "former {person type}"?

**Comment by joewhitsitt** [comment]
It wouldn't be that smart I don't think. The allowed options function for the field would just check which person types are enabled for the site and create former/current options based on those. All would be visible and available unless you want to take it a step further and create some visibility states based on it. I don't know how to show hide individual options based on the selection of another field. For some we could specify a custom label option if the need is there.

On the render side a site or default could check for the person type to be selected before displaying the former/current selections as well.

**Comment by GaryRidgway** [comment]
To reduce fields so we don't have to create a "Current/Former" option for each Person type, would it be easier to just have select boxes instead of checkboxes? like so?

![fc4a2b490381ae2d544ab14fe2225358](https://user-images.githubusercontent.com/23122142/108871885-3991ec80-75bf-11eb-8a66-aa5566e5e56c.gif)

That was you can cut down on the amount of chaff and it is clear to the user what person type they are making? Unless people are selecting multiple types, then this may not work as well.

**Comment by joewhitsitt** [comment]
so i added "current", but i am not sure that is the scope and might just be implied by selecting a person type. former is really what we are after here, but I could see other options besides former. i do think there are use-cases where multiple person types are selected (staff/student). this suggestion still might work though as a combination field and that maps the combined value to the allowed options to clean up the form.

**Comment by pyrello** [comment]
I agree that "current" would be implied unless another option is chosen, but that adding it to the field as the default would make sense. I'm not sure how you would adjust the above UI example to allow for multiple entries, which is, for better or worse, where we are currently at with person types.

**Comment by joewhitsitt** [comment]
If we wanted to do it like the above example, I imagine a multi-value compound field type similar to the headline field. Otherwise, we could start off small if we just wanted to capture former of a few default person types. I don't think you can be a former emeritus?

**Comment by pyrello** [comment]
We are going to discuss this during the next backlog grooming.

**Comment by joewhitsitt** [comment]
Talked to @pyrello about this a bit after planning. Here is, I hope, a better description of what I am thinking as a solution:

- [ ] Person type configuration entity gets a new boolean "Allow status"
- [ ] Person content type gets a new list checkboxes allowed values function field, "Person status"

- The default allowed values function checks which person types are available and if they have the "allowed status" boolean checked. The default functionality can provide "former" options for each person type but uncheck "allow status" on the obvious emeritus person type. Of the "allowed status" person types (including custom site defined person types), former options will be provided by default.
- I am moving away from just scoping this to "former" because I see other use-cases coming up in the future and that this field should be flexible enough to handle those. With that, there is an alter opportunity (similar to v2 paragraphs styles) for a site to add/edit/remove options. This way a site could change the default option label to be better suited for their needs (e.g. Past fellow, 2016 Committee Chair, Inactive member, President-elect, Recent graduate, Incoming student), or provide replacements.
- These options can then be used by sites to provide additional fields, filter views, etc.
- These options would all display at once based on the available person types and their "allow status" value, but we could look into show and hide possibilities if need be.
- Logic based on this data would have to go the extra step of ensure the right combination of type/status are selected.
- Platform level data targeting will be limited to the default options' machine names with the understanding that developers won't repurpose those but create their own.

**Comment by pyrello** [comment]
I updated the original post to provide some examples of what this functionality would be used for.

**Comment by joewhitsitt** [comment]
Example of the configuration entity lookup might be academic units field widget

**Comment by richardbporter** [comment]
Nice to have: update hook to take care of sites that are already using person_extended current student field to move those values into this.

**Comment by pyrello** [comment]
@joewhitsitt I started working on this in #3337. I added a property to the person type class and a corresponding field to the person type form. However, when I save the form, the value doesn't save. I'm not seeing anything in the current setup that would seem to indicate that special handling is necessary for this new property. Any ideas?

**Comment by joewhitsitt** [comment]
Hmm. Does the schema file need to be updated and imported?

**Comment by pyrello** [comment]
Nevermind... I think I figured it out.

**Comment by pyrello** [comment]
I don't think the `#states` behavior can be achieved with the field widgets as structured. While `#states` can be applied to individual `checkbox` fields, there is no way to apply different `#states` to each checkbox in a `checkboxes` field. My best way of how to achieve a better UI is to hide the existing fields and build a set of pseudo fields that behave as desired. Then populate the values correctly in a validate function.

**Comment by joewhitsitt** [comment]
i can't give this the attention it deserves at the moment but what about trying an ajax callback or show/hide via css?
