### ISSUE TITLE
Build out migration system to allow for generalized custom migrations

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2654]
# Motivation
As we ramp up custom development, we are going to have an increasing need to be able to migrate different types of content beyond the standard content types provided by SiteNow V2/3 or different source implementations from D7 sites that are not standard SiteNow V1.

# Proposed solution
* Augment or add new source plugins that allow for many or most custom migrations to be defined via `migrate_plus` config yaml files. 
* Determine the process by which new migrations are added and enabled for a site (e.g. config split per site, or custom module, or both)

**Comment by cory-skeers** [comment]
Gathering the state of things now:

- There is the "base" sitenow_migrate module, which contains the standard SiteNow V1->V3 migration, as well as shared functionality which may be built upon for custom migrations
  - The `Files.php` is more or less usable for _all_ migrations. Can be improved, but unlikely to need any changes or custom functionality for any individual migration
  - The `ProcessMediaTrait.php` contains several methods for replacing inline file embeds from D7 with their D8 counterpart. These are agnostic of how inline embeds worked in the D7 site, and require only that a regex can be written that captures the embed (and the referenced file id) and callback to these methods to construct the new embed. Shared destination platform makes this straightforward.
   - The `BaseNodeSource.php` serves as a base for any node migration. Provides basic query, as well as a few supplementary methods. Basic pages, articles, and people for SiteNow are completed. Others, like Engineering articles, may be able to use these with minor modifications.

Basic process of adding a new migration, given the current state:
 - Each migration needs a migration YML, which defines the source plugin to use, and the mapping from source to destination. Examples of these can be found in `config/features/sitenow_migrate` and `config/features/grad_migrate`
 - If the existing file, page, article, or people source files cannot be used, a new source plugin can be added to a new module (e.g. `grad_migrate`) or `sitenow_migrate` // to be determined
   - Primary need for this is if the base `query()` is not adequate. The fields from this source plugin feed the YAML definition. A `prepareRow()` can also be included, if needed to process data.
   - If there is a 1-to-1 migration path from source to destination, _all_ that is needed to be added is the field to the source `query()` and its destination mapping/plugin definition in the migration YAML. (e.g. Articles which have additional checkboxes and/or other simple fields)
 - If needed, add the the migration ids to the event listeners.
   - `PostRowSaveEvent` mostly needed for files in order to create media entities. For nodes, `onPostRowSave()` can be updated to set the proper body format.
   - `MigratePreRollbackEvent` only needed for files, currently, in order to delete the separate media entities in addition to rolling back the imported files.
   - `MigratePostImportEvent` Can be used for any node-type migration. Uses the migration mapping in order to (try to) update internal links to their new locations. Buggy, and could use some work. Its methods also need to be abstracted in order to work with new migrations.
 - Database and file source info is handled through `sitenow_migrate` module, or can be hardcoded into a new `migration_group` YAML (e.g. `grad_migrate` feature)

**Comment by cory-skeers** [comment]
> * Augment or add new source plugins that allow for many or most custom migrations to be defined via `migrate_plus` config yaml files.

We're in a fairly good spot with this now. File migrate is pretty universal, and generic node migrate is in place along with several generalized utility methods. A general taxonomy migrate may be necessary, but there is not a current call for one. Should be a short lift if/when that is, as it can be a 1-to-1 move.

D7 sites which use panels or similar complexity in their body construction are not currently supported. Similar to taxonomies, can cross that bridge if/when needed. `p2lb` module, which maps content from paragraphs into layout builder sections and blocks, has some functionality which could possibly be used as a starting point.

> * Determine the process by which new migrations are added and enabled for a site (e.g. config split per site, or custom module, or both)

I'm leaning toward a config split per site, and keeping everything in a single module (or two: `sitenow_migrate` and `grad_migrate` that's already put together). As migrations are created, run, and completed, source plugins can be repurposed or removed to keep it clean. The primary part that needs to be kept separate are the migration definitions, and as long as they're kept separate by config split, the same migration group YAML can be reused (and hardcode the database and file source info as an added testing ease). 

An extra option could be to reuse the same migration ids, as well, so `migrate_map_*`, `migrate_message_*` tablenames stay consistent and shared event listener functions don't require an extra addition to fire. Neither are too crucial.

**Comment by pyrello** [comment]
Here are some examples of upcoming migrations that I need:
* #2540 Thesis defense content (destination content type is in progress)
* #2334 Article content type, which is different than standard SNV1
* #2558 SROP mentors - this is an interesting case because the source is separate content type, but the destination is the Person content type using the Mentor person type.

**Comment by cory-skeers** [comment]
After additional thought, I think I'm more inclined toward continuing your initial approach with `grad_migrate`, @pyrello.

Thinking of the possibility of overlapping migration work (e.g. if we get into Admissions Areas of Study migration while working on Grad migrations), it might get confusing and lead to branch conflicts. Probably `sitenow_migrate` for all the base, common functionality, and a custom split for YAML and custom, site-specific module for the source plugins.
