### ISSUE TITLE
As a site owner, I can add/remove margins on components used in the same layout column

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2670]
# Story

As a site owner, I want add/remove margins on components used in the same layout column so that I can clearly view components with and without spacing in a page design. 

All components do not have margins that will separate them if used in the same layout column.  See https://github.com/uiowa/uiowa/issues/2554 as an example. 

# Proposed solution

## First slice (present at mid-sprint demo)
- [ ] In `global.scss` add a global rule for components like `.block` within the same layout column like:
- [ ] Add the `.block` class to all custom block components that don't have it like the `card` and `stat`.
```
// Set spacing as the default for mobile. 
.layout__region .block {
  & + .block {
    margin-bottom: 1.5rem;
    @include breakpoint(sm) {
      margin-bottom: 0;
    }
    &:last-child {
      margin-bottom: 0;
    }
  }
// Add modifier class through layout builder styles to apply the spacing above the `sm` breakpoint. 
.layout--margin .layout__region .block {
  & + .block {
    @include breakpoint(sm) {
      margin-bottom: 1.5rem;
    }
    &:last-child {
      @include breakpoint(sm) {
        margin-bottom: 0;
      }
    }
  }

```

# Second slice (decide at mid-sprint demo whether to continue this work)
- [ ] Add a layout builder style checkbox like `Remove default component spacing` to unset the global rule. 
   - Update hook to check this box for existing pages
   - New pages have it unchecked
- [ ] Remove or adjust https://github.com/uiowa/uids/blob/main/src/components/card/card.scss#L355?
- [ ] We will also want to address this issue with components creating gaps between sections: https://github.com/uiowa/uiowa/issues/5631.  

This solution will also need to be implemented for setting/unsetting margins on lists in grids when https://github.com/uiowa/uiowa/issues/2309 is built.

**Comment by bspeare** [comment]
Since all components don't have a `block` class on them that we can target, do we need to add a universal class on components so that we can target them with this adjacent sibling selector rule?

**Comment by bspeare** [comment]
I wonder if the proposed solution should be to add the "Spacing" layout builder styles to all blocks and set the default value to `-None-` and allow site owners to "Add extra top spacing" and "Add extra bottom spacing" to each layout builder block.  

<img width="623" alt="Screen Shot 2021-06-03 at 3 36 13 PM" src="https://user-images.githubusercontent.com/1036433/120708661-7a808380-c481-11eb-84e6-82d04a0f0178.png">

**Comment by pyrello** [comment]
Seems like we might want to pair this with the introduction of container queries to UIDS 4. It seems like we might be able to set rules that account for the single column situation specifically.

**Comment by pyrello** [comment]
Also, this seems like something that we would want in UIDS as part of expanded layout options.

**Comment by bspeare** [comment]
> Seems like we might want to pair this with the introduction of container queries to UIDS 4. It seems like we might be able to set rules that account for the single column situation specifically.

I think we probably would want this to apply to all components stacked in any of the columns so I'm not sure we would need container queries for this.  

To proceed, maybe we should:
- Add a `block-component` class to all blocks used in layout builder. 
- Add a rule like:

```
 .layout__region .block-component {
  & + .block-component {
    @include breakpoint(sm) {
      margin-top: 1.6rem;
    }
    &:last-child {
      @include breakpoint(sm) {
        margin-bottom: 1.6rem;
      }
    }
  }
```
- Add an option to remove the spacing through `Remove default component spacing` in the "Spacing" layout section options, which would allow specific spacing control through the margin and padding styles currently offered in the text area blocks.

**Comment by bspeare** [comment]
The Careers site is a good example for why we need this ASAP: https://careers.uiowa.edu/career-communities/data-info-tech, https://careers.uiowa.edu/career-communities/arts and https://scholardev.sites.uiowa.edu/search.  

<details>

<img width="392" alt="Screen Shot 2022-08-09 at 2 54 15 PM" src="https://user-images.githubusercontent.com/1036433/183748960-2400089d-108b-45d8-acf4-8a6d80d07f58.png">
 
<img width="809" alt="Screen Shot 2022-08-09 at 2 54 43 PM" src="https://user-images.githubusercontent.com/1036433/183749044-20d35246-6a6a-4a9d-bcfb-644a51b7f785.png">

</details>

**Comment by bspeare** [comment]
In grooming we decided that the work for this should be to first show some examples in the mid-sprint demo and then decide whether we want to implement this through a layout builder style.

**Comment by bspeare** [comment]
We will also want to address this issue with margins on components creating gaps between sections: https://github.com/uiowa/uiowa/issues/5631.

**Comment by mark-bennett-uiowa** [comment]
Pulled for testing.

**Comment by bspeare** [comment]
After working with this a bit, I would be in favor of rolling out this spacing as the default for all existing pages without an update hook. 

- All blocks are not designed to be stacked on top of each other, having this extra space implemented will help existing layouts that do have blocks stacked within the same column. 
- Stacked blocked that have used the top and margin block styles will continue to work. 
- The margins can easily be removed for each section if a customer has built a custom layout with tons of stacked blocks like in the screenshot below from https://advisingcenter.stage.drupal.uiowa.edu/program-requirements. 

<img width="1477" alt="Screen Shot 2022-09-23 at 4 38 55 PM" src="https://user-images.githubusercontent.com/1036433/192060282-53451d09-2d44-4eba-a71e-3889741025c4.png">

**Comment by mark-bennett-uiowa** [comment]
This looks good with the new margin-top addition on not-first children in a column.

- The card blocks now have .block class added from original post
- The card blocks do not have the .block-component class from Aug 1 post.
- Good spacing of 1.5rem, works for both mobile and non-mobile display:
![margins1](https://user-images.githubusercontent.com/3067017/192057872-dfc5aead-2b7b-4d3e-a1a5-5513a225e913.jpg)
- Once section "Components" setting changed to "Remove default component spacing", it properly removed margins and squashed components:
![margins2](https://user-images.githubusercontent.com/3067017/192058326-6133b89b-98d3-43af-9045-323143148dec.jpg)

### Concerns?

- Statistic blocks do not have .block class added from original post, though new style updates since original post has added padding around these blocks that avoid squash of text.
- Stacked text areas add additional space that was previously possible via Margin: top to the text area block with even more margin. The .block-margin__top of 1.05rem gets overridden by an inherited margin from somewhere. Removing the "Remove default component spacing" setting from the containing Section makes the problem even worse. This throws off the display as you can see below from [https://dwllc.uiowa.edu/news](https://dwllc.uiowa.edu/news).
![margins5](https://user-images.githubusercontent.com/3067017/192061345-f048774c-f2ca-43d0-a381-254787d0cffc.jpg)
![Screen Shot 2022-09-23 at 4 41 06 PM](https://user-images.githubusercontent.com/3067017/192062002-03115529-399d-4507-9a39-ba58b7090a92.png)
- Did we want to change the label of that section setting to something other than Components? Maybe "Components Styles", "Section Component Styles", "Component Styles Override", etc.?
- Did we want to move that setting field below Spacing and Styles since those two were for the section itself, and this field was for internal components/blocks within the section?
- Did notice that in mobile display, the components within a column retained their 1.5rem margin, but when columns stack, there is the 2rem bottom margin spacing the stacked columns. Is this a concern for anyone?
![margins3](https://user-images.githubusercontent.com/3067017/192058512-9130cfa8-3142-4537-a1d1-e2561f0a9593.jpg)

**Comment by bspeare** [comment]
After the discussion this morning, I think it might make sense to add the "Margin" style to every block and allow users to "Remove default margin" from each block instead of at the section level since we are already setting custom margins on some of our blocks already.   I've adjusted the pr https://github.com/uiowa/uiowa/pull/5725/commits/26b45ad8a5d9ee6d91577d842e8d8d19ed121295 if anyone wants to test it out. 

<img width="461" alt="Screen Shot 2022-09-27 at 2 54 24 PM" src="https://user-images.githubusercontent.com/1036433/192623041-79cc33f7-3a04-4179-a025-36069d5161bc.png">

**Comment by joewhitsitt** [comment]
Do we need to update feature and site splits that have custom blocks?

**Comment by bspeare** [comment]
@joewhitsitt I would vote to not update those since this is a minimal spacing change that occurs only if two blocks are stacked in the same layout.    

I could see us adding it and other margin properties to custom blocks like https://github.com/uiowa/uiowa/issues/5565 or https://github.com/uiowa/uiowa/issues/4917 as we revisit those blocks in the future.
