### ISSUE TITLE
Add room info to maps site gender inclusive restroom view

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2681]
* Adding room number(s) to https://maps.uiowa.edu/extras/gender-inclusive-restroom (extra column or two)
* Linking to https://trans-resources.org.uiowa.edu/gender-inclusive-restroom-map-campus

Understand that this is part of the reason we are replacing with Concept3d, so I'm not sure this is a priority.  Curious about sizing though.

**Comment by briand44** [comment]
This is done. The view was a taxonomy term view so the same view was being used for each term. I combined the fields in views since there is only one place where there is both a link and a description and the output isn't terrible. After chatting with Joe, a better approach may have been to hide table column when no results and just add the additional description column.
