### ISSUE TITLE
Investigate past event logic and options

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2739]
# Story

As a site owner I want to be able to display any past events and set exact filters on how far back my past events display (e.g. 1 year) so that I can control what past events show up on my site.

# Proposed solution

* Improve logic for getting past events by storing the timestamp when dates were last fetched and then only fetch updated events since then.
* Optionally batch fetching of events if timeouts are an issue for more than 50 events being fetched.
* Figure out how to handle deleted events.
* Add option to the events block to allow for specifying a relative date range (e.g. -1 year).

**Comment by mark-bennett-uiowa** [comment]
I would use it, activate it on all sites, as long as we could pull from Content Hub, I would want to continue avoiding local events. I will have sites that have a massive amount of events, so setting a limit to the past year would be great. So yes, paging becomes an issue. It follows with CLAS’s decision to limit historical entries to 2-3 years on news, etc. 1 year would be fine on events as long as thats the limit of Content Hub’s API.

**Comment by joewhitsitt** [comment]
This should be updated to state the additional requirements for past events. Currently there is a 1 year past range and a max of 50 events displayed.

**Comment by pyrello** [comment]
Updated the story and proposed solution to reflect what has been done and what is still being requested.

**Comment by briand44** [comment]
Obermann would like to show past events that are greater than 365 days old.

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/3809

**Comment by e-marie-w** [comment]
The Center for the Book is also interested in showing past events more than a year old.

**Comment by briand44** [comment]
Scoping this to an investigation. Out of this it would be great if we had a proposed solution on how we can eliminate the restrictions of only being able to display events within the last 365 days and at most 50.

**Comment by cory-skeers** [comment]
Some of the work that's been done in #5170 but could be improved on and taken further, other notes, etc.:

- Added an adjustable cache duration to the events loader. I think for past events in particular, it would be safe to increase this as we shouldn't expect (m)any updates to already completed events.
- Added a relative date field as a plain text field with some minor processing and a fallback to 1 year if it doesn't form a coherent date. Works pretty well, but worth discussing if the plaintext field is the best approach, or if we want a more structured approach like a combined int/select list to choose number and duration (eg "2" and "weeks") that could then be combined to a solid date
- Experimented with using a date range rather than the "past or future" approach. It's really tricky dealing with both past and upcoming events, and it became confusing and/or fragile pretty quickly. I think most use cases for this could be better accomplished by using filters and/or combinations of multiple events blocks.
- Removed the 50 items limit, along with the rel date, and the events API works pretty well with this. Each page of results needs to be called separately already, and pulling it includes info on the number of results pages that are available. This gives some built-in batching of results in the calls made, and gives some flexibility in how and when events are called
  - In the PR it just pulls all results, but I think we'd want to explore things like dynamic pulling depending on how a pager is set up
  - Need to account for "too many" results in some way. I'm assuming this would be some form of adding a pager to the results depending on settings. The current logic builds all the events individually, so there's a little extra work that would need to be done to account for this
- For a more long-term solution, I think we may want to consider storing past events in the database in some manner, or at least providing the option. I think we can do this by just storing the event IDs to avoid db bloat, but to have enough to
  - check the 'latest date fetched' info from the block in order to pull any new dates needed in a smaller call and add them to the db,
  - have some flexibility to dynamically pull events as needed more easily, knowing which ids are needed
  - without anything like this, the results themselves are batched, but each call depends on content hub querying and fetching the results, and is where the page batching starts to break down as an option, where in many cases just pulling pages with subsequent calls worked well enough

# First slices to finish up

- Update the rendering logic to add a pager or alternative option to prepare for the situation of many events
- Settle on the best editor UX to include a relative date option, and add it, but still include a limit for how far it will extend and/or limit the number of results fetched
- Decide on if it's worth increasing past events cache time, determine the new cache length, and implement

**Comment by cory-skeers** [comment]
Opened relevant follow-up issues. Closing investigation, work to continue in #5187 , #5188 , #5189 , and #5190
