### ISSUE TITLE
As a site owner, I can have more control over my tables in the WYSIWYG

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2748]
# Story

As a site owner, I can have more control over my tables in the WYSIWYG and how they display on the page. 

Related issues: #139, #995

# Proposed solution

- Add ability to apply table styles/classes via WYSIWYG
- Add Ability to set table width?
  - Add a class that will allow contents of table to determine width?
  - Explore options using layout columns to determine table width.

**Comment by joewhitsitt** [comment]
**Correction from the Admissions meeting**, it appears that Full HTML does not strip the styles attribute because it doesn't have the "Limit allowed HTML tags and correct faulty HTML" feature selected. That and table resize works. With that in mind, full html access can technically be handled with just a permission change (site by site), but I still don't think this is something we want to do for the service.

I think utility classes are the only secure way to move forward with this for the service. Which it looks like @pyrello started investigating (https://github.com/uiowa/uids/issues/468#issuecomment-790666700). How these are implemented is going to be a UX issue that can only partly be solved by https://github.com/uiowa/uiowa/issues/2195 and https://github.com/uiowa/uiowa/issues/2826.

Unfortunately, many folks paste table markup in from another source and expect it to just work and classes prevent that.

**Comment by GaryRidgway** [comment]
I am going to hijack this issue (at the permission of Ben) to be the home of these changes:

- [ ] Add visible outline to cells of table when initially created in the WYSIWYG.
- [ ] Add caption styles to put a caption above tables that can be edited
- [ ] Investigate options for using multiple style options in the Styles dropdown of the wysiwyg, or adding common configurations to it.
- [ ] Verify that all recent changes in uiowa/uids#490 work in uids_base
