### ISSUE TITLE
Investigate options for embedding a livestream on a page for Writing University

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2790]
# Motivation
The Writing University website livestreams readings from Prairie Lights Bookstore and Shambaugh House, using a server set up at UI Strategic Communications. The page has a .js script that runs the stream:
https://www.writinguniversity.org/page/writing-university-live-stream

The script runs //content.jwplatform.com/players/QrLfvuCb-7EaCFiXK.js

In D7, this script was loaded in the body of a page. We need an alternative to this approach.

**Comment by joewhitsitt** [comment]
Wondering if there is overlap with the live stream events that OSC was dealing with.

**Comment by pyrello** [comment]
I believe that the script that runs these is an OSC product.

**Comment by GaryRidgway** [comment]
After the communication today, and with some discussion afterword, I believe it may be useful to have this be a block that can be configurable by a user for JW player (Picking from a predetermined list of channels that we provide), or a configurable youtube livestream. I tested whether we could embed a youtube livestream with OEmbed and it seems to error out and not allow livestreams, so I think this might be a good alternative to that.

There is a way, [detailed in this article](https://webcam.io/support/howto-embed-youtube-live/), to grab a livestream and embed it on a page with just the Channel ID. For this we could simply craft the proper embed by allowing a user to select controls, auto play, height, width, etc, and also input a channel ID for the channel of the livestream they want to embed (I think offering some steps on how to get a channel id in the helper text would be valuable here).

This would also allow people who didn't have access to the JW player, but still want to hold digital events (Think student orgs) to simply configure a block and have access to a livestream option on their main website by linking a youtube channel. I believe this also could alleviate future confusion if people see livestreams on other websites but have no access to them because they have no channels on the JW player.

**Comment by mjoneill** [comment]
> I believe that the script that runs these is an OSC product.

The script that runs the players referenced here (http://osc.uiowa.edu/live) are copy and pasted from the JWPlayer service.  

The livestreaming service is one provided to campus via OSC.  JWPlayer is necessary in some instances for some streams, including those that might include music with copyright, etc...

**Comment by joewhitsitt** [comment]
Though we are waiting for a response from folks involved, we think we should move forward with a solution to allow webmasters to add these themselves.

**Comment by joewhitsitt** [comment]
See https://github.com/uiowa/uiowa/issues/3054
