### ISSUE TITLE
Create migration for Writing University's Blog Entry: Image content type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2792]
# Motivation

The D7 Writing University website has about 450 content items in a content type called "Blog Entry: Image." The site owner has requested to have these content items migrated via automated migration.

# Proposed solution
* Create a `writinguniversity_migrate` module and site split
* Add a migration yml file for the aforementioned content type to map it to the Article content type.
* Only need to preserve title, body, and category fields.

**Comment by cory-skeers** [comment]
@pyrello 

> * Only need to preserve title, body, and category fields.

I didn't see an existing category field--did these need a default tag added as they're migrated in?

The PR #3028 is also currently set up to import the featured image, create media, and such. Did we specifically want to drop the featured image, or was it just not a must-have?

**Comment by cory-skeers** [comment]
#3028 has been merged in, and has a sample log output for warnings (mostly the `array_flip()`, with a few like `A non-numeric value encountered PelIfd.php:611` that should be able to be safely ignored).

There is also the basis for a redirect migration that can be run following the blog entries. Hasn't been tested beyond that it runs and appears to create some redirects.

# Next steps
Check that there aren't any adjustments that need to be made to the migration, spot check some blog entries.
Confirm that featured images should be brought in, and that image captions are okay to be lost (alternative: add them as image alt text?).

## For migration
Sync fresh copies of D7 and D8 sites prior to migration
Enable migration module (`drush @org-writinguniversity.local en writinguniversity_migrate`)
Run migration (`drush @org-writinguniversity.local mim d7_writinguniversity_blog`, and possibly `drush @org-writinguniversity.local mim d7_writinguniversity_blog_redirect` for redirects)
Disable migration module (`drush @org-writinguniversity.local pmu writinguniversity_migrate`)
Sync files to production
Sync database to production

**Comment by cory-skeers** [comment]
~Source blogs that have an inline image which weren't able to be created as part of the migration. Checking to see if it was an issue for me locally, as I didn't see any reason in the few that I spot checked for why they shouldn't have been downloaded and processed.~

~`select sourceid1 from migrate_map_d7_writinguniversity_blog where destid1 in (select entity_id from node__body where body_value like "%<!--Miss%");`, or post-migration to check on local D8: `select destid1 from migrate_map_d7_writinguniversity_blog where destid1 in (select entity_id from node__body where body_value like "%<!--Miss%");`~

Edit: ^ Looks like I'd missed a hard-coded filepath in bringing over the inline image method, and that should resolve the issues.

---

Also list of source ids which had a youtube video linked in their body, and should be checked post-migration; many of them will likely be broken due to either differences in manner of embedding or with recent issues with youtube embed URLs.


| sourceid1 |
|-------|
 | 11255 |
 | 11998 |
 | 12008 |
 | 14322 |
 | 15162 |
 | 15441 |
 | 15502 |
 | 15516 |
 | 15896 |
 | 15901 |
 | 16141 |
 | 16216 |
 | 16271 |
 | 17436 |
 | 17466 |
 | 17651 |
 | 17686 |
 | 17731 |
 | 17766 |

**Comment by cory-skeers** [comment]
@pyrello I believe this is ready to go using the `writinguniversity_migrate` module that just got merged into main. The main followup will be wanting to do something with the youtube embeds above.

One last thing--it looks like there are no summaries. Right now the migration's leaving them blank (like w/grad migration), but we can change that to fill them in with truncated body text if desired. Checking my assumption was accurate there.
