### ISSUE TITLE
Switch Writing University website to use serif font by default

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2807]
# Story

As a Writing University website visitor I want to see pages using a serif font by default because that is my expectation based on my experience with other literary websites.

# Proposed solution

- [x] Add Lora fonts to UIDS.
- [x] Add a theme setting to UIDS Base to allow switching between sans serif and serif fonts defaulted to sans serif.
- [x] Limit access to theme setting to only sites matching site path of `sites/writinguniversity.org`.
- [x] Add logic to `uids_base_preprocess_html` or `uids_base_preprocess_page` to add a `text--serif` class to the `<body>` element.
- [x] Add style definitions to appropriate stylesheets to override font-family for the following elements:
     * Body field
     * Bio field?
     * Text area blocks
- [ ] Test extensively using the Writing University site and the sandbox site.

**Comment by GaryRidgway** [comment]
I've been working on taking a look at all that is currently changing with this update, and I think we may need to add more areas that change to serif when the site has it set as the Font family. These being the following:

- [x] Card Body
- [x] Articles
    - [x] Listing
    - [x] Page
- [x] People
    - [x] Listing
    - [x] Page
- [x] Events
    - [x] Listing
    - [x] Page
- [ ] Banner Text

Additionally Headlines and Headings for text areas are being converted to Lora as well because they are printed inside the `.block-inline-blockuiowa-text-area` class. Should these be returned to Zilla? Left as Lora?

Also, if we are to add lora to the description of cards, I think we may need to fix https://github.com/uiowa/uiowa/issues/3090 first, as the class is not easily mappable to the WYSIWYG text area.

**Comment by GaryRidgway** [comment]
It is also possible that we may want to add the Font Family to the WYSIWYG as well because it currently is not showing lora in it, and that could be confusing to the user?

**Comment by pyrello** [comment]
Discussed in a call that we would scope the font change to `main.content__container` because that is the element that contains the content. Any higher up the DOM and it starts to affect the site's chrome.

**Comment by GaryRidgway** [comment]
@pyrello Upon further review, i think it might be better to scope it to `body.text--serif main` because on listing pages instead of `body.text--serif main.content__container` the class structure is `body.text--serif main.page__container`. With just `body.text--serif main` it catches both. Does that seem alright?

**Comment by pyrello** [comment]
I think I'm good with that. I'm interested in hearing @bspeare's thoughts when he is able to chime in.

**Comment by bspeare** [comment]
I think going with `main` is a good idea.

**Comment by bspeare** [comment]
After taking a look at the example site that @GaryRidgway has put together, I think I would prefer to only target areas of text like https://org-writinguniversity.prod.drupal.uiowa.edu/teaching-research/first-year-seminars and https://org-writinguniversity.prod.drupal.uiowa.edu/about-us/writing-iowa#history.  As they note on https://brand.uiowa.edu/fonts, Lora is best used for "Long-form body text".
