### ISSUE TITLE
Create Thesis Defense calendar for Grad College

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2836]
# Story

As a Grad College site owner I want to display a calendar of Thesis Defenses so that people involved in the process know when they are happening.

Existing page: https://www.grad.uiowa.edu/academics/thesis-and-dissertations/calendar

# Proposed solution

Build a view using the [fullcalendar module](https://www.drupal.org/project/fullcalendar) to display a monthly calendar display thesis defense content items.

**Comment by joewhitsitt** [comment]
Default styles. Not sure if we take this opportunity to apply some branding to this so that future implementations will be on-brand by default.

<img width="1219" alt="Screen Shot 2021-01-19 at 3 45 23 PM" src="https://user-images.githubusercontent.com/4663676/105096909-60637d00-5a6d-11eb-8e41-fa782f4776e4.png">

Also, I know the current calendar also says "Upcoming" but there is nothing preventing navigation back previous months, etc.

**Comment by pyrello** [comment]
Maybe just remove the "Upcoming"?
