### ISSUE TITLE
Provide branding recommendations for admissions application

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3035]
# Story

As a developer of the Admissions Application, I would like some feedback on branding recommendations, so that we can make sure we are meeting University Brand guidelines and have a consistent feel for users coming from University websites such as uiowa.edu and admissions.prod.drupal.uiowa.edu.

# Additional Info
 
https://test.its.uiowa.edu/admissions/

I think we also would like to understand if there is a way for this application and others to pull styles/components from the UIDS so that teams are not duplicating efforts maintaining updates to the UI Brand.

# Proposed solution

**Comment by bspeare** [comment]
Closing this in favor of https://github.com/uiowa/uids/issues/486.

**Comment by bspeare** [comment]
Adding some comments and screenshots here to provide specific feedback for the application form. 

**1. Remove bulleted list and left margin from sidebar:**
<details>
<img width="277" alt="Screen Shot 2021-03-08 at 4 05 00 PM" src="https://user-images.githubusercontent.com/1036433/110387991-0bcd8e80-8028-11eb-8f3b-efb754db3e76.png"></details>

**2. Change form name to use `Zilla`:**

<details><img width="1621" alt="Screen Shot 2021-03-08 at 4 06 40 PM" src="https://user-images.githubusercontent.com/1036433/110388404-a928c280-8028-11eb-95b0-d16d5b63766c.png"></details>

**3. Align all form items to the left an remove random space indents:**

<details><img width="1053" alt="Screen Shot 2021-03-08 at 4 08 40 PM" src="https://user-images.githubusercontent.com/1036433/110388440-b8a80b80-8028-11eb-900f-9f5a4fb6a62e.png">
![Screen Shot 2021-03-08 at 4 10 31 PM](https://user-images.githubusercontent.com/1036433/110388643-ff960100-8028-11eb-8bc5-8c7104293966.png)
<img width="1047" alt="Screen Shot 2021-03-08 at 4 12 25 PM" src="https://user-images.githubusercontent.com/1036433/110388753-2f450900-8029-11eb-988d-59721c5720ec.png">
<img width="935" alt="Screen Shot 2021-03-08 at 4 14 44 PM" src="https://user-images.githubusercontent.com/1036433/110389229-d75ad200-8029-11eb-9c53-bbd7576e31ef.png"></details>

**4. Change all `letter-spacing` to `0`;**

**5. Update sidebar contact info to use inline `fas` icons:**

<details><img width="281" alt="Screen Shot 2021-03-08 at 4 16 45 PM" src="https://user-images.githubusercontent.com/1036433/110389198-cca03d00-8029-11eb-8d3e-e5a20cb7a8a7.png"></details>

**6. Update buttons to use UIDS style: https://uids.brand.uiowa.edu/components/detail/button.html.**   

**7. Division between form sections is unclear.  Consider adjusting heading sizes and label colors to create more contrast.** 

<details><img width="792" alt="Screen Shot 2021-03-08 at 4 22 18 PM" src="https://user-images.githubusercontent.com/1036433/110389706-83042200-802a-11eb-87bf-1c54fc06f624.png"></details>

**8. Add a little more padding in the tables?**

<details><img width="928" alt="Screen Shot 2021-03-08 at 4 24 13 PM" src="https://user-images.githubusercontent.com/1036433/110389891-c8285400-802a-11eb-9397-c2f1ae55692e.png">
<img width="1088" alt="Screen Shot 2021-03-08 at 4 29 39 PM" src="https://user-images.githubusercontent.com/1036433/110390384-85b34700-802b-11eb-8b1b-ce6f23abd5b6.png">
</details>

**9. Add more space between header and content?  It is very crunched.** 

<details><img width="1309" alt="Screen Shot 2021-03-08 at 4 25 04 PM" src="https://user-images.githubusercontent.com/1036433/110389975-e68e4f80-802a-11eb-8a5b-71027b850575.png"></details>

**10. Use Zilla for all h1 headings.** 

<details><img width="1309" alt="Screen Shot 2021-03-08 at 4 25 04 PM" src="https://user-images.githubusercontent.com/1036433/110389975-e68e4f80-802a-11eb-8a5b-71027b850575.png"></details>

**11. Add padding in places where borders sit on top or under text.**

<details><img width="914" alt="Screen Shot 2021-03-08 at 4 26 58 PM" src="https://user-images.githubusercontent.com/1036433/110390151-2ce3ae80-802b-11eb-9c8c-04b202744975.png"></details>

**12. Payment page changes header structure and loses sidebar shading: https://test.its.uiowa.edu/admissions/form-payment.page.** 

**13. Padding issue on https://test.its.uiowa.edu/admissions/form-validate.page.** 

**14. International and Undergraduate forms have different sidebar and heading treatment.** 

<details><img width="1520" alt="Screen Shot 2021-03-09 at 10 41 58 AM" src="https://user-images.githubusercontent.com/1036433/110506174-79c79380-80c4-11eb-9980-0fbaf47f66fd.png">
<img width="1551" alt="Screen Shot 2021-03-09 at 10 42 13 AM" src="https://user-images.githubusercontent.com/1036433/110506176-7a602a00-80c4-11eb-9a3c-09bc9056b66c.png"></details>

**15. Add some spacing between all checkboxes to make them more readable.**

<details><img width="405" alt="Screen Shot 2021-03-09 at 10 48 46 AM" src="https://user-images.githubusercontent.com/1036433/110506886-2144c600-80c5-11eb-9572-24878ffaba65.png"></details>

**16. Form label gray does not appear accessible.**

<details><img width="1075" alt="Screen Shot 2021-03-09 at 10 52 58 AM" src="https://user-images.githubusercontent.com/1036433/110507508-b34cce80-80c5-11eb-8f32-b2f393c6dc81.png"></details>

**Comment by bspeare** [comment]
Closing this for now and sharing the feedback with Adam Pyatt.

**Comment by bspeare** [comment]
Additional notes on https://test.its.uiowa.edu/admissions:

# Desktop Notes


**1. Change site name text and size to `1.3rem`.  The current text is too small.** 
<details>
<img width="649" alt="Screen Shot 2021-04-13 at 8 45 06 AM" src="https://user-images.githubusercontent.com/1036433/114562990-a0816880-9c34-11eb-8a6c-abd1bdd5b6b9.png"></details>

**2.  Change "Application Status" section to just show a badge with status information and an icon in the main form area instead of sidebar?**

<details>
<img width="863" alt="Screen Shot 2021-04-13 at 9 47 47 AM" src="https://user-images.githubusercontent.com/1036433/114572694-551f8800-9c3d-11eb-85a3-732f144789a1.png"></details>

**3.  Update Sidebar navigation to reflect the screenshot below.** 
  - Remove gray background.
  - Adjust design of navigation to appear more grouped together. 

<details>
<img width="307" alt="Screen Shot 2021-04-13 at 9 50 06 AM" src="https://user-images.githubusercontent.com/1036433/114573051-a6c81280-9c3d-11eb-8a20-041c8f93f83a.png">
</details>

**4. General font weights/headings seem off in size in various places.**

  - Update form title to   `margin-bottom: 1rem;font-size: 2.5rem;letter-spacing: 0;`
  - Remove gold background and left padding from headings and set to Zilla with a border-bottom instead of an underline property. See the screenshot below for sizing: `font-size: 1.7rem;`
  - Increase size of `Zilla` font if used in paragraph text.  The font renders much smaller than Roboto. See the screenshot below for sizing. 
  - Increase padding around entire form frame to at least `padding: 20px;`

<details>

![app](https://user-images.githubusercontent.com/1036433/114572457-1ee20880-9c3d-11eb-9c1b-cc1c5ef56383.png)

</details>

**5. Sidebar icon for email needs a space (screenshot) and Totally remove the PDF language and button. It isn’t necessary since nearly every browser includes a PDF viewer now (screenshot).**

<details>

![Unknown](https://user-images.githubusercontent.com/1036433/114090829-8daa1500-987d-11eb-8f7a-2db60269aa89.png)


</details>

**6. Application summary has an extra table column on the far right which is visible now with the shaded rows (screenshot).**

<details>

![Unknown-1](https://user-images.githubusercontent.com/1036433/114090816-8a168e00-987d-11eb-82b8-f907604ba306.png)

</details>

**7.  Reset fields button background color varies.  Would prefer the lighter gray.** 

<details>
<img width="327" alt="Screen Shot 2021-04-09 at 10 39 49 AM" src="https://user-images.githubusercontent.com/1036433/114210966-b2f25e00-9925-11eb-894d-cc755759089f.png">
<img width="154" alt="Screen Shot 2021-04-09 at 10 37 46 AM" src="https://user-images.githubusercontent.com/1036433/114210969-b4238b00-9925-11eb-9344-83f8d4019040.png">
</details>

**8.  Fonts not loading in Safari**

<details>
<img width="1234" alt="Screen Shot 2021-04-09 at 11 23 05 AM" src="https://user-images.githubusercontent.com/1036433/114211216-f8169000-9925-11eb-849b-0c4d7c56a3fd.png">
</details>

**9. Help text still not accessible, change to `#666`?**
<details>

<img width="526" alt="Screen Shot 2021-04-09 at 11 24 44 AM" src="https://user-images.githubusercontent.com/1036433/114211473-4d52a180-9926-11eb-89a6-d5df804aa747.png">
</details>

**10. Adjust design on tables like example below on https://test.its.uiowa.edu/admissions/form-validate.page. Increase cell padding everywhere to at least `.5rem`.** 

<details>
<img width="1460" alt="Screen Shot 2021-04-09 at 11 30 22 AM" src="https://user-images.githubusercontent.com/1036433/114212099-0d3fee80-9927-11eb-9ea4-d0346df4646a.png">
</details>

**11. Admissions site name needs to link to admissions website.** 

<details>
<img width="487" alt="Screen Shot 2021-04-09 at 11 33 16 AM" src="https://user-images.githubusercontent.com/1036433/114212436-74f63980-9927-11eb-8276-f8ed1e3edb24.png">
</details>



# Mobile Experience

**1. Site name needs to be black and entire bar should be clickable?**

<details>
<img width="372" alt="Screen Shot 2021-04-09 at 11 38 27 AM" src="https://user-images.githubusercontent.com/1036433/114213057-2301e380-9928-11eb-96b9-9bdd81f491ae.png">
</details>

**2.  Content overflows into header**

<details>
<img width="722" alt="Screen Shot 2021-04-09 at 10 47 55 AM" src="https://user-images.githubusercontent.com/1036433/114212730-c4d50080-9927-11eb-9e96-5a2fbe728b26.png">
</details>

**Comment by bspeare** [comment]
**1. Safari fonts for Zilla appear to not be loading.** 

<details>
<img width="1233" alt="Screen Shot 2021-05-03 at 11 41 35 AM" src="https://user-images.githubusercontent.com/1036433/116905398-89ff7900-ac04-11eb-8e01-ea40fd09d657.png">
</details>

**2.  Adjust font of majors field to match other input fields?**

<details>
<img width="1279" alt="Screen Shot 2021-05-03 at 11 38 31 AM" src="https://user-images.githubusercontent.com/1036433/116905730-fb3f2c00-ac04-11eb-9fb8-bfa093236796.png">
</details>

**3. Remove flexbox height of `100vh` for sidebar menu?**

<details>
<img width="384" alt="Screen Shot 2021-05-03 at 9 53 37 AM" src="https://user-images.githubusercontent.com/1036433/116905409-8d930000-ac04-11eb-9146-25a3fe714dc3.png">
</details>

**4. Is it possible to remove `position: sticky` from sidebar menu and allow it to behave like a normal sidebar?**

**5. Increase sidebar padding to `.5rem` on left and right?**

<details>
<img width="356" alt="Screen Shot 2021-05-03 at 11 43 43 AM" src="https://user-images.githubusercontent.com/1036433/116905658-e5316b80-ac04-11eb-846c-104a8e72aa36.png">
</details>

**6. Add bold to question headings?**

<details>
<img width="1219" alt="Screen Shot 2021-05-03 at 11 49 08 AM" src="https://user-images.githubusercontent.com/1036433/116906246-9f28d780-ac05-11eb-8950-f0218b58edf6.png">
</details>

**7.  Any headings or paragraphs using `Zilla` should increase the font size by `.25rem` because Zilla renders smaller than other fonts.  Below is an example of a heading h2 increased to `1.55rem`.** 

<details>
<img width="1348" alt="Screen Shot 2021-05-03 at 11 50 33 AM" src="https://user-images.githubusercontent.com/1036433/116906433-deefbf00-ac05-11eb-9803-0bb2ce66be98.png">
</details>
