### ISSUE TITLE
Investigate how to handle displaying past events

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3131]
As a first step to potentially displaying past event, we need to understand what is involved in doing that.

**Comment by joewhitsitt** [comment]
In D7 we have past events option, profiles/sitenow/modules/custom/uiowa_events/uiowa_events_page, but like I said in grooming, it is limited in how many are displayed. Not sure a dynamic display makes sense as the number of events goes up. Local events are coming. Maybe the sites that need the past events should get the local events content type.

I know you can view past events on events.uiowa.edu. Is there any point in looking into whether we can make friendly permalinks there and make the view experience better there?

**Comment by pyrello** [comment]
The specific requirement for one of my site is to display every event for the past year, so it would not just be every past event.

@joewhitsitt Is your suggestion that sites that need to display past events would only use the local event type? And not use events.uiowa.edu? I would reiterate that we already moved a year's worth of past events to events.uiowa.edu for AMCS because we already told them we could just pull past events from there. I'd just like to understand how you think it would work.

**Comment by joewhitsitt** [comment]
without saying it, i was hinting at importing :drupal_cry:

**Comment by joewhitsitt** [comment]
I think this needs to be addressed on content.uiowa.edu by creating a separate API endpoint to pull from that is reverse sorted. The solution we have in profiles/sitenow/modules/custom/uiowa_events/uiowa_events_page requires paging and the result is funky. page 0 shows the oldest results then sorts newest to oldest. the last page shows the most recent past events, newest to oldest.

That still only gets us part of the way. We would want a dynamically load more button instead of querying all of the results in one go and then caching that data.

Just throwing this out here, you can view a past event already (e.g. https://gis.sites.uiowa.edu/event/67481/0) but I understand the desire for the filtered list.
