### ISSUE TITLE
Signage is using formal wordmark instead of block Iowa

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3142]
Signs have the ability to place a "UI Nameplate" widget which uses the formal wordmark instead of the block Iowa. Should it be switched?

Ex. https://signage.uiowa.edu/registrar/office-registrar

**Comment by briand44** [comment]
We should communicate with Jessica Richardson once this is planned and when it will be rolling out so she can communicate the change with users.

**Comment by mark-bennett-uiowa** [comment]
The current University logo is found at [https://signage.uiowa.edu/sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/uiowa_nameplate_gold.svg](https://signage.uiowa.edu/sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/uiowa_nameplate_gold.svg) but is using some styling to set the size system wide. I created a RGB mode SVG that we can replace this with, and then would need to:

- Change the referenced image to the new path
- Adjust styling to properly size this logo.

**Comment by mark-bennett-uiowa** [comment]
[block_iowa_gold.svg.zip](https://github.com/uiowa/uiowa/files/6618851/block_iowa_gold.svg.zip)

**Comment by briand44** [comment]
will need applied to both Signage and HC Signage

**Comment by briand44** [comment]
Reached out to Jessica about a communication channel and here is her response.
>So I do have a list called UI-SigangeList@iowa.uiowa.edu
 
>It has a majority of our users in there but I’m sure I’m missing some as I have to remember to add them any time someone request someone have rights to the sign.  If you can pull a list of users (with hawkids) out of Drupal signage, I can get it up to date.

**Comment by bspeare** [comment]
Do we want to pull a list of users (with hawkids) out of Drupal signage before we move forward with this communication?  If so, is there a herky drush command that does this?

**Comment by richardbporter** [comment]
No herky commands on signage. :(

**Comment by mark-bennett-uiowa** [comment]
I talked to Jessica last night about the communication to users. She thought that even though this was a required change due to branding, that we should alert all users prior to the change, even if requires no adjustments or input on their end. Healthcare should be unaffected, because they will continue to use their UI Healthcare logo in place of the UIowa logo. Im trying to verify that they dont use the UI logo as we speak.

**Comment by mark-bennett-uiowa** [comment]
@GaryRidgway Here was my plan to tackle this:

### Notes

- Directly replace the old wordmark image with the new block logo image (using the same filename) so that we didnt have to find and replace the old path in the code. It doesnt matter either way, but it might be helpful to keep the old one around for historical purposes.
- The old logo is found at: [https://signage.uiowa.edu/sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/uiowa_nameplate_gold.svg](https://signage.uiowa.edu/sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/uiowa_nameplate_gold.svg). In its default state, it is sized at 2210 px wide by 167 px tall, 300dpi.
- In /docroot/sites/signage.uiowa.edu/themes/uiowa_signage_theme/stylesheets/uiowa_signage_theme.styles.css (line 1772) is the width: 300px; setting. This will need to be changed below. This makes the image 300px by 23px in size on the screen.
- In /docroot/sites/signage.uiowa.edu/themes/uiowa_signage_theme/sass/components/pane_widgets/_pane-uinameplate.scss (line 3) is the same width: 300px; setting. This will need to be changed below as well.
- The block IOWA logo linked above as a zip file (just uncompress, svg files cant be uploaded in Slack) is currently sized at 5408 px wide by 1567 px wide, 300dpi.

### Plan

- Add the block_iowa_gold.svg file to the uiowa_signage_panes module alongside the old nameplate logo.
- Edit the /docroot/sites/all/modules/custom/uiowa_signage_modules/uiowa_signage_panes/plugins/content_types/uinameplate.inc file, replacing '/uiowa_nameplate_gold.svg' with '/block_iowa_gold.svg' on line 60.
- Edit the /docroot/sites/signage.uiowa.edu/themes/uiowa_signage_theme/stylesheets/uiowa_signage_theme.styles.css file, replacing 'width: 300px;' with 'width: 79px;' on line 1772.
- Edit the /docroot/sites/signage.uiowa.edu/themes/uiowa_signage_theme/sass/components/pane_widgets/_pane-uinameplate.scss file, replacing 'width: 300px;' with 'width: 79px;' on line 3.

See what happens. The block IOWA logo is awfully small, but so was the nameplate. We could consider changing this in the near future, or when signage gets re-developed in D9, but for a quick replacement this should be fine.

**Comment by mark-bennett-uiowa** [comment]
I have made these changes locally, and inspecting the page is showing the proper image, and proper styling, but no image. A cache clear did not fix this. Still testing.

**Comment by mark-bennett-uiowa** [comment]
@GaryRidgway found out that the SVG image that was being used was improperly formatted, which was causing the issue. This has been fixed. We also decided to update the image to 97px tall to give it more readability. Great call by the way Alan! Making same changes to healthcare signage even though they dont use the image. Pushing shortly.

**Comment by mark-bennett-uiowa** [comment]
> Reached out to Jessica about a communication channel and here is her response.
> 
> > So I do have a list called [UI-SigangeList@iowa.uiowa.edu](mailto:UI-SigangeList@iowa.uiowa.edu)
> 
> > It has a majority of our users in there but I’m sure I’m missing some as I have to remember to add them any time someone request someone have rights to the sign.  If you can pull a list of users (with hawkids) out of Drupal signage, I can get it up to date.

I think this is supposed to be UI-SignageList@iowa.uiowa.edu, the 'a' and 'n' got transposed.

**Comment by mark-bennett-uiowa** [comment]
Email sent out to ui-signagelist@iowa.uiowa.edu and verified that emails were received. Changes made to dev, stage (both tested), and now prod. Completed.
