### ISSUE TITLE
Additional PDF pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3180]
# Story

As an Admissions site owner, I want to convert additional pages to a PDF so that these pages can print consistently between browsers.

# Additional Info

There are some additional pages that are not areas of study that also need to be converted to PDFs to print. These should be listed at the bottom of the list of print links. These will be more than two pages.

The additional pages can be seen at the bottom of this page. https://admissions.uiowa.edu/at-iowa-print

Here are the existing pages on the new site. I don't believe the Global Assessment Certificate Program (GAC) page has been created yet on the new site.
https://admissions.prod.drupal.uiowa.edu/academics/ap
https://admissions.prod.drupal.uiowa.edu/academics/college-level-examination-program-clep
https://admissions.prod.drupal.uiowa.edu/academics/ib
https://admissions.prod.drupal.uiowa.edu/academics/cambridge-international-exams-cie

# Proposed solution

**Comment by bspeare** [comment]
Do we only want this to function with the `body` field on the page content type?  I think we should scope it to only work with the `body` field.

**Comment by dnkemper** [comment]
@bspeare I mean, that would definitely make this easier for sure! Only problem is that it doesn't include all information on the page if only focusing on body field... they could keep things current and move what's in the body field to a text block? Then what they want downloaded in pdf = display in body field and then remove the body field block in lb? Because here's what happens when downloading a pdf with a lot of blocks on a page vs only in the body field
[Distance and Online Students.pdf](https://github.com/uiowa/uiowa/files/6125494/Distance.and.Online.Students.pdf)
[Diversity on Campus.pdf](https://github.com/uiowa/uiowa/files/6125496/Diversity.on.Campus.pdf)

**Comment by dnkemper** [comment]
It works great when we move block content to body field though.. just need some styling tweaks: 
[Advanced Placement Program AP.pdf](https://github.com/uiowa/uiowa/files/6125549/Advanced.Placement.Program.AP.pdf)

**Comment by bspeare** [comment]
We should probably try to work towards this example for the styling the tables:
[AP.pdf](https://github.com/uiowa/uiowa/files/6125834/AP.pdf)

I updated https://admissions.prod.drupal.uiowa.edu/academics/ap for local testing.

**Comment by dnkemper** [comment]
Thank you so much, @bspeare
