### ISSUE TITLE
Service Outage Comms Playbook

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3276]
As a campus partner, I receive timely notifications when there is a service outage affecting Acquia Hosting/Our Web Service

Possible comms channels
- Dispatch to Sitenow service subscribers
- UI Web Announcements listserv
- #Drupal slack channel in UI Web Community
- #General in OSC channel
- ITS' service outage distribution service
- ITS' Twitter account
- #webteam slack channel on UI Web Community Slack

- Acquia support ticket

**Comment by joewhitsitt** [comment]
Additional option/piece. We can directly subscribe to SiteNow alerts on ITS: https://its.uiowa.edu/alerts/feed/all/all/100028/all

The feed URL can be customized to only show certain severities: https://its.uiowa.edu/alerts/generator

This can feed into the uiweb slack channels, v3 website, etc.

Long term as a developer, I don't know the post-D7 its website and offerings is going to look like. There is a lot bits like this on that website...

**Comment by mjoneill** [comment]
> Additional option/piece. We can directly subscribe to SiteNow alerts on ITS: https://its.uiowa.edu/alerts/feed/all/all/100028/all
> 
> The feed URL can be customized to only show certain severities: https://its.uiowa.edu/alerts/generator
> 
> This can feed into the uiweb slack channels, v3 website, etc.
> 
> Long term as a developer, I don't know the post-D7 its website and offerings is going to look like. There is a lot bits like this on that website...

I like this. Whatever we can do to make it easy to communicate timely info with minimal overhead I think is worth solid consideration.  I'd like to see what makes sense, especially if there are things we can learn from today's experience...

**Comment by richardbporter** [comment]
Any AC ticket should use the base application uiowa. I think that includes the most collaborators.

**Comment by joewhitsitt** [comment]
I've looked at what has been written and I am wonder something similar to what Danielle hinted at in Slack. We have several possible communication methods, but which ones do we _need_ to do? We don't want to spend a lot of time on this stuff as it happens. 

Did the help desk say what their preferences were regarding this when they came to us with concerns? For the rest of our community which list serves them the best? When Acquia specifically goes down, most likely it will be all applications or not v1 or v3 specific so does it make sense to target the mainly v2/v3 audience of our dispatch list? Do we need to take an initial step to notify v1 customers to hop on a specific list so they receive this important information? Our Slack plan only has so many "seats" (last I heard) so do we want to advertise this as the place to get important info?

I thought this issue was filled out more than it is, so I applaud Danielle going this far. I think some questions need to be answered before we can call this task done.

I will say that https://github.com/uiowa/uiowa/issues/3276#issuecomment-810487548 was not mentioned in the AC portion of the doc. Also, for an outage which this mainly pertains to, what should the value of some of these other required fields be? Type = Drupal Application Support? Product or Service = Acquia Cloud Platform? Critical?

**Comment by dnkemper** [comment]
@joewhitsitt THIS ^^^ 👏 👏 👏

**Comment by dnkemper** [comment]
Added the [#3276 (comment)](https://github.com/uiowa/uiowa/issues/3276#issuecomment-810487548)

Added to only tweet if catastrophic and have to? 

BUT still questions I don't feel comfortable answering on my own...

Definitely wasn't comfortable w/ this issue 😬

**Comment by joewhitsitt** [comment]
@briand44 are you comfortable with answering some of these questions? https://github.com/uiowa/uiowa/issues/3276#issuecomment-832971820

**Comment by dnkemper** [comment]
https://wiki.uiowa.edu/display/drupaldev/Communication+Plan+for+Service+Outage

**Comment by briand44** [comment]
Attempting to answer questions from above.

> Also, for an outage which this mainly pertains to, what should the value of some of these other required fields be? Type = Drupal Application Support? Product or Service = Acquia Cloud Platform? Critical?

Yes, I think those values are good. The most important is to have the urgency as critical when there is an outage. Last time I had the Type as Acquia Platform/Services mainly because I was aware Acquia was having issues.

**Comment by briand44** [comment]
> Did the help desk say what their preferences were regarding this when they came to us with concerns?

No, they were mostly asking what they should do in the event they are notified of an outage off hours. Who do they contact on our team and how?

> For the rest of our community which list serves them the best? When Acquia specifically goes down, most likely it will be all applications or not v1 or v3 specific so does it make sense to target the mainly v2/v3 audience of our dispatch list? Do we need to take an initial step to notify v1 customers to hop on a specific list so they receive this important information? Our Slack plan only has so many "seats" (last I heard) so do we want to advertise this as the place to get important info?

I would say we use the SiteNow announcements list and the UIWeb list as the main channels and we can also mention it in Slack . Those are really the only two email lists we currently do anything with so I think that is where we start. This can evolve as needed in the future if we are seeing holes or missing communications with an audience. I don't think we necessarily need to take an initial step to notify v1 customers to hop on a specific list, they may already be on one of the others. I personally wouldn't advertise Slack as the place to get important info but others may have a different opinion.

**Comment by pyrello** [comment]
Can this be closed?

**Comment by dnkemper** [comment]
CRAP! Thank you Sean!
