### ISSUE TITLE
Directory Profiles Integration

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3286]
# Story

As a SiteNow site owner, I would like the ability to integrate with the campus Directory Profiles solution, so that I can have information about faculty/staff/etc visible on my website without having to manually create them.

# Additional Info

This should be similar to the existing APR integration that the College of Pharmacy is using on SiteNow v3.

Denny provided some initial information https://git.uiowa.edu/java/profiles/-/issues/174

# Proposed solution

**Comment by richardbporter** [comment]
Sounds like duplicating the uiowa_apr module and modifying as needed would work. Plus, we'll need to keep uiowa_apr for unknown amount of time until Pharmacy can move away from it.

**Comment by richardbporter** [comment]
Sounds like multiple directories are needed so we'll need to refactor #3644 to handle multiple configurations. We talked about using a custom block but decided that would be too complicated, at least initially. This means the limitation of multiple directories is that they must exist at separate paths.

I would propose nesting the `uiowa_profiles.settings` config under a top level collection of `directories` and hooking into that to define the router paths.

**Comment by GaryRidgway** [comment]
- [x] Validate every form
- [x] Make add button look like a tab???
- [x] Be able to remove profiles form instances
- [x] Generate multiple pages
- [x] Intro text TODO
- [x] Style these to look like tabs, because I think that will be the most clear
- [x] If there are already saved forms, be able to iteratively load them in to the config page
- [x] Save data from every form in instanced/indexed versions of the forms
- [x] Nest forms under a common parent so that the submit button saves all form instances at one time
- [x] Be able to add another instance of the form

Nice to have
- [x] JS to detect when title is edited to edit tab name
- [x] JS to focus the most recently added tab when it is added
- [x] make delete button red
- [x] Comment Run. This is a complicated but valuable set of code for future reference, and I think comments on what we are doing and how things work will be valuable to people in the future. Invest now for that gain later.

**Comment by richardbporter** [comment]
I found myself clicking the Delete button accidentally while testing this. Might be good to make that red or something to differentiate it from the Save button.

**Comment by richardbporter** [comment]
> JS to focus the most recently added tab when it is added

That got me a few times as well.

**Comment by GaryRidgway** [comment]
> I found myself clicking the Delete button accidentally while testing this. Might be good to make that red or something to differentiate it from the Save button.

I'll turn the delete button red then

**Comment by richardbporter** [comment]
One last thing to do is removing our canonical config and grabbing it from the new API endpoint whenever that is ready: https://git.uiowa.edu/java/profiles/-/issues/293
