### ISSUE TITLE
SSL cert - *.physics.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3344]
SSL cert - *.physics.uiowa.edu on uiowa01.   There is currently coverage for tracers.physics.uiowa.edu on uiowa01, but @mark-bennett-uiowa says that along with vanallen.physics.uiowa.edu, there are more coming.

**Comment by mark-bennett-uiowa** [comment]
Updated SSL certificate for uiowa01 by removing the tracers.physics.uiowa.edu entry and replacing it with *.physics.uiowa.edu in order to cover additional subdomains for physics.uiowa.edu. Certificate in place, previous certificate disabled. Just waiting on verification via browser that new certificate is active.
