### ISSUE TITLE
Articles Monthly Archive block showing links where no content exist

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3387]
## Issue

As I understand it, the year pages for articles exist (e.g. https://law.uiowa.edu/news/2021). The monthly archive block if enabled is displayed on these pages. If someone clicks a month link from a different year, the link is relative and breaks.

## Notes

Law is not using SiteNow Articles for /news. It is a basic page, but the view page is still enabled.

## Proposed Solution

- Revisit how these menu links are being created. Look for opportunities to make them more absolute while keeping the custom path variable in mind.
  - It is set here: admin/structure/views/view/articles/edit/block_articles_archive but is changed via docroot/modules/custom/sitenow_articles/src/Form/SettingsForm.php
- Worse case, hide this block on all contextual arguments but the view root.

**Comment by cory-skeers** [comment]
It seems like this is something getting confused between the view page existing and a basic page existing at the same path. Manually changing the block contextual filter path to something other than `news` works. Something like `news/archive` actually drops the 'archive' and works, creating correctly formed links like `/news/2019/05`. Haven't dug into the process that handles this to understand why, or if there's a way to handle it there.

I'm wondering if we should include an option in Sitenow Articles for people creating their own news pages that could update the path accordingly, if it's desired to have a custom landing page but still use the child view pages off the same path.

**Comment by dnkemper** [comment]
As Cory stated, Law is not using SiteNow Articles for /news. They configured SiteNow Articles to display at the /news path but also created a basic page at the /news path which is creating the "bug". So since both exist at the same path, there are conflicts with the article links (/news/2021/04 etc) not linking up to the correct ‘/news’ path. Manually changing the block URL path to something other than /news works. Or deleting the basic page with the same URL path as the sitenow articles path works as well.
