### ISSUE TITLE
Promoted search results for HawkShop

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3405]
# From the email request:
I’m hoping for those search terms to bring up the bookstore url as a result.
 
The urls that would be good for these terms are:
 
BOOKS - https://www.bkstr.com/iowastore/home
CLOTHING - https://www.bkstr.com/iowastore/shop/clothing-accessories
T-SHIRTS - https://www.bkstr.com/iowastore/search/keyword/tshirts
SUPPLIES - https://www.bkstr.com/iowastore/shop/school-supplies/school-supplies-sub
 
Since your site uses Google as its search engine, here is a helpful link with information on how to promote the link to the bookstore to the top of results pages for certain search terms https://developers.google.com/custom-search/docs/promotions

More details in email titled **Iowa Hawk Shop Search Terms** in ITS-web email account archive.

# Proposed solution

See @richardbporter's [comment below](https://github.com/uiowa/uiowa/issues/3405#issuecomment-825721302). After complete, follow up with @mjoneill.

**Comment by richardbporter** [comment]
Plan
- Log in to Google CSE admin interface using its-web credentials in esaccess
- Edit the CSE in use on the home page
- Find promoted search terms somewhere in the interface and add the terms above

**Comment by mjoneill** [comment]
OK. Instructions indicated something about uploading text files (I assumed to root of a domain).  If it's all driven through the interface, maybe it's something I can do.

**Comment by richardbporter** [comment]
Is someone working on this? I just assigned myself but can stop if so.

**Comment by pyrello** [comment]
Nope. Go for it!

**Comment by richardbporter** [comment]
None of these are showing currently (ex. https://uiowa.edu/search?terms=title%20ix) because the homepage search results are limited to only that site (even though the CSE config includes other domains). That limit is set through the module config which in turn sets the as_sitesearch attribute on the CSE. It seems like we would need to remove that constraint to get these to show up unless there is another setting that controls it - I haven't found it yet. Are we ok doing that?

 https://stackoverflow.com/a/16818750

The existing promoted items need to be cleaned up too. They are missing protocols, descriptions, etc. and some point to broken links. They look better with all those attributes set but they need additional CSS as well:

![image](https://user-images.githubusercontent.com/1068523/115927175-a30c6b00-a449-11eb-817f-003c648caae7.png)

**Comment by richardbporter** [comment]
I noticed some internal search results being returned as well: https://uiowa.edu/search?terms=icfm This is because D7 apps lost dynamic robots writing so nothing is denying those domains. We could exclude a pattern in the CSE config, maybe *.drupal.uiowa.edu?

**Comment by richardbporter** [comment]
I think these are the docs for the CSE: https://developers.google.com/custom-search/docs/element

**Comment by richardbporter** [comment]
> I noticed some internal search results being returned as well: https://uiowa.edu/search?terms=icfm This is because D7 apps lost dynamic robots writing so nothing is denying those domains. We could exclude a pattern in the CSE config, maybe *.drupal.uiowa.edu?

The *.drupal.uiowa.edu domain exclusion seems to have fixed this.
