### ISSUE TITLE
Investigate using media_iframe for UICapture/Panopto Embeds

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3450]
# Story
As a site owner, I can embed a UICapture or Panopto video in my site so that I can share those videos with visitors.

# Motivation
UICapture/Panopto embeds do not use OEmbed, which is necessary for the remote video media type that we are currently using. We need another solution for this type of embed.

# Proposed solution
- Investigate whether we can use the [media_iframe](https://www.drupal.org/project/media_iframe) module for embedding UICapture/Panopto embeds. This will probably require setting up a new test media type with a field using the `media_iframe` type.
- Recommend whether we want to use that module directly or create our own custom module based on it.

**Comment by briand44** [comment]
look into https://www.drupal.org/project/media_iframe

Ideally the first slice of this is entering a url and outputting a id using a media object.

**Comment by pyrello** [comment]
Updated the description.

**Comment by bspeare** [comment]
@joewhitsitt when you have a moment, could you take a look at https://github.com/uiowa/uiowa/pull/3509 and evaluate the module's functionality?

**Comment by joewhitsitt** [comment]
My initial thoughts are that this looks promising for Panopto being stored as a media entity instead of as a CKEditor object but I see some fundamental things that should probably change which _might_ warrant us forking or writing our own version of media_iframe (not the iframe module).

- I think the labels that the editor sees are misleading and should be changed. As a user, if I click to add an iFrame, I expect to be able to paste my entire iframe object in.
- For reasons we don't currently allow editors to place iFrames in the WYSIWYG, we need to create and validate against an "Allowed" list of sources.
- Since the main priority is Panopto at this point, not all other iframes, there are additional attributes we will probably have to capture that the iframe module does not currently collect (e.g. Start At). Maybe this can be done with the media entity fields and not the iframe form.

**Comment by richardbporter** [comment]
> For reasons we don't currently allow editors to place iFrames in the WYSIWYG, we need to create and validate against an "Allowed" list of sources.

I don't see a way of doing that in the module code.

The module code is very minimal. Using it as template for a more restricted Panopto widget of our own seems viable.

**Comment by pyrello** [comment]
I don't think that we can accomplish everything that we need for this to work with this module. Either we utilize it and then build additional custom code to build upon it (my favored approach since it is community supported and has a very light footprint) or we build something that approximately duplicates this and add our custom logic to that. Doing the second will make it harder to potentially contribute back to the community if we figure out anything useful. It will, however, give us more control to create exactly what we want.

**Comment by bspeare** [comment]
Closing this since our investigation into the module is complete.
