### ISSUE TITLE
Career Center Video Embeds

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3499]
# Story

As a content editor for the Career Center, I would like to be able to embed Candid Career videos so that students can have access to career educational videos directly on our site.

# Additional Info
This request if for their SiteNow v3 site that currently exists at https://careers.stage.drupal.uiowa.edu/.

I created a test page with an example of an embedded video using full html at https://careers.dev.drupal.uiowa.edu/test-widget.

Here is a link to the welcome kit and additional info.
https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/Career%20Center/CandidCareer.docx?d=w0d82fd3e6e064b2baff9545a163063d2&csf=1&web=1&e=bDw6cA

# Proposed solution

**Comment by joewhitsitt** [comment]
Capturing possible proposed solutions for consideration/probing:

- Media type similar to Panopto just for careers in a site split
- "Generic embed" media type (control list of allowed domains, create plugins based on domain to provide domain specific attributes/markup to be captured/rendered). Better suited to handle the laundry list of embeds folks want.
- CKEditor Plugin (easier to one-off but requires split and would create custom thingy that we would have to account for in CKEditor 5)
- Custom block (minimal split work but prevents inline placement)
- oEmbed (easy peasy with oembed_providers if vendors would just support it)

**Comment by briand44** [comment]
I added a link to Sharepoint that contains the welcome kit and additional info in the original issue description. Let me know if you can't access.

**Comment by pyrello** [comment]
For the generic embed, we could eventually develop a plugin system that would allow us to use plugin class files to provide the embed-specific attributes and possibly specialized form settings.

**Comment by richardbporter** [comment]
> Media type similar to Panopto just for careers in a site split

We got kinda lucky with Panopto in that we discovered a public thumbnail URL to use for the media thumbnails. We should probably be using the API to get that and ideally the video title. I'm not seeing  that for this service which makes finding/re-using this media difficult.

**Comment by joewhitsitt** [comment]
Rick and I had a slack conversation and I wanted to capture a few points here:

- Our battle with previews could be reduced with placeholders like we used to have for Twitter tweets, etc.
- Not valuable as media entities without additional metadata. Could collect more info besides URL though.
- CKEditor plugin needs iframes to be allowed to work...
- I didn't love the UX for that iframe module we evaluated - https://github.com/uiowa/uiowa/issues/3450

**Comment by richardbporter** [comment]
Yea I don't like the UX either. I think people will be annoyed having to split out a copy/paste of iFrame code into separate fields. That seems like a bigger issue than the module not having a media library form or any way to limit the allowed URLs.

**Comment by richardbporter** [comment]
It seems like because of the filtered HTML, we either use the generic media embed or a custom block. I guess the question is if these "generic embeds" would be useful to have in the media library. I'm not so sure they would be but if that is the route we take with oEmbed providers than maybe it'd be good to be consistent?

**Comment by richardbporter** [comment]
> It seems like because of the filtered HTML, we either use the generic media embed or a custom block.

I was actually able to add the `iframe` element to the allowed tags of the Filtered HTML text format and it worked. 

> I guess the question is if these "generic embeds" would be useful to have in the media library

I don't think it is useful for this type of embed. This is what oEmbed is for as the standard allows us to grab metadata to store along with it. It seems like site editors sharing embed videos more than once would be more inclined to copy/paste the embed code again rather than go look for the thing in the media library when there is no thumbnail.

**Comment by richardbporter** [comment]
I'm really curious about allowing iFrames in filtered HTML. I wonder if we could use the Filter API to validate the `src` is from an allowed set of values we maintain and then strip it if not. That is not great UX but that is how it works right now - if someone copy/pastes an iframe into the source, it gets stripped with no messages.

https://www.drupal.org/docs/8/api/filter-api/overview

**Comment by joewhitsitt** [comment]
I like the idea of this being a "secret menu" type of thing with more specific allowed sources. Wonder if we could hide or alter the iframe tag showing in /filter/tips as well. If we are going forward with #3838 could we ignore the allowed sources and create a UI for adding/removing them so that we can easily add site specific ones?

**Comment by richardbporter** [comment]
I assume that would be possible but we may want to version it for visibility and a clearly defined deployment process for reviewing the security, a11y and design of the allowed sources.

One downside to this approach is we'd probably need one class to style all of these embeds. Some might be videos but some might not be. It is probably possible to extract part of the `src` and use as a class. Right now in the POC, I'm just wrapping the `iframe` in a media div. The WYSIWYG preview does not get this div so it looks like the width/height dimensions. I'm assuming we'll need a wrapper div of some kind.

**Comment by richardbporter** [comment]
I'm looking for another domain to test #3838 with. I see #3415 but that uses oEmbed. I'm not in favor of #1689 and the admissions ones all seem to have JS and/or CSS associated with it. If this is the only non-oEmbed that only requires an iframe, should we just embed it for them?

**Comment by joewhitsitt** [comment]
grab a map from google maps

```
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11923.152282319676!2d-91.5693139!3d41.66032075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1626890020751!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
```

**Comment by richardbporter** [comment]
> grab a map from google maps
> 
> ```
> <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11923.152282319676!2d-91.5693139!3d41.66032075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1626890020751!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
> ```

Is that on-brand? Should we support that?

**Comment by joewhitsitt** [comment]
thought you were just testing. i know folks have requested them and that we don't have a solution.

**Comment by richardbporter** [comment]
Yea good call. Trying it out now.

**Comment by richardbporter** [comment]
I'm second guessing the approach in #3838 now. Since we have to wrap these in divs to style them, the media system gives a theme-able way of doing that. It also allows placing them in the CKEditor easier and moving them around WYSIWYG style.

Could we consolidate our media types somehow? Maybe rename remote video to oEmbed?

**Comment by joewhitsitt** [comment]
I think remote video should stay as-is. Label could be changed to oEmbed video, but that is technical jargon an editor doesn't know about. A lot of styling is set for that to be 16:9 and responsive.

I think I would be interested in consolidating the other oEmbed objects (twitter, facebook, instagram, etc.) but that seems like a lot of work just to reduce buckets for the editor and then we would be on our own.

A generic embed or "misc embed" still sounds like a good idea if we can get around the preview issue

**Comment by richardbporter** [comment]
What was the preview issue? The WYSIWYG preview in #3838 does not look good since the wrapper div is not added yet.

**Comment by joewhitsitt** [comment]
previews for the media entities have just been troublesome in general (styling for in wysiwyg, retrieving a still frame, etc.)

**Comment by joewhitsitt** [comment]
I am going to pull down and review the UX for this, but I did some reading about iFrames.

looks like we mitigate quite a bit by setting the allowed list for src and stripping other attributes. since we are only allowing certain sources we could review what each of those "needs" to function and use the sandbox attribute to block the possibility of anything else: https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/

things we might want to add to all instances would be loading="lazy" and seamless (chromium support)

**Comment by briand44** [comment]
Do these always display full width? If they wanted to embed a smaller size would they need to use layout builder and add it to a narrower column?

**Comment by richardbporter** [comment]
Yes probably. Another option would be to specify a width/height does not meet our supported aspect ratios of 1x1, 4x3 or 16x9. I think if it doesn't match those it won't get the responsive classes added to it.
