### ISSUE TITLE
Adjust delete permissions

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3559]
# Story

As a site owner, I would like to limit delete rights so that content is not accidentally or mistakenly deleted since it cannot be easily recovered.

# Additional Info

Only allow editors to delete content they "own". I think this could be done the same for publishers as well since they do have the ability to archive content but would like to get feedback on the team if this should be done for just editors or both editors and publishers.

We should verify that webmasters have the ability to change author of content.

Dentistry would like to have this by the beginning of July.

# Proposed solution

**Comment by joewhitsitt** [comment]
I think adding this to just the editor role makes sense to me. We gave editors more permissions initial because we didn't have publisher and we didn't want sites to just make everyone a webmaster. We can rely on the publisher role more to give a step up in access without warranting promotion to webmaster.

**Comment by briand44** [comment]
We decided to scope this to the editor role only. Publishers will continue to be able to delete any content but editors will only be able to delete content they own.
