### ISSUE TITLE
Carousel Paragraph Bundle

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#357]
### Problem
Site owners are expecting us to have similar slideshow and image gallery functionality out of the box. We more or less need a port of the snp_image_gallery within our paragraphs implementation.

### Proposed Solution
Create a paragraph bundle that allows the upload of multiple images (bulk upload would be a bonus). The bundle settings can then default as a fancybox/lighbox thumbnail gallery or be turned into a slideshow.

We should evaluate if the libraries we were using in snp_image_gallery are still what we should be using in Drupal 8 (slick slider, fancybox).
- [x] Images should be able to be reordered by the editor.
- [x] Slideshow
- [ ] ~~Thumbnail with modal displays.~~

Additionally, we should consider supporting captions/title text that users can toggle on to display as part of the modal or slide.

**Comment by richardbporter** [comment]
Thumnails with modal display are not available on the current SiteNow service. We should move that to a follow-up issue for later.

**Comment by dnkemper** [comment]
**Currently Testing**

**Comment by dnkemper** [comment]
**Test**

After adding carousel items and selecting *Half* in 'Column Width', it looks awesome and has arrows to view the next image. The different image sizes change the carousel size slightly.
![Screen Shot 2019-08-14 at 7 28 45 AM](https://user-images.githubusercontent.com/16872949/63021102-74ad4e80-be65-11e9-9114-628e009d4f4f.png)


**BUT**

When adding carousel items and selecting *Full* in 'Column Width', the image sizes aren't consistent and the carousel changes sizes depending on the uploaded image (carousel header changes sizes with the image as well). Unlike the *Half* column width carousel, the last picture in the *Full* width carousel doesn't have an arrow on the right side. Not sure if it's important but figure might want to be consistent?

![Screen Shot 2019-08-14 at 7 33 49 AM](https://user-images.githubusercontent.com/16872949/63021327-f4d3b400-be65-11e9-9039-195e06dd3cbc.png)
![Screen Shot 2019-08-14 at 7 34 12 AM](https://user-images.githubusercontent.com/16872949/63021332-f7cea480-be65-11e9-9164-948f81c8a8b0.png)

**Comment by GaryRidgway** [comment]
Need image style. Double check last arrow display - may not show up at certain widths.

**Comment by dnkemper** [comment]
Update: Right arrow exists but moves vertically & horizontally depending on image size

<img width="1240" alt="Screen Shot 2019-08-14 at 1 37 36 PM" src="https://user-images.githubusercontent.com/16872949/63046767-bd322f80-be98-11e9-8e50-37cbcdb86c5e.png">
<img width="1287" alt="Screen Shot 2019-08-14 at 1 39 05 PM" src="https://user-images.githubusercontent.com/16872949/63046902-f1a5eb80-be98-11e9-80d0-b2d5dcf0666b.png">

**Comment by richardbporter** [comment]
Be sure to re-compile SASS via `blt frontend` or manually within uiowa_bootstrap theme.

**Comment by dnkemper** [comment]
### **Section Content Width = 'Medium'**

**Full width Carousel**
1. Images are same width and height = good **BUT** the images sometimes get cropped weird? Is there a way we could control how they get cropped or is that out of reach?
![Screen Shot 2019-08-15 at 10 55 57 AM](https://user-images.githubusercontent.com/16872949/63108458-86b5ec80-bf4c-11e9-8770-04e4f790520b.png)
2. Some images also get stretched weird/distorted.. Is that something we could control?
![Screen Shot 2019-08-15 at 11 06 37 AM](https://user-images.githubusercontent.com/16872949/63108638-fa57f980-bf4c-11e9-9c50-ba8fb610a4ef.png)

**Half width Carousel**
1. Images are same width + height = good **BUT** the images get cropped weird and look a little distorted? Can we control this?
![Screen Shot 2019-08-15 at 11 13 46 AM](https://user-images.githubusercontent.com/16872949/63109054-ebbe1200-bf4d-11e9-9964-6e59b0a77f79.png)
![Screen Shot 2019-08-15 at 11 13 39 AM](https://user-images.githubusercontent.com/16872949/63109069-ef519900-bf4d-11e9-8868-1388c97f216b.png)

**Comment by dnkemper** [comment]
### **Section Content Width = 'Large'**
**Carousel column width = 'Full'**
1. Looks good! Cropping issue, but pretty clear for the most part
![Screen Shot 2019-08-15 at 11 25 15 AM](https://user-images.githubusercontent.com/16872949/63109906-d649e780-bf4f-11e9-9563-5c8a39d48c5d.png)


2. **ALL** width mobile views looks distorted and there isn't a caption but not sure if intentional or not
![Screen Shot 2019-08-15 at 11 27 19 AM](https://user-images.githubusercontent.com/16872949/63109877-c205ea80-bf4f-11e9-8bf0-e21940efa716.png)
![Screen Shot 2019-08-15 at 11 29 18 AM](https://user-images.githubusercontent.com/16872949/63109966-f8dc0080-bf4f-11e9-8622-d0eb84417aa6.png)

3. Tablet view is decent for full column width

**Carousel column width = 'Half'**
1. Looks A LOT better than when section content width = medium
2. Still cropping issue
![Screen Shot 2019-08-15 at 11 23 58 AM](https://user-images.githubusercontent.com/16872949/63109612-38eeb380-bf4f-11e9-8048-d77edba6d821.png)
3. tablet view is a little distorted
![Screen Shot 2019-08-15 at 11 36 36 AM](https://user-images.githubusercontent.com/16872949/63110400-f928cb80-bf50-11e9-8a59-de9535775c96.png)



**Carousel column width = 'Third'**
1. Looks a little bit better than when the section content width =medium
2. Still a little distorted but I'm not sure how to fix that
![Screen Shot 2019-08-15 at 11 22 03 AM](https://user-images.githubusercontent.com/16872949/63109476-ef05cd80-bf4e-11e9-9fea-f5517d68f25f.png)
![Screen Shot 2019-08-15 at 11 22 23 AM](https://user-images.githubusercontent.com/16872949/63109504-ff1dad00-bf4e-11e9-9fa0-f95f1593f4ad.png)

**Comment by richardbporter** [comment]
We may want to Slick for this instead but we'll be loading both libraries. Looks like HDS is using Slick.

**Comment by dnkemper** [comment]
Review

Looks awesome in **all** browsers and full, half, third and fluid sizes. 

Only size that it doesn't look great in is the 'Quarter' size but I can't really see anyone wanting to use that size? 
<img width="315" alt="Screen Shot 2019-09-17 at 11 45 26 AM" src="https://user-images.githubusercontent.com/16872949/65062143-087ca980-d941-11e9-8559-35c7bff77b13.png">

BUT if users do select 'Quarter' size, and have a small caption, then it works
<img width="324" alt="Screen Shot 2019-09-17 at 11 50 25 AM" src="https://user-images.githubusercontent.com/16872949/65062347-732de500-d941-11e9-8c09-3100b1daa5c4.png">

Overall, THIS IS AWESOME! Well done!
<img width="666" alt="Screen Shot 2019-09-17 at 11 42 28 AM" src="https://user-images.githubusercontent.com/16872949/65062432-9eb0cf80-d941-11e9-8662-c77dc4e7e2e8.png">
<img width="1205" alt="Screen Shot 2019-09-17 at 11 40 05 AM" src="https://user-images.githubusercontent.com/16872949/65062497-c011bb80-d941-11e9-98cc-2c168ee7cf65.png">
