### ISSUE TITLE
Basic Page - Add Featured Image

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#362]
### Problem
With the #220 featured content bundle, basic page is the only content type that doesn't have a featured image available for use in the teaser view mode. Additionally, for SEO purposes, a featured image would help editors provide an image for twitter cards, opengraph, etc.

### Proposed Solution
Add the existing field_image to the content type similar to how article was done placing the field in the advanced sidebar. For this task, render the featured image for the teaser view mode similar to article (in sitenow.profile preprocess_node the teaser view mode and render the image using the sitenow_card image style). For MVP, don't display the image on the full node. There will be another task to provide and option to display the featured image on the full node.

#351 can be expanded to wire up the featured image for page, article, person to the metatag fields via token.

### Test
Populate a page with a featured image that has a consistent UX like article. See if the image displays properly in the teaser view mode.

**Comment by dnkemper** [comment]
**Testing Instructions**

1. Go to content -> add content -> person
2. Add Info (first & last name, credentials, title, email, phone, bio, *on right sidebar* add short bio and person photo **make sure to add a short and long bio*
3. Save as ‘Published’
4. Please add a second person too
5. Go to content -> add content -> and edit an existing page
6. On the right hand menu, ‘Tags’ should not exist
7. Add a featured content paragraph to the existing section 
8. Click on ‘Select Content’
1. In the popup window, check the two people you created
2. Should be grouped by CT (not required just thought it helped visually)
9. The two people should be displayed vertically, NOT horizontally
1. FACT: entity reference backend display is not feasible at the moment (See #[414](https://github.com/uiowa/uiowa/issues/414))
10. When you save the page, you should see the person’s short bio
11. There should NOT be a ‘Read More’ option on the ‘Person’ teaser
12. When you click on the person, you should see the full view/bio

**Comment by joewhitsitt** [comment]
PR #415 wasn't started off master and had stuff related to the featured content branch. Had to close. Starting a new branch with the harvested good stuff for this issue.

**Comment by dnkemper** [comment]
**Testing Instructions**

1. Code is on branch ‘basic-page-feat-image’ on uiowa
2. Once your site is set up, go to ‘Content’ and edit existing default ‘Basic Page’ content ie ‘Home’ or ‘About’
3. In the right hand menu of the page you’re editing, there should be a ‘Featured Image’ tab below the ‘Content Description’ tab
4. Click ‘Add Media’ and add a random image
    1. Add alt text and click ‘Save and insert’
5. Instead of saving the content type, click ‘Preview’
6. You should see the ‘Full’ view of the page without the featured image you added
7. In the far right corner above the header, there’s a dropdown box with the label ‘View mode:’
8. Select Teaser view
9. You should see the teaser image that you uploaded
