### ISSUE TITLE
People block pager count is broken when set to 1

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3661]
# Problem
The people list block pager displays an inaccurate count when set to `1`. 

# Steps to reproduce
Check out the top two blocks on https://sandbox.prod.drupal.uiowa.edu/people-directory. 

# Proposed solution
- ?

**Comment by richardbporter** [comment]
Investigate opening bug in ctools_views project to potentially address there.

**Comment by joewhitsitt** [comment]
There might be pager id issue here. We got a separate ticket saying a pager wasn't even displaying. The difference is there is another block where the pager is not set.

Might be worth checking into what the pager id is set to and if it conflicts with another block on the page.

**Comment by joewhitsitt** [comment]
Pager ID takes integer, and ideally we would supply something unique which our ListBlock submit doesn't seem to have access to.

Drupal 10 plans to make this dynamic https://www.drupal.org/project/drupal/issues/3225987

A ListBlock specific hack would be to set a block config value `rand(10, 1000)` update the pager id on preBuild. Still a collision possibility but less so. Views would have to be re-saved to get the unique id but this ensures the same id is used for submit/load/ajax. Unfortunately, `Html::getUniqueId` itself won't work for this because we need an integer.

Having a unique pager id seems to resolve this issue as well as the missing pager issue that was recently reported.

**Comment by pyrello** [comment]
I may have accidentally stumbled on to a fix for this. Going to test today.

**Comment by pyrello** [comment]
> I may have accidentally stumbled on to a fix for this. Going to test today.

This did not pan out as I had hoped. I had just not constructed the right case for testing the issue.

**Comment by pyrello** [comment]
I worked on trying to adapt a patch using the code in this comment: https://www.drupal.org/project/drupal/issues/3225987#comment-14177968

This caused the pager to render correctly on first load, but broke the behavior when first clicking a page link. This would cause the first item to reload. Subsequent clicks after that worked correctly.

I like the approach of doing this dynamically and not getting into having to generate and store a value. It seems that some additional tinkering with this patch could probably get us there: https://git.drupalcode.org/project/drupal/-/merge_requests/1439.diff

**Comment by dnkemper** [comment]
NOTE:

Load page
Hover over pager #’s: https://sandbox.local.drupal.uiowa.edu/people-directory?block_config_key=72Wnq25U6UiG7BFE-WftmKAKa6vpX-MEMdx597rxaAE&page=0%2C0%2C0%2C0%2C1%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0 

https://sandbox.local.drupal.uiowa.edu/people-directory?block_config_key=72Wnq25U6UiG7BFE-WftmKAKa6vpX-MEMdx597rxaAE&page=0%2C0%2C0%2C0%2C2%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0


THEN - click ‘2’ of pager - reloads items and URLs are then:
https://sandbox.local.drupal.uiowa.edu/people-directory?view_query=&block_config_key=72Wnq25U6UiG7BFE-WftmKAKa6vpX-MEMdx597rxaAE&page=1

https://sandbox.local.drupal.uiowa.edu/people-directory?view_query=&block_config_key=72Wnq25U6UiG7BFE-WftmKAKa6vpX-MEMdx597rxaAE&page=2

**Comment by joewhitsitt** [comment]
The problem with the initial load is that `setCurrentPage` runs first before `updatePageInfo` where the dynamic id is set. After that, it works because it re-runs and has the updated id.

Setting the id in `preBlockBuild` works because it runs before either of these. The downside is that it is unaware of the dom position at this point, and there is very little in terms of a unique id to latch on to. We can get the uuid of the FormObject of the block but translating or assigning a small integer to that is where I get stuck. Random works until it doesn't.

Update: I think it works if ajax is disabled on the views block

As an aside, I found out from looking into this earlier, the `%2C0` are expected based on the number of pager ids on the page.

**Comment by joewhitsitt** [comment]
In a bit, I am going to let the debugger take me away on this and see where it goes because at some point the current page seems to change and the pager ids seem to be the same.

**Comment by dnkemper** [comment]
Would be nice to eliminate list block as part of this if we could set up the same conditions but for generic views blocks and see it it also happens 😜 **cough cough ** @pyrello with your lando environment possibly?

**Comment by pyrello** [comment]
FWIW, I think we should all have a method for confirming or disproving bugs as coming from outside our platform via setting up a standard install, @dnkemper. I can look into this, but not immediately.

**Comment by dnkemper** [comment]
@pyrello 100% agree. With new laptop I'll be all over it! I can try to set it up in the mean time on this one though... just would like to apologize in advance for how my laptop handles it 😂🙈

**Comment by pyrello** [comment]
Best case scenario here is that we write a failing test. Then the fix just fixes the test. Also more likely to get reviewed sooner by a maintainer if it has a passing test.

**Comment by joewhitsitt** [comment]
Finally made a step forward. Page render builds out `pagerElements` but then that is lost when the first ajax paging is called. The first block on the page still works because it uses the same pager id "0". Any others on the page have to go through the process of being established again in the pagerElements array. That is why it works again after the second pager click on the block.

**Comment by joewhitsitt** [comment]
I think I got it... using shared temp store. Might be one of these patches that never gets committed though...

This does fill in the key_value_expire table and things like a `cr` will generate new dom ids. The default sharedtempstore holds items for 7 days. Might be a "growing" problem as-is.

https://git.drupalcode.org/project/drupal/-/commit/c2ec77f515f778362a8e1afd8a3eef9c8e5b2fa3

#4501 should grab the latest if composer install re-applies patches.

**Comment by joewhitsitt** [comment]
Wondering if hook_views_pre_build() could house a temp solution until the core solution gets more traction. It runs before SqlBase and has the dom_id available.

**Comment by joewhitsitt** [comment]
reopening due to solution rollback...

**Comment by joewhitsitt** [comment]
something was causing the table to fill up with dom_id instances, all associated with single owner (siteimprove?)

need to look into this a bit more
