### ISSUE TITLE
"Person type status" not showing on initial "person type" selection

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#3662]
# Story

As a site editor I want to be able to assign the `Former faculty` person type status to a `person` without having to assign them `Faculty`, save the page, click edit again, and then check the `Former faculty` box.

Currently, when you check `faculty` on a person as a `person type`, `former faculty` does not show up.You have to save the node and re-edit the person to then find a new checkbox field titled `former faculty`.

# Proposed solution

Possibly use states to show and hide this field?

**Comment by cory-skeers** [comment]
It looks like this chunk
https://github.com/uiowa/uiowa/blob/ee0c4e1a27c1e6e0e81e836986394c9e454ce91e/docroot/modules/custom/sitenow_people/sitenow_people.module#L264-L284
is doing double duty for the exposed filters people list block and the node form, but the form structure is different for both. On the node, `$type` and `$person_type_status_options` end up being `null`, and the form isn't updating. After saving and re-editing, the field is visible because it isn't relying on ajax at that point.
