### ISSUE TITLE
make ckeditor responsive

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#3791]
# Problem
CKEditor has fixed width set so as you resize the browser window the editor gets covered up.

https://user-images.githubusercontent.com/731952/125478407-a4306b9a-0518-43aa-ab3f-b38312880cf0.mov

**Comment by joewhitsitt** [comment]
I think this might be the related d.o ckeditor issue: https://www.drupal.org/project/drupal/issues/3218421

**Comment by pyrello** [comment]
@bewoldt Can you explain the use case here? Is this something that you are going to need to do a lot?

**Comment by bewoldt** [comment]
@pyrello Resizing the browser? Yeah, I do that a lot.

**Comment by bewoldt** [comment]
It looks like the editor breaks when you add enough content to resize the editor window.


https://user-images.githubusercontent.com/731952/125664260-4914c896-222c-4697-b388-c41ff8666e38.mov

**Comment by pyrello** [comment]
But is it necessary to resize the browser while using the WYSIWYG editor?

**Comment by bewoldt** [comment]
I was just trying to help by pointing out a UX issue. I realize this is a Drupal problem.

**Comment by pyrello** [comment]
@bewoldt I appreciate you bringing it up. My questions are based on trying to understand how to prioritize solving this. I have not encountered it myself, but I appreciate that my experience is not everyone's. If this is something you encounter a lot and other people are having this issue, then I think it is important to solve it sooner rather than later. If it is, however, not an issue you commonly experience and more of an issue about making the system work as well as it possibly can, I would probably not choose to prioritize it over the many other items we have in our backlog. We have to make a lot of these decisions all the time, so the better we understand the impact of the problem, the easier it is for us to decide.

**Comment by bspeare** [comment]
@bewoldt are you still seeing this as an issue?  I just tried to recreate it and I wasn't able to.  If you are, can you create a page on the sandbox site?

**Comment by bewoldt** [comment]
@bspeare No, I am not seeing this issue anymore.

**Comment by joewhitsitt** [comment]
Closing as it is no longer reproducible. I think this issue was resolved with the adoption of CKEditor5. The upstream issue above, though still open, relates to CKEditor4
