### ISSUE TITLE
Audit P2LB PR and clean up #1803

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3792]
# Motivation
#1803 has gotten to be a bit unwieldy and so it need some love to get it back into actionable shape.

# Proposed solution
- [x] Checkout #1976
- [x] `blt ds` a V2 site
- [x] Build or find content example for each Paragraph type.
- [x] Run the conversion tool on your example pages.
- [x] Make note of what works and what doesn't. Pay attention to all the fields on each content type and make sure that we are not losing any data.
- [x] Compile a list of what is not working yet.
- [x] Either: a) Clean up #1803 or b) Create a new issue with the list of remaining tasks and retire #1803.

**Comment by e-marie-w** [comment]
(Putting this here until I know what 'other to-dos' of #1803 are done)
Conversion tool seems to be working fine for most part. Here's the only things I've found so far:
- Events - converting a page with this paragraph style will give me an error. However, the v3 draft was successfully created when I check revisions.
- Background images - in V2 you can set a background image for a section. After converting to a v3 draft the images do not show up. Upon publishing the v3 draft, however, the images are all there.

**Comment by e-marie-w** [comment]
Event paragraph convert error:
`Error message
Notice: Trying to get property 'value' of non-object in sitenow_p2lb_process_paragraph() (line 651 of modules/custom/sitenow_p2lb/sitenow_p2lb.module).
sitenow_p2lb_process_paragraph(Object, Object) (Line: 217)
sitenow_p2lb_process_section('1625', Object, Object) (Line: 58)
sitenow_p2lb_node_p2lb(Object) (Line: 36)
Drupal\sitenow_p2lb\Plugin\Action\ConvertParagraphsToLayoutBuilder->execute(Object) (Line: 22)
Drupal\Core\Action\ActionBase->executeMultiple(Array) (Line: 129)
Drupal\system\Entity\Action->execute(Array) (Line: 415)
Drupal\views\Plugin\views\field\BulkForm->viewsFormSubmit(Array, Object) (Line: 185)
Drupal\views\Form\ViewsFormMainForm->submitForm(Array, Object) (Line: 187)
Drupal\views\Form\ViewsForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 113)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('views_form_content_page_1', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 219)
Drupal\Core\Form\FormBuilder->getForm(Object, Object, Array) (Line: 2258)
Drupal\views\Plugin\views\display\DisplayPluginBase->elementPreRender(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 781)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 372)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 444)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 706)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Notice: Undefined variable: pager in sitenow_p2lb_process_paragraph() (line 666 of modules/custom/sitenow_p2lb/sitenow_p2lb.module).
sitenow_p2lb_process_paragraph(Object, Object) (Line: 217)
sitenow_p2lb_process_section('1625', Object, Object) (Line: 58)
sitenow_p2lb_node_p2lb(Object) (Line: 36)
Drupal\sitenow_p2lb\Plugin\Action\ConvertParagraphsToLayoutBuilder->execute(Object) (Line: 22)
Drupal\Core\Action\ActionBase->executeMultiple(Array) (Line: 129)
Drupal\system\Entity\Action->execute(Array) (Line: 415)
Drupal\views\Plugin\views\field\BulkForm->viewsFormSubmit(Array, Object) (Line: 185)
Drupal\views\Form\ViewsFormMainForm->submitForm(Array, Object) (Line: 187)
Drupal\views\Form\ViewsForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 113)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('views_form_content_page_1', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 219)
Drupal\Core\Form\FormBuilder->getForm(Object, Object, Array) (Line: 2258)
Drupal\views\Plugin\views\display\DisplayPluginBase->elementPreRender(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 781)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 372)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 444)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 706)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

**Comment by e-marie-w** [comment]
~Noticed problem with converting carousels to v3. When the carousel is in a two column section it disappears from the v3 layout builder. I think it's because slider blocks can only exist in one column sections. Carousels in one column sections do correctly convert to sliders in v3 layout builder.~

Other issue is that regardless of whether it disappears or turns to a slider in layout builder, it still looks like the v2 carousel when viewed, even when I publish the v3 version.

**Comment by e-marie-w** [comment]
Correction: Carousels in one column sections SOMETIMES correctly convert to sliders. Apparently clicking the Layout tab before you've converted the page to v3 stops it from converting correctly.

**Comment by e-marie-w** [comment]
Update: the main issue is actually captions/headlines. If the carousel items have something in the caption field they convert fine, regardless of if they're one column or two column or three column. The caption fields correlates to the headline field in the slider slides. This headline field is required to save the slide. Captions on carousel items are not required. 

So, possible solutions, off the top of my head: have some default text to fill in the headline field if the carousel item doesn't have a caption. Or, run a check for captions and not allow the page to be converted until the caption fields all have text.

**Comment by e-marie-w** [comment]
I mentioned issues with visiting layout builder before converting to v3, I'm examining it in-depth now.

### For every paragraph style:
If you visit layout builder BEFORE converting to v3 but DO NOT SAVE in it, once you have converted to v3 and go back to layout builder it will tell you you have unsaved changes and it will resemble the v2 block if you click configure. If you click 'Save Changes' layout builder will keep it in this v2 block. If you instead click 'Discard Changes' layout builder will correctly display the v3 block configure options.

Now, if you visit layout builder BEFORE converting to v3 and DO SAVE in it (regardless of whether you actually changed anything), once you convert the page to v3 and go back to layout builder it has duplicated every piece of content. The first version of every block is the v2 configuration. The second version of every block is the v3 configuration. The published page does not have the content blocks repeated and instead only displays the v2 blocks.

**Comment by e-marie-w** [comment]
Not convinced the converted and published v3 page is displaying right, I think it's instead still showing the v2 version. I've assembled a list of differences between the published page and layout builder, and included any problems I noticed.

- Cards: v2/published page with content in link field makes the entire card clickable to follow the link, layout builder adds a clickable button for the link. Also, the subtitle and text fields from v2 are captured in the excerpt field for v3, however, the text format (minimal HTML or plain text) is not set for the excerpt field. 
- Featured Content, Image Gallery, Events, Articles: display/hide value of title field in v2/published page is set to opposite value in headline field in layout builder
- Webform: v2/published page correctly displays/hides title field, layout builder shows title field regardless of display/hide. Also, since there isn't a headline field for webform in layout builder there is no way to change the text or display setting
- Accordions: v2/published page correctly displays/hides title field, layout builder does not display or capture the title field in the headline field.
- People: v2/published page correctly displays/hides title field, layout builder does not display the title field and I'm unsure if it's being captured (v3 people block not editable)
- People, Articles, Events - v2/published page formatted differently than in layout builder. Also, these three types are not editable in layout builder, even though they're not the v2 uneditable block. 
- Carousel: Mentioned before that v2/published page still displays the carousel while layout builder shows the slider. Also, the carousel title field is not being captured in the slider headline field.

**Comment by e-marie-w** [comment]
Now I'm looking at what happens if you go back to the edit tab after converting a page to v3. If you make changes and save them in the edit tab, it will show on the page because it's still displaying the v2 version. In layout builder, however, the page is still the same as when you converted it (or, if you made/saved changes in layout builder after converting it to v3, it's still that). 

I assume we're just going to recommend that after converting a page to v3 people only work on that page in layout builder? But I messed with what I thought people still might try to do (aka convert the page again after changing stuff in edit) just in case. If you save a converted page in the edit tab, convert it to v3 again, and then check layout builder, it sometimes now displays the original converted page's blocks followed by the new converted page's blocks. Other times, layout builder only displays the original converted page's blocks and tells you there are unsaved changes. I'm having trouble identifying what factors cause two sets of blocks and what factors cause only one. 

For now, I'm going to leave this at 'converting a page again doesn't work.' If we end up needing to know I can continue investigating what causes one set of blocks vs. two sets of blocks.

**Comment by e-marie-w** [comment]
One last thing I'm not sure about. On a v2 page if I check layout builder I can see the "placeholder for the 'Main navigation' block" left column thing. And the published v2 page does not show me any child pages I have added. When I convert a page to v3 and publish it, I can then see the child pages in the left sidebar. But when I go to layout builder the placeholder is gone. So I'm confused if it's completely working or not.

**Comment by e-marie-w** [comment]
Closing in favor of #3878 and #3880, which better organize the problems mentioned in comments here. Future work can be tracked on those issues.
