### ISSUE TITLE
As a visitor to uiowa.edu, I can read the university's mission, vision, and values.

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#3839]

**Comment by mjoneill** [comment]
Mission, vision, values document is here: https://iowaweb.slack.com/files/U3ZNGRC30/F028SGBVDEW/mission_vision_values.docx

**Comment by mjoneill** [comment]
Adding @ABoston88

**Comment by ABoston88** [comment]
Making some styling adjustments, still. But this is now visible at: https://uiowa.edu/about-iowa

**Comment by mjoneill** [comment]
Reopened, hoping that @bspeare can take a look.  Seems like we have some vert-alignment opportunities, or perhaps more?

**Comment by bspeare** [comment]
@mjoneill @ABoston88 We would need to add a new banner style for aligning the text to the top of the banner to fix this alignment issue.  Right now the only options are centered and bottom aligned so this layout should probably use text areas or cards in order to align properly to the top.

I think we should also flip the styling on the Mission and Vision columns so that the right column has the gray background.

**Comment by ABoston88** [comment]
Apologies it took me so long to get back to this. Changes made. Let me know if anything else is needed, here.
