### ISSUE TITLE
Graduate Admissions site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3842]
Grad Admissions would like an Areas of Study content type that has similar fields to the existing Grad Admissions site (https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc=%7B611D3AB0-35BC-4BB4-A703-71548F2D1778%7D&file=AoS_Fields.docx&action=default&mobileredirect=true). 

There is also another content type for Estimated Costs (similar to transfer tips on admissions) that would relate to an Area of Study that provides specific cost estimations for each program and can be referenced to one or many programs. (Fields should be similar to existing content type on current Grad Admissions site - Year and costs for US and year and costs for international)

Additionally, each Area of Study would have the ability to reference one or more Colleges (similar to main Admissions site), and those Colleges would be output as a link on the Area of Study. The Colleges should also be able to contain information such as an image, description, link and display list of referenced areas of study.

Grad Admissions would like to display the Areas of Studies similarly to the main admissions site (https://admissions.uiowa.edu/areas-of-study). One catch here is that each Area of Study can have one or more degree options that may contain the same or different information.

Grad Admissions has also requested we migrate content from the existing Grad Admissions site (Areas of Study, Estimated Costs, Colleges, degree types?).

# Proposed Solution

- [x] #4521
- [x] #4520
- [x] #4475
- [x] #4476
- [x] #4568
- [x] #4473
- [x] #4628 
- [x] Views page
  - Taxonomy based view (term per row), bringing in the see also field or term description and a comma separated series of linked degree types going to the AoS study node. User filtered on degrees and colleges
- [x] #4627 
- [x] #4638

**Comment by pyrello** [comment]
> No PDF stuff

Yay!

**Comment by pyrello** [comment]
A question that came up in grooming: Is there any opportunity to use the existing generic Areas of Study feature (not the Admissions one) and extend it? Or do we want to just forgo that because it ended up making the previous Admissions Areas of Study work more difficult and we ended up splitting them apart anyways?

**Comment by joewhitsitt** [comment]
So the ideal view display has a single row per area of study taxonomy term which the content type references (potentially multiple going forward), the `See also` information will move from the content type to the taxonomy. The migration will also have to account for the `See also` information moving from content to taxonomy.

I don't see a way around having a separate AoS taxonomy for this content.

**Comment by joewhitsitt** [comment]
>Is there any opportunity to use the existing generic Areas of Study feature (not the Admissions one) and extend it?

The previous Admissions AoS has been completely split off from the feature. I see more similarities with the grad admissions stuff and the AoS feature. It might be a good starting point, but we might find ourselves down the same path where we ultimately break away completely to make maintaining the AoS feature easier for simpler sites (education, distance).

**Comment by joewhitsitt** [comment]
For the views page, I thought I was being clever by going down this approach (taxonomy view where there is only one row for each term and the degree types queries and combines all results linking back to their nodes). This works... until you want to try and filter by the colleges and degrees on the view. Not sure which one (or both) is preferred.

```php
if (isset($variables['view']->field) && $variables['field']->realField == 'nothing' && $variables['field']->options['id'] == 'nothing') {
          $tid = $variables['row']->_entity->get('tid')->value;
          $nids = \Drupal::entityQuery('node')
            ->condition('status', 1)
            ->condition('type', 'area_of_study')
            ->condition('field_area_of_study_area', $tid)
            ->execute();
          if (!empty($nids)) {
            $degree_types = '';
            $node_storage = \Drupal::entityTypeManager()->getStorage('node');
            $nodes = $node_storage->loadMultiple($nids);
            foreach ($nodes as $node) {
              if ($node->hasField('field_area_of_study_degree_types') && !$node->get('field_area_of_study_degree_types')->isEmpty()) {
                $tids = $node->get('field_area_of_study_degree_types')->getValue();
                foreach($tids as $tid) {
                  $term = Term::load($tid['target_id']);
                  $options = ['absolute' => TRUE];
                  $url = Url::fromRoute('entity.node.canonical', ['node' => $node->id()], $options);
                  $degree_types .= Link::fromTextAndUrl(t($term->label()), $url)->toString() . ', ';
                }
              }
            }
            $degree_types = trim($degree_types, ', ');
            $variables['output'] = [
              '#markup' => $degree_types,
            ];
          }

        }
```

<img width="1288" alt="Screen Shot 2021-12-28 at 3 31 58 PM" src="https://user-images.githubusercontent.com/4663676/147608579-17ac81ec-5e0f-4bde-9bc3-a1008cbfa7bc.png">

A way to handle this pickle via content is to also place the degree types and colleges references on the AoS taxonomy. Duplicates the maintenance of content but not visible to the user.

There is a views_merge module out there but the core patches it relies on don't seem to be moving along. I think this way would be a content based view "merged" on taxonomy term. Some processing will still have to be done to link the degrees to the node instead of the degree term.

**Comment by pyrello** [comment]
Added an optional bullet point related to [this comment](https://github.com/uiowa/uiowa/pull/4523#issuecomment-1002679900):

> The taxonomies are all public but should they be? Should we rabbit hole AoS and degree type terms?
