### ISSUE TITLE
As a developer, I can create a migration script for the Physics ITU site content to a new site.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#3904]
# Story

As a developer, I can create a migration script for the Physics ITU site content to a new site. Currently not sure of the future domain name, but this needs to be moved away from the Physics website.

# Proposed solution

**Here is the 'Physics ITU' content type structure on the existing physics.uiowa.edu site:**

Title
Physics ITU Courses Category (field_physics_itu_category) - Term reference to Courses taxonomy
Physics ITU Labs Category (field_physics_itu_labs_category) - Term reference to Labs taxonomy
Physics ITU Tutorials Category (field_physics_itu_tutorials_cate) - Term reference to Tutorials taxonomy
Physics ITU Body (field_physics_itu_body) - Long text and summary (includes embedded images)
Physics ITU File Upload (field_physics_itu_file_upload) - File
Physics ITU Image (field_physics_itu_image) - Image

**Here is the structure of the Courses taxonomy:**

Name (name)
Description (description)
Physics ITU Taxonomy Body (field_physics_itu_taxonomy_body) - Long text and summary
Physics ITU Taxonomy Image (field_physics_itu_taxonomy_image) - Image
Physics ITU Taxonomy Category (field_physics_itu_category) - Term reference to Courses taxonomy

**Here is the structure of the Labs taxonomy:**

Name (name)
Description (description)
Physics ITU Taxonomy Body (field_physics_itu_taxonomy_body) - Long text and summary
Physics ITU Taxonomy Image (field_physics_itu_taxonomy_image) - Image
Physics ITU Taxonomy Category (field_physics_itu_labs_category) - Term reference to Labs taxonomy

Path settings would need to strip the /itu at the start of the path and maintain the remaining path in the new site.

It seems like the tutorials and courses pages are of the Physics ITU content type, and the labs are all taxonomy items. There is a menu structure as well as a taxonomy structure for most of these items.

It might be easier to just rebuild all of this from the ground-up.

**Comment by cory-skeers** [comment]
Menu structure's one thing we haven't worked with yet in migrations--generally it's been a process of migrating content in, and then manually setting up the menu after. For some migrations it's still been useful to get all the pages pulled in prior to the menu, unless it'd be useful to start from scratch in order to re-think the structure.

For the fields themselves, we should have a path available for everything. There might need to be minor updates to the image field in order to work for non-image files, but I'm not sure that's even needed. They can be migrated into a file field of a new content type, or appended to the end of the body if something like a Basic Page is used.

I think the main complication here is how the taxonomy content gets handled, and their extra fields. We can fetch any of the fields based on reference to pull them into whatever content type the Physics ITU content gets migrated into, or put into their own content.

It'd be a decent amount of custom work, but not overwhelming. The main things that would need to be decided first is if it's getting migrated into an existing content type(s), or how that will work, and if it's important to try to migrate the menu structure as well or if it's alright to put that together post-migration.
