### ISSUE TITLE
Immunology - Why are new students not showing up in Students list?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#3913]
# Problem

New people of person type Student have been added to the site but they are not showing up on this list:

https://immuno.grad.uiowa.edu/people/students

**Comment by mark-bennett-uiowa** [comment]
I mentioned this to Marie, but could it be the Program start date. If you look at Kyra Watral, her start date hasnt occured. Is there anything in the view code that is filtering based on this field? Other than the University ID, Its the only field or tag that I see is different.

Update: I changed her start date to something that had already occurred, and added a University ID in that field, and she still didnt show up in the students list. I cant seem to find a way to access that view filtering. Is this custom code, or through an admin screen?

**Comment by bspeare** [comment]
Looks like the contextual filter set to `field_person_contact_information` is causing this bug because some of the profiles do not have this contact address information attached.   Do you need this contextual filter?

**Comment by bspeare** [comment]
The options to fix this are to either remove the contextual filter as in (https://github.com/uiowa/uiowa/pull/3964) or specify to editors that they must include "Lab" as the title to the address field, otherwise the profile won't show up. 

<img width="808" alt="Screen Shot 2021-08-13 at 8 15 51 AM" src="https://user-images.githubusercontent.com/1036433/129362764-0244a907-0b9c-4a69-b0cf-c7ae675f0b85.png">
