### ISSUE TITLE
Update signage, recserv and UHD Outlook integrations to use new API.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3933]
Develop a signage widget that displays UCC Conference space reservations similar to EMS and Mazevo.

We will only display the date, time and summary 

Test environment Resource Group and example API call.
https://es-apps-test.iowa.uiowa.edu/hours/api/v2/signage

https://es-apps-test.iowa.uiowa.edu/hours/api/v2/signage/RES-UCC2429-ConfRoom?nohtmldesc=true&start=2021-08-01&end=2021-09-01

**Comment by richardbporter** [comment]
This is basically the gist of it. We won't need as many fields on the custom content pane edit form. 

There are some examples of working with this type of Exchange data in uiowa703: dining_hours within dining.uiowa.edu and rec_hours within recserv.uiowa.edu.

**Comment by richardbporter** [comment]
It doesn't look like the signage endpoint exists in prod (https://es-apps.iowa.uiowa.edu/hours/api/v2/signage) so we'll want to get that added and use it when ready.

**Comment by richardbporter** [comment]
I would start by duplicating the mazevo content pane and add/remove as necessary using the examples mentioned above as reference.

**Comment by briand44** [comment]
Good opportunity to test upgrading signage php7.4

**Comment by joewhitsitt** [comment]
This is on the signage application `signage-outlook` for review. We need the [final endpoint](https://github.com/uiowa/uiowa/issues/3933#issuecomment-900633741). Disables the EMS widget as well.

**Comment by richardbporter** [comment]
I'll take a look at this.

**Comment by richardbporter** [comment]
Checked out in dev. Sent email to customer for review.

**Comment by richardbporter** [comment]
Approved by customer. Future tweaks might be possible to room name. We may want to change the default API endpoint to prod URL when that is ready.

**Comment by richardbporter** [comment]
There is a new test API URL that reflects changes that will be deployed to production once we give the go ahead. It is https://hours-test.iowa.uiowa.edu/api/Hours/signage/ The parameter format hasn't changed but some other things have:
 
- The start/end fields are now formatted using ISO 8601 dates (e.g., 2021-09-15T14:30:00Z instead of 1631714400, the integer Unix epoch).
- There is a bonus $id field it adds in case the JSON self-references (in our case, I believe it does not).
- The day groups now appear in sorted order.

I think we'll need to try out this new URL and make any adjustments necessary. 

Also, this new URL is what D7 UHD and RecServ sites will need to use for hours so we'll have to update that code as well. That could be done separately and represents an obviously thinner slice however, it might be advantageous to address them all at once while this is fresh in our minds.

**Comment by richardbporter** [comment]
>That could be done separately and represents an obviously thinner slice

If we went that route, it sounds like UHD and RecServ would need to be updated within one month, before the server switchover.
