### ISSUE TITLE
Consider moving all CLAS sites to a new uiowa0x application once one opens up?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#4153]
With uiowa01 reaching its SAN limit (thanks to the 10 new DWLLC sites), and nursing potentially reaching the point of its launch, would it be a potential option to move all CLAS collegiate and department sites to a newly "recovered" application? That way, the "high-maintenance" college can be off on its own and not disrupt the other applications. Would require new SSL certificates (easy enough), database and file migration.

- How possible is it to move sites from one D9 application to another?
- What time constraints does this put on the developer?
- Can databases and files be moved "easily"?
- Is this even a possibility for consideration?

**Comment by pyrello** [comment]
Here is a theoretical idea for how this could work:
* You would need to create a temporary drush alias file for the site at the new server using the `.prod.drupal`. This will be necessary for syncing the database and files later.
* Set up the `.prod.drupal` domain on the new application.
* Create the database(s) for the site on the new application.
* Run the site install command on the new server - I think this will work because it looks for the existence of the database, but @richardbporter will correct me if I'm wrong.
* Sync the database and files from the current site to the new site.
* Move domain from the current application to the new application.
* Release a code update which updates the sites permanent drush alias file to point to the new server.
* If there is any reason why you need to continue to access the old version of the site, you may need to update the temporary drush alias file to point to the old server.
* Whenever you are done, release a code update to remove the temp drush alias file.

While it may be technically possible, I guess I'm not sure what the value would be. What problem are we attempting to solve? It won't make any difference in the current process of using config split for sites or features. It won't make it easier to introduce new features that are CLAS-specific, because it will still run on the same underlying application. If it weren't to rely on the same underlying application, then CLAS would be inviting a ton of work on themselves to maintain that application separately from the other platform.

I think it's a good question to ask, but I honestly can't see any benefit in doing it. We will probably end up moving sites, but I think it would actually create more work to try to make sure that only CLAS sites were placed on a single server.

**Comment by richardbporter** [comment]
I agree with everything @pyrello said. Another thing to note is that the SAN limit is more a best practice for performance and not a hard technical limit (https://github.com/uiowa/uiowa/issues/3136#issuecomment-805247370).

I know what we have isn't perfect and needs improvement but this feels like a step backwards and doesn't seem to have any tangible benefits. It also creates an illusion that these "isolated" applications can do whatever they want without affecting anyone else which simply isn't true.

**Comment by mark-bennett-uiowa** [comment]
Sounds good, and I appreciate the feedback. Closing this issue.

**Comment by pyrello** [comment]
While I don't think it is a good idea to do this for moving CLAS sites specifically, we may want to create a process for moving sites in the future to streamline SSL cert management or for other reasons. I thought there was an issue in the backlog about it, but I couldn't find it. At least if we do want to do that at some point, we have the start of a process worked out.

**Comment by richardbporter** [comment]
> Here is a theoretical idea for how this could work:
> 
> * You would need to create a temporary drush alias file for the site at the new server using the `.prod.drupal`. This will be necessary for syncing the database and files later.
> * Set up the `.prod.drupal` domain on the new application.
> * Create the database(s) for the site on the new application.
> * Run the site install command on the new server - I think this will work because it looks for the existence of the database, but @richardbporter will correct me if I'm wrong.
> * Sync the database and files from the current site to the new site.
> * Move domain from the current application to the new application.
> * Release a code update which updates the sites permanent drush alias file to point to the new server.
> * If there is any reason why you need to continue to access the old version of the site, you may need to update the temporary drush alias file to point to the old server.
> * Whenever you are done, release a code update to remove the temp drush alias file.
> 
> While it may be technically possible, I guess I'm not sure what the value would be. What problem are we attempting to solve? It won't make any difference in the current process of using config split for sites or features. It won't make it easier to introduce new features that are CLAS-specific, because it will still run on the same underlying application. If it weren't to rely on the same underlying application, then CLAS would be inviting a ton of work on themselves to maintain that application separately from the other platform.
> 
> I think it's a good question to ask, but I honestly can't see any benefit in doing it. We will probably end up moving sites, but I think it would actually create more work to try to make sure that only CLAS sites were placed on a single server.

Reminder to maybe extract this into another issue since it outlines the process of transferring sites between applications.

**Comment by pyrello** [comment]
> Reminder to maybe extract this into another issue since it outlines the process of transferring sites between applications.

Done
