### ISSUE TITLE
Ability to Duplicate Pages

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4223]
# Story

As a content editor/webmaster, I would like to be able to duplicate an entire page so that I don't have to recreate it from scratch to have a consistent look.

# Additional Info

Replicate and Replicate UI modules have been discussed as a potential way forward.

Some additional information and conversations have been captured https://github.com/uiowa/uiowa/issues/2848.

Some more thoughts on possible issues with replicate https://github.com/uiowa/uiowa/pull/4214#issuecomment-929709156

# Proposed solution

Use replicate, replicate_ui, [this patch](https://www.drupal.org/project/replicate/issues/3100763), and possible a custom event listener to provide this functionality.

If entity_clone is used in place of replicate, there is a [patch here](https://www.drupal.org/project/entity_clone/issues/3050027) that is aimed at getting paragraphs nested under blocks working (may also be useful in setting up any necessary event subscribers for replicate).

**Comment by GaryRidgway** [comment]
Investigating entity_clone has left us in a much better place than the replicate module, but it REALLY clones things. So much so that we probably want to dial it back a little bit. a few things to need to have solved in order to be able to use this module would be:

- [x] Referencing media entities instead of making a copy of media entities.
- [ ] Creating a copy of view blocks instead of a new revision of a view block.
- [x] Referencing taxonomies instead of copying taxonomies.
- [x] Permissions

**Comment by cory-skeers** [comment]
Potential permissions patch: https://www.drupal.org/project/entity_clone/issues/2931143

**Comment by GaryRidgway** [comment]
We have found that entity_clone does not update the uuids in configuration for the entities that it clones. This leads to the scenario where layout builder block configuration will point to the `revision_id` for one block, but the `uuid` of a different block. This is obviously a problem, because no two things should ever have the same uuid (especially if they have different `entity_id` and `revision_id`). 

At this point there is a lot of custom code that we would have to write to update the `uuid`s for everything. Is this a deal breaker? Should we proceed? should we look at the template module? We are a little unclear on a path forward.

**Comment by joewhitsitt** [comment]
does replicate generate new uuids?

**Comment by briand44** [comment]
I would be in favor of trying the page template module. It may be more overhead for a user to save a page as a template and then create a new page using that template but if it works nicely it would basically achieve the desired goal and may give us options in the future to programmatically create templates.

**Comment by GaryRidgway** [comment]
> does replicate generate new uuids?

Replicate was not working for non-reusable blocks, but there is a patch for that that _should_ work, but in our original pass it didn't work for everything. I don't think we even got far enough to test the uuid issues with `replicate`.

**Comment by bspeare** [comment]
> I would be in favor of trying the page template module. It may be more overhead for a user to save a page as a template and then create a new page using that template but if it works nicely it would basically achieve the desired goal and may give us options in the future to programmatically create templates.

@briand44 The page template module relies on the Replicate module.

**Comment by bspeare** [comment]
> I would be in favor of trying the page template module. It may be more overhead for a user to save a page as a template and then create a new page using that template but if it works nicely it would basically achieve the desired goal and may give us options in the future to programmatically create templates.

I think we should pursue https://github.com/uiowa/uiowa/issues/2378 before moving forward with the page template module.   There is already work started with that issue and it would possibly allow us to provide templates for the entire service on not just on a per site basis.

**Comment by briand44** [comment]
After replicating the home page and publishing the new page, I deleted the new page and got the following error:
`The website encountered an unexpected error. Please try again later.`

**Comment by joewhitsitt** [comment]
ruh roh

**Comment by briand44** [comment]
this is on default.stage if we want to check logs. I am going to continue testing to see if it happens with any page or if this is because it is home page or default content.

**Comment by joewhitsitt** [comment]
might want to get @richardbporter to provide thoughts about cherry picking the branch out of main so we have more time to work on it

**Comment by joewhitsitt** [comment]
`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 143 of core/lib/Drupal/Core/Entity/EntityTypeManager.php).`

is what i got on sandbox local homepage (copy) when deleting

**Comment by cory-skeers** [comment]
> this is on default.stage if we want to check logs. I am going to continue testing to see if it happens with any page or if this is because it is home page or default content.

On a local copy of main, I tried just creating a new page (not replicate), publish, and delete, and get the same error.

**Comment by cory-skeers** [comment]
It looks like it's occurring after any page has been replicated, but after that, whenever any page is deleted...I think.

**Comment by joewhitsitt** [comment]
Talked to Rick. So, we can't undo this from main. There are sites being staged and the removal would cause errors.

What we can do is either update permissions again to now allow OR set the `replicate_allowed` to empty on all sites. Our checks would then prevent replicate from taking place (even for admins)

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/4306

**Comment by joewhitsitt** [comment]
Replicate is still enabled on sites but is preventing users from triggering the functionality.

Cory did some digging and it seems to be an issue with slider/collection where replicate is duplicating referenced paragraph items.

**Comment by cory-skeers** [comment]
Steps to reproduce:

- Replicate a page which uses either sliders or accordions (blocks w/ nested paragraphs)
- Publish the replicant page
- Delete the replicant page
- Attempt to view the original page, and get a WSOD

Looking at the `entity_usage` table, or loading in the paragraph and checking `->getParentEntity()` both seem to point to that new paragraphs are being created (so the original should not end up with multiple parents), and that the parentage on the new paragraphs are being set correctly (so that the new paragraphs are listed as children of the replicant page's block, and not the original page's block).

More digging is needed. Have narrowed it down to: deleting a replicant page creates an issue with the original page if and only if a paragraph was replicated.
