### ISSUE TITLE
Require Authentication to view all content on SiteNow site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4241]
# Story

As a SiteNow v3 site owner, I would like to have all my content behind authentication so it is not available publicly.

# Additional Info
It would be nice if there was some sort of option or split that could be enabled that would automatically make it so authentication was required to view content. That same option or split would also turn on all of the related functionality in future slices.

# Related Issues
#4242 
#4243 
#4244 

# Proposed solution

**Comment by briand44** [comment]
Doesn't need to be a checkbox to enable this, it could be a manual process that needs to happen. If so, we should document the process.

**Comment by briand44** [comment]
Want to avoid the possibility of this accidentally getting turned off/on and causing issues or displaying content that should not be public.

**Comment by mjoneill** [comment]
For consideration for sites that require authentication to view content:

* We need a search solution that doesn't rely on Google indexing public pages
* robots.txt should likely be disallow all bots and agents
* Sitemap.xml should NOT disclose pages that are not accessible without authentication.
* Each page should have the meta noindex, nofollow tag set in the meta.  <--- extra layer of protection in case the pages are made visible by accident

Undoubtedly more as we think through this further...

**Comment by pyrello** [comment]
I haven't read this yet, but it may be relevant: https://robertroose.com/blog/drupal/how-create-groups-within-drupal-which-can-share-nodes-and-files-privately

**Comment by joewhitsitt** [comment]
if the first slice is just stopping folks at the bootstrapped drupal level this looks like an easy step forward that could be separate in a feature split: https://www.drupal.org/project/require_login

**Comment by cory-skeers** [comment]
> if the first slice is just stopping folks at the bootstrapped drupal level this looks like an easy step forward that could be separate in a feature split: https://www.drupal.org/project/require_login

I'm having trouble getting this set up to test locally. Visiting any page (including the login page) redirects to the homepage, and I'm not sure why. If the homepage is excluded from needing to log in, that's the end of it. If it's not excluded, a redirect loop occurs between the home and login pages.

Don't see any issues in the module, and saml routes seem to be properly excluded to where I'd think there wouldn't be an issue there.

**Comment by cory-skeers** [comment]
https://www.drupal.org/project/restrict_ip seems to work well out of the box in initial testing. By blocking all IP addresses (or allowing a select few like local connections) and allowing specific roles to bypass the blocking, it can be used to lock down all or parts of a site except for specific roles, which would work for assigning AD groups in the future.

Also has options to redirect to an existing login page, include a message re: logging in, etc that could be customized to fit our needs.

**Comment by joewhitsitt** [comment]
It is also "recommended" by Acquia for restricting website access - https://docs.acquia.com/cloud-platform/arch/security/restrict/

though it also says...

>If you are restricting an entire website, using Drupal’s access controls and requiring an authenticated user are better methods of accomplishing this goal.

So do we just need to split permissions and dress up the access denied page?

**Comment by richardbporter** [comment]
>Even with these protections in place, Varnish® can cache a restricted webpage if the webpage isn’t specifically marked uncacheable

We'll need to make sure all "intranet" pages are marked with the appropriate Cache-Control headers to prevent this.

**Comment by joewhitsitt** [comment]
going to push this forward a bit. swarming welcome!

**Comment by joewhitsitt** [comment]
One thing to note with restrict_ip and probably other modules is that by using the access denied option instead of sending traffic directly to saml login is that the header and footer are exposed (fyi, squeezed almost mobile screenshot):

<img width="880" alt="Screen Shot 2022-01-05 at 5 14 19 PM" src="https://user-images.githubusercontent.com/4663676/148303178-ceb71910-6441-436c-80c8-657e9a69f427.png">

**Comment by pyrello** [comment]
> One thing to note with restrict_ip and probably other modules is that by using the access denied option instead of sending traffic directly to saml login is that the header and footer are exposed

Would we not want to show header and footer? I wasn't under the impression that we were trying to lock those down. Although I guess the menu may technically be in the header, so that could be a problem.

**Comment by joewhitsitt** [comment]
>Would we not want to show header and footer?

Not clear from the requirements, just going off of past drupal intranets (https://intranet.oneit.uiowa.edu, etc.). I think we can take restrict_ip further if needed and alter what regions are allowed using `hook_restrict_ip_whitelisted_regions`

I'd like to try this branch in DEV with the redirect to saml login just to experience it. Locally, I am getting a loop issue because saml isn't there.

**Comment by joewhitsitt** [comment]
Updated thought, I don't think the immediate redirect to saml is wise. It is a different website and people will wonder if they are logging into to the correct site.

**Comment by quamsta** [comment]
+1 for not redirecting to SAML automatically.

However, can the "Access Denied" page be a bit more friendly? It might be okay for someone stumbling on or entering an admin section they don't have access to, but seems harsh for an intranet environment. 

We dressed our SilverStripe intranet, "Student Life Connect" up with a support email address to help smooth over any login issues with some code we are using to check AD groups and such:

<img width="1288" alt="Screen Shot 2022-01-06 at 1 55 41 PM" src="https://user-images.githubusercontent.com/472923/148443170-e902955d-12e3-4f45-bdae-cdd88dba16a6.png">

**Comment by joewhitsitt** [comment]
Absolutely want to freshen it up but i'd like to decide if this is the route we are headed

**Comment by quamsta** [comment]
Gotcha, I see you mentioned the dressing up part earlier now. Carry on haha.

**Comment by joewhitsitt** [comment]
Sounded like the team is comfortable moving forward with restrict_ip so I have a list of todos left on the PR - https://github.com/uiowa/uiowa/pull/4626

**Comment by joewhitsitt** [comment]
Removing myself for now since I will be out tomorrow

**Comment by joewhitsitt** [comment]
@briand44 should we create an epic for this and the other related issues? I have a list of future considerations to add and none of the `intranet` tagged issues are the correct bucket.

**Comment by richardbporter** [comment]
There are a couple issues related to restrict_ip caching: https://www.drupal.org/project/restrict_ip/issues/3052094 and https://www.drupal.org/project/restrict_ip/issues/2941386. However, both steps to reproduce indicate some IP restriction which we aren't doing. I think if we were, we might run into those problems but I'm unable to access a restricted page in dev from an anonymous session.

All I can access from an anonymous session is https://default.dev.drupal.uiowa.edu/robots.txt.

**Comment by joewhitsitt** [comment]
The initial requirements are done and reviewable but it is agreed that the PR should not be merged as-is for the following reasons:

- Customer feedback on if they really need site-wide/lb or if we can just provide the private page content type with private files field
- Probe into splitting private files config

**Comment by joewhitsitt** [comment]
Capturing my thoughts from today's Intranet tour:

- Didn't seem to see examples of creating authenticated "experiences" which needed layout builder functionality, but I did see an "full" authenticated site worth of content that had a menu system, different types of content and a friendly look-feel compared to a Sharepoint site in the right hands.
- Email communication still seems to reign supreme at the U for sending out internal information and that the intranet serves as an archive of that information. I wonder how many groups use a shared calendar as well because it seemed awkward to me to have to login to another site to see that kind of internal events information.
- What also stuck out to me is that Rachel said the purpose of the main site changed to marketing/single audience and that they still needed a place for their other audiences.
- The file storage seemed like a perfect fit for sharepoint and something they are going to have consider anyway.

**Comment by quamsta** [comment]
Hey all,

As I mentioned yesterday, we can also provide a tour of our Intranet solution. Things have been a bit hectic, but we're willing to show this off in the near future. Can we schedule something?

I can provide some screenshots and context too if that helps:

- [Screenshot of the Intranet homepage](https://user-images.githubusercontent.com/472923/149577379-df62f6c4-905c-465b-b7c0-5258901fbf50.jpg)

Some of the big features we use the Intranet for are:

- Internal news posts, including pulled-in RSS feeds from Dispatch emails
- "Start pages" for some departments, essentially large sets of quick links for specific departments that use web apps or other tools, [Example Here](https://user-images.githubusercontent.com/472923/149577026-a2e0706b-c318-4521-8059-9a6bd8c036a5.png)
- Human resources and hiring information
- Training and development information
- Awards and recognition for staff, including a "Thank You"-like program to send and view "High Fives" [Screenshot](https://user-images.githubusercontent.com/472923/149577563-e4c004b2-8816-406a-9ea5-503d12914938.png)

**Comment by joewhitsitt** [comment]
Thank you for sharing at Drupal Dev community. One thing that not mentioned in this issue that I wanted to capture from your demonstration is that you had a destination parameter setup for after login so that if someone came to an interior page from an email or something, once they login, they will be redirected.

I am not seeing anything in the restrict_ip functionality or issue queue that currently does this but I think this would be a nice to have later on.

**Comment by briand44** [comment]
>I am not seeing anything in the restrict_ip functionality or issue queue that currently does this but I think this would be a nice to have later on.

I wonder if an additional module could handle this and not conflict with restrict_ip? I think Login Destination or Login Toboggin maybe did this type of thing in D7
