### ISSUE TITLE
List of articles by author

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4261]
# Story
As a SiteNow user, I would like to have the option to display articles on the authors person page so that visitors can see all the articles that an individual authored.

# Additional Info

Example https://uipress.uiowa.edu/people/matthew-j-c-clark

# Proposed solution

- Setting for default that can be turned on, linked to from other settings page
- Use article teaser default
- Output using pager

**Comment by joewhitsitt** [comment]
Could this just be a slice of https://github.com/uiowa/uiowa/issues/3501?

**Comment by pyrello** [comment]
Potentially! Good call.

**Comment by pyrello** [comment]
This site may not get built on SiteNow. I think this is still potentially a good feature, but I don't need it for that until I get confirmation of that.

**Comment by pyrello** [comment]
This is desired for the 91st Meridian site.

**Comment by makurj** [comment]
Quick note about this: We are working on getting 91st Meridian to be a Regent's site.

**Comment by bspeare** [comment]
Here's what this is looking like so far:
- The article teaser would make more sense without the summary. 
- Pager is set at 3. 
- Any other suggestions for this?

<img width="935" alt="Screenshot 2023-06-26 at 12 53 50 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d9e57684-8389-495a-b21d-c5b2bea1ac4b">

**Comment by bspeare** [comment]
Here is the current checkbox on the settings page.   

- Any suggestions on placement?

<img width="1058" alt="Screenshot 2023-06-26 at 12 58 12 PM" src="https://github.com/uiowa/uiowa/assets/1036433/8907fa2d-acc3-4ca3-a6d7-14606c63d16b">

**Comment by makurj** [comment]
https://github.com/uiowa/uiowa/issues/4261#issuecomment-1607961400 Looks good to me.

**Comment by pyrello** [comment]
> Any other suggestions for this?

The label "Author" seems not quite right to me. "Author of" or "Authored by [name]" could possibly make it more clear. Or "Contributions"

**Comment by bspeare** [comment]
@pyrello good suggestions.   Does the term "Author" box this in too much?  Should it be "Latest from [name]" or something similar?

**Comment by joewhitsitt** [comment]
I had wished we had done it for events, but I don't like the duplication of author/presenter in these content by person view teasers. https://iowasummerwritingfestival.uiowa.edu/people/jennifer-fawcett. I think these teasers should be stripped down to just linked title/date so that it doesn't detract from the actual content on these nodes.

Since this is a view showing articles with the person assigned to the author field, I think it is appropriate for us to do the "Authored by [name]" as Sean suggested which will work with all variations of the article content type (news, articles, updates, periodical issue, etc.)

**Comment by maramcconnell** [comment]
When I spoke to Mike and Natasha at 91st Meridian about this issue, I showed them an author page from UI Press as an [example](https://uipress.uiowa.edu/people/sufiya-abdur-rahman).  This page only lists the title of the authored works.  I will reach out to them to see how they feel about having the summary visible.

**Comment by bspeare** [comment]
Here's the latest.  Hiding everything but Title and date with a more descriptive title of "Authored by [first name last name]".  

<img width="1523" alt="Screenshot 2023-06-27 at 10 15 22 AM" src="https://github.com/uiowa/uiowa/assets/1036433/e8753f60-6803-4083-bf1d-0ebf0c403dd1">

**Comment by bspeare** [comment]
Are there any of these that I don't want to check to make sure this block is displaying on?  

<img width="1355" alt="Screenshot 2023-06-27 at 10 52 50 AM" src="https://github.com/uiowa/uiowa/assets/1036433/cfcbcd30-1e67-4a73-b5ba-a24b3117ae91">

**Comment by joewhitsitt** [comment]
Sounded like uipress already had something for this. Would they be open to merging with this?

ighn_person is a separate content type so no worries there.

i can't speak to the other grad splits.

admissions, pharmacy don't use their person content type in the traditional sense, but if it will be off by default, I don't think there is any harm.

**Comment by bspeare** [comment]
Is the "Point of contact" info supposed to show up on the person node for Iowa Now?  Or is that used elsewhere?

**Comment by joewhitsitt** [comment]
For IowaNow, I thought it was related to the experts list, but then we added it to the default where it is displayed on the node: https://github.com/uiowa/uiowa/pull/6027

**Comment by bspeare** [comment]
Thanks @joewhitsitt, it looks like it was supposed to appear on the person node, but maybe got lost in the card_4x layout update?

<img width="1426" alt="Screenshot 2023-06-27 at 12 51 28 PM" src="https://github.com/uiowa/uiowa/assets/1036433/4e8afd31-e0bb-4822-a6ec-de10c938c7a7">

**Comment by bspeare** [comment]
Does anyone know where `grad_person_extended` is used?  I see that it is inactive on grad.uiowa.edu.

**Comment by joewhitsitt** [comment]
https://immuno.grad.uiowa.edu/

**Comment by bspeare** [comment]
Thanks, how does that work when there is https://github.com/uiowa/uiowa/blob/main/config/sites/immuno.grad.uiowa.edu/core.entity_view_display.node.person.default.yml and https://github.com/uiowa/uiowa/blob/main/config/features/grad_person_extended/core.entity_view_display.node.person.default.yml - does one override the other?

**Comment by joewhitsitt** [comment]
site stacks on top of the feature. so to just focus on this feature. you will want to enable it on the default site and make adjustments there. export. then sync immuno.grad and see what additionally needs to be adjusted. export.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Comment by maramcconnell** [comment]
I got feedback from the folks at 91st Meridian.  They did not like that there are snippets of the articles visible.  They would prefer to just have the title of the article and the issue in which it appeared to be visible and they would like for the article and issue to link to the appropriate pages.

Here is what they said in the email:
"1. Overall, we feel the example below is more than we need. Because the format of issues and pieces varies a fair deal, we don’t think the results of pulling a snippet will look good. So we wouldn’t include snippets.
2. We also wouldn’t include the headshot on the right—we don’t have photos for a bunch of our contributors.
3. Our suggestion would be to only include the title of each piece and the issue in which it appeared—with both pieces of information linking to the appropriate pages (the piece and then the issue, in other words).
4. It also looks like there is a text field in the example where biographical information can be added. That’s good for us—assuming we can include links and such if we want to provide a reference to materials on the other IWP websites."

**Comment by pyrello** [comment]
After taking a look at this for testing, I think we should move the section of the form to enable this setting to the SiteNow Articles configuration page. It just makes more sense to me that way.

Also, thinking about it from a dependency standpoint (as I brought up in EoD yesterday), SiteNow Articles has a dependency on SiteNow People because the person content type has to exist already for the article content type have a reference to it for the author field. Based on this, I also think it makes sense on the Article configuration page.
