### ISSUE TITLE
Add a visual indicator to article teasers that there is more content upon clicking/tapping the article

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#4372]
Similar to https://github.com/uiowa/uids/issues/460, but more specific to articles and article teasers.
# Story

As a user I want to be able to see that an article is clickable and has more content than what the teaser is showing so that I don't miss important details in a longer article.
<details>

![image_from_ios](https://user-images.githubusercontent.com/472923/139934552-8b7a5b33-9def-4ce9-aeb0-f654cc997fa2.png)

</details>

# Proposed solution

# First Slice 

## Card block 

- Add circle button option if link text is not provided: https://github.com/uiowa/uiowa/issues/4372#issuecomment-962091338
  - Rework logic in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/uids/card.html.twig#L108-L122 to display new button
 - Add a modifier class style adjustments to current button style for circle button in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/card.scss
 - Search for all uses of `card` and test: https://github.com/uiowa/uiowa/search?q=card.html.twig
   - As you can see we have 25 templates using the card template such as views templates and custom modules. 
   - V2 Also uses this card template.  

# Second Slice

## List blocks (People, Articles)

- Add checkbox to display a button below each item
  - If box is checked, allow user to add custom link text like "Continue Reading"
  - If no link text is provided, then circle button will be default

Original solution:
<details>
I think adding any of the following to an individual article teaser may help alleviate this:

- Underlined link in the headline indicating that it's clickable (may be less visually appealing, but more functional)
- A "Continue Reading" button (may have accessibility issues, but could be done in a CSS psuedo-class, e.g. `:after { content: "Continue reading" }` to prevent screen readers from repeating "Continue reading" over and over).
- An ellipsis character after the body of the teaser (may be the most elegant, probably also could be done in a pseudo-class
</details>

**Comment by pyrello** [comment]
Is there a way that we could add an icon to headlines that are links? Not sure what that would look like, but maybe that could be a replacement for the link being underlined.

Another idea for this would be to add a button with the text "Read " and the title of the article, but have the article title in a `.sr-only` class so that it would be read in screen readers, but not show up for sighted users.

**Comment by pyrello** [comment]
This article has several ideas about how to add text like "Read more" in an accessible way: https://www.visionaustralia.org/services/digital-access/blog/how-to-make-read-more-links-accessible

**Comment by quamsta** [comment]
Added a screenshot to give some more context to this

**Comment by bspeare** [comment]
Since cards already have the ability to add a button to clarify that there is a link attached to the card, I think it would make more sense to add an option to toggle a "continue reading" button in the list blocks to add that as a display option that is turned off by default.   UIDS does have a minimal button option (see below) that would work well with lists and not add that much visual clutter.   In addition, moving forward with https://github.com/uiowa/uids/issues/460 will help with cards where site owners do not provide a button option.   

<img width="178" alt="Screen Shot 2021-11-02 at 2 24 47 PM" src="https://user-images.githubusercontent.com/1036433/139935863-e29d6bf7-6d05-4ef9-ae8e-2f0ebc56f787.png">

**Comment by quamsta** [comment]
Also, to add some more context and examples from publications and blogs:

When we simply have a headline, byline, and maybe an image, I think it's easily inferred that those items are clickable. It's only when there's a longer content description that this becomes an actual issue.

Examples:

The Onion, small headline and image: no ellipsis or continue reading button
![Screen Shot 2021-11-02 at 3 18 28 PM](https://user-images.githubusercontent.com/472923/139945877-c9b9cbf9-0c35-4210-b82e-1e4a1f7dec4a.png)

The Onion, article with a content description/teaser

![Screen Shot 2021-11-02 at 3 18 50 PM](https://user-images.githubusercontent.com/472923/139945925-5429e292-ad54-44c8-8aad-cdaefd9730dc.png)

Talking Points Memo, small article with headline and image, no ellipsis/continue reading indicator:

![Screen Shot 2021-11-02 at 3 21 02 PM](https://user-images.githubusercontent.com/472923/139946237-97d1a906-ef02-4f22-ab37-00c569799558.png)

Talking Points Memo, article with a content description/teaser

![Screen Shot 2021-11-02 at 3 20 00 PM](https://user-images.githubusercontent.com/472923/139946087-aa6f8e1a-99a2-4d35-b9f8-41dec54b711c.png)

**Comment by bspeare** [comment]
@quamsta Thanks for the examples but we could also post screenshots of major publications and universities that don't provide that link either such as  nytimes.com below.  

<img width="880" alt="Screen Shot 2021-11-02 at 3 35 53 PM" src="https://user-images.githubusercontent.com/1036433/139947916-039fbfb8-ae26-4f73-96fc-ca8dcc352b06.png">

**Comment by quamsta** [comment]
@bspeare  Totally fair!

However, in that NYT example, the teaser is still visually distinguished from normal body text by being gray instead of black. Currently our teasers are the same color and typeface as the rest of the body text on the page, which may lead to some confusion as to whether "that's it" when there are longer teasers entered by the editor. 

I still think there should be some kind of visual distinction from "body text" vs " teaser text," and it doesn't necessarily have to be a button or ellipsis, just... something.

**Comment by bspeare** [comment]
@quamsta Great point about the gray text! Perhaps that's another possible solution.

**Comment by joewhitsitt** [comment]
> However, in that NYT example, the teaser is still visually distinguished from normal body text by being gray instead of black. Currently our teasers are the same color and typeface as the rest of the body text on the page, which may lead to some confusion as to whether "that's it" when there are longer teasers entered by the editor.
> 
> I still think there should be some kind of visual distinction from "body text" vs " teaser text," and it doesn't necessarily have to be a button or ellipsis, just... something.

So should a linked static card should have some visual distinction too? Should https://github.com/uiowa/uids/issues/460 be expanded to offer that distinction without hover/focus as well?

**Comment by joewhitsitt** [comment]
education, if linked the icon shows and is part of the hover/focus effect (invert colors):

<img width="811" alt="Screen Shot 2021-11-03 at 10 15 14 AM" src="https://user-images.githubusercontent.com/4663676/140088611-c501fd66-8cbd-4ea3-92d2-1081eb06ffd5.png">

**Comment by bspeare** [comment]
> So should a linked static card should have some visual distinction too? Should [uiowa/uids#460](https://github.com/uiowa/uids/issues/460) be expanded to offer that distinction without hover/focus as well?

Since cards have the ability to add a faux button, I would prefer to not add an extra icon just to distinguish if the card is linked.   I think some users will use the faux button if they want to reinforce that the card contains a link, and others will want to not clutter up the UX with more visual information to scan.  In your example above @joewhitsitt, the first or second thing you see is the solid icon, not the headline or content.   I think we want to keep the focus on the content.

**Comment by joewhitsitt** [comment]
> I think some users will use the faux button if they want to reinforce that the card contains a link, and others will want to not clutter up the UX with more visual information to scan.

okay so to @quamsta's point, the article teasers are not wired up to show the faux button or provide the option to toggle.

>the first or second thing you see is the solid icon, not the headline or content. I think we want to keep the focus on the content.

good point. agreed that education's example is very link over content focused. it was just to show an non-eplisis, read more version. i have seen examples of a little ghostly faded link icon in a corner of a card that becomes more visible on hover.

**Comment by bspeare** [comment]
Yes, so for articles/lists it sounds like we could implement these items for a solution:

- Add a toggle to show the faux button under each item with "Continue Reading" text
- Make the teaser content gray
- Get better hover/focus styling: https://github.com/uiowa/uids/issues/460

**Comment by pyrello** [comment]
I kind of like that example of the button with no text that @joewhitsitt shared above. Not sure how it would work in tandem with the option to show text also, but I enjoy the visual indicator without unnecessary extra text.

**Comment by bspeare** [comment]
I think the arrow icon next to the title could be cool, but it would set up inconsistent UX for link visual indicators since we are already attaching buttons below the card content as our main visual indicator.  If this is something that we decide to move forward with, what if we just add an arrow icon in place of the button as the visual indicator if no button text is provided?  I've added a screenshot below of a card row featuring an unlinked card, a linked card without button text, and a card with button text.
  
<img width="1866" alt="Screen Shot 2021-11-05 at 12 25 38 PM" src="https://user-images.githubusercontent.com/1036433/140554170-e387b62e-ed36-4e7a-97d2-22a408acaba2.png">

If we add this as an optional toggle for lists, here's how it could look:

<img width="1013" alt="Screen Shot 2021-11-05 at 12 40 28 PM" src="https://user-images.githubusercontent.com/1036433/140554773-2426aac3-e0c2-4879-aadc-cf402109c862.png">

**Comment by bspeare** [comment]
@quamsta and I talked about this some more yesterday and discussed:

- Changing the circle to a square so that it matches the "Read More" button style.
- Adding a toggle option to list blocks that add the arrow and the option to set "Continue Reading" custom text for the button.  

<img width="1610" alt="Screen Shot 2021-11-10 at 8 14 44 AM" src="https://user-images.githubusercontent.com/1036433/141129828-40421672-e3a7-4064-acbd-be65a11980d5.png">

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by quamsta** [comment]
@bspeare I’m sort of coming around to the circle + arrow..

**Comment by pyrello** [comment]
@quamsta Me too

**Comment by bspeare** [comment]
I updated the proposed solution with some ideas of where we might want to start working on this issue.

**Comment by briand44** [comment]
Scope to card block for first slice

**Comment by quamsta** [comment]
Stanley Museum is also interested in this feature!
