### ISSUE TITLE
Directory profiles style bugs

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4438]
# Problem
- Breadcrumbs in Safari are not displaying inline
- Page title sitting on top of page filters
- Container has `tab-index: 0` creating blue border - is this tab index necessary?

<img width="609" alt="Screen Shot 2021-11-15 at 8 49 06 AM" src="https://user-images.githubusercontent.com/1036433/141802087-fd0985c0-8fd8-40e4-9b39-8ff8b294f795.png">

<img width="259" alt="Screen Shot 2021-11-15 at 8 48 52 AM" src="https://user-images.githubusercontent.com/1036433/141802075-6cf34925-e1f4-4b4d-b4f6-c15e2fb31522.png">

<img width="1479" alt="Screen Shot 2021-11-16 at 2 27 02 PM" src="https://user-images.githubusercontent.com/1036433/142060523-5f2021cd-f813-4a8f-be4e-9a909e86e2b9.png">

# Steps to reproduce
Go to https://education.uiowa.edu/directory and see the page title sitting on top of the page filters. 
Go to https://education.uiowa.edu/directory/john-achrazoglou in Safari

# Proposed solution
- Fix.

**Comment by GaryRidgway** [comment]
After discussion and looking at [this article](https://www.a11yproject.com/posts/2021-01-28-how-to-use-the-tabindex-attribute/), it seems like we should solve the first two problems with CSS, and message Denny about the third. we should remove the `tabindex=0` because it is non-interactable, and it will make stuff actually MORE confusing for Assistive technology users

**Comment by dcrall** [comment]
I am fine with removing the `tabindex`. Do we have an `aria-live` attribute around the profiles content? I can potentially add that on my side.

**Comment by GaryRidgway** [comment]
looks like there is already an `aria-live="polite"` on the `#uiprof` element, if that's what you mean
