### ISSUE TITLE
DCV

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4444]
Clear site cache for V2 and possibly V3 to hit the .txt URL.

- [x] iowalakesidelab.org (11/30/2021 00:00 GMT)
- [x] www.iowalakesidelab.org (11/30/2021 00:00 GMT)
- [x] writinguniversity.org (11/30/2021 00:00 GMT)
- [x] marce2020.com (11/30/2021 00:00 GMT)
- [x] www.marce2020.com (11/30/2021 00:00 GMT)
- [x] molcellcog.org (11/30/2021 00:00 GMT)
- ~[ ] www.molcellcog.org (11/30/2021 00:00 GMT) - currently not covering this domain~
- [x] iaapt.us (11/30/2021 00:00 GMT) "A request for HTTPS validation of iexplorestem.org has been successfully submitted. Awaiting the validation result..."
- [x] iowateacherintern.org (11/30/2021 00:00 GMT)
- [x] iowasummerwritingfestival.org (11/30/2021 00:00 GMT)
- [x] www.iowateacherintern.org (11/30/2021 00:00 GMT)
- [x] www.iowasummerwritingfestival.org (11/30/2021 00:00 GMT)
- [x] iowamade.org (11/30/2021 00:00 GMT) - need to reach out to customer
- [x] humanitiesiowa.org (11/30/2021 00:00 GMT)
- [x] www.humanitiesiowa.org (11/30/2021 00:00 GMT)
- [x] iowareadingresearch.org (11/30/2021 00:00 GMT)
- [x] www.iowareadingresearch.org (11/30/2021 00:00 GMT)
- [x] geriatricpain.org (11/30/2021 00:00 GMT)
- [x] www.geriatricpain.org (11/30/2021 00:00 GMT)
- [x] icfm2020.org (11/30/2021 00:00 GMT) - This does not need validated, site can go away!
- [x] wirrc.org (11/30/2021 00:00 GMT)
- [x] www.wirrc.org (11/30/2021 00:00 GMT)
- [x] iowahumanrights.org (11/30/2021 00:00 GMT)
- [x] hawkeyecaucus.com (11/30/2021 00:00 GMT)
- [x] www.iowahumanrights.org (11/30/2021 00:00 GMT)
- [x] www.hawkeyecaucus.com (11/30/2021 00:00 GMT)
- [x] iowalionseyebank.org (11/30/2021 00:00 GMT)
- [x] iowajpec.org (11/30/2021 00:00 GMT)
- [x] www.iowajpec.org (11/30/2021 00:00 GMT)
- [x] jacobsoninstitute.org (11/30/2021 00:00 GMT)
- [x] www.jacobsoninstitute.org (11/30/2021 00:00 GMT)
- [x] chsciowa.org (11/30/2021 00:00 GMT)
- [x] www.chsciowa.org (11/30/2021 00:00 GMT)
- [x] neuronext.org (11/30/2021 00:00 GMT)
- [ ] iowastem.org (11/30/2021 00:00 GMT)
- [x] idrs2020.org (11/30/2021 00:00 GMT)
- [x] www.iexplorestem.org (11/30/2021 00:00 GMT) "A request for HTTPS validation of iexplorestem.org has been successfully submitted. Awaiting the validation result..."
- [x] iywp.org (11/30/2021 00:00 GMT) - CLAS
- [x] iowareview.org (11/30/2021 00:00 GMT)
- [x] www.iowareview.org (11/30/2021 00:00 GMT)
- [x] iowamommoodbooster.org (11/30/2021 00:00 GMT) - CLAS
- [x] www.iowalionseyebank.org (11/30/2021 00:00 GMT)

**Comment by briand44** [comment]
@mark-bennett-uiowa I think iowamommoodbooster.org and iywp.org are CLAS sites you will need to validate.

**Comment by briand44** [comment]
I reached out to iowamade and icfm2020 to find out what is going on with those sites

**Comment by briand44** [comment]
iowamade is working again and I validated it

**Comment by briand44** [comment]
icfm2020 can go away so we will not need to validate.

**Comment by briand44** [comment]
ok, so we had to validate all of these again because of the change with file upload based DCV. I have validated all except www.marce2020.com (needs added to cert manager), www.molcellcog.org (needs added to cert manager) and molcellcog.org (validate button not appearing).

I also did not validate iowastem.org again. I worked with UNI to validate this last week but am planning on finding out if we can test just validating se.iowastem.org so I am purposely holding off on this one.

We have a meeting with Warren on Nov 29th and we should be able to work with him to finish these last few as well as discuss long term plans for DCV. I will follow up here after meeting with Warren.

**Comment by briand44** [comment]
The plan is to continue using the file upload method for validation. Because of recent changes with the file upload validation method, we now will need to validate www and any other subdomains in addition to the FQDN. Warren is going to provide a export of all of the domains for us to verify which are using www or wildcards, etc. so we only include the domains in cert manager that we are covering in our SSL certs. He is also going to add the www domains listed in my previous comment so we can finish validation and close this issue.
