### ISSUE TITLE
SiteNow Find Text - Main Menu links support

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4445]
Epic: https://github.com/uiowa/uiowa/issues/4268

This is the next _first_ slice of extending SiteNow Find Text functionality

## Proposed Solution

- [ ] Working off the existing code, extend to provide search support to menu link titles and path to catch the common *.prod.drupal.uiowa.edu menu items.

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by cory-skeers** [comment]
Adding a few notes for this since I'd missed grooming.

We can either update this to not skip over `menu_link_content`, and set it up to use the existing queries that are entity-based:
https://github.com/uiowa/uiowa/blob/76377f455800203d9311dece113ea2ada0d4b8c9/docroot/modules/custom/sitenow_find_text/sitenow_find_text.module#L45-L47

Or we can do separate queries outside of the existing query loops, since we are more sure of the table column names and value names for menus than regular fields.
If a separate scan, the queries can be something like (needing to account for regexped and not, and looking at both the `title` and `link__uri` columns):
```
$db->select('menu_link_content_data')
  ->fields('menu_link_content_data', ['id', 'title'])
  ->condition('menu_link_content_data.title', '%' . $needle . '%', 'LIKE');
  ```
