### ISSUE TITLE
As a site owner, I can show tags and related content at the bottom of every article

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4480]
# Story

As a site owner, I can show tags and related content at the bottom of every article content type to help direct readers to related content. 

# Proposed solution

<img width="1858" alt="Screen Shot 2021-11-22 at 10 00 54 AM" src="https://user-images.githubusercontent.com/1036433/142894810-98edf87e-a66d-4111-98f0-847d10df644a.png">

@dnkemper brought this up recently, and if we used the view created for the `topic_page` feature we could display tags and links to other articles for each page. 

- Utilize `block_2` from https://github.com/uiowa/uiowa/blob/main/config/features/topic_page/views.view.topic_page_browse_by_tag.yml.

**Comment by bspeare** [comment]
Related issues:
- https://github.com/uiowa/uiowa/issues/3420

**Comment by bspeare** [comment]
Related issue: https://github.com/uiowa/uiowa/issues/4405

**Comment by benlewzz** [comment]
I wonder if the scope of this could include pages. I am hoping to list tags in a flexible way on the mental health site, and others. This is how we've done it on some previous sites, at the bottom of the page:

<img width="637" alt="Screen Shot 2022-02-14 at 4 16 18 PM" src="https://user-images.githubusercontent.com/2752004/153955757-ff2f79b8-5836-4372-928c-db66faa19bd6.png">

**Comment by joewhitsitt** [comment]
I want to resurface https://github.com/uiowa/uiowa/issues/3420 where we are wondering if tags should be visible at all. Seems like there are two camps and this might shape if/how we approach this.

We have configuration settings for each default content type where we could include a checkbox to opt-in to this site-wide but that checkbox would be dependent on whether or not the tags public.

**Comment by dnkemper** [comment]
@benlewzz I'm a big fan of that idea! A cool way to let people view content of a specific topic. IMO this feels important but I'm clearly biased 🤷🏼‍♀️

**Comment by briand44** [comment]
Opt in per content type on config pages. Articles, Pages, People.

**Comment by dnkemper** [comment]
So add tag at bottom of content through config. If tag button is clicked, show all pieces of content that relate to specific tag -> Create view that shows a list of all content with related tag.

**Comment by quamsta** [comment]
Hi all, just trying to get a good sense of how I should approach this pretty widereaching issue. Hoping I didn't bite off more than I could chew in this sprint, but I'm willing to take a stab at it.

Here are my thoughts so far:

## In Drupal:
- Showing tags on Articles, Pages, and People content types requires a setting checkbox for displaying tags on these content types
- Articles and People = easier since layout builder is not enabled
- Pages may require a separate "pre-pre-footer-like" region due to Layout Builder
- Is it possible to just blanket a "pre-pre-footer-like" region across Articles, Pages, and People so they're all using the same sort of approach and if Layout Builder is ever enabled on something like Articles, we don't need to adjust it?

## Frontend/displaying these:
- We can just show the tags listed as @benlewzz suggested:
![](https://user-images.githubusercontent.com/2752004/153955757-ff2f79b8-5836-4372-928c-db66faa19bd6.png)
- OR we can show a full list of tags and the tagged content like @bspeare suggested in the original post in the issue

![](https://user-images.githubusercontent.com/1036433/142894810-98edf87e-a66d-4111-98f0-847d10df644a.png)

- I have some reservations about the display of both the tags and the tagged content in some cases (when there are only one or two tags, or not very much content in general, for example).
- Can we just display tags for now and work on a rabbit hole-like functionality for "Related content" in the future? @bspeare, thoughts on this?

**Comment by joewhitsitt** [comment]
I wonder if it can just be in the established "prefooter region" just above the "prefooter block"

**Comment by quamsta** [comment]
> I wonder if it can just be in the established "prefooter region" just above the "prefooter block"

This is exactly the sort of efficiency I'm looking for in this large issue I've wrapped myself up in, Joe. 😄

**Comment by bspeare** [comment]
The related content list (https://user-images.githubusercontent.com/1036433/142894810-98edf87e-a66d-4111-98f0-847d10df644a.png) would be most useful for Articles.  Can we have an option to toggle between the two display options?

**Comment by quamsta** [comment]
> The related content list (https://user-images.githubusercontent.com/1036433/142894810-98edf87e-a66d-4111-98f0-847d10df644a.png) would be most useful for Articles. Can we have an option to toggle between the two display options?

The examples there are pages, not articles, but I can see uses for both versions of showing tags like that. That one seems good if there's a substantial amount of content that's been tagged. I can attempt to make a toggle to determine how they're shown

**Comment by quamsta** [comment]
This is what I'm thinking right now:
<img width="608" alt="Screen Shot 2022-02-18 at 9 50 07 AM" src="https://user-images.githubusercontent.com/472923/154716072-e6bc211d-9623-4b41-a2fa-509b097ad987.png">

**Comment by bspeare** [comment]
@quamsta I like that!

**Comment by quamsta** [comment]
Working on this issue this week, will probably pull you both in @joewhitsitt, @bspeare for assistance/making sure I'm on the right track, but have made some progress.
