### ISSUE TITLE
Domain changes policy needs updating

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4516]
If we aren't billing as a way to dissuade folks, maybe we should be more transparent with, "we would prefer you to request a replacement site unless you can convince us otherwise."

https://sitenow.uiowa.edu/policies

**Comment by briand44** [comment]
Update docs - remove cost recovery language - we do this as support and may take us some time to get to this -

**Comment by mjoneill** [comment]
Revision points:
- REMOVE copy about charging for domain name changes (because we are not cost recovery)
- ADD Make it clear that initial domain name selection should be planned and considered carefully. We are here to consult if they want to discuss prior to requesting a site.  
- ADD We do not have a magic button that just changes a domain name. It takes a significant investment from the dev team to do something like this while maintaining the integrity of our hosting infrastructure for 1200ish sites.
- ADD For small sites, it will make sense for partners to actually request a new site with the domain they want and manually rebuild their site
- ADD The team will address domain name change work as part of support, and it will be prioritize it as non-urgent support

**Comment by mjoneill** [comment]
I have some draft copy ready for review, thoughts, edits, opinions. Make it bleed & add comments, edits, etc...

https://docs.google.com/document/d/1noEeRqKjY_7G3frbbcGwOOjBa2yx3DoZ2xobq8wJo68/edit?usp=sharing

**Comment by briand44** [comment]
I think it looks good. The only thing I would possibly add is for the customer to add a comment on the site request letting us know what site it will be replacing.

>Preferred: Request a new site with the preferred domain name and add a comment on the site request form letting us know what site you are intending to replace.

^^ don't love my language here but I think it would be good to understand the intention from the site request so we know to make sure we remove the old site when it is finished and in case hostmaster needs to know this in order to approve the domain.
