### ISSUE TITLE
Secondary Navigation: Visual Adjustments

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#4544]
# Story

As a designer, I want the ability to make adjustments to the secondary navigation style to be more visually appealing.

**Comment by bspeare** [comment]
@makurj Do you know what sort of visual adjustments you are looking for?  There is currently a pull request open in https://github.com/uiowa/uids/pull/477 that updates the secondary navigation appearance.   

<img width="435" alt="Screen Shot 2021-12-07 at 2 34 40 PM" src="https://user-images.githubusercontent.com/1036433/145102428-bd5260c6-c4f6-4f0f-a0bf-e367e3bc72aa.png">

**Comment by bspeare** [comment]
Here's what this adjustment could look like.   We've had some Slack conversations with Tippie and I have ran this by the Brand team as well.

- Reduce nav font size 
- Use brand gray color instead of black
- Make divider lines a lighter gray

<img width="1539" alt="4" src="https://user-images.githubusercontent.com/1036433/146577625-0b75dbf1-cb92-48fe-a663-34936c1d1476.png">

**Comment by makurj** [comment]
Not needed by tippie.prod.drupal.uiowa.edu anymore, only for https://tippiestudents.prod.drupal.uiowa.edu/
