### ISSUE TITLE
Replace swiftmailer with symfony_mailer

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4623]
https://www.drupal.org/project/swiftmailer

>Warning: the swiftmailer library is no longer maintained and so this module is obsolete. It has not yet been marked unsupported, but that could change at any time due to discovery of a security bug or on advice of the Drupal Security Team.

https://www.drupal.org/project/symfony_mailer

## Proposed Solution

Uninstall the Swift Mailer module.
Uninstall the Mail System module.
Add the Symfony Mailer module (using Composer).
Install the Symfony Mailer and Symfony Mailer Back-compatibility modules to the default split. Add local env config for DDEV SMTP.
Re-configure, update brand site split and export config similar to how it was before
Try testing the lockup approval email and the local digest email with DDEV's mailhog. Also test that platform email still sets the correct header and adjusts the from address if not a uiowa.edu domain

## Follow-up slice:

Remove Swift Mailer and Mail System composer dependencies if no longer in use.

**Comment by joewhitsitt** [comment]
symfony_mailer is still in alpha - plan for beta: https://www.drupal.org/project/symfony_mailer/issues/3267230 (fixed)

plan for stable release (shooting for March 2023): https://www.drupal.org/project/symfony_mailer/issues/3316214

**Comment by joewhitsitt** [comment]
Stable release https://www.drupal.org/project/symfony_mailer/releases/1.2.1

Again, I think only brand.uiowa.edu is using this for the lockup generator daily digest, approval email

**Comment by joewhitsitt** [comment]
This might take a few steps to complete. Could uninstall swiftmailer and mailsystem (requires swiftmailer to be uninstalled first) in prod and have the new and updated config ready to push right after.

**Comment by joewhitsitt** [comment]
Ruh roh. Running into issues:

https://www.drupal.org/project/reroute_email/issues/3261831

`uiowa_core_mail_alter()` and `brand_core_mail()` will have to be updated

**Comment by joewhitsitt** [comment]
I thought I had this working at one point: https://www.drupal.org/docs/contributed-modules/symfony-mailer-0/development/architecture-and-discussion#s-back-compatibility

**Comment by joewhitsitt** [comment]
Will need to make sure these still fire or refactor them to continue working
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L91
https://github.com/uiowa/uiowa/blob/main/docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module#L364

**Comment by pyrello** [comment]
> Ruh roh. Running into issues:
> 
> https://www.drupal.org/project/reroute_email/issues/3261831
> 
> `uiowa_core_mail_alter()` and `brand_core_mail()` will have to be updated

It looks like there is a Symfony Mailer-specific replacement for reroute email that we could adopt: https://www.drupal.org/project/symfony_mailer_reroute. Based on the module description, it sounds like it integrates more specifically with Symfony Mailer's policy system. Our updates here would probably go through that.

**Comment by pyrello** [comment]
@joewhitsitt Was it intentional to set `sendmail` as the transport for default config and `smtp` as the transport for the `local` split?

**Comment by pyrello** [comment]
@joewhitsitt Any idea why this is necessary? Also why these changes are made and not scoped to the section below for the lockup specifically?

https://github.com/uiowa/uiowa/blob/41e9ccef201e82323a3e1ef143d3c6121ac8c979/docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module#L365-L371

**Comment by joewhitsitt** [comment]
>Was it intentional to set sendmail as the transport for default config and smtp as the transport for the local split?

I believe it was necessary.

>It also includes necessary local config for use with DDEV Mailhog.

**Comment by joewhitsitt** [comment]
>Any idea why this is necessary?

It could be scoped to just those emails. That was just something I overlooked at the time.

The reply-to line was necessary at the time but I wonder if they have since been covered by these modules. https://github.com/uiowa/uiowa/pull/3919

The headers/langcode was probably an early attempt to get HTML emails working. This was some of the earliest d8 work and there was a mix of d7/d8 documentation I was referencing.

**Comment by joewhitsitt** [comment]
Ah I remember why it was scoped that way. Originally there were going to be more emails so I started with the switch statement, then we found workbench_email for the other email so the switch wasn't necessary anymore but not updated.

**Comment by pyrello** [comment]
To test that this works with Acquia's Platform Email, I temporarily removed the settings for the `dev` split that would prevent emails from being sent. I've merged #6542 into `develop` and once it is deployed will test emails functionality there. After that is done, I'll re-add the setting to the `dev` split that prevent emails from sending, merge it into `develop` again and re-test that those settings work as expected. If there are no issues at that point, I think we merge it into main and re-check it on the stage server just to double check everything. If it all looks good, deploy to production :)

**Comment by pyrello** [comment]
The Symfony Mailer module introduces the concept of policies which can implement alterations based on particular contexts. I had thought that maybe policies could be used to handle our customizations in `uiowa_core` and `brand_core` but I don't see anyway to update a from address conditionally based on one not being provided or to set an arbitrary header, so we are going to have to figure out how to implement those things still in code.

**Comment by pyrello** [comment]
While testing this on dev, I encountered the following error:

> Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly.

[This issue](https://www.drupal.org/project/symfony_mailer/issues/3343418) and [these docs](https://docs.acquia.com/cloud-platform/manage/platform-email/faq/#can-i-use-symfony-mailer-with-platform-email) seem to indicate that we need to override a setting for sendmail gets triggered.

I added the setting to `docroot/sites/settings/global.settings.php` with the idea that we need this in production, email sending will be disabled in stage and dev, and trapped locally using Mailpit, so it shouldn't matter that its production-specific. In the event that we need to test on dev or stage in the future, we can disable the split settings that prevent email from being sent and those environments will be able to pick up this setting at that point.

Still need to validate it works whenever the `develop` branch makes its way to `dev`.

**Comment by pyrello** [comment]
> Still need to validate it works whenever the `develop` branch makes its way to `dev`.

Bummer. I'm still getting the same error message. Not sure if there is some process that needs to restart or what. Not sure how to proceed.

**Comment by pyrello** [comment]
Just now realizing that I'm not sure how compatible the Symfony Mailer module is with Webform: https://www.drupal.org/project/symfony_mailer/issues/3260134

**Comment by pyrello** [comment]
I opened a ticket with Acquia to see if we can get some help figuring out why this isn't working correctly.

**Comment by pyrello** [comment]
Acquia support helped me figure out the issue, I think! I had created a custom command option in global settings file, but had not actually selected it to use. For some reason the config stores which command is selected using the text of the command instead of a key to represent it. The command text will differ per application/environment because it includes a reference to the application machine name. To get around this, I'm trying out setting the config for the command in the global settings file. Waiting for this to deploy to dev environments to test it out.

**Comment by pyrello** [comment]
It looks like those changes worked! I'm going to finish the updates to custom code and test that that is working in dev, then change the dev settings back.

**Comment by pyrello** [comment]
It was tricky to understand what was going on in dev since the configuration overrides are not reflected in the UI. I was able to figure out how to see the actual config value by referencing https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system#s-global-overrides and running the following command:

```
ddev drush @sandbox.dev config-get symfony_mailer.mailer_transport.sendmail --include-overridden
```

**Comment by pyrello** [comment]
On Friday, I was working on moving the items from https://github.com/uiowa/uiowa/issues/4623#issuecomment-1593174267. My base assumption was that `hook_mail_alter` could not be used because it doesn't fire when using Symfony Mailer. I did not remove the old code and started adding an adapted version of the code in a `hook_mailer_build` hook. At one point I noticed that the `X-UI-Hosted` header appeared to be getting added twice and became confused about whether `hook_mail_alter` was actually getting fired or not. After a round of commenting out code and trying to validate whether `hook_mail_alter` was firing or not, I seemed to be getting inconsistent results. It was at this point that I took a break to focus on something else. Today I'm picking the work back up to try to figure this out.

**Comment by pyrello** [comment]
Last two things that need to be done (I think):
- Adjust or rewrite tests or fix code to pass tests
- See how the lockup digest is currently rendering and recreate that

**Comment by joewhitsitt** [comment]
I'll ask Sondra to forward a recent digest for comparison.

**Comment by joewhitsitt** [comment]
Based on the example from Sondra, i'd say there was a _small_ regression previously 😅

**Comment by pyrello** [comment]
> Based on the example from Sondra, i'd say there was a _small_ regression previously 😅

I have fixed this.

**Comment by pyrello** [comment]
Looking into the tests I was seeing that the tests appeared to be failing because our customizations were not firing. I was puzzled by this until I realized that the test wasn't including the `symfony_mailer` module. After adding that, the customizations get added as expected. However now I'm running into an issue where we don't have a generic `EmailBuilder` for the `uiowa_core` module and it seems to be expected that it would. I'm not sure why it doesn't get picked up by the legacy email builder.

We could potentially adjust the tests... either to directly use the Symfony Mailer workflow or by choosing an existing module/subtype that will trigger an email builder that exists. On the other hand, I kind of like that this tests that the core functionality still works in case an email is ever sent that way.

**Comment by joewhitsitt** [comment]
So is it my understanding that symfony mailer is overriding core for all outgoing mail now (webform, etc.)? Maybe a huddle about this would be good.

**Comment by pyrello** [comment]
Opened this issue: https://www.drupal.org/project/symfony_mailer/issues/3393337

**Comment by pyrello** [comment]
@joewhitsitt and I huddled and here is the summary from Slack:
> Walked @joewhitsitt through why our mail tests break with Symfony mailer, some potential ways we could rewrite the tests, and why I'm hesitant to rewrite the tests because I think any of those options will fundamentally change what we are testing and provide less solid coverage. I think we are in agreement on this. I'd like to allow a day or so to see if we get a response on the issue I opened. We also talked about what a potential patch might look like.

**Comment by pyrello** [comment]
I thought I had an idea for an easy way to provide a fallback to the `LegacyEmailBuilder` in cases where no `hook_mail()` exists. However, I'm finding that it is much more convoluted than I thought.

I did come up with a solution that fixed the failing test I created for https://www.drupal.org/project/symfony_mailer/issues/3393337, but then I ran into another issue where it appears that the hook we are using for modifying our emails before they are sent does not get called, so our mail tests still fail.

I'm starting to think that maybe we should accept that we are not going to have the same level of test coverage as we previously did, adjust the tests so that they work with Symfony Mailer and then have a follow-up task to revisit this later after we are done with the D10 transition.

**Comment by pyrello** [comment]
Got tests working in #6542 and merged that into `develop` to test mail functionality on dev. After that, I'll revert the mail settings for the dev split, re-merge into `develop` and then test that mail _does not_ send on dev.

**Comment by pyrello** [comment]
I did a series of tests on dev to check various aspects of how this all works:
- Used the Symfony Mailer test form to test sending an email via the "native" mailer functionality
- Tested a couple webforms to test sending email in compatibility mode
- Tested the brand lockup digest
- Tested the workbench lockup approval emails

As best I could tell it all seems good.

**Comment by pyrello** [comment]
Tested again on dev again. I did most of the same tests. As far as I can tell, the `null` transport works perfectly for our use case.
