### ISSUE TITLE
Adjust breakpoint for two column layout

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4653]
# Problem
The two column layout mobile breakpoint becomes a little unreadable on smaller devices. 

# Steps to reproduce
<img width="640" alt="Screen Shot 2022-01-13 at 9 35 24 AM" src="https://user-images.githubusercontent.com/1036433/149365403-47d47b82-a058-44ab-b453-cd3cd7302fc9.png">

# Proposed solution
Adjust the breakpoint for 67/33 and 75/25 away from `sm` breakpoint to perhaps a different breakpoint around 850px.

**Comment by quamsta** [comment]
Interested in pairing/working with you on this @bspeare !

**Comment by quamsta** [comment]
@bspeare A couple options I've been brewing up for this. Let me know if either of these work or if you have some additional ideas:

## Option A:

Shift the `grid-base` mixin in `themes/custom/uids/assets/scss/_grid.scss` to use the `md` breakpoint instead of `sm`:


```
@mixin grid-base {
  @include breakpoint(md) {
    @include display-grid;
    grid-template-columns: 1fr;
  }
}
```


## Option B:

Adjust `.layout--twocol . layout_spacing_container` in `themes/custom/uids_base/scss/layouts/twocol.scss` to use a `md` breakpoint and adjust the following two column layouts to also use a md breakpoint.

### Before:

```  
.layout--twocol {
  .layout__spacing_container {
    @include grid-base;
    row-gap: 0;
  }

&.layout--twocol--33-67 {
    .layout__spacing_container {
      @include breakpoint(sm) {
        grid-template-columns: repeat(3, 1fr);
      }
      .layout__region--first {
        grid-area: 1 / 1 / 6 / 2;
      }
      .layout__region--second {
        grid-area: 1 / 2 / 6 / 4;
        @include inner-grid(67);
      }
    }
  }


...

```

### After:

```
.layout--twocol {
  .layout__spacing_container {
    @include breakpoint(md) {
      @include grid-base;
      row-gap: 0;
    }
  }
  &.layout--twocol--33-67 {
    .layout__spacing_container {
      @include breakpoint(md) {
        grid-template-columns: repeat(3, 1fr);
      }
      .layout__region--first {
        grid-area: 1 / 1 / 6 / 2;
      }
      .layout__region--second {
        grid-area: 1 / 2 / 6 / 4;
        @include inner-grid(67);
      }
    }
  }

(adjust other layouts to also use `md`)
...

```

**Comment by bspeare** [comment]
I'd vote for using option B to change the breakpoints to `md` only when we need it.   I think the `sm` will still work well with other grids, the 67/33 and 75/25 are probably the only ones that need adjusting.

**Comment by quamsta** [comment]
Okay post-huddle and discussion with @bspeare and @bewoldt we have these thoughts:

- Possibly use modified Option A, where we adjust the layouts/grids so that we see a single column until we the `menu` breakpoint (855px) instead of `md`
- Once container queries are implemented on some of the card styles and other block styles, using a 50/50 grid on the two and four column layout should be safe on smaller displays.

Questions:

- If we go with the modified Option A, do we merge the `menu` and `md` breakpoints into one singular breakpoint?
- Is there an advantage to keeping both of those breakpoints?

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/issues/4653.
