### ISSUE TITLE
Cannot add additional items to Timeline on Stanley

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#4691]
# Problem
Stanley Museum has a timeline on one of their pages. https://stanleymuseum.prod.drupal.uiowa.edu/about/history. Any additional items added won't save or update.

# Steps to reproduce
Try adding an item to the timeline block on this page. https://stanleymuseum.prod.drupal.uiowa.edu/about/history.

**Comment by bspeare** [comment]
These errors appear at the top of the block if you try to add a new timeline item to this timeline:

<img width="465" alt="Screen Shot 2022-01-21 at 9 05 57 AM" src="https://user-images.githubusercontent.com/1036433/150550317-ce844191-c173-4e37-b065-671d1a161c1f.png">

**Comment by joewhitsitt** [comment]
looks like a couple inner media items were deleted and the related timeline items need to be "resaved" after the media reference is removed or updated.

**Comment by bspeare** [comment]
@joewhitsitt what's the best way to find the problematic media items and re-save them?

**Comment by joewhitsitt** [comment]
not easy but i use those ids to construct a URL to find what exactly they are (e.g. /media/image/123)

then using the context of the timeline you could pinpoint which one without clicking in to all.

**Comment by bspeare** [comment]
I tried removing an existing image and got this message:

<img width="360" alt="Screen Shot 2022-01-21 at 10 17 50 AM" src="https://user-images.githubusercontent.com/1036433/150562038-53b44386-e72a-4877-a18d-96beedf33326.png">

**Comment by joewhitsitt** [comment]
could you try harvesting the content of this timeline item and remove entire timeline item and recreate without the image? ideally if this works, then revisions should be cleaned up so it doesn't get reverted back

**Comment by bspeare** [comment]
Next steps for this:

- Recreate timeline block with text only
- Delete old timeline block
- Add images back into the new timeline block, saving the block each time after the image is added.

**Comment by joewhitsitt** [comment]
Since these error messages by themselves are not very helpful to editors, we might have to start printing the media id (if provided) as part of the paragraph preview to help track down "corrupted" timeline items while they are collapsed. This has previously been an issue in v2 sites and some layout builder blocks.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/4691#issuecomment-1018656724

Was this caused by a file migration bypassing our file size restriction?

**Comment by cory-skeers** [comment]
> [#4691 (comment)](https://github.com/uiowa/uiowa/issues/4691#issuecomment-1018656724)
> 
> Was this caused by a file migration bypassing our file size restriction?

Possibly... The node migrations that pull files in if they're used should respect any restrictions when using the file api, but the old files-only migration saved files directly and then created media entities, so it could have missed restrictions.

**Comment by joewhitsitt** [comment]
Upstream issue: https://www.drupal.org/project/paragraphs/issues/3095945

Changes the error message to something more helpful. Won't be merged until tests are updated.

`The referenced entity (media: 37) does not exist. (UIowa Timeline Items » Timeline Item [1] » Media [1])`

**Comment by GaryRidgway** [comment]
Currently in this issue, I have created "Media error" pills to notify people of media errors in their timelines. They currently look like this, and only work for timeline elements:
<img width="654" alt="Screen Shot 2022-02-09 at 11 25 36 AM" src="https://user-images.githubusercontent.com/23122142/153255888-db69945f-50d5-4b4c-95b6-bf124c8b0d96.png">

@joewhitsitt sugested instead [utilizing this patch]("https://git.drupalcode.org/project/paragraphs/-/merge_requests/1.patch") that would create better paragraph messages for all paragraphs, which i think is a good idea. 

This patch changes the errors at the top of a block about paragraphs having missing media entities from this:
`Validation error on collapsed paragraph field_references.0.target_id: The referenced entity (node: ) does not exist`
to this:
`The referenced entity (media: 1291) does not exist. (UIowa Timeline Items » Timeline Item [36] » Media [1])`

These appear as such:
<img width="633" alt="Screen Shot 2022-02-09 at 11 35 58 AM" src="https://user-images.githubusercontent.com/23122142/153257709-d62d2a95-29d0-4dfe-bd54-55e46b2d19ac.png">


This looks a lot better, however one change i would like to see if we add this patch is adding the Timeline item number to the Timeline item label so that users can easily identify what Timeline item the error is referencing.

The discussion point: Do we keep the Media error pills AND add this patch? Or do we just add the patch and remove the error pills?

Pros of the `Media error` pills:
- It is very clear to the user which media items are problematic, and visually they pull your eye and let you know something is wrong
- The logic to create them is strictly contained to Timeline items.
- Does not require you to submit the block form to know there is a media error

Cons of the `Media error` pills:
- There is a lot of logic to get them to show up, and it may not be worth it to maintain all of it just for timeline items.

**Comment by cory-skeers** [comment]
> The discussion point: Do we keep the Media error pills AND add this patch? Or do we just add the patch and remove the error pills?
> 
> Pros of the `Media error` pills:
> 
> * It is very clear to the user which media items are problematic, and visually they pull your eye and let you know something is wrong
> * The logic to create them is strictly contained to Timeline items.
> * Does not require you to submit the block form to know there is a media error
> 
> Cons of the `Media error` pills:
> 
> * There is a lot of logic to get them to show up, and it may not be worth it to maintain all of it just for timeline items.

I think the media error pills are a great addition to the patch, particularly if there is a decent number of timeline entries to sort through (thinking 10+, and trying to look for specific ones if the validation message gave a delta). Could be persuaded based on the complexity of maintaining it, but generally think it's a really useful addition.

**Comment by joewhitsitt** [comment]
>however one change i would like to see if we add this patch is adding the Timeline item number to the Timeline item label so that users can easily identify what Timeline item the error is referencing

This might be difficult because they can be reordered and lose meaning quickly. The issue says that the form is not reloaded during validation so what would update the numbers?

**Comment by joewhitsitt** [comment]
This issue worries me in that we have gone from trying to fix the immediate issue (afaik, stanley museum hasn't been fixed yet) to making it look better in this one silo of content when the whole platform has this issue (e.g admission_card, v2).

**Comment by GaryRidgway** [comment]
Talked with Brian on this, and we determined that the current proposed solution would be this:

## Proposed solution:
1. Finish up media error code.
2. Apply patch
3. review code
4. notify Stanley museum to fix the broken media elements themselves with our ways to identify them.
5. Create a follow up issue for any trailing thoughts or necessities coming off of this one.
