### ISSUE TITLE
As a site owner, I can have a row of buttons that appears fixed to the bottom of the browser

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4767]
# Story

As a site owner, I can have a row of buttons that appears fixed to the bottom of the browser when scrolled

As seen on https://viewbook.admissions.uiowa.edu/. 

<img width="1730" alt="Screen Shot 2022-02-07 at 8 29 09 AM" src="https://user-images.githubusercontent.com/1036433/152807179-a57a2b9b-f664-4b61-8960-e3c786257793.png">

# Proposed solution

## First slice
- [x] Blocker: #2873 
- [x] Add a "After content" region to our theme to handle the placement of these region fragments. The exact placement of this is still up for debate so it may change, but we'll move forward with the assumption that this new region will be place in between the end of the content and the Pre-footer region.
- [ ] Add a set of reference fields (one per region that can be overridden) that directly references the region fragment type. We could also potentially allow people to create alternate region fragments inline.
- [x] Update the SiteNow Regions settings page to account for multiple regions.
- [ ] Update the RegionContentBlock class to check if a page is a node and has override fields set and not empty, in which case it would pull the appropriate fragment from the node instead.
- [x] Place an instance of the RegionContentBlock in our new theme region.
- [x] Set up custom onecol layout
- [x] https://github.com/uiowa/uiowa/issues/4622
- [x] Set "Default" as the default container size. 

## Second slice
- [ ] Add a global setting to allow displaying the new region as a fixed area at the bottom of the view port.
- [ ] Implement final design.
- [ ] Optional depending on how the previous slice gets rolled out: Update hook to allow setting the global setting to false for any sites that started adding region fragments to this new area.

<details>
<summary>Original proposed solution</summary>
- [x] Investigate possible solutions for this, documenting the pros/cons of each solution for both the developer and the customer. - completed 06/29/2022
- Create a new button row block that can only be placed in one column sections?
- Allow user to check a box to make the block sticky?
</details>

**Comment by joewhitsitt** [comment]
- Concerns about taxonomy (tag) driven solution for this.
- This doesn't seem like it should fit within the normal layout interface since it is fixed bottom (needs to break out of main content container). Also how to prevent multiple?
- Mobile concerns (disappear, condense, only show first, etc.?)
- We do have a button block in our backlog but not necessarily a button row - https://github.com/uiowa/uiowa/issues/2873
- Probably want to limit the number of buttons, little can do about button text length
- Current page illustrates CTA buttons - https://tippie.uiowa.edu/iowa-mba/curriculum
- https://documentation.unbounce.com/hc/en-us/articles/115005919683
- Joe pitched his inrc.law global aside solution for providing prefooter overrides

<img width="830" alt="Screen Shot 2022-06-28 at 2 21 37 PM" src="https://user-images.githubusercontent.com/4663676/176267804-77f69267-2183-491c-95e4-2a16543e3b92.png">
<img width="561" alt="Screen Shot 2022-06-28 at 2 21 07 PM" src="https://user-images.githubusercontent.com/4663676/176267813-135dcd5d-7818-4298-9e0e-07cf33d5c7e1.png">

**Comment by cory-skeers** [comment]
For this and other forms of CTA elements, would like to keep in mind future tracking efforts. Don't think any of the proposed solutions here yet make it more or less difficult (mostly JS-based solutions would be the most impactful), but in the future we'll want to make sure we can differentiate user journeys based on whether they use one of these buttons, a menu link, or on-page link.

**Comment by pyrello** [comment]
> Concerns about taxonomy (tag) driven solution for this.

@joewhitsitt Can you explain this a little bit more?

**Comment by pyrello** [comment]
After looking at this and thinking it through a little bit here is where I am at for how to set it up:
- Add a "Fixed bottom" region to our theme to handle the placement of this content.
- Need to determine what fallback placement looks like when there is not enough screen real estate, probably just on mobile. Should it be placed after the content before the prefooter region?
- Add a set of reference fields (one per region that can be overridden) that directly references the region fragment type. We could also potentially allow people to create alternate region fragments inline.
- Update the SiteNow regions settings page to account for multiple regions.
- Update the `RegionContentBlock` class to check if a page is a node and has override fields set and not empty, in which case it would pull the appropriate fragment from the node instead.
- Place an instance of the `RegionContentBlock` in our new theme region.
- I think we could just use the existing layout options to allow for setting up buttons next to each other. If they want 3, then they would use a 3-column layout.
- Optional: Implement a button block type for easier generation of the buttons.
- Still to be determined:
  - Do we need a way to disable the region on a node?
  - What about a non-node pages?

**Comment by joewhitsitt** [comment]
> > Concerns about taxonomy (tag) driven solution for this.
> 
> @joewhitsitt Can you explain this a little bit more?

Um. I think initially, there was a thought about using tags to determine where this fixed bottom would show. (e.g. all pages with iowa-mba). I was trying to capture the thoughts that I missed out on specific concerns.

**Comment by joewhitsitt** [comment]
>Should it be placed after the content before the prefooter region?

Seems like the viewbook actually has this higher up in page for mobile. Is this where pre-content region with a fixed bottom option comes into play. pre-footer would also have a fixed bottom option and so the order on mobile would be content, footer, fixed pre-content, fixed pre-footer or pre-content, content, pre-footer, footer depending on what is set.

>Do we need a way to disable the region on a node?

I say for MVP that isn't necessary but could be needed in the future.

>What about a non-node pages?

If I recall the global prefooter shows on all routes (includes view pages) so is it a concern that a fixed bottom override can't be called? For default view pages (articles/people), this could be added to the settings _if needed_.

**Comment by bspeare** [comment]
Thinking ahead with the work in https://github.com/uiowa/uiowa/issues/5371,  https://github.com/uiowa/uiowa/issues/4716 - is there a way we could show these on mobile through our menu toggle?   What if we want to use this for the home page actions of Apply, Visit, and Request Info?  These types of actions are often concealed within the mobile dropdown.

<img width="485" alt="Screen Shot 2022-06-29 at 1 04 52 PM" src="https://user-images.githubusercontent.com/1036433/176505510-ba710769-5fa2-4e84-97ca-5431ef6b079e.png">

**Comment by mjoneill** [comment]
Would an approach like that described above preclude our ability to do something like this (if we wanted to):

* buttons appear anchored on the side on initial page load (see image)
* on scroll down event, side buttons are replaced by the bottom button bar (see image)

I think this might help with some of the challenges moving to exposed menu for uiowa.edu (#4716) and seems to be a familiar interaction pattern.  

![2022-06-30_16-05-51](https://user-images.githubusercontent.com/7144234/176780165-4af89f96-f38a-494b-8b3f-5d25ba3581b0.jpg)

**Comment by mjoneill** [comment]
adding @meganyoder for visibility

**Comment by pyrello** [comment]
> Would an approach like that described above preclude our ability to do something like this (if we wanted to)...

No, it would not.

@bspeare and I were just talking about some options for how to handle the fallback scenario (mobile) and I think the best idea is to produce some basic mockups to show what the various options would look like so we can get a sense of where were are actually going to put this region in the flow of the page.

**Comment by mjoneill** [comment]
OK. 

Looks like Maryville went with a slightly different approach that seems to be trying to address to a similar opportunity...
Sharing without endorsement...just an example.
https://www.maryville.edu/bu/accounting

**Comment by mjoneill** [comment]
![](https://nmcdn.io/e186d21f8c7946a19faed23c3da2f0da/347bed083486499c98f1609efa95efbd/files/2--cal-sticky-cta-min.gif)

**Comment by mjoneill** [comment]
ASU with a similar convention...  
CTA is actually a form embed.  once it scrolls off the page, a stickybar with a CTA appears at the bottom

https://start.asuonline.asu.edu/study/language-degrees/

**Comment by pyrello** [comment]
> ASU with a similar convention...
CTA is actually a form embed. once it scrolls off the page, a stickybar with a CTA appears at the bottom
>
> https://start.asuonline.asu.edu/study/language-degrees/

I think the notable innovation here is that the action in the button is tied to an anchor on the page, rather than directing the user to another page.

**Comment by pyrello** [comment]
I want to add a little bit more context with regard to my thinking about the placement of a region that becomes a fixed (sticky) container:

This discussion is largely oriented towards thinking about where the region is displayed when it can't be displayed as fixed and the most likely case for this is on a mobile device below a certain breakpoint.

# Site chrome (spoiler: nope)

Everything in the menu and above and in the footer, I would consider to be site chrome and immutable. This means that the user should be able to expect that it is exactly the same on every single page. I believe as a basic principle of site design that changing the elements that are represented in site chrome based on what page you are on is confusing to the user and makes it difficult to reason about how to navigate the site. Therefore the placement of and page-specific element in these areas is a no go. This includes a collapsed mobile menu. Similarly, it would be inappropriate to have a global element disappear because it was being replaced by a page-specific element somewhere else on the page.

# Above the page title (wait, what?)

Putting elements that are page-specific above the page title seems nonsensical. I'm a bit squishy on this point, as I obviously believe that an image above the title can make sense. But CTA's above the title don't make sense to me because surely the user needs to have the context of the actual page content before they are going to click a CTA button.

# Below the page title (descending into the murky depths of element placement with Layout Builder)

For our page content type, putting a page-specific CTA below the title opens up a whole can of worms because then we are dealing with layout builder and we have a lot less certainty about what exactly is going to be present and where. We could potentially place a CTA section and block by default on a page, but I don't see a clear path to being able to prevent a content editor from being able to remove it. 

Sections in Layout Builder are not strictly defined: they don't have UUIDs, so the only way they are kept track of is by their delta. That means that on our standard layout (the template), the moderation controls section is delta 0, the header is delta 1. If we want to have a particular section be pulled out of the flow of the rest of the page and be displayed as a fixed element, it becomes hard to figure out what that section is. Because the user can delete the header and replace it with a banner, the potential layouts we might encounter are pretty hard to determine. We are left with our only option of "finding" the correct section to make a fixed area is to loop through all the sections and then inspect all their blocks until (and if) we find the right one, then setting the appropriate classes on the section. This adds some performance overhead for loading any LB page. And we may run into caching caveats and difficulties.

# Above the prefooter (not ideal, but maybe makes the most sense)

A region above the prefooter could live outside of Layout Builder and therefore save us a mess of trouble (see above). This also makes sense from a content flow perspective because the user has had the opportunity to consume the page content that presumably is a prerequisite to clicking a CTA button.

# Mobile collapse option (a possible compromise!)

One more idea is that we could have our mobile fallback still be a fixed container, but one that is collapsed so that only the first CTA shows and the rest can be exposed through a `...` or hamburger menu. It requires extra action to get to the second or third button, but we don't have to give up the ubiquitous visibility of the fixed container.

**Comment by joewhitsitt** [comment]
>pre-content region

I forgot about how our layouts are structured. Nevermind

**Comment by bspeare** [comment]
I put together an animated gif to illustrate the mobile collapse option outlined in https://github.com/uiowa/uiowa/issues/4767#issuecomment-1172458139.  

 ![ezgif-4-4d4c24ed2e](https://user-images.githubusercontent.com/1036433/177384378-70db3cf7-d1fe-4bb1-bbbd-f80d357ccec3.gif)

**Comment by briand44** [comment]
Grooming conversation - initial slice scoped to pre-pre-footer functionality that allows only button component. Second slice would add sticky functionality and design work.

**Comment by bspeare** [comment]
Example showing the first item only. 

![ezgif-2-d3c3e2daef](https://user-images.githubusercontent.com/1036433/177394148-65ee5d0e-cf73-4a9d-a28c-12073db28689.gif)

**Comment by pyrello** [comment]
Because of how we are wanting to implement this, it is agreed that the best way to do it is via a dedicated button component. That mean that #2873 is a blocker for this issue.

**Comment by joewhitsitt** [comment]
After hearing the discussion in the Tippie meeting and assuming that whatever we develop will be restricted to buttons, I wonder if we are adding unnecessary complexity by trying to reuse a block component and place it via layout builder. I raised a question in Slack about whether or not we are able to limit the number of items within a section column. This would be another thing to workaround to make sure we have a max of three buttons.

Might I propose continuing down the path we are (region placement, mockups, global/override) but using a separate fragment type to collect "button" info. The global field and the node override field could just be a limit-3 fragment reference. Yes it would be a duplication of button type functionality, but putting it where we need it would be simpler. The button fragments could then be re-used, interchangeable where necessary instead pulled together as one button group.

The button component that is developed for page layout builder doesn't need to account for the special circumstances that might occur in this space.

**Comment by pyrello** [comment]
> Might I propose continuing down the path we are (region placement, mockups, global/override) but using a separate fragment type to collect "button" info.

@joewhitsitt Can you unpack this a bit more? I'm unclear what this actually looks like. It seems like this would require that we build a separate and parallel system to the pre-footer region admin UI we built. One of the benefits of the approach I laid out before was that we could hook into that existing system. And the improvements we make for this would also benefit the pre-footer.

Assuming that will only ever need a button is a pretty big assumption. If that turns out to be wrong, then building this parallel system for managing a global region with per-page overrides will require either a reversion back to the existing system, or further investment in parallel structures. Personally, I would prefer to stick to the plan as outlined and just figure out how to limit each layout region to one block.

**Comment by joewhitsitt** [comment]
>Assuming that will only ever need a button is a pretty big assumption

That is why I asked before pitching this, though as I was seeing in the mobile mocks, there isn't a whole lot else that could fit. Three buttons already seemed complicated.

To unpack though:

- Region Settings could still be used.
  - Two buttons (Add region item, Add Button Thingamajig)
  - Sticky footer region entity reference allowing up to three thingamajig references (I think this would have to be done either way). This is wired up to a sticky footer block (similar to prefooter block) where they are rendered as buttons.
  - I believe the prefooter entity reference only allows region item fragment types to be selected. If not, change it.
  - The Available region items view below would be renamed and the fragment type (Region Item, Sticky footer button thingamajig) would be displayed next to each item.
  - The button thinamajig fragment type would consist of uids button component fields (doesn't have to be a full implementation if not needed).

**Comment by bspeare** [comment]
Maybe we do want to leave the door open for this to be more than buttons in the future?  The comment from the meeting yesterday about turning this into a general mobile toggle has somewhat changed my mind on this.   Perhaps we would want to put something different in there for uiowa.edu or admissions.uiowa.edu in the future? 

I would like to make sure that we can only add one item/block per layout column.

**Comment by pyrello** [comment]
> That is why I asked before pitching this, though as I was seeing in the mobile mocks, there isn't a whole lot else that could fit. Three buttons already seemed complicated.

That it is complicated as envisioned and would be more complicated with the introduction of other elements does not preclude that it will eventually happen.

After looking at this a bit more closely, I'll admit that this idea would not require as much duplication as I originally thought. I do believe that the UX is going to be confusing, specifically having the "Add button Thingamajig" button. It also doesn't seem like a very sustainable path if we are going to start forking off in a different direction each time we encounter requirements that allow it.

**Comment by bspeare** [comment]
Placing a CTA into a one-column layout might be useful in the future to have sticky on pages.  I prefer to only use the buttons to start, but future components might be useful in this region.  

<img width="1728" alt="Screen Shot 2022-07-13 at 1 04 05 PM" src="https://user-images.githubusercontent.com/1036433/178800844-fc7e7eed-c786-46d6-9164-75db7ad76fc7.png">

**Comment by joewhitsitt** [comment]
Going with @pyrello's original suggestion just extends what we are already doing and would be easier to pivot from if we needed to change directions later (existing region items can fallback and just be assigned to prefooter). Because we can't rule out the possibility of this space being used for more than just buttons pokes serious holes in the suggested alternative.

**Comment by bspeare** [comment]
Here are the mockups from Tippie:

<details>

![sticky_ctas_desktop (2)](https://user-images.githubusercontent.com/1036433/182405111-6eca75e0-324d-4859-802b-a66729be0f5c.jpg)
![sticky_ctas_mobile](https://user-images.githubusercontent.com/1036433/182405149-b87164d4-c5b5-40c1-ac4e-9dfecc6166c8.jpg)
![sticky_ctas_mobile_firstpreference](https://user-images.githubusercontent.com/1036433/182405150-ba6d5515-5a93-4723-abe9-e1acd695bd23.jpg)
![sticky_ctas_mobile_all_active](https://user-images.githubusercontent.com/1036433/182405639-bd1fdcba-d9cb-4a64-a0ce-3132716cd7ee.jpg)

</details>

One additional note: they have said that they would be fine with the solution if we can't right align the buttons/menu.   Perhaps we build the solution using layout builder and buttons and a future slice could be enhancements if they would like to pursue the right-aligned direction?

<details>
<img width="1385" alt="Screen Shot 2022-07-20 at 3 12 39 PM (1)" src="https://user-images.githubusercontent.com/1036433/182405555-189cf41d-ec5c-4125-950a-dadabeb17a77.png">
</details>

**Comment by briand44** [comment]
Adding needs grooming label again as there appear to be questions around the design of this.

**Comment by bspeare** [comment]
Here are some screenshots of what the cta row looks like using the new button block aligned to the center and a layout region.  Open the details to view them.  The small button size looks a little weird in here and the container spacing also seems to wide.  Perhaps the narrow container would be a good default for this?

<details>

Some screenshots.  I don't think the container top and bottom spacing is correct in these:

<img width="1902" alt="Screen Shot 2022-08-02 at 11 33 51 AM" src="https://user-images.githubusercontent.com/1036433/182427093-7de15b6a-cf30-40ec-a56d-bf1722ff1760.png">
<img width="1803" alt="Screen Shot 2022-08-02 at 11 33 17 AM" src="https://user-images.githubusercontent.com/1036433/182427098-137727ac-ad4c-47d4-969a-9e19768734aa.png">
<img width="1656" alt="Screen Shot 2022-08-02 at 11 31 58 AM" src="https://user-images.githubusercontent.com/1036433/182427103-4dc9ba60-e945-4643-9ea1-b53e9ae33530.png">
<img width="1792" alt="Screen Shot 2022-08-02 at 11 31 03 AM" src="https://user-images.githubusercontent.com/1036433/182427106-37163579-9526-49b4-8a68-9d4936dedd3f.png">
<img width="1553" alt="Screen Shot 2022-08-02 at 11 30 27 AM" src="https://user-images.githubusercontent.com/1036433/182427109-571ec05e-96dc-4299-b542-60e1dcbdfc07.png">
<img width="1696" alt="Screen Shot 2022-08-02 at 11 34 28 AM" src="https://user-images.githubusercontent.com/1036433/182427079-7c79f6f7-eace-479d-a46a-b193a4e7d4c2.png">

</details>

**Comment by bspeare** [comment]
The narrow container looks a lot better for a row of buttons, but we would need to adjust the top and bottom container spacing.  The current default container spacing of `3rem` would take up too much space.   Perhaps we need to add a `Add small top spacing` and `Add small bottom spacing` options to our container settings?

<details>
**Default container spacing of `3rem`:**
<img width="1393" alt="Screen Shot 2022-08-02 at 11 51 12 AM" src="https://user-images.githubusercontent.com/1036433/182442603-87e16467-b799-4958-a358-3f21818128b6.png">



**Container spacing removed:** 
<img width="1338" alt="Screen Shot 2022-08-02 at 11 45 34 AM" src="https://user-images.githubusercontent.com/1036433/182442685-757b059a-42b4-4910-a697-7eb2764d6c7b.png">
**Proposed "small" container spacing of `1.5rem`:**
<img width="1393" alt="Screen Shot 2022-08-02 at 11 51 12 AM" src="https://user-images.githubusercontent.com/1036433/182430699-9b59b658-9a69-4c9a-a55c-39bae6aa5cab.png">
**Or, we could provide the `borderless` option for buttons and use a default container with vertical spacing removed:**
<img width="1250" alt="Screen Shot 2022-08-02 at 12 43 13 PM" src="https://user-images.githubusercontent.com/1036433/182442768-b8fa730e-893f-4329-b7c1-457cb5a589c4.png">



</details>

**Comment by briand44** [comment]
may need to make alterations to button block options available in these region? (full width - maybe this could stack?)

**Comment by bspeare** [comment]
As discussed in grooming, the idea of a one column flex layout was proposed for this.   Below I've added a few screenshots on why this might not be an ideal solution. 

Flexbox approach with `bttn--full` class: `display:flex` on the parent container and with `flex-grow: 1;` on each button.  With this approach you lose on out equal columns. 

<img width="1478" alt="Screen Shot 2022-08-02 at 2 24 02 PM" src="https://user-images.githubusercontent.com/1036433/182456844-29602b27-f31e-4966-8f43-135d6e18e431.png">

This example uses our four column grid layout to create equally sized columns when used with `bttn--full` class:

<img width="1465" alt="Screen Shot 2022-08-02 at 2 26 52 PM" src="https://user-images.githubusercontent.com/1036433/182457373-834a0449-8d36-4df6-a000-41e57b516d32.png">

I think I would prefer to keep using grid layout because it keeps the columns all the same size.  This article sums up the difficulties for equal Flexbox columns: https://css-tricks.com/equal-columns-with-flexbox-its-more-complicated-than-you-might-think/#aa-why-css-grid-is-the-better-choice-here.

**Comment by bspeare** [comment]
We huddled about this and discussed:
- Keeping this based in our grid layout builder solution instead of a full width flexbox layout. 
   - Because it is a familiar and established UX pattern for editors and that we don't necessarily need the flex properties that a flex layout would provide. 
   - Offer 2, 3, 4 column layouts with some custom container padding overrides for the pre-pre-footer region only to address the concerns in https://github.com/uiowa/uiowa/issues/4767#issuecomment-1202978850 like having specific `1` or `1.5rem` container padding instead of the default `3rem`. 
- Set the button block to be `bttn--full` by default. 
- Possibly introduce a "narrower" container so that two buttons could be centered within a two column layout?

**Comment by makurj** [comment]
I'd like to pair on this.

**Comment by bspeare** [comment]
I'm unclear on these parts of the proposed solution: 

- Add a set of reference fields (one per region that can be overridden) that directly references the region fragment type. We could also potentially allow people to create alternate region fragments inline.
- Update the RegionContentBlock class to check if a page is a node and has override fields set and not empty, in which case it would pull the appropriate fragment from the node instead.

I'd be interested in pairing/mobbing on this to get a better sense of this work.

**Comment by joewhitsitt** [comment]
>Add a set of reference fields (one per region that can be overridden) that directly references the region fragment type. We could also potentially allow people to create alternate region fragments inline.

From what I understand, this is an "after content" reference field on the page content that could be turned into an inline entity form field where it can reference an existing item or create a new region item (fragment) on the fly. I think the scope of adding multiple new regions or allowing multiple within a region was dialed back for now.

This would be the per-page override of another reference field located at `admin/config/sitenow/region-settings` that works similar to the pre_footer.

>Update the RegionContentBlock class to check if a page is a node and has override fields set and not empty, in which case it would pull the appropriate fragment from the node instead.

This would change docroot/modules/custom/uiowa_core/src/Plugin/Block/RegionContentBlock.php to display the region item set for the after content field within the region settings or the per-page specific region item set on the page.

The region block itself must be named correctly so that the machine name of the block matches (e.g. after_content). This block is placed in the new template region and saved as config for all default.

**Comment by GaryRidgway** [comment]
After some discussion today, here is what we decided might be the best path forward:

- [x] - We would like to limit the number of blocks in a region item to one item
- [x] - We would like to remove the Styles dropdown from the "Configure region" options of a region on a "Region item" fragment type.
- [x] - We would like to make the button block a multi field option, allowing for up to four buttons in it. 
    - [x] This would have some styles allowing vertical stacking for buttons as well.
- [x] - We would then enable the button block for the "Region item" fragment type.
- [x] - Create a new reference field on the "Region settings" configuration page for the "After content" region.
- [x] - Style the "After content" region to have a sticky style.
- [ ]     - It would be nice to add some JS to make this disappear on upward scroll in a later slice.

This allows us to add robustness to our button block, allowing for stacked button items in other places that have a desire for that ([See tippie admissions](https://tippie.uiowa.edu/executive-mba/admissions))
This also allows us to keep the region item un-opinionated and able to be placed in either section (Pre footer or After content) without any need for configuring them differently.


## Added 8/22/22
- [ ] per page overrides for region items
- [x] styling for region items
- [ ] toggle stick off? how do we scope stickyness?

**Comment by joewhitsitt** [comment]
We arrived here based on the limitations we encountered while trying to move forward with the original proposed solution.

In addition to what Alan mentioned, this path allows us:

- to maintain locked down single column section without extra code.
- to continue to use region_item and not create a separate fragment type, therefore keeping a consistent editing experience. 
- to provide region specific spacing
- open up after_content to other layout builder components in the future.

**Comment by bspeare** [comment]
~We also might want to remove the "Spacing" display options and set a fixed amount of padding for the pre_footer and after_content areas.~ 

- edit: actually Student Life is using the prefooter spacing properties so we probably will need to keep these.
