### ISSUE TITLE
Image Gallery does not respect focal point of images

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#4795]
The image gallery widget does not respect image focal points when used with Masonry style. Masonry style displays images properly (as they are not cropped), but still has the column-first approach rather than row-first approach, but will be a separate issue. You can see the issue on the frontpage of the [https://facultyhonors.clas.uiowa.edu/](https://facultyhonors.clas.uiowa.edu/) site.
<img width="1546" alt="Screen Shot 2022-02-10 at 3 48 42 PM" src="https://user-images.githubusercontent.com/3067017/153502727-e03c1ed1-a39a-47d3-8148-93f85c4b8341.png">

**Comment by mark-bennett-uiowa** [comment]
@dnkemper here ya go! :)

**Comment by dnkemper** [comment]
thank you, @mark-bennett-uiowa 🥳

**Comment by joewhitsitt** [comment]
Little background before we pursue a change here:

- Focal point wasn't originally supported on these since we were changing styles in css between grid/masonry (https://github.com/uiowa/uiowa/pull/877#issuecomment-587005674): 

<img width="372" alt="Screen Shot 2022-02-11 at 9 30 37 AM" src="https://user-images.githubusercontent.com/4663676/153620823-bb66d102-1e0f-40a1-ba54-d0c9a6c08036.png">

>Image Gallery Thumbnail (Default): 768px x Auto - Maintains original aspect ratio but scales to a horizontal width of 768px.
> Image Gallery Thumbnail (Masonry): 768px x 768px - Image is cropped into a 1:1 square image with a center pixel focus. Focal Point is not currently supported.
https://sitenow.uiowa.edu/documentation/media/images-and-files

- Also looks like there was a recent change to get lazy working but in my mind these are reversed compared to what colorbox had which was to provide a smaller image for the grid/masonry but then let the lightbox viewer see unmodified image that is then restricted by user viewport (https://github.com/uiowa/uiowa/blob/b781a753b6e751bfa78284a55f7042068bcca29f/config/default/core.entity_view_display.media.image.image_gallery.yml#L28):

<img width="340" alt="Screen Shot 2022-02-11 at 9 29 49 AM" src="https://user-images.githubusercontent.com/4663676/153620864-5ae6c211-af66-461e-8824-f93e187630e9.png">

**Comment by bspeare** [comment]
Since our image thumbnails are set by CSS and not through an image format, should we close this issue?  If a user wants a gallery that respects the focal point they can now select "No crop" on the preview image.

**Comment by bspeare** [comment]
I'm going to close this until we decide to render our image gallery styles based on image formats.   Until then, this will always be an issue, except you can use the "No crop" option in the image block now and it will respect the focal point set on images.
