### ISSUE TITLE
Stop users from being able to delete media items that are in use

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#4810]
Users can currently delete media items that are referenced in other blocks (e.g Timeline referencing a deleted image). We should find a way to remove this as a possibility.

**Comment by joewhitsitt** [comment]
entity usage has a warning message (that no longer appears to be configured) that we could latch on to disable the delete button or something. we currently don't allow bulk delete of media.

<img width="699" alt="Screen Shot 2022-02-15 at 3 03 42 PM" src="https://user-images.githubusercontent.com/4663676/154149281-75b5e71d-38b9-4b17-bba1-455ed234b329.png">

however, until we clean up media revisions in https://github.com/uiowa/uiowa/issues/4338 some files won't be able to be deleted because there are revisions the site editor doesn't have access to.
