### ISSUE TITLE
Run news migration for International Programs

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4812]
- [x] Setup dev environment for v3 site
- [x] Run migration in dev and provide broken links report
- [x] Update migration to bring keywords into tags
- [x] Update migration with image styles/default styling
- [x] Update manualLookup with client-provided mappings
- [x] Test run in dev for a final sign-off on some of the updates, such as image styling
- [x] Run migration in prod once we get approval from customer, and provide new broken links report

Related issue https://github.com/uiowa/uiowa/issues/4685

General steps to run the migration (adjust depending on which environment it's being run):

- drush @international.local en international_migrate -y
- drush @international.local uli /admin/config/sitenow/sitenow-migrate
- Complete the configuration form following each field's help text
- drush @international.local ms
  - Check that the migrations both listed, one for articles and one for article redirects
- drush @international.local mim international_articles --limit 50
  - There's a memory issue that prevents being able to simply run them all at once. Instead, use this to run it in batches.
  - It will print the potential broken link report after each run, but we only need the last one.
- drush @international.local mim --all
  - Can use this as the last batch or after all the articles have run to do the redirects (or `drush @international.local mim international_article_redirects`)

**Comment by cory-skeers** [comment]
The migration has been run on dev, 1848 articles migrated over along with redirects created from old alias pattern to the new.

Attached is the possible broken links report (migrated articles which had `/node/` style links within their body).

[Possible broken links report.xlsx](https://github.com/uiowa/uiowa/files/8117536/Possible.broken.links.report.xlsx)

**Comment by cory-skeers** [comment]
Couple notes from the client:

- They are going to review the broken links and provide a mapping for those pages which have been built in the new site, as well as some known links that can be stripped (eg links to programs that no longer exist)
- They will like all tags to be brought over for the articles, which was not set up originally, but has been handled in other existing migrations
  - Check for existing tags as part of this. There are some tags already created on the new site that we don't want to duplicate, and the migration needs to be run in multiple batches due to memory, and we don't want each separate run to create duplicate tags
- Check on the image styles, as they appear to not be brought over. Might be broken functionality in the migration, might be inconsistent styles on the existing site
  - As a fallback, if a style cannot be brought over, should default to a smaller image floated to the side of the text

**Comment by cory-skeers** [comment]
PR #4862 has the keyword->tags updates in it.

**Comment by cory-skeers** [comment]
Default fallback image styles have been implemented. The styles weren't being translated because on the existing site they are in the form of wrapping divs with e.g. "image-right-350" classes.

May want to add some cleanup to the migration to remove these. They don't create direct issues, but when the article gets edited/re-saved, they get emptied out and turned into `<p>&nbsp;</p>` creating extra, unnecessary space surrounding images.

**Comment by cory-skeers** [comment]
> May want to add some cleanup to the migration to remove these. They don't create direct issues, but when the article gets edited/re-saved, they get emptied out and turned into `<p>&nbsp;</p>` creating extra, unnecessary space surrounding images.

A method of cleanup (and application of original alignment options, but not size) has been added to the PR. Leaving it open until the manualLookup task can be completed. Can then test all the updates together.

Blocked until we receive feedback from the client.

**Comment by briand44** [comment]
Removing blocked label since Katie provided the updates to the broken links report we were waiting on. I will prioritize this work for an upcoming sprint.

**Comment by briand44** [comment]
Once we run the migration, Katie is hoping to get another report of broken links for articles that have been created since the first report we provided so she can manually update.

Also, she had a question about existing links on the new site that are linking to articles on the old site. Will those need to be manually updated or will they work after the migration?

**Comment by cory-skeers** [comment]
> Once we run the migration, Katie is hoping to get another report of broken links for articles that have been created since the first report we provided so she can manually update.

Can do--updated issue description to include this.

> Also, she had a question about existing links on the new site that are linking to articles on the old site. Will those need to be manually updated or will they work after the migration?

I believe she is using absolute links when linking to articles on the old site, and those links will continue to work after the migration, as there will be redirects in place to direct to the new alias pattern.

**Comment by cory-skeers** [comment]
Planning on running this in prod Tuesday (April 5) eod.

**Comment by joewhitsitt** [comment]
I have read through the issue and looked at the previous related PRs. Though I think I am comfortable running this in Cory's absence, a release needs to be deployed before this can happen.

**Comment by briand44** [comment]
>I have read through the issue and looked at the previous related PRs. Though I think I am comfortable running this in Cory's absence, a release needs to be deployed before this can happen.

Can we create a release then?

**Comment by joewhitsitt** [comment]
Deployment done. Planning on starting after 3:30. Customer has been contacted. Thanks Brian!

**Comment by joewhitsitt** [comment]
Migration seemed to be going well. There were a couple errors and warnings along the way:

`[error]  Unknown format: 0x300`

`[warning] Invalid argument supplied for foreach() NestedArray.php:327`

`[warning] strlen() expects parameter 1 to be string, array given PelEntryAscii.php:101`

`[error]  Invalid marker found at offset 0: 0x52`

`...not enough reclaimed, starting new batch`

Then, muscle memory got the best of me and I didn't realize the migration was "done" and triggered another batch run which spit out:

```
 [warning] array_flip(): Can only flip STRING and INTEGER values! ContentEntityStorageBase.php:670
 [warning] Creating default object from empty value Articles.php:328
 [warning] Creating default object from empty value Articles.php:328
 [error]  Error: Call to undefined method stdClass::save() in Drupal\international_migrate\Plugin\migrate\source\Articles->replaceSpecifiedLinks() (line 329 of /mnt/www/html/uiowa/docroot/sites/international.uiowa.edu/modules/international_migrate/src/Plugin/migrate/source/Articles.php) #0 /mnt/www/html/uiowa/docroot/sites/international.uiowa.edu/modules/international_migrate/src/Plugin/migrate/source/Articles.php(248): Drupal\international_migrate\Plugin\migrate\source\Articles->replaceSpecifiedLinks(Array)
```

At this point, the articles migration was still "importing" but with 0 left to process. I couldn't run mim --all for the remaining redirects migration. Running the redirects migration separately seemed to cause broken links to be re-run. Inspecting links on https://international.prod.drupal.uiowa.edu/students/award-recipients/fulbright-us-student-award-recipients didn't seem correct.

We reset the migration statuses and rolled back. It was thought that since the files were all imported we could try again running `mim --all` but ran into the same array_flip error as above.

We have rolled back, locked out users and notified the customer of the situation. Plan to look at this tomorrow. I had created a backup of the site before running so we could restore and try that with less muscle memory.

**Comment by cory-skeers** [comment]
Can at least add some context for a few of these.

> `[error] Unknown format: 0x300`
> `[error] Invalid marker found at offset 0: 0x52`

These should both be different versions of the same error, where an image is labeled as one format, but is actually another (eg a .jpg that is actually a PNG). The error gets thrown, but everything works fine, because the systems are smart enough to work with what the file actually is. Mostly it's interesting to see how many mislabelled files are out there, and how at least for images, it just kinda gets taken care of by the browser, OS, etc.

> `[warning] strlen() expects parameter 1 to be string, array given PelEntryAscii.php:101`

The PEL is the PNG Exif Library. Don't remember exactly, but this is something like camera EXIF data being more complex than expected, but nothing to worry about for the image itself.

> 
> `[warning] Invalid argument supplied for foreach() NestedArray.php:327`

Not sure about this one...

> 
> `...not enough reclaimed, starting new batch`

This should be the expected behavior for large migrations, but if you watch the memory, something never actually gets reclaimed, leading to our needing to explicitly run separate batches. 

Hopefully that at least helps put the mind at ease given the extra trouble running this, if it needs to be run again! :)

**Comment by richardbporter** [comment]
I can replicate this locally and will work to debug.

**Comment by richardbporter** [comment]
The error is caused by `$revision_id` being `NULL` because `$component['configuration']['block_revision_id']` is not set in some cases: https://github.com/uiowa/uiowa/blob/ca5999eb2c9ca54d37e40710993153d93e17d2cb/docroot/sites/international.uiowa.edu/modules/international_migrate/src/Plugin/migrate/source/Articles.php#L302 This means the block cannot be loaded and the `save()` method does not exist.

One example is node 1391. Trying out a few things locally...

**Comment by joewhitsitt** [comment]
@bdickey Rick created a hotfix that we believe fixes the issue we encountered yesterday. We need to deploy it and then restore the db to yesterday before we try running the migration again. Because the images are already there, we plan to run it without batching.

**Comment by joewhitsitt** [comment]
I want to note that there are image duplicate issues on the current d7 website (including duplicate media ids 👀 ). Though the image duplicates seem to be carried over as it relates the articles they are attached to, they are getting separate media ids this time around and should be easier to deal with if we need to clean them up in the future. D7 = ~400 pages of media, D9 = ~74 pages of media. Short-term win!

**Comment by briand44** [comment]
>I want to note that there are image duplicate issues on the current d7 website (including duplicate media ids 👀 ). Though the image duplicates seem to be carried over, they are getting separate media ids this time around and should be easier to deal with if we need to clean them up in the future. D7 = ~400 pages of media, D9 = ~74 pages of media. Short-term win!

Good to note. I vaguely remember issues from years ago that could be related to this. Good to see there are not 400 pages of media!
