### ISSUE TITLE
Add meta description to uiowa_profiles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4889]
Follow-up from https://github.com/uiowa/uiowa/issues/4837

# Story

As a site owner, I expect meta description to be provided for directory profiles using the uiowa_profiles feature.

# Proposed solution

- [ ] Wait for profiles team to provide meta description value via metadata endpoint
- [ ] Assuming it is similar to canonical_url, wire this up to set the meta description for the page.

**Comment by briand44** [comment]
I think we want to move forward with a simple meta description for now until the directory profiles team is able to provide a better meta description. `<meta name="description" content="Name - University of Iowa" />`

**Comment by briand44** [comment]
Update from Denny:
>Great we will add directoryTitle to the metadata endpoint -- see [#489](https://git.uiowa.edu/java/profiles/-/issues/489). This is a quick change. Beth or Spencer should be able to get it in early next week at the latest.

**Comment by richardbporter** [comment]
I'm assuming this will need to be done via JS to cover the SPA "load" - just like canonical.

**Comment by briand44** [comment]
It looks like the directory profiles team has added `directoryTitle` to the endpoint. I think we will want to setup the meta descriptions to be ```<meta name="description" content="Name - directoryTitle - The University of Iowa" />```. So for https://education.uiowa.edu/directory/john-achrazoglou the meta description would be ```<meta name="description" content="John G. Achrazoglou - Clinical Associate Professor - The University of Iowa" />```.

**Comment by briand44** [comment]
@mjoneill ^^ Does that work for you?

**Comment by mjoneill** [comment]
> @mjoneill ^^ Does that work for you?

Absolutely.  Thanks @briand44 !

**Comment by GaryRidgway** [comment]
Thanks for the updates all! appreciate ya!

**Comment by GaryRidgway** [comment]
I might need a bit of a refresher, do we have separate API keys for profiles to work locally?

edit: i found one that Denny shared with me a while ago.

**Comment by GaryRidgway** [comment]
@mjoneill should there be a description for the listing pages as well?

**Comment by mjoneill** [comment]
> @mjoneill should there be a description for the listing pages as well?

Ideally, yes...but not critical for this story. If it's right there and makes sense to do it now, I'm down with it provided it is really low additional effort and @briand44 gives thumbs-up.  Otherwise, it can wait...  The actual profiles are where the value is.

**Comment by GaryRidgway** [comment]
I think it would be incredibly easy for me to do right now, because it would most likely be a static string. An example of what it might look like would be helpful if possible.

The reason it would be useful to do it now is because i will have to delete the description every time they go back to the listing anyways, so it would be roughly the same amount of work to just set it to a default description.

**Comment by mjoneill** [comment]
Sorry I missed this.  @ABoston88 can help in my absence.  In general, something like: 

`<meta name="description" content="Explore the people of the College of Education.">`

Of course, "College of Education" would have to change depending on site/unit, and that might mean the preceding sent. structure would have to be adjusted depending on Unit Name (what happens if the unit includes "the" or it's multiple units, etc?).  So we get into dev complexity. 

Alex, have a good way through this?

**Comment by briand44** [comment]
We discussed setting the directory listing meta description temporarily to use `Site name - Directory title` and then have conversations with the Directory Profiles team if we should be handling this long term or should they. This would result in a meta description like ```meta name="description" content="College of Education - People.">``` for Education and ```meta name="description" content="College of Dentistry and Dental Clinics - Faculty Profiles.">``` for Dentistry. This allows the customer control since they have the ability to set the directory title and if they had multiple directories the meta descriptions could be different for each directory. If we handle this long term we would likely add a field on the Directory Profile config page to set this individually for each directory. @mjoneill thoughts??

**Comment by mjoneill** [comment]
@briand44 I like this.  Let's roll this direction if it's doable.
