### ISSUE TITLE
UICB - Build migration for News Item content type

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#4901]
Need a script to migrate the 130 News Items as Articles for the Center for the Book. Fields are pretty straightforward, there is a file upload field but only [one article](https://book.grad.uiowa.edu/news/2017-10-22/faculty-news-emily-martin-speaks-university-northern-iowa-and-octavo-fest-cleveland) uses it, so the file could just be added manually if needed.

One possible hiccup is the image field. Articles only allow one featured image but some of the news items have multiple images, [like this](https://book.grad.uiowa.edu/news/2017-11-10/uicb-mfa-candidates-among-caxton-award-winners).

**Comment by joewhitsitt** [comment]
is this the `book` database on the grad application?

**Comment by briand44** [comment]
See if customer has thoughts on how they would prefer to handle the multiple images.

**Comment by e-marie-w** [comment]
So I added the filter, turns out only 4 articles have more than one image. 

It seemed like more, but sometimes what looks like multiple images are all part of only one, like [https://uicb.uiowa.edu/news/2019-02-18/uicb-codex-2019](https://uicb.uiowa.edu/news/2019-02-18/uicb-codex-2019).

**Comment by briand44** [comment]
Based on ^^ I would say we just migrate the first image and the additional images could be added manually within the article body? Thoughts?? We also got some feedback from Iowa Now folks that they would like to be able to have a photo gallery on news articles so that is a feature we will likely be discussing in the near future but not sure if it is worth holding this up.

**Comment by pyrello** [comment]
We have capacity, so we are going to migrate these by hand.
