### ISSUE TITLE
Run UIPress Migrations in Prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4903]
- [x] Run UIPress author migration
- [x] Run UIPress book migration
- [x] Delete unpublished book stubs
- [x] Fix Ed Folsom and Doug Henderson person pages
- [x] [Add additional aliases with accented characters](https://github.com/uiowa/uiowa/pull/4873#issuecomment-1060746588)
- [x] Fix MP3 links on Poems From Guantanamo: https://uipress.prod.drupal.uiowa.edu/books/poems-guantanamo

Blocked until #4663 and #4662 are complete.

**Comment by pyrello** [comment]
Added a couple bullet points for clean-up tasks that will need to be done after this is completed.

**Comment by pyrello** [comment]
This is no longer blocked.

**Comment by e-marie-w** [comment]
Had a quick meeting with customer this morning, they want some minor changes to the book content type - in the right sidebar, the publication details should be the last accordion instead of the first. It should also be closed by default while the paperback, hardcover, ebook, etc tabs should be open by default.

These changes can be done in a PR after the migration, correct? Or should they be done first, before any migration?

**Comment by joewhitsitt** [comment]
If there are no changes to fields in how they capture data and they are just display adjustments then I think these things can wait till after.

**Comment by joewhitsitt** [comment]
I believe this is done. Notified the customer to review. We suspect the mp3s didn't migrate because it was mapping to a minimal format where the media functionality is not present. Had to link to relative paths after uploading them to the website.
