### ISSUE TITLE
[Spike] As a developer, I can articulate a desirable path forward for how we can solve for an off-brand theme.

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5007]
The off-brand theme will be:
- turned on by the web team (not enabled/adjusted by site owner)
- maintainable by web team with minimal overhead
- provides logo swap capability
- provide a fixed set of non-UI colors

Deliverables:
- Recommendations for how we could move forward

# Investigation outcomes
## Customizations needed
- Color changes
- Logo swap
- Search change

**Comment by pyrello** [comment]
In trying to understand @GaryRidgway's suggestion about using `:root` variables in CSS, I came across this article which helped me grok the concept better: https://css-tricks.com/breaking-css-custom-properties-out-of-root-might-be-a-good-idea/. Also might specifically be helpful because of how our CSS is built in a modular fashion.

**Comment by briand44** [comment]
Does something need to happen with search. Can CSE search if it is a non uiowa domain?

**Comment by GaryRidgway** [comment]
I think a good first step for using html/:root variables is creating a proof of concept in uids to show that we can change the color with JS. Making notes of problems along the way and discerning the viability of that approach is important to note.

**Comment by joewhitsitt** [comment]
@mjoneill i was wondering if we could think about just not allowing a replacement logo and just hiding the block iowa in the header/footer. for branded websites the policy is no alternative logos. could we use that in a way to say "no logo for you?"

i am asking this not knowing the technical difference between supporting alternative logos versus just hiding the part of the header.

**Comment by GaryRidgway** [comment]
[I whipped up a quick example of how this might work](https://codepen.io/purple_salmon/pen/rNpzdMw)

**Comment by mjoneill** [comment]
> @mjoneill i was wondering if we could think about just not allowing a replacement logo and just hiding the block iowa in the header/footer. for branded websites the policy is no alternative logos. could we use that in a way to say "no logo for you?"

I like the thinking behind this, and would encourage us to consider all alternatives.  

Partners who need an off brand theme will likely need a mechanism to express their logo/identity mark at the top of each page.  I articulated a possible solution for that as "logo swap" in the current mechanism...but if there is an alternative path that is more appropriate, let's explore it.  Ideas?  @bspeare ?

It also strikes me that we'll likely need to solve for site search issues.  Current search implementation of the header uses a site search tied to Google.  I don't know if we can use that for sites on off-campus domains, etc...

Tagging @joewhitsitt

**Comment by bspeare** [comment]
@mjoneill can you provide some potential sites that will be using this off-brand theme?  It would be nice to use one of their logos as we are working through this spike.

**Comment by mjoneill** [comment]
- https://iexplorestem.org/
- https://iowalionseyebank.org/
- https://iowareadingresearch.org/
- https://neuronext.org/
- https://wirrc.org/
- https://iae.education.uiowa.edu/
- https://iowateacherintern.org/
- https://www.humanitiesiowa.org/

@bspeare

**Comment by bspeare** [comment]
Edit: The logo swap in the block Iowa section doesn't look that great.  

<details>
<img width="1482" alt="Screen Shot 2022-03-31 at 11 05 48 AM" src="https://user-images.githubusercontent.com/1036433/161101134-a15c0f0e-0a91-4860-a1ea-64891286fd22.png">
<img width="1483" alt="Screen Shot 2022-03-31 at 11 07 34 AM" src="https://user-images.githubusercontent.com/1036433/161101136-add0dd00-26ec-4211-a856-ab15b69bf821.png">
<img width="1502" alt="Screen Shot 2022-03-31 at 11 10 20 AM" src="https://user-images.githubusercontent.com/1036433/161101148-0a63f2ad-4caa-4014-af28-be60781967cb.png">
<img width="1494" alt="Screen Shot 2022-03-31 at 11 04 04 AM" src="https://user-images.githubusercontent.com/1036433/161101131-b7f9335a-4ae7-4c13-978f-90399fa1051d.png">
 </details>

**Comment by pyrello** [comment]
Creating this feature likely means having to set up SiteNow/theme configuration options that we would not want to be available on most sites. These sites are going to need to use a mechanism similar to how intranet sites are set up. We would enable this feature for relevant sites (rather than allowing them to opt in on their own).

> Does something need to happen with search. Can CSE search if it is a non uiowa domain?

> It also strikes me that we'll likely need to solve for site search issues. Current search implementation of the header uses a site search tied to Google. I don't know if we can use that for sites on off-campus domains, etc...

We solved for this in the intranet feature by using a generic search block and having a different settings for where it directs depending on whether we are in the default system or an intranet-enabled site. I imagine that the solution for this would be similar. @bspeare wired this up, so he might have a bit more insight.

**Comment by briand44** [comment]
As far as search goes, I think we want to understand limitations for Google CSE before going a different route. Some of these sites are currently using Google CSE

**Comment by joewhitsitt** [comment]
If they currently have a separate CSE id which I most of the above do, we should be able to repurpose it.

**Comment by GaryRidgway** [comment]
@bspeare and I were talking over other options for this and we pondered up the solution of putting the logos in the Sitename section below the top yellow bar. [For context, we are talking about the portion on this page where it says "Site Name".](https://uids.brand.uiowa.edu/components/detail/iowa-bar--site_name_below.html)

<details>
<summary> Here are a few examples of this in action.</summary>
<img width="1482" alt="Screen Shot 2022-03-31 at 11 05 48 AM" src="https://user-images.githubusercontent.com/23122142/161107647-ad512a98-8603-4f3e-9af1-fec1cf660247.png">

<img width="1482" alt="Screen Shot 2022-03-31 at 11 05 48 AM" src="https://user-images.githubusercontent.com/23122142/161107654-18c8d9fb-a66a-47ff-86a8-9efcb3ee8b16.png">

<img width="1482" alt="Screen Shot 2022-03-31 at 11 05 48 AM" src="https://user-images.githubusercontent.com/23122142/161107661-b6eef58d-4d62-49e2-ad81-7ae510560b4b.png">

<img width="1482" alt="Screen Shot 2022-03-31 at 11 05 48 AM" src="https://user-images.githubusercontent.com/23122142/161107667-f3203b2a-0ed2-47ab-8a58-082fac44eaa4.png">

</details>

**Comment by pyrello** [comment]
If we are only talking about ~10 sites, then it might be worth considering whether we need to build a system for overriding theme settings at all. It might make more sense (and take less time) to just work on each of these sites as custom one-off, providing a site split for each one and a corresponding custom module that would provide theme overrides. It seems like the issue above about swapping icons is partially an issue because we are trying to find a one size fits all solution.

**Comment by briand44** [comment]
The list above is not exhaustive but yes, we are only referring to a fairly small number of sites.

**Comment by pyrello** [comment]
I'm interested in pairing on this.

**Comment by GaryRidgway** [comment]
I would also like to be involved if at all possible

**Comment by GaryRidgway** [comment]
Talked to @pyrello today after standup about what this probe might look like. We decided that it would be a good path forward to create a module that would cover all of the necessary things to modify a website, and then document discoveries about it as we go. We also decided that we wanted to do daily checkins so that we aim the probe over time and don't invest too hard in one direction or another.

**Comment by pyrello** [comment]
Intended deliverable is a list of customizations we will need to make and our proposed solution for each one. The hope is that we can then evaluate whether applying those customizations per site or building a system to handle it makes the most sense.

**Comment by bspeare** [comment]
@GaryRidgway Do you want to post a link to your Google doc here and then close the issue?

**Comment by GaryRidgway** [comment]
[Here is the writeup that I have created!](https://docs.google.com/document/d/1rc4S0CX08DIc1ZMbW6x1OMPb77aCTIgQTVDUVHmQxPE/edit?usp=sharing)
