### ISSUE TITLE
Override template for area of study PDF layout

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#5022]
Override for area_of_study PDF layout. See

https://github.com/uiowa/uiowa/blob/68325126adc6d9be0b338b9c74fb074442422eff/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--area-of-study--pdf.html.twig#L68

https://github.com/uiowa/uiowa/blob/68325126adc6d9be0b338b9c74fb074442422eff/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--page--pdf.html.twig#L68

**Comment by richardbporter** [comment]
Seems like this is done, no?

**Comment by bspeare** [comment]
Yeah, not sure what this one is about.   Was the todo meant as a comment about what the template was doing?

**Comment by richardbporter** [comment]
node--area-of-study--pdf.html.twig is definitely scoped to AOS so that seems done. If I had I to guess, I'd say I set up the initial PDF functionality with a generic template, added a todo, scoped it to AOS later and forgot to remove the todo. 

The node--page--pdf.html.twig todo comment seems like it can be removed because I think that is printing other stuff.

**Comment by richardbporter** [comment]
>node--area-of-study--pdf.html.twig is definitely scoped to AOS so that seems done. If I had I to guess, I'd say I set up the initial PDF functionality with a generic template, added a todo, scoped it to AOS later and forgot to remove the todo.

I think this is something that the GitHub app could help with - make todos visible on PRs before they're merged.

**Comment by richardbporter** [comment]
I remove these in #4991
