### ISSUE TITLE
IISC - Customize Person content type

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#5049]
## Story
As an IISC editor/webmaster, I want the same fields/options available in D7 Person content to be available in the D9 Person content.

## Solution

Add the 'Groups' field options (Affiliated Faculty and Staff, Community Partner, IISC Faculty & Staff Network, IISC Staff) to our Person Type list. Remove other Person Type options?
Create 'Role with the IISC' textfield (note: this is different from the Job Title field, which can be migrated to the Title/Position field in D9.)

**Comment by pyrello** [comment]
There are the following roles:
- Faculty Advisor
- IISC Founder, Advisory Board member
- Community Coordinator
- Advisory Board - Community Representative
- Faculty partner

I'm not a fan of adding a new field if it can be avoided because it will force us to split the person entity view display.

I have laid out 3 different options for the customer:
1. Move everything into person types.
2. Move groups into person types and roles into tags.
3. Move everything into tags.

Waiting to hear back.
