### ISSUE TITLE
Terms of Service content not showing

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5131]
# Problem
When creating a webform and adding the Terms of Serice element, the contents of the element are hidden from view.

# Steps to reproduce
Visit the page https://sandbox.prod.drupal.uiowa.edu/form/terms-of-service. Click the link in the terms of service to open up the modal. The title is shown but the terms content/description are hidden from view.

There is a class `.js-hide` that is on the div.

**Comment by joewhitsitt** [comment]
I think this started happening when we adopted drupal 9. somewhere, we are still loading some stable theme stuff and this is applying: docroot/core/themes/stable/css/system/components/js.module.css

stable9 was introduced and doesn't have the `!important` on this css.

**Comment by bspeare** [comment]
This should be fixed by now, shouldn't it?  It is removed here: https://git.drupalcode.org/project/drupal/-/blob/9.4.10/core/themes/stable/css/system/components/js.module.css  But our current version still has it: https://sandbox.prod.drupal.uiowa.edu/core/themes/stable/css/system/components/js.module.css.   @joewhitsitt Any idea why this is the case?

**Comment by joewhitsitt** [comment]
Our codebase has this:
docroot/core/themes/stable/css/system/components/js.module.css (still important) and what is being called.
docroot/core/themes/stable9/css/system/components/js.module.css (important removed) not being called.

https://www.drupal.org/node/3107179

Since we are still using classy, I think stable is still being called because of it.

>a "snapshot" of Drupal's default themes/CSS at the time of an initial major release (i.e. Stable uses the CSS/templates that were default when Drupal 8.0 was released...).

>A theme will use the Stable themes as a base theme to ensure markup and styling are not changed by Drupal updates. This ensures that themes will not have unpredictable changes resulting from a Drupal update. Note that the "fence" provided by Stable as a base theme also means core template/CSS improvements do not make it through either. Stable themes will not change unless it's an objective bug fix.

**Comment by bspeare** [comment]
Thanks @joewhitsitt.  It looks like this would be fixed if we moved to https://www.drupal.org/project/classy before Drupal 10.  I'll create an issue for it.
