### ISSUE TITLE
uiowa.edu vertical videos not working for iPads

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#5221]
# Problem
uiowa.edu vertical videos not working for iPads

# Steps to reproduce
Go to uiowa.edu on an iPad and try watching the vertical videos. 

# Proposed solution

- Investigate removing `iPad` from https://github.com/uiowa/uids/blob/3.x/src/components/video/vertical/vertical.js#L56. 
- Investigate removing https://github.com/uiowa/uids/blob/3.x/src/components/video/vertical/_vertical.scss#L164-L169

**Comment by joewhitsitt** [comment]
At the moment, I have a device lab of different ipads to volunteer for testing

**Comment by GaryRidgway** [comment]
After investigating it seems that the problem is the `highlight__wrapper" element overlaying the video controls on ipad width.
![2bfdea352ad0346a282f63758d6fa9d5](https://user-images.githubusercontent.com/23122142/170781443-d1397e45-d5ba-4157-b7ba-26b18ae28041.gif)
![b4940d95308f96b5d271ec0c24e9ceab](https://user-images.githubusercontent.com/23122142/170784881-e00c5b88-a1a0-4a97-b408-00c4cc17dbbe.gif)
