### ISSUE TITLE
Taxonomy term feeds contain breadcrumbs and duplicate titles

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5229]
# Problem
The out of the box taxonomy term view feed displays are pulling in the full node render for items.

<img width="822" alt="Screen Shot 2022-05-04 at 12 14 26 PM" src="https://user-images.githubusercontent.com/4663676/166744075-c6357e1d-2c82-4537-8aa6-f3a7270f6604.png">

# Steps to reproduce
Pull in a v2/v3 feed into aggregator/rss block and see how it is displayed: https://education.uiowa.edu/taxonomy/term/196/feed

# Proposed solution
- [x] Modify the taxonomy_term_view RSS display to breakup items into the proper RSS spec elements similar to SiteNow Articles.

**Comment by briand44** [comment]
sitenow articles is an example of where this is working correctly.

**Comment by pyrello** [comment]
Just noting that we discussed that this would move us away from core's default view config for the term RSS feed. I don't believe that the core team provides update hooks for default views because that would potentially break lots of sites. Our option for keeping up-to-date with core changes is to periodically compare our views to theirs and see if there are changes we want to pull in.

**Comment by joewhitsitt** [comment]
This might cause https://github.com/uiowa/uiowa/issues/5025 to come up sooner than later. By specifying specific fields in this view, each content type that wants a description in their RSS feed item is going to have to use field_teaser or split and switch this to body.
