### ISSUE TITLE
Design enhancements for 2plus2 pages 

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5253]
Way to call out that a visitor is on a 2plus2 page vs an Area of Study page (url structure "/2plus2/" including updated breadcrumbs, maybe banner with pre-title?)

**Comment by briand44** [comment]
template has been set up already as part of previous work.

**Comment by GaryRidgway** [comment]
Does anyone have any more context on what we decided on for the enhancements last planning?

**Comment by briand44** [comment]
I wasn't in last planning but it was previously mentioned that potentially using banner image with pre-title on all of the 2+2 pages could be a way to differentiate these pages from AoS pages.

**Comment by bspeare** [comment]
@GaryRidgway here's what I think is the work to be done here:

1. A field_image (featured image), field will need to be added to the content type.
2. The content type will need to be converted to use a layout builder layout 
3. The layout builder template will need to be converted to have a Header region so that the featured image will use the banner template (https://github.com/uiowa/uiowa/blob/main/config/sites/admissions.uiowa.edu/core.entity_view_display.node.event_series.default.yml#L28-L85)
4. Banner settings and pre-title will need to be set and passed in through `admissions_core_preprocess_layout` in the `admissions_core` module

**Comment by bspeare** [comment]
As @cory-skeers mentioned, these pages might also need some banner images.  Not sure if we've added a banner block to views pages yet...?

https://admissions.uiowa.ddev.site/2plus2/majors
https://admissions.uiowa.ddev.site/2plus2/colleges

**Comment by bspeare** [comment]
Maybe we limit the first slice of this to the content type and plan an additional slice to groom the views pages?

**Comment by bspeare** [comment]
Jessica recommended that we put the `2 Plus 2 Plan` in a gold background and set the page title without the gold background.   She also said they spell out 2Plus2 as `2 Plus 2 Plan` in the brochure they designed.  Here's what the proposed change would look like.   It will require overriding some custom CSS in `admissions_core` to override the banner styles. 

<img width="1654" alt="Screen Shot 2022-05-20 at 10 34 01 AM" src="https://user-images.githubusercontent.com/1036433/169562619-b2e12019-852d-44fd-b766-c8256eaa38f8.png">

**Comment by GaryRidgway** [comment]
I will get to work on this!
