### ISSUE TITLE
Give sitenow_find_text back to the community?

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5282]
# Story

As a drupal site builder, I can leverage the sitenow_find_text module on my non-university Drupal 9 website.

# Question

Is this module something we want to generalize and give back to the community? Is it possible or is it too specific to our codebase? 

# Proposed solution

- [ ] Audit and generalize code so that it works for any Drupal website's fields, blocks.
- [x] Rename to https://www.drupal.org/project/find_text and see if Mark would hand over the project to us.

**Comment by pyrello** [comment]
If we are not able to immediately get this setup in the `find_text` module namespace, we could potentially release this as a sandbox module first. 

I would suggest that our goal should be to get could into an external repo ASAP because it opens up the possibility of other community members getting involved sooner rather than later and that is ultimately one of the goals with this project.
