### ISSUE TITLE
Create 2plus2 landing page and demo content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5291]
As a site owner for Admissions, I would like to see an example of how site visitors will be able to navigate to 2plus2 information through a community college as well as through an available major.

# Additional Info
Add a landing page with community colleges and available majors and any other additional content needed that ties all these pages and functionality together and allows Admissions to be able provide feedback or sign off on this work.
- Add basic page at `2plus2` url and design a landing page, intro text with links to the view pages. 
- Possibly use existing community colleges block?
- Might need a majors block if that's an easy lift?

**Comment by joewhitsitt** [comment]
Sorry, i missed the bit where DEV was removed from the title. Where is this being added?

Looks like there is a redirect in place for /2plus2 that would need to be removed if a separate page will be created there.

**Comment by briand44** [comment]
>Where is this being added?

I guess I was assuming DEV unless something else makes more sense?

**Comment by joewhitsitt** [comment]
Started this here: https://admissions.dev.drupal.uiowa.edu/2plus2

Looks like we need to adjust URL paths and breadcrumbs depending on where they want this. If they like the sidebar navigation, it needs to be in the menu system

**Comment by bspeare** [comment]
I updated the https://admissions.dev.drupal.uiowa.edu/2plus2 page with some more demo content.  Since we have the participating colleges view block, should we just create a majors block too?  I think it would be useful to have that content on the overview page.   They could also manually add the majors to a text area like I have on the demo page.

**Comment by joewhitsitt** [comment]
I like the idea of consolidating majors and colleges "all" listings on one page and getting rid of that navigation. the view page (all) for majors can still exist but the majors block will go straight to those contextual paths.

**Comment by briand44** [comment]
I like what you have and feel like we wouldn't need those menu links but wonder if we lose contextual information without that all majors page? Maybe some of that text could be worked into the landing page? Maybe I am missing something as well.

**Comment by joewhitsitt** [comment]
Created a proof of concept "Available Majors" block in case consolidation is preferred. These are linked on the fly in `admissions_core_preprocess_views_view_field()` so I am not sure how much visual change there can be.

https://github.com/uiowa/uiowa/pull/5306

This could be merged into DEV to be of use there or demonstrated locally during zoom.

**Comment by bspeare** [comment]
It looks like there might be around 280 `Major (2 Plus 2)` pages total.  We might want to put the work into setting the featured image for them.

**Comment by bspeare** [comment]
This may have been already discussed, but is Scott ok with not having separate listings for these?

- [Economics](https://2plus2.admissions.uiowa.edu/majors/majors/economics-ba.htm) (BA program)
- [Economics](https://2plus2.admissions.uiowa.edu/majors/majors/economics.htm) (BBA program)

**Comment by briand44** [comment]
Are these pages supposed to use the path `/2plus2/....`?

- https://admissions.dev.drupal.uiowa.edu/majors/des-moines-area-community-college
- https://admissions.dev.drupal.uiowa.edu/majors/des-moines-area-community-college/american-studies

Also should they have a breadcrumb path back to the landing page?

**Comment by briand44** [comment]
>This may have been already discussed, but is Scott ok with not having separate listings for these?
[Economics](https://2plus2.admissions.uiowa.edu/majors/majors/economics-ba.htm) (BA program)
[Economics](https://2plus2.admissions.uiowa.edu/majors/majors/economics.htm) (BBA program)

I don't recall if we discussed that.

**Comment by bspeare** [comment]
I know we discussed with Scott that https://admissions.dev.drupal.uiowa.edu/majors/des-moines-area-community-college/american-studies would not have a breadcrumb link just like the major pages https://admissions.dev.drupal.uiowa.edu/academics/accounting.    I don't know about the `/2plus2/....` part.

**Comment by bspeare** [comment]
Here are the requests from today's meeting:

- Remove "RSS Feed" button from taxonomy term page. 
  - Do we create an entirely new taxonomy view for this one thing or do we try to use the existing "Colleges (taxonomy term)" TVI?
- Set the breadcrumbs page to include the `2 plus 2` page on the community college pages. 
  - Is there a way to set breadcrumbs to appear on taxonomy pages?   
- If we can't set the breadcrumbs on the community college pages, then he wants all breadcrumbs removed.
  - If all breadcrumbs are removed from the `2 plus 2` pages, then perhaps we add a button to the bottom of each `2 plus 2` pages that says `2 Plus 2 Grad Plan` or something like that.

**Comment by bspeare** [comment]
Perhaps we can switch the banner on the majors page to use a button instead of the pre-title?  Making that change might help clear up the ambiguity of whether the pre-title is meant as a breadcrumb. 



Current version:

<img width="1702" alt="Screen Shot 2022-05-25 at 2 55 01 PM" src="https://user-images.githubusercontent.com/1036433/170356567-394686eb-6a3b-4ec0-9fd9-b434b96bbe72.png">


Proposed version:

<img width="1587" alt="Screen Shot 2022-05-25 at 2 55 01 PM" src="https://user-images.githubusercontent.com/1036433/170357040-b0f98c55-b137-43a2-a899-8307ba955812.png">

**Comment by bspeare** [comment]
@pyrello brought up the point that the button acts as more of a forward prompt instead of a return action.   Here's a screenshot of the page using the breadcrumbs in the content area.   I think this could be a good solution, however it looks like there's a pattern/token issue. 

<img width="1604" alt="Screen Shot 2022-05-25 at 3 24 18 PM" src="https://user-images.githubusercontent.com/1036433/170360820-f3b09bbc-0a49-4714-8789-becc3a0a96f4.png">

**Comment by briand44** [comment]
I like ^^ better if we can get it to work

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uiowa/pull/5306.
