### ISSUE TITLE
As a content creator on Signage, I am unable to use the dropdowns to schedule a sign

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#5442]
Potential Solutions:

1. Signage: Patch https://www.drupal.org/project/drupal/issues/3292211 
2. Adminimal theme
3. Our own CSS

More details: https://iowaweb.slack.com/archives/C0164FNN1PV/p1657310435684399

**Comment by joewhitsitt** [comment]
Since the apps are covered by RA and this might not get merged/released, I say we just load a simple css file with the solution using the uiowa_signage info file for both signage and healthcare signage https://www.drupal.org/docs/7/theming/working-with-css/adding-style-sheets-from-info-files

Adminimal solves this issue but could cause other issues

**Comment by briand44** [comment]
https://www.drupal.org/project/drupal/issues/3292211 is getting quite a bit of recent activity.  We may find out soon if this is going to get committed. Currently RTBC. I would be fine going with the patch if we have any issues with custom css.

**Comment by makurj** [comment]
Patch hasn't been committed as of right now. Going with CSS.

**Comment by joewhitsitt** [comment]
Once in PROD and solution confirmed, communicate/resolve the cherwell ticket 1437037

**Comment by makurj** [comment]
UI Signage working great. Deployed to Healthcare signage also. Someone on campus will need to test.
