### ISSUE TITLE
Create mockup of an LLC page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5453]
As a Housing site owner, I would like to see a mockup of an LLC page.

# Additional Info
Mockup using basic page

This will help us understand what can be done currently, if this needs to be structured, what additional development is needed and provide something to get feedback on.

# Requirements

They would like the ability to have some intro text explaining the LLC on each individual LLC.

They would like the ability to have a personal student headshot with a quote for each LLC https://housing.uiowa.edu/communities/business

They would like the ability to enter one or more course names that are related to an LLC and have course information display with a link to MyUI (https://housing.uiowa.edu/communities/business). https://github.com/uiowa/uiowa/issues/5071

They would like the ability to list one or more LLC contacts in a card format that display a photo, name, position/title, [pronouns](https://github.com/uiowa/uiowa/issues/2234), phone and email. https://housing.uiowa.edu/communities/business.

They would like the ability to list what majors are open to each individual LLC https://housing.uiowa.edu/communities/iowa-writers

They would like the ability to display upcoming events for a particular LLC.

They would like to output a call to action link on each LLC for "Why LLC's" that would link to a similar page as https://housing.uiowa.edu/why-communities similarly to "Learn More" link on https://housing.uiowa.edu/communities/business

They would like to output a call to action link for information on how to apply for housing. My understanding is these all link to same page.

They would like the ability to reference a location (residence hall) to tell students where the LLC will be for the upcoming year. https://housing.uiowa.edu/communities/business

They would like the ability to display information about who campus partners are and how to contact them. Currently text area. https://housing.uiowa.edu/communities/business

**Comment by joewhitsitt** [comment]
As I go along on this, I am going to make some notes about how this could be easier:

- Allow residence halls to be selected through the featured content block (site-split)
- Allow Person reference via Blockquote block - Future slice: https://github.com/uiowa/uiowa/issues/2881
- Events keyword per learning community to start with
- Obviously a solution for pronouns would be helpful: https://github.com/uiowa/uiowa/issues/2234

**Comment by joewhitsitt** [comment]
>They would like the ability to list what majors are open to each individual LLC https://housing.uiowa.edu/communities/iowa-writers

Is this the blue info alert text or am I missing something else?

**Comment by briand44** [comment]
>Is this the blue info alert text or am I missing something else?

Yes, it is. I believe there is some sort of paragraphs implementation on the existing site that allows for text or choosing a major (taxonomy)

**Comment by joewhitsitt** [comment]
Staging work here: https://housing.prod.drupal.uiowa.edu/connect2biz

Feel free to review while in progress

**Comment by joewhitsitt** [comment]
I believe I have accounted for the elements specified in this issue. Reviewers, have at it.

**Comment by mkyoder** [comment]
This looks great so far! Here are some notes/questions at first glance:

**Related community experiences**
I know that this is not on these pages since we determined we are not doing the filtering for these like we did with the residence hall pages. 

A related question I have to these is: since there is no filtering, do you recommend building out a basic page with some text at the top to tell about the LLC experience and list all the LLCs using the cards features to display them? 

Basically I would like to cut down the text on these pages and combine the two on one page: https://housing.uiowa.edu/why-communities and https://housing.uiowa.edu/communities. Is that recommended or will that be too crowded with information? 

**Open to/LLC majors**
This looks good! I think we would just need some type of text field here (or whatever solution you all determine is best) to tell what majors this LLC is open to or what types of students. 

Some identity based LLCs like these pages: https://housing.uiowa.edu/communities/unidos, https://housing.uiowa.edu/communities/young-gifted-and-black, https://housing.uiowa.edu/communities/all-in are not open to a specific major but student identity. 

And with the selector going away and not using taxonomy terms anymore for these, then maybe a basic text field makes sense here? I will defer to you all. 

**Apply**
Looks great! This would link here: housing.uiowa.edu/apply. 

**Explore**
Looks good! This currently links back to the selector and that is going away.

I think this can link to a basic page that I can create with more information about LLCs and cards showing the individual LLCs. 

**Student quote**
Will be there an option to add more the one student quote? We would like this option if possible. 

**Community details**
Is there an option to display the residence hall differently? The photo seems just a bit small here.  

**Living Learning Community Courses**
Looks great! 

**Upcoming Events**
Looks great!

**Contact**
Looks great!

**Campus Partners**
Looks great!

**YouTube Video**
Some of our LLCs have videos telling about the community, but not all. What do you advise for this? Can this be displayed on the page in some way? Or it a basic hyperlink to the video the advised solution?
See here: https://housing.uiowa.edu/communities/unidos, https://housing.uiowa.edu/communities/young-gifted-and-black

**Why Living Learning Communities**
I really like this! However, maybe I need to think on it a bit. 

If information on these two pages are being combined (https://housing.uiowa.edu/why-communities and https://housing.uiowa.edu/communities) and linked from the explore piece at the top, maybe this doesn’t make sense to have anymore? Just think out loud here...

**Comment by mkyoder** [comment]
Also, if this is not the type of feedback you are looking for, please let me know. :)

**Comment by bspeare** [comment]
The page looks good!  I have a few suggestions on the first part of the mockup:

- Featured image: Use a banner instead of the featured image and move the "Apply" and "Explore" buttons into the banner? Use banner pre-title for "Living Learning Communities" and that would free up more room for the Community details block.
- Community details: center all of the headings and info in the community details block or left aligned?  The mixture of the two looks a little off. 
- Locations: Maybe these should move to a separate section in a grid display so it doesn't create an extra long sidebar like on https://housing.uiowa.edu/communities/new-student?  Perhaps move to under the blockquote section?
- CTA: move to the bottom of the page?

**Comment by mkyoder** [comment]
Reached out to housing this afternoon in order to get events for content.uiowa.edu. When I hear back from them with event information, I can add it into content.uiowa.edu.

**Comment by joewhitsitt** [comment]
@bspeare I tried some of your suggestions but I am not sure I pulled them off.

@mkyoder thanks for your comments. here are some responses:

- Ultimately think of these as a template you can start with to create consistency across your site but that you can modify (to the extent a page can) to fit the specifics of a particular LLC.
- I think consolidating pages for this content would work. Since the LLCs are basic pages they can be referenced to any basic page using the featured content block (one look) or by crafting a static card (more style options). Since this content doesn't change as often as articles, it should be fairly easy to update this page as LLCs are added/removed/updated.
- Re Open to/Majors - This is currently just a text field. I am leveraging some specific classes to create the badges but this text can be modified to work for most situations.
- Updated the apply link (absolute link).
- Once a landing page for explore is created, we can link to it.
- "Will be there an option to add more the one student quote?" - Yes, as a basic page, the quote block is available to add as many as you think.
- Per Ben's recommendation since there could be many locations, I split it out to a separate grid and set a larger card picture. Since this is just a card currently, there are several display options for how to shape this content.
- YouTube videos can be added to any wysiwyg and since this is a page, you can place them wherever.


For now, I have left the CTA "Why LLCs" where it is. Knowing where it will link and how important it is to send visitors that way from an LLC will help decide if it is needed/where on the page it should be.

**Comment by bspeare** [comment]
@joewhitsitt I think it looks good.   I made a couple of proposed design adjustments at https://housing.prod.drupal.uiowa.edu/node/556/latest.  Feel free to revert to the previous version if you disagree.   Notably, I moved the "Why LLCs" to a card and the events section to the bottom of the page since it sounds like those might not be populated that much.

**Comment by mkyoder** [comment]
I looked at this again and this looks great! I realized I was looking at it not from a functionality perspective before. So sorry about that! After going over this page again: https://housing.prod.drupal.uiowa.edu/connect2biz, I think this looks great and will definitely work for us functionality wise. Once it is in a spot where I am able to clone it and add in real content, I will let you know if I run into any issues. 

I still haven't heard back from the UHD team yet on LLC events to add so that piece can be tested. If they don't get back to me this week, am I able to add in dummy content into content hub? Or is that not advised? My guess is that they won't know any upcoming LLC events this early as they don't plan those until close to August when students arrive. But I will push to get something from them.

**Comment by briand44** [comment]
@mkyoder , have you had a chance to look at https://housing.prod.drupal.uiowa.edu/node/556/latest? Ben made a few adjustments mentioned in https://github.com/uiowa/uiowa/issues/5453#issuecomment-1190401677. Curious if you prefer how it is or those new adjustments? I think once we decide on that we may be in a place where you could replicate this page and try creating another LLC.

**Comment by mkyoder** [comment]
Yep! Sorry I was getting a ‘page not found’ when I clicked on that even after being logged into housing. But I can see it now. I'll take a look at it.

**Comment by mkyoder** [comment]
This looks great as well! However, I think I’d prefer how it was before. From a user perspective it makes sense to keep events and courses together in order to show a user the “package” so-to-speak of what they would get if they joined this LLC (e.g. courses and events to attend). 

I think it makes sense to keep the CTA of “Why LLCs” of how it was previously as a separate call out piece since it will link off to more general information about joining LLCs, benefits, etc.

**Comment by bspeare** [comment]
@mkyoder thanks for looking!  I have reverted it to the previous version.  I think this is ready to move on to the next step.

**Comment by briand44** [comment]
Closing this. If any issues arise when @mkyoder replicates this for additional LLC's we can create follow up issues.
