### ISSUE TITLE
Update mglaman/drupal-check to 1.4.0

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5467]
This update changes the settings for the `drupal-check` tool to enforce more strict standards for deprecated code. When running `blt tests:deprecated`, there are around 50 new errors that get generated that will need to be fixed and tested.

# Proposed solution
- Run `ddev blt tests:deprecated`.
- Review each error and fix it.
- Test changes.

**Comment by briand44** [comment]
Joe going to check if there is an old PR from the last time just to see how we addressed it then.

**Comment by joewhitsitt** [comment]
Looks like https://github.com/uiowa/uiowa/pull/4508 is the only time we need to correct things before upgrading

**Comment by makurj** [comment]
I would like to pair on this.

**Comment by makurj** [comment]
https://github.com/mglaman/drupal-check/releases/tag/1.4.0

**Comment by makurj** [comment]
For later, line numbers may be slightly different.

Line   sitenow/sitenow.install                                     
 ------ ------------------------------------------------------------ 
  603, 755, 2022    Variable $tables in empty() always exists and is not        
         falsy.     
  1432   Access to an undefined property                             
         Drupal\Core\Field\FieldItemListInterface::$alt.

**Comment by joewhitsitt** [comment]
Fixing all of the errors in profiles/custom has now revealed ~291 issues within modules/custom. The command seems to stop traversing directories when it gets errors which mean there are theme issues and site issues as well.

https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L115

Though we should probably continue to chip away at this, we aren't sure to what level we can be done with this as it relates to upgrading drupal core or PHP. Do we just scale back what we scan? [Do we rollback the level at which drupal-check is scanning](https://github.com/mglaman/drupal-check#rollback-update-to-phpstan-level-2-for-deprecation-analysis)? Here are the rule levels and what we are encountering https://phpstan.org/user-guide/rule-levels

We are wondering if @pyrello has an understanding of what we need to make sure we do before attempting to update to core 9.4 and php 8.1.7

**Comment by pyrello** [comment]
> We are wondering if @pyrello has an understanding of what we need to make sure we do before attempting to update to core 9.4 and php 8.1.7

I'm not sure this is specifically a requirement for either Drupal 9.4 or PHP 8.1. I'm cool with looking at how to rollback the PHPStan level, although I'd like to understand the ramifications of that a bit better.

**Comment by joewhitsitt** [comment]
There is one more theme issue but it relates to person extended (not sure why this is here) which i plan to address this morning. i think that any any other modules/custom issues we can tidy up by the end of today should be the cap to this particular PR, move towards testing and we temporarily remove modules/custom and sites from the scan and follow up again in separate issues. My fear is that the PR will get too big with testing instructions otherwise.

One of those issues should be just to scan for specific errors about deprecated code and fix those before 9.4, 8.1., the other to deal with the new level of standards related to "basic dead code checking"

**Comment by joewhitsitt** [comment]
Might also want to exclude `default.settings.php` from the sites check because every site is being flagged for `Variable $app_root might not be defined.` and `Variable $site_path might not be defined.`

There are ~124 errors that aren't related to default.settings.php within the sites directory (this includes .install files)

**Comment by joewhitsitt** [comment]
From planning: Move forward with removing the dependency update from #5324 and test/merge the changes we have made. Keep this issue open to eventually update.

**Comment by joewhitsitt** [comment]
This would be good to do first https://github.com/uiowa/uiowa/issues/5924

**Comment by joewhitsitt** [comment]
Currently set up to be removed in https://github.com/uiowa/uiowa/pull/8133
