### ISSUE TITLE
Classrooms probe

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5520]
Potential first slice: build a proof of concept that involves creating the node type, adding a field to store the unique ID from MAUI, and pulling that data back to render it. Also figuring out what the MAUI ID will be.

**Comment by briand44** [comment]
Would we be handling all of the classrooms information with one node type? https://github.com/uiowa/uiowa/issues/4966#issuecomment-1116334687

**Comment by joewhitsitt** [comment]
Part of this proof of concept will involve a site split and a content type if anyone has the capacity to set that up.

**Comment by joewhitsitt** [comment]
Hoping to start looking at this after 1 PM. Will start a huddle.

**Comment by joewhitsitt** [comment]
@briand44 Do you know if there is there going to be MAUI data that needs to be modified or overridden on the content type? The parent issue talks about "additional" data that is not kept in MAUI that needs to be added/edited.

**Comment by briand44** [comment]
I am not sure going forward. Currently, I believe UCR/SPS (Registrar classrooms) do allow modifying MAUI data but it is reset during an import if the source entity changes. I believe this works because they manually trigger that import and it is not running on a schedule. I don't believe the classrooms on the classrooms website overrides MAUI data currently, just allows adding additional information.

**Comment by makurj** [comment]
Should we have users pick building and room from a pre-populated list that we build off of the MAUI data? https://github.com/uiowa/uiowa/issues/4966#issuecomment-1121237415

**Comment by joewhitsitt** [comment]
Capturing some thoughts from the probe:

- I think I recall that we wanted to avoid importing and that instead we were going to migrate initial content and then have manual content management from then on to edit the additional information (non-maui) and create and display new rooms.
- Like Rick had previously mentioned, there is not a "MAUI ID" to work with. Instead we need a building id and a room id to be able to pull data. With this in mind, we created those two fields which would be required to pull data in. This allows rooms disconnected from MAUI if needed.
- Because the current sites import both building id and room id, this should make migration easy.
- By being an initial migration process followed by manual management, there site owners are in control of what rooms are added instead of having to programmatically filter and manually mark nodes as unpublished.
- Right now I have it dumping in an extra field, but I imagine that the pull will happen on presave so that the data is available for filtering.
- I also think a per field boolean might be needed to determine if MAUI data for the field should be imported or if manually entered overrides should be displayed instead.
- In a presave, this will also allow site owners the ability to refresh the content if the MAUI content is stale.
- The MAUI `AstraRoomData` endpoint which Classrooms uses provides more information than the `AstraBldgRmCompleteList` endpoint which Registrar uses. Bringing Registrars data in using the `AstraRoomData` should be fine.
- We need to know what rooms are needed for the separated registrar data and how to filter them.
- We also need a MAUI value to taxonomy term name mapping for anything that needs to be filtered on later.
- As brought up in https://github.com/uiowa/uiowa/issues/5520#issuecomment-1254090340, making the building ID and room ID fields populate using allowed values functionality would reduce validation, but we will probably need a separate data.its feed of building ids with nested room ids. With these changes, I would think the ClassroomsController on data.its can either be repurposed or removed.
