### ISSUE TITLE
Reduce the likelihood of deployment-related outages

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5559]
# Story

As a web team, we have invested in something to help reduce the likelihood of deployment-related outages from occurring in the future.

# Additional Comments

Let's identify something(s) we can do to reduce the potential for deployment-related outages from occurring in the future.

Ideas sourced from ORID.  Add more as you think of 'em.

# Proposed Solution

- [x] #5683
- [x] #5580 
- [ ] Evolve working agreement for code reviews to include checking for best practice of making sure fields exist when referencing them in code (defensive coding).
- [ ] Evolve working agreement for code reviews to check for high risk scenarios

# Future Investigations

- SiteFactory
- Pantheon
- Increased Stage environment testing

**Comment by mjoneill** [comment]
Some ideas from ORID:
* Pay attention/active and intentful listening during standups (a number of people reported that they didn't hear the risk assessment prior to deployment
* set up automatic deployment checks that run every night
* Learn about possible testing suites that could focus on the deployment/multisite setup.
* Replicate/monitor stage deployments so we catch issues before prod deployment
* Only do scheduled releases from here on out 
* Move to after-hours releases with all-hands strategy for dealing with deployment issues
* More code reviews (required 2 people?)

**Comment by joewhitsitt** [comment]
Moving this comment from https://github.com/uiowa/uiowa/issues/5558#issuecomment-1215703313

In addition to the points made here and on the miro board (thanks for the link Brian), I want to add:

- There have been situations where we haven't had the if/else fallbacks because we assume something exists. In this case, for a small period of time, it didn't exist. Do we maintain that if/else fallback forever as a just in case?
- Another local test we can do is to sync the site locally (main), checkout the branch and try to hit the site/functionality before the update hook or config import runs.
- Off-hours deployments still can affect sites like [italymba](https://italymba.tippie.uiowa.edu/)

**Comment by briand44** [comment]
Evolve working agreement for code reviews to include checking for best practice of making sure fields exist when referencing them in code (defensive coding).

**Comment by cory-skeers** [comment]
> Evolve working agreement for code reviews to include checking for best practice of making sure fields exist when referencing them in code (defensive coding).

General defensive coding; eg might be necessary to check the type as well as its existence (this relates to the errors found when using [render classes in custom blocks](https://github.com/uiowa/uiowa/issues/5577)). Probably other defensive coding details we could capture as part of updating this.

**Comment by briand44** [comment]
Evolve working agreement to require multiple code reviews/approvals for high risk scenarios (update hooks, template name changes, etc). We need to identify these high risk scenarios

**Comment by joewhitsitt** [comment]
I think this event is generally a "reset" in that folks are going to be more cautious with writing code, identifying potential issues, labeling them and being more cautious with giving approval.

I also have concerns about the cost of additional decision trees, checks, restrictions and/or removing the flexibility of our current workflow.

I'd like to see more scheduled deployments because they do take a long time and by the time we talk about one in PL, put it together, it is deploying at a high-traffic period. If we can change the customer expectation about web request turnaround and when something that is "done" is actually deployed then I don't see a need for mid-day deployments beyond hot fixes or changes that can only be tested in PROD (e.g. search, seo, siteimprove, gtag).

**Comment by briand44** [comment]
Also, wanted to capture that there were some other "high cost" items mentioned including hosting changes/services, stage environment changes, etc.

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/5580

**Comment by bspeare** [comment]
Is it worth putting together a quick decision tree of deployment scenarios where we would want to:

- clear cache during deployment
- run config imports during deployment
- re-run a release 
- anything else?

I put together https://wiki.uiowa.edu/display/drupaldev/Useful+blt+commands+for+or+during+a+deployment which starts this somewhat, but it would be great to have something to reference the next time this happens.

**Comment by briand44** [comment]
Team determined the proposed solution can be completed all as one slice.

**Comment by pyrello** [comment]
We had a bit of a conversation about what it might mean to start using stage as an additional deployment step. I explained that my concern had to do with databases and files being out of sync. However, after a little bit of investigation, I don't believe this would actually be an issue. This is a problem with the dev environment because it does not get updated code every time that a PR is merged into main. Hence, not all updates run, which can cause issues with out of sync config. On stage, on the other hand, code gets deployed automatically every time a PR is merged into main. That being the case, if we are always using an update hook to appropriately modify configuration, then it makes sense that even if the content is out-of-date on a stage site that config should still be in sync.

All this is to say that I think that we can use stage to test code updates. However, I think we should be doing this after PRs are merged into main, rather than at the point where releases are being created.

Also, to be able to effectively do a side-by-side comparison, we may want to consider a process to periodically sync DBs and files from prod. We would need an opt-out mechanism for sites that are currently being worked on in stage (like manual V2 => V3 conversions).

I see that we last had a stage (test) deployment failure on August 4 on uiowa02. I think we should make it a regular part of our process to investigate stage deployments to see why they are occurring. They may provide us with an early clue that we have a problem.

**Comment by briand44** [comment]
Should we consider this done based on https://wiki.uiowa.edu/display/drupaldev/Development+Workflow#DevelopmentWorkflow-Someconditionsunderwhichyoushouldrequestchangeswhendoingacodereview: and https://wiki.uiowa.edu/display/drupaldev/Development+Workflow#DevelopmentWorkflow-Shouldthereleasebedeployedoff-hours?

**Comment by briand44** [comment]
Marking this complete
