### ISSUE TITLE
Iowa Now Spotlights

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5562]
# Story

As an Iowa Now website editor, I would like to be able to place a listing of articles that are spotlights on our SiteNow v3 site similarly to other article types.

# Additional Information
Currently "Spotlights" are "In the News" content that have a source url containing `uiowa.edu`.

When migrating from D7 we will want to migrate any "In the News" content that has a source url containing `uiowa.edu` to be granted the "Spotlight" type.

# Proposed Solution

- [x] Add article type for "Spotlight" that contains the same fields (hidden/shown/required) as "In the News" type.
- [x] Programmatically create tags for articles based on the Article Type (In the News, News Feature, Achievement, Spotlight) when saved.

**Comment by makurj** [comment]
I'd like to pair on this.

**Comment by cory-skeers** [comment]
@briand44 and others--for adding the tags in the presave, I'm wondering if that should be limited to when an article is created? It would give more flexibility in being able to manually override after creating a node (remove a tag, and/or tag with a different article type if the need arose). The downside is if someone created a news feature, then decided it should have been an achievement, the tagging would need to be manually handled.

If we don't limit it to newly created articles, we might also want to consider what happens if an article type changes post-creation: Should the old article type's tag be removed and replaced? Just add the new tag? (I would think probably the former.)

Lastly...for the Spotlight, should it get both the "in the news" tag as well as "spotlight," or just "spotlight?"

**Comment by briand44** [comment]
Good questions @cory-skeers. My initial reaction is to not limit it to when an article is created so that we can avoid the case you mentioned where if they change an article type they won't have to manually add the tag. In this case, I do think the tag should be removed and replaced.

Just the spotlight not both in the news and spotlight, IMO.

Open to feedback from the team on any of this.
