### ISSUE TITLE
Purge aggregator items no longer in feed source.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5615]
Currently we are retaining aggregator items for 1 year. Would it make more sense for our use cases to only retain items that exist in the feed source?

This would allow folks to have archived feeds like https://apps.its.uiowa.edu/dispatch/archives/past/--iowa-law---september-25-lxj144j without requiring us to keep items for 1 year.

It could also help prevent issues with high volume feeds like we have seen on careers.uiowa.edu.

It sounds like there is conversation around this in the issue queue but is not currently an option for the aggregator module.

**Comment by joewhitsitt** [comment]
Actually it is a really old issue that was moved over..

https://www.drupal.org/project/aggregator/issues/1294472

**Comment by cory-skeers** [comment]
From @makurj this could be useful to look into again. They are using https://hris.uiowa.edu/otac-rss/jobs.php?dept-code=29- to pull in staff jobs to https://grad.uiowa.edu/jobs (unpublished)

The option exists to manually delete and then update as needed, but an option to keep aggregator items in sync rather than just pulling in new (specifically, remove items that are no longer in the feed) could be a useful option.

Similarly, there is currently work being done on creating an RSS feed for Jobs@UIOWA, and similar to MJ's use case, it would work best if items fell off when they were no longer part of the feed.

https://www.drupal.org/project/aggregator/issues/1294472 is still "active", but hasn't had any activity in awhile.
