### ISSUE TITLE
Docs - Update Region Settings docs

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5620]
# Story

As a SiteNow editor, I can read basic documentation about region settings, prefooter and after content.

# Proposed solution

- [x] Update https://sitenow.uiowa.edu/documentation/layout-builder/pre-footer-content to re-frame around region settings and the different options there.

**Comment by cory-skeers** [comment]
Docs are updated: https://sitenow.uiowa.edu/node/431/latest

Additional edits and feedback are welcome!

Otherwise, blocked by #5576. Once that gets merged, we can publish the doc updates.

**Comment by bspeare** [comment]
This looks good! I love the "Congratulations" bit at the end.   The one thing I would add is that we might want to give better advice about the types of links to use in a button row from a content strategy perspective, but that could be a separate page or even a page on the web community site.

**Comment by GaryRidgway** [comment]
I agree, looks good!

I made a few small changes to wording and bolding.

https://sitenow.uiowa.edu/node/431/revisions/view/4531/4551/split_fields

I removed the first change because the position is ambiguous with those words and is clearly defined in the next sections.

The second change is for consistency.

**Comment by bspeare** [comment]
Now that the new region is deployed, I have published the new docs: https://sitenow.uiowa.edu/documentation/layout-builder/regional-content. Thanks @cory-skeers!
