### ISSUE TITLE
Searchable list of FM managed buildings

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5659]
# Story

As a Facilities site owner, I would like to display a searchable list of FM managed buildings so that visitors can quickly find a FM managed building.

# Additional Information

Should be able to be placed on a layout builder page so that editors can add additional contextual content.
Should output building number, building name and building abbreviation.
Should be able to sort by and search each of the fields being output.
Building name should render as a link to a page that will eventually contain additional building information for that specific building.

Endpoint - https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
Existing code - /docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/includes/facilities_buildings.buildings.inc
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/facilities_buildings.module
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_core/facilities_core.module (API call)

Existing site - https://www.facilities.uiowa.edu/buildings

# Proposed Solution

- [x] Building content type (webmasters and below do not need access to add/edit/delete)
  - [x] Building Name
  - [x] Building Abbreviation
  - [x] Building Number
- [x] Create views block utility table to filter, sort on.
- [x] Periodically add/update/delete from https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings (e.g. Feeds, a Facilities type MAUI API integration running on cron)

**Comment by joewhitsitt** [comment]
Not tested but I saw this module when thinking about our approach here. It would appear to provide us with a views table that could be filtered on (using design patterns we already have). https://www.drupal.org/project/views_json_source

**Comment by briand44** [comment]
Grooming conversation... Build out a structure for this to store the information needed for the view display and create the searchable/sortable display.

**Comment by pyrello** [comment]
Just documenting the rationale for considering a content entity vs some other mechanism of locally caching the data. We're going to be getting the data to display a building page from an API. Its inefficient to have to call the API every time we display the page, so we'll be using some sort of local caching to store the API data for a little while. The data from the API will likely need some processing to get it into the format that we want to display it in, so we'll need some logic that identifies fields and transforms them before they are stored in cache. Finally, we'll need one or more templates that tell the building page how to look and we'll need those templates to use variables that come from the cached API data. So we are going to essentially be providing some sort of hard-coded mapping either in a theme preprocessing function or in the templates themselves which describes what field gets displayed where and how.

With a content entity, we will need some mechanism to map the incoming API data to fields (e.g. feeds or something like what we are doing in #6035). But after that point, we can rely on existing Drupal systems to handle everything else. We can build a layout builder template and add field templates. We can build a view to display the search page. The content entity is probably more overhead overall, but it is largely managed by Drupal's content management system, so there is less maintenance than for custom code. And it reduces our custom code footprint. This makes it easier for anyone on the team to reason about how things work because it is more consistent with how we do other things on our platform.

**Comment by briand44** [comment]
Can we document the negative affects of this to compare against? Database size, etc.

**Comment by joewhitsitt** [comment]
I approximate 384 nodes would be created by this. Limiting references to other content and keeping revisions off or to a minimum will keep the db impact fairly low. Compare this to the thousands of nodes created by Iowa Now or if ITS support articles and alerts are content entities than it is not even the same level of content.

**Comment by pyrello** [comment]
> Can we document the negative affects of this to compare against? Database size, etc.

One thing to note: There will be more database tables with a content entity solution because each field gets its own table.

> ...and keeping revisions off or to a minimum will keep the db impact...

It might be nice to have at least a few revisions just to be able to have some record of changes over time if we are ever asked to account for them. Maybe limit it to 3?

**Comment by joewhitsitt** [comment]
Interested in starting this. Open to pairing/mobbing

**Comment by joewhitsitt** [comment]
>Bypass content access control
_Warning: Give to trusted roles only; this permission has security implications. View, edit and delete all content regardless of permission restrictions._

This permission is coming back to bite with regards to this work. I think we talked about webmasters not needing the ability to even see this content type on the backend. This gives them visibility and editing permissions.

Introduced here: https://github.com/uiowa/uiowa/issues/1355

This is where I'd like to get to, similar to what an editor sees (content overview but no options, revision diffs, no edit):
<img width="503" alt="Screen Shot 2023-01-06 at 3 18 35 PM" src="https://user-images.githubusercontent.com/4663676/211101976-6cf1cfe9-2034-442b-b3c9-f845be24fee5.png">
<img width="997" alt="Screen Shot 2023-01-06 at 3 18 54 PM" src="https://user-images.githubusercontent.com/4663676/211101980-05c88eb7-b3f3-411a-aec4-7000a8455714.png">
