### ISSUE TITLE
Clickable people profile images

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#5666]
# Story
As a user, I would like to be able to click the profile image on a people listing to view their profile.

- Making the People images not clickable breaks with breaks with how the cards, events, and articles are used.
- The default people directory listing has the images clickable.

examples:
https://sandbox.prod.drupal.uiowa.edu/sandbox-people
https://sandbox.prod.drupal.uiowa.edu/people-examples

**Comment by bspeare** [comment]
I think this is happening because this is being set https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/uids/card.html.twig#L41 because it is seeing `card_link_url` as empty from https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L1331?

**Comment by bspeare** [comment]
I added this to the bug smash milestone.
