### ISSUE TITLE
Add ability to have people in lists link directly to first website

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5722]
# Motivation

On https://uicb.prod.drupal.uiowa.edu/associates, UICB would like to just have the record directly link to an external website to prevent the user from having to click through to the profile then click a link to a website.

This is kind of similar to the "Link directly to source" feature with articles.

# Proposed solution

- Adapt logic for article content type to "link directly to source" to work for person content type teaser display.
- Add boolean field to person content type to "link directly to first website".
- If there are multiple website links, use the first one.

**Comment by cory-skeers** [comment]
Visibility: We've had an additional request for functionality like this
https://developmental-psychopathology.lab.uiowa.edu/
(eg people page linking instead to https://psychology.uiowa.edu/people/isaac-petersen)

**Comment by e-marie-w** [comment]
Summary of where I'm at and some questions I have:

Since a few sites are interested and it's already an option for articles, I set the direct link stuff up for default. During mid-sprint demo, there was some discussion of setting up rabbit hole so the person nodes aren't visible on the site. Since then, I noticed that articles aren't doing it, so I wanted to double-check if we still wanted to add it for just people, or if we thought both or neither should have it now instead. 

Second thing is that the direct link stuff is only set up for the People view right now. I assume we want it to work for the People List Block view too so I've been working on that and ran into issues. Basically, sitenow articles mostly sets up the list block within the `preprocess_views_view_unformatted` function instead of the twig template. Sitenow people uses just the twig template. Unless the team is against it I want to refactor it to also use a preprocess function.
