### ISSUE TITLE
Investigate displaying in-progress events

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5748]
# Story

As a content editor I want events with an end date that has not passed to show up in lists of upcoming events (from content.uiowa.edu) so that they don't disappear from those lists while the event is still going on.

This feature is being requested for uicb.uiowa.edu.

# Proposed solution
Investigate:
- Query the number of in-progress events to get a sense of what the effect should be
- What adjustments to event instance API view would be necessary to get in-progress events to show? 

<details>
<summary>Original proposed solution</summary>
- Clone the existing endpoint on content.uiowa.edu: https://content.uiowa.edu/admin/structure/services
- Change "Path to endpoint" to `api/v2` and machine name to `content_v2` (`events_v2`?)
- Clone the Event Instances API view and name it "Event Instances API V2"
- Adjust filters in cloned view to allow for dates with an end date that hasn't passed yet to be included
- Any other adjustments to Uiowa Events that are needed based on the changes to the view filters
</details>

**Comment by joewhitsitt** [comment]
Might be related if we want to maintain existing endpoints https://github.com/uiowa/uiowa/issues/5521

**Comment by briand44** [comment]
Grooming conversation - Possibly create a new version of the endpoint. We should test against repeating events and long spanning all day events. Should revisit at mid sprint checkin.

**Comment by briand44** [comment]
From what I can tell, if an event spans multiple days and started prior to today but ends at a future date, the event is not displayed as an upcoming event or past event. So we currently have no way of showing an event that is "in progress" without using the date range feature.

**Comment by joewhitsitt** [comment]
I think we are going to run into issues trying to re-shape the current view and for it to work with our block. Might I propose just including a new checkbox (include in-progress) and doing a separate query for those that gets merged or set to the top of the other events. We will have to account for number of items/pager though with this approach or create a dividing line that separates in-progress from the upcoming (where paging is handled).

Another option would be to have a "In-progress" option so folks would create a separate block and we could add a "hide block if empty" checkbox.

**Comment by briand44** [comment]
Probe to see if we can make changes to the existing views to account for in progress events. Come up with a proposed solution.

**Comment by pyrello** [comment]
> Probe to see if we can make changes to the existing views to account for in progress events. Come up with a proposed solution.

Updated the proposed solution to reflect the nature of the probe.

**Comment by cory-skeers** [comment]
Was starting to look into this.

**Comment by cory-skeers** [comment]
Couple notes on the amounts of extended events

Vast majority of events span 0 (end date is same as start date) or 1 day (end date is day after start date)-- little over 95% of the 30000ish events currently on the site.

Of the extended duration events, it looks like a lot of them tend to be ones that end around semester ends, with some difference in when they start (eg start around September, end mid-December)

Were this change to go into place today, there are 27 events that began prior today and end some time today or later, most of which (17 of the 27) are ones that are these extended duration ones (many for 259 day durations, each off-set by a week, so I am guessing they all belong to a single group, but I'm not sure).

From this, it looks like the change would be pretty low-impact for most people, and maybe changing things for a small handful of groups that make a number of semester/year long events. Having, say, 17 ongoing events appear in your feed after a change might be a lot, but that shouldn't be a common occurrence unless it's one or two very commonly pulled depts that are doing that.

Still looking into what the actual changes are that'd need to be made for this, but wanted to toss up the initial numbers for people to chew on, or if anyone has specifics or other details to look into.

<details>

<summary>Current in-progress events</summary>

start | end | date_diff
-- | -- | --
10/17/22 19:00 | 10/18/22 21:00 | 1
10/17/22 13:00 | 10/18/22 1:00 | 1
10/11/22 13:00 | 10/19/22 4:59 | 8
10/10/22 5:00 | 10/21/22 5:00 | 11
10/7/22 20:30 | 11/11/22 23:00 | 35
8/25/22 20:35 | 10/28/22 1:00 | 64
8/18/22 13:00 | 10/26/22 4:59 | 69
9/18/22 5:00 | 11/30/22 6:00 | 73
9/21/22 22:00 | 12/15/22 0:00 | 85
10/5/22 22:00 | 12/29/22 0:00 | 85
8/25/22 22:30 | 5/11/23 23:30 | 259
9/1/22 22:30 | 5/18/23 23:30 | 259
9/8/22 22:30 | 5/25/23 23:30 | 259
9/15/22 22:30 | 6/1/23 23:30 | 259
9/22/22 22:30 | 6/8/23 23:30 | 259
9/29/22 22:30 | 6/15/23 23:30 | 259
10/6/22 22:30 | 6/22/23 23:30 | 259
10/13/22 22:30 | 6/29/23 23:30 | 259
8/24/22 21:00 | 5/10/23 22:00 | 259
8/31/22 21:00 | 5/17/23 22:00 | 259
9/7/22 21:00 | 5/24/23 22:00 | 259
9/14/22 21:00 | 5/31/23 22:00 | 259
9/21/22 21:00 | 6/7/23 22:00 | 259
9/28/22 21:00 | 6/14/23 22:00 | 259
10/5/22 21:00 | 6/21/23 22:00 | 259
10/12/22 21:00 | 6/28/23 22:00 | 259
9/8/22 18:00 | 9/8/23 21:00 | 365
</details>

<details>
<summary>All events, based on number of days they span</summary>

count(*) | date_diff
-- | --
24901 | 0
3904 | 1
98 | 2
50 | 3
143 | 4
38 | 5
44 | 6
65 | 7
102 | 8
7 | 9
43 | 10
33 | 11
18 | 12
3 | 13
26 | 14
6 | 15
7 | 16
5 | 17
2 | 18
1 | 19
4 | 20
11 | 21
3 | 22
2 | 23
4 | 25
3 | 26
1 | 27
5 | 28
12 | 29
9 | 30
2 | 31
1 | 32
4 | 35
9 | 37
13 | 38
1 | 39
1 | 42
1 | 43
8 | 44
1 | 50
2 | 51
1 | 56
1 | 58
3 | 62
1 | 64
1 | 68
1 | 69
1 | 70
2 | 72
2 | 73
1 | 77
55 | 79
8 | 85
104 | 87
1 | 88
7 | 89
2 | 91
1 | 93
1 | 95
1 | 99
1 | 104
16 | 105
2 | 106
1 | 115
1 | 116
1 | 122
1 | 123
1 | 137
1 | 157
1 | 161
109 | 190
54 | 191
51 | 259
12 | 260
5 | 327
1 | 336
11 | 365
6 | 366
1 | 367
1 | 6209
</details>

**Comment by cory-skeers** [comment]
The more I look at this, the more I think I was overthinking it, and the main issue is that unless you're looking specifically for a date range of events, the views should only ever really need an end date.

Right now, they're set up to take both Start and End date constraints, defaulting to Today if either (or both) are not provided. Defaulting both to today gives all events that start and end today, which isn't exactly representative of all events going on today, as it cuts off events that started prior but end today, events that start today but end tomorrow or later, and events that started prior to today and end tomorrow or later.

The way we call things in SiteNow are to set today's date for the Start constraint and a far future date for the End constraint. This is where we end up with all future upcoming events being included, EXCEPT for events that started prior to today.

Essentially, if in-progress events are to be included, if you want all upcoming Events, you want all events whose End time has not passed. And if you want all past Events, you want all events whose End time has passed. For just this upcoming or past, there's no reason to provide an actual Start date unless you're looking for a Date Range or are looking to exclude in-progress events.

SO:
# Proposal

- Change the views to remove the Start date defaulting to today, and rather default to not using that filter if no time is provided.
- Change the End date to filter on anything with an End date AFTER the provided constraint, such as the current date. (For past events, this would be reversed.)
- If users would like to filter OUT any in-progress events, they can then include a Start Date of today (or this week, month, etc., depending on what is defined as a "current" event and not stale)
  - For the most part, looking at the long-term events, I don't think many people would need this, but at least this could provide the option to choose

With flipping the way End date constrains the results, changing the current api would break it for anyone currently specifying an end date (for instance, us--without updating the code from defaulting to a way future date to today for end date, we'd immediately start getting 0 results for all "upcoming" events blocks). It also makes handling date ranges tricky, unless we add a second End date constraint option (I wonder if this is why the original api is set up the way it is). The Date Range would then consist of an optional start date and then a "starting" end date and "ending" end date in order to form the bounds of the date range of interest.

Creating a new api, at least for now, would give time for people (including us) to update how their queries are formed while updating to point to the new api. After that, it might be useful to leave the current in place specifically for date ranges.

**Comment by joewhitsitt** [comment]
Thanks for writing this out. Have you tried any of these proposed steps locally by changing the v2/v3 endpoint to devdesktop?

**Comment by cory-skeers** [comment]
> Thanks for writing this out. Have you tried any of these proposed steps locally by changing the v2/v3 endpoint to devdesktop?

Sort of...the request fails because it doesn't like the local endpoint. For testing I've just put a breakpoint in the code (after making the few adjustments to how it works) in order to get the full URL w/query, and pull that up in a browser.

**Comment by cory-skeers** [comment]
Short summary from in-group demo:
Add a new display_id that is a copy of Events from the Events API. Remove the Start Date constraint. Change End Date constraint to events with an end date after the provided date.
Update sitenow_events.module parameter handling in the case that it is upcoming (ie not `date_range` or `past`): Remove the start date and set the end date to Today instead of `31-12-2037`

**Comment by cory-skeers** [comment]
Followup issue created #5878

**Comment by joewhitsitt** [comment]
FWIW, I think the unit you were curious about was largely https://events.uiowa.edu/?f=259 (Intramural sports)
