### ISSUE TITLE
Finish building out Classrooms content type

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5769]
# Story
As someone who manages classroom information, I would like to store manually entered and MAUI classroom information  in my website so that it can be displayed to the appropriate audiences.

# Proposed solution
## Additional info
- ~Ability to override individual fields is not needed~
- ~Need a human friendly name instead of "ABW 240" (Art Building West 240 https://classrooms.prod.drupal.uiowa.edu/art-building-west-240)~
## Basic Fields
Moved to https://github.com/uiowa/uiowa/issues/6033

## Fields placed in theming slice
Moved these to #6044 

## Fields populated from API
Moved to #6032

## Outstanding Questions - Future slice

These have been split out into https://github.com/uiowa/uiowa/issues/6041

**Not Needed from MAUI or Registrar website**
- Room Category - https://registrar.uiowa.edu/admin/structure/taxonomy/gac_type - Category has a title and description
- Room type group - text field
- *Seating type - https://registrar.uiowa.edu/admin/structure/taxonomy/gac_seating_type - title and description - may need to code around MAUI title vs display title - https://github.com/uiowa/uiowa/issues/4966#issuecomment-1116334687
- Classroom Scheduling manages initial classroom assignment - boolean - need to understand how this is assigned
- Event Management Process - text field
- *Room entry type - https://registrar.uiowa.edu/admin/structure/taxonomy/gac_entry_types - title only
- *Management - https://registrar.uiowa.edu/admin/structure/taxonomy/gac_management - title only
- Comment - text
- Office Comment - text - only displayed to authenticated users

**Comment by joewhitsitt** [comment]
Today's meeting made me feel like we named the content type incorrectly. Should just be “room” to handle both classroom and speciality space (e.g. gym). Now is the chance to do it with little harm since the split has not yet been turned on in PROD.

**Comment by briand44** [comment]
Grooming conversation - fields!!

**Comment by joewhitsitt** [comment]
~~The work started in #5718 does not finish the content type with regards to https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes or our new schema.org blueprints patterns. Those should be addressed in this issue.~~

**Comment by pyrello** [comment]
To get this started, I enabled the site split created in #5718 for the Classrooms site in production.

**Comment by pyrello** [comment]
> - Room number - can contain letters and numbers
>   - will be used with building code for MAUI identifier

@briand44 Is this different than the room ID field that was created in #5718?

**Comment by pyrello** [comment]
> ~Ability to override individual fields is not needed~

So, we do need to be able to override fields? If a field is overridden, then does that mean we need a mechanism for protecting it from being overwritten when a subsequent update from the API call happens?

**Comment by briand44** [comment]
@pyrello Room Number is the same as Room ID. The APIs call it roomNumber.

They do not need the ability to override fields. This is something they currently have but is no longer needed.

**Comment by pyrello** [comment]
Okay. I was confused because it said "Ability to override individual fields is not needed" but then it was crossed out.

**Comment by briand44** [comment]
Yeah, I crossed it out because Joe already had some of that in the original probe but he removed it when we found out it was no longer needed. I was crossing things out that were already done.

**Comment by pyrello** [comment]
> Seating Chart - file upload

What are the file extensions that are allowed for this?

> - Tile Details - multiple items - name and detail?
> - Design Details - multiple items - name and detail
> - Classroom Furniture - multiple items - quantity? and detail

What is the status of the question marks on `detail` and `quantity`? Also, these all seem like field collections, so we'll need paragraphs for each one?

> Room schedule - from Astra - may not need any structure for this but will need displayed? If no structure needed this may make sense to be in a future slice.

If there is no structure, how will it display the schedule? I'm assuming this is an embed. Are we able to pull it based on the value of another field we're already storing? If so, then we can probably use extra fields to display this.

> Video - they would like a media field so they can embed a single video of the room

It seems like we did something like this for the dorms on https://housing.uiowa.edu. @bspeare Do you think there is anything from that that we can reuse?

> - **Features
>   - They would like to break this into two groups - Room Features and Technology features

It seems like we should potentially split this into two fields? Otherwise, we'll need to store each as a field collection to determine which list it should be shown in.

> **Responsible Unit - List of Department/Units

Do these records get displayed anywhere on their own? If not, it seems appropriate to use fragments or paragraphs depending on whether they need to be reusable or not.

**Comment by briand44** [comment]
>Seating Chart - file upload
>
>What are the file extensions that are allowed for this?

PDF

**Comment by briand44** [comment]
rescoped to include creating 3 fields

**Comment by bspeare** [comment]
For housing we had a "Remote video" field for Allowed providers: University of Iowa, Vimeo, YouTube.  @briand44 will that be enough?

**Comment by briand44** [comment]
yes, those are the only videos we support outside the banner right?

**Comment by bspeare** [comment]
> Do you think there is anything from that that we can reuse?

@briand44 are you suggesting that we pull out https://github.com/uiowa/uiowa/blob/main/config/sites/housing.uiowa.edu/field.field.node.residence_hall.field_residence_hall_video.yml from housing into a reusable video field that can be shared by all of our content types?

**Comment by briand44** [comment]
I wasn't suggesting anything. I think that comment was from Sean. I just assumed we would create a video field for the classrooms "room" content type.

**Comment by pyrello** [comment]
> > Do you think there is anything from that that we can reuse?
> 
> @briand44 are you suggesting that we pull out https://github.com/uiowa/uiowa/blob/main/config/sites/housing.uiowa.edu/field.field.node.residence_hall.field_residence_hall_video.yml from housing into a reusable video field that can be shared by all of our content types?

This might be worth considering. I wasn't specifically suggesting this, I was just wanting to see what, if anything, we could reuse.

**Comment by bspeare** [comment]
It sounds like these "links" can be set by us since they will not change very often.  How do we want to set these up?  With a custom block?

- Check availability - http://classroomscheduling.registrar.uiowa.edu/AdAstra7Prod/Portal/GuestPortal.aspx
- Request this room - https://workflow.uiowa.edu/entry/new/667/
- Report an issue - https://classrooms.prod.drupal.uiowa.edu/classroom-assistance

<img width="759" alt="Screen Shot 2022-12-12 at 10 57 18 AM" src="https://user-images.githubusercontent.com/1036433/207106388-df13b2c2-a164-47c1-9882-8cf7b91bc835.png">

**Comment by bspeare** [comment]
Mid-sprint discussion recap:
- It sounds like we can postpone the links work on https://github.com/uiowa/uiowa/issues/5769#issuecomment-1346884646 until the theming happens. 
- We talked about using the campus maps media field that we used on housing.uiowa.edu and outputting the url of that map in the "Additional details" section to save them from filling out multiple fields.  I checked in with Caroline and they confirmed that they will only be using maps.uiowa.edu for building links. 
- The facilities link in "Additional details" uses the building number in the url https://www.facilities.uiowa.edu/building/0037.  Unfortunately, that is not available in https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list so we still need to figure out how/if we want to pull that building number into the site.

**Comment by joewhitsitt** [comment]
It was talked about in standup that the part of this issue is done as part of https://github.com/uiowa/uiowa/pull/6003 and that it be pulled back to top of backlog to plan the next slice.

**Comment by bspeare** [comment]
@joewhitsitt for the classroom type, max occupancy, and features fields from the MAUI API, do we grab and set those values inside the presave function?  Are we relying on `getRoomData` for all of the info?
- https://github.com/uiowa/uiowa/blob/main/docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/classrooms_core.module#L28
- `getRoomData` function https://github.com/uiowa/uiowa/blob/4938b1db51a952d112c18070f5cef1003c8b2fd2/docroot/modules/custom/uiowa_maui/src/MauiApi.php#L297

**Comment by joewhitsitt** [comment]
I think the majority of info is in that MAUI call. There might have been one or gotchas where we need to query a facilities feed. We had talked about capturing the one bucket of features into separate taxonomy vocabularies (reference existing, not to create new) so that classrooms folks could control those lists (what features are in which bucket, and whether or not to highlight them by leaving them out of the vocabulary).

Not sure if we ruled out Feeds, but the MAUI call and presave seemed to work well in the proof of concept. If kept in presave, I believe the classroom editors will want the ability to bulk re-save to fetch updated content. Feeds would be a routine call.

**Comment by e-marie-w** [comment]
Right now, the value of the responsible unit field links out to the related unit taxonomy term. In the theming slice we'll want to update that term display. If we switched to pulling the taxonomy term into the room node the teaser display for it would still need theming.

**Comment by briand44** [comment]
Closing this as related issues have been completed.
