### ISSUE TITLE
Searchable named buildings list

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5803]
# Story

As a Facilities site owner, I would like to display a searchable list of FM managed named buildings so that visitors can quickly find named buildings.

# Additional Information

- [x] Should be able to be placed on a layout builder page so that editors can add additional contextual content.
- [x] Should output honoree and building name (title).
- [x] Should be able to sort by and search each of the fields being output.
- [x] Building name should render as a link to named building entity.
- [x] Change content type from 'Place' to 'Named Building' (change machine name fromplace to named_building).
 ~~- [ ] Add preprocessing logic and field templates to finish getting the node LB template looking like the pages that were built out.~~
- [x] change honoree name field to two fields, first, last name. 
- [x] make table display for searchable named buildings list  "last, first"
- [x] store building ID on "Named Building" content type
- [x] Correct label of "Aeriel" view. It is misspelled. 

Endpoint - https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
Existing code - /docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/includes/facilities_buildings.building_named_building.inc
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/facilities_buildings.module
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_core/facilities_core.module (API call)

Existing site - https://www.facilities.uiowa.edu/named-buildings

Example of individual named building on new site - https://facilities.prod.drupal.uiowa.edu/philip-d-adler-journalism-and-mass-communications-building

# Questions
How do we want to handle linking to these manually created pages? I think on the current site these are all created with a similar url structure (named-building/[BuildingCommonName] but that could create issues if the content isn't managed appropriately. We will want to let Facilities know how we intend to move forward here so they can update url aliases if needed.

What technology/JS libraries to use for search/sort functionality.

# Proposed Solution

**Comment by joewhitsitt** [comment]
I worry how fragile this linking is, but I am not coming up with alternatives.

It seems overkill to add a buildingID field to the basic page content type to control this. Additionally, moving to a buildingID URL alias seems like the opposite direction for a named building page.

At this point though, I am trying to decide the value of pulling this data since content is manually created and managed anyway? Shouldn't Stanley Art Museum be on this list? Could this list be some how be managed in Drupal, tied to nids?

**Comment by joewhitsitt** [comment]
Possible routes:

- Create a manual table through content. No query needed.
- Programmatically create a table based on query results that assumes a path
- Split the page content type to have a building/honoree designation to construct a table drupal view. No query needed.
- Custom content type to structure all of the data and have consistent look and feel, also resulting in a drupal view. No query needed.

Thoughts from grooming: There is a strong argument that even though they already built these as pages, that this should be switched to a structured content type. This would be the ideal for long term maintenance.

Could migrate content programmatically if most content has the same layout.

Otherwise a split page content type that designates the page as a building page with an identifier.

They would have to touch these anyway to update the URL alias.

**Comment by joewhitsitt** [comment]
Establishing a filter as you type search box for the frontend seems like a separate slice as the current list only includes ~60 items and has honoree sorting.

**Comment by pyrello** [comment]
I went rogue and put this together: https://github.com/uiowa/uiowa/pull/5934. Some things need to be renamed to be more specific to the use case and it still needs some tweaks to get the design looking right, but the investment so far for it is under 2 hours.

**Comment by pyrello** [comment]
To do for #5934:
- Change content type from 'Place' to 'Named Building' (change machine name from`place` to `named_building`).
- Add preprocessing logic and field templates to finish getting the node LB template looking like the pages that were built out.

**Comment by briand44** [comment]
Design of structured named buildings will be in a future slice.

**Comment by briand44** [comment]
I got some clarification on the outstanding questions. They are ok with us going the structured route as long as they don't have to move content. They prefer last, first when outputting the honoree in the searchable list. They were also ok with just outputting the title (formal name) rather than collecting the building common name and using that in the searchable list. They are ok with us putting together the layout and getting feedback though they prefer the Facility description and Honoree info (photo, name, etc. near the top).

One other wrinkle here is that they mentioned the majority of traffic to these pages actually comes from the building page rather than this display. So the building page will need to link to the named building page. Example https://www.facilities.uiowa.edu/building/0456. How do we wire up that link from the building page to the named building page? Are we going to have to store additional information like building id on a named building? This is another example where we are currently assuming the link based off the building formal name.

**Comment by GaryRidgway** [comment]
Do we need to add the building page, or can we just consolidate everything in to the named building?

**Comment by briand44** [comment]
The building pages will be dynamically displayed in a future slice.

**Comment by joewhitsitt** [comment]
Going to poke at this
