### ISSUE TITLE
ISWF - Probe using events, event series and people to see what can be reused vs what needs to be custom

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5810]
# Motivation
As part of #5732, we need to understand what existing pieces we can use that pertain to building out the functionality for the Iowa Summer Writing Festival.

# Proposed solution
- [x] Investigate the Event feature, what could be used and what would need to be modified.
- [x] Investigate the Event Series content type that exists in the Admissions split to see how similar/different it is from from the requirements of ISWF.
- [x] Investigate the Person content type to see what modifications would need to be made to it to use it as the basis for instructors on ISFW.
- [x] Make a recommendation to the team about how to proceed.
- [x] If you make code updates that are potentially useful to your proposed path forward, put them into a PR for future use.

**Comment by briand44** [comment]
Wanting to draw attention to the difference between the online festival and in person festival mentioned in the update in https://github.com/uiowa/uiowa/issues/5732#issuecomment-1263915168

**Comment by pyrello** [comment]
> Wanting to draw attention to the difference between the online festival and in person festival mentioned in the update in [#5732 (comment)](https://github.com/uiowa/uiowa/issues/5732#issuecomment-1263915168)

I made a comment with an idea for how to address the apparent discrepancy: https://github.com/uiowa/uiowa/issues/5732#issuecomment-1273913210

**Comment by briand44** [comment]
Lets keep in mind other potential conference type websites in the future.

**Comment by joewhitsitt** [comment]
Without digging yet, this seems more and more like schema.org's EventSeries > Event setup with "superEvent" and "subEvent" relationships.

Olympic Games (EventSeries) > The Rio 2016 Summer Olympics (Event with superEvent=Olympic Games, subEvent=Rowing). Then Rowing (Event with superEvent=The Rio 2016 Summer Olympics and subEvent=Rowing Semi-Final) and onward. So I think if there can be some flexibility in what we call the buckets, we should be able to capture the content for ISWF as well as several other use-cases.

https://schema.org/EventSeries

**Comment by mark-bennett-uiowa** [comment]
If we have the potential to use this same structure for other conferences, festivals, or super-events on campus, do we want to consider a structure to work with something like a DrupalCon? Where you have the top level conference/festival/super-event, etc. Within that you have a Monday session, a Tuesday session, a Wednesday session, etc each with their own start/end date/time. Within that you have workshops with their OWN start time / end time, but their start date / end date is dependent on the session that contains them, or include a start date / end date for sessions as well?

- What should we call the conference/festival/super-event level?
- Does session still work as the name for this level?
- What should we call the workshop level? Does this need to be more inclusive of other "events"?
- How does the EventSeries work with this model?

**Comment by pyrello** [comment]
> What should we call the conference/festival/super-event level?

Conference seems like the most common name used for something like this.

> Does session still work as the name for this level?

Session seems like the right name, but this is essentially what we are currently calling an Event.

> What should we call the workshop level? Does this need to be more inclusive of other "events"?

This is essentially the event series, I believe. I'm not sure what the best name for this is TBH.

---

One thing to note: If we need to change the labels of these content types for ISWF to fit with what they are expecting, that is pretty minor config split customization.

**Comment by mark-bennett-uiowa** [comment]
I did some digging into major conferences that I could find. It appears most of them have similar structures, but limit their sessions to one day within the conference.

For ISWF we need to account for the "Day" level spanning 2, 5, or 10 days, and what we would call that, outside of a generic "Event Series". [https://evenues.com/event-planning-guide/types-of-meetings-and-events](https://evenues.com/event-planning-guide/types-of-meetings-and-events) defines some of these terms, but not what a grouping of "Days" would be. Should we just stick with "Days" and allow that to cover multiple days?

What about creating additional structure for Workshops (vs Sessions, i.e. Instructional vs Informational)? Notice the difference between instructor and presenter as well.

Here are some of the big ones:

**DrupalCon Conference:**
Conference > Day > Session > Presenter
Conference > Day > Workshop > Instructor

**HighEdWeb Conference:**
Conference > Day > Session > Presenter

**THAT Conference:**
Conference > Day > Session > Camp Counselor

**Smashing Conference:**
Conference > Day > Session > Presenter
Conference > Day > Workshop > Instructor

**Event Apart:**
Conference > Day > Session > Speaker

**Comment by joewhitsitt** [comment]
I think what I was hinting at with https://github.com/uiowa/uiowa/issues/5810#issuecomment-1278049198 is that there is a top-level event series, but everything else is technically an "event" and that the type and the information provided changes using parent (superEvent) and child (subEvent) relationships to tie things together.

There is similar mixing of types with events.uiowa.edu but just at a singular level:

<img width="256" alt="Screen Shot 2022-10-18 at 10 03 48 AM" src="https://user-images.githubusercontent.com/4663676/196468757-5bb082ac-c86b-48bb-bc3a-14047484d406.png">

So Event Series in this case would either be the ISWF as a whole (year after year) or the specific year's collection.

Event Series can also be a superEvent so there could be an entity reference tied to superEvent that could reference either a Event or an EventSeries

**Comment by mark-bennett-uiowa** [comment]
Things to consider from huddle:

- Utilize schema.org for EventSeries and Events.
- Capturing eventID for pathing, e.g. /event/12345/human-readable-title
- Limit event nesting to 3 levels to start: festival > session > workshop
- Joe pointed out that performer property is the schema mapping for performer, instructor, etc.
- Also pointed out offers property for registration link

**Comment by joewhitsitt** [comment]
I want to dig a bit more into the Schema.org Blueprints module in terms of blending with existing content types (e.g. Event) but my proposed solution would be to address as much of this with the event content type. I want us to ignore the "Event Series" content type that we half-did for Admissions as "EventSeries" is just a type of "Event" in schema.org's mind. _If_ we needed a separate content type, I think Event Series would make sense and both Event Series and Event would be reference-able for parent/sub.

- Event title (required)
- Generate title based on event type and date (boolean) custom to ISWF.
- Event type (e.g Festival, Session, Workshop, Series, General event (default), Performance, etc.) (required)
- Single Date/range (required)
- Date/time description - Text field to capture a more general timeframe.
- Event range type (e.g. weekend, week long) that shows for specific event types like session custom to ISWF.
- Genre - custom to ISWF that shows based on Workshop event type.
- Description
- Location
  - Place, Address, Virtual Event Info
- Performer (person or contact reference similar to Iowa Now) which will have good help text to describe speaker, instructor, group, musician, etc.
  - Instructor, etc. would just be additional person types.
- Parent event (e.g. reference the conference event, festival, etc. that this event belongs to)
- Sub-event(s) (e.g. IEF create/reference the smaller events that spin off this event). Since these are all the same content type, referencing the same content type, we will probably need to add some inline-validation to prevent more than 3 levels deep.
- Ticket/registration link (offers) with label.

With training, the staff would move away from some of their terminology to fill in different types that are all essentially event types.

Type, parent(s), sub-event(s) will be listed on the full node and teaser if needed. "Part of: ...", "Events include: ..."

The events list block can then filter on event type and the parent event to provide list of sessions, etc. An overall view will have everything in a chronological based listing.

**Comment by joewhitsitt** [comment]
looks like the schema.org blueprints suite will allow us to extend the existing event content type instead of starting from scratch.

<img width="1008" alt="Screen Shot 2022-10-19 at 9 39 16 AM" src="https://user-images.githubusercontent.com/4663676/196722646-a115ae2a-5cec-4a55-b73f-5486e28ecd5b.png">
<img width="817" alt="Screen Shot 2022-10-19 at 9 38 43 AM" src="https://user-images.githubusercontent.com/4663676/196722649-fb241e22-eb6a-4e09-b4b8-54762fdb3283.png">
<img width="419" alt="Screen Shot 2022-10-19 at 9 41 29 AM" src="https://user-images.githubusercontent.com/4663676/196723197-a2d5aeaa-7839-4de8-ad70-8063b277fb8b.png">



field_event_series_link probably needs to be moved to the admissions split.

per https://git.drupalcode.org/project/schemadotorg/-/blob/1.0.x/modules/schemadotorg_smart_date/README.md, it is recommended to use the eventSchedule with smart date instead of dealing with startDate/endDate.

going to look into limiting superEvent and subEvent programmatically

**Comment by joewhitsitt** [comment]
So there is definitely potential with out of memory or max input vars issues with nesting deep. The good news is that if they were able to save enough, the next time the parent event is modified, the IEF is collapsed.

Any kind of limit imposed on form_alter probably won't work because it is re-triggered at each level.

It might be that only hook_field_widget_WIDGET_TYPE_form_alter or custom JS traversing the DOM could allow limiting the functionality from going too deep

**Comment by joewhitsitt** [comment]
It looks like we can use hook_schemadotorg_jsonld_alter to adjust the mapping if we have different field types serving the same schema property (e.g. location as both a physical address as well as providing a virtual option)

Generally, this kind of jsonld handling seems a lot more flexible than our schema_metatag implementation, however after our findings in https://github.com/uiowa/uiowa/pull/4646 it sounds like having multiple representations providing different values is not a big deal.

**Comment by joewhitsitt** [comment]
>field_event_series_link probably needs to be moved to the admissions split.

Bummer, looks like this was intentionally added to the feature split even though the Event Series content type doesn't exist. https://github.com/uiowa/uiowa/issues/4010 I am scratching my head trying to remember the details of this and why it wasn't name Source Link like Articles.

Anyway, I continued experimenting with using just the event and person content types to setup a structure for ISWF if we can adjust their workflow and have them be flexible on terminology.

https://github.com/uiowa/uiowa/pull/5869

**Comment by joewhitsitt** [comment]
A few additional notes:

- Session Type, Genre (ISWF specific) would be fields that would show/hide based on the event sub type (e.g. session, workshop) however, I ran into an issue using non-spec sub types. Session and workshop aren't in the spec and I imagine there are other ones we want so we might have to move away from blueprints for this.

- Currently our event content type is single date specific. That is the Google way. I saw on the online version of ISWF that they have an event serving multiple dates/times. Schema.org does support date repeating and the blueprints module recommends using eventSchedule/smart_date. Not sure what this does for our list block stuff though.

>Saturdays on Zoom, October 15–November 12, 2022
>11:00 a.m.–1:30 p.m. Iowa/Central Time (12:00–2:30 p.m. Eastern; 9:00–11:30 a.m. Pacific; 10:00 a.m.–12:30 noon Mountain)

**Comment by joewhitsitt** [comment]
Capturing from internal-demo:
- CLAS approval to move forward with single content type parent/child representation and event type classification.
- Workflow/reference direction decisions
- Figure out schema subtype or event category for classification of festival, session, workshop, etc.
- Update Series Link label to Source Link
- Make sure admissions, oniowa can accept changes
- Separate issue: making person content type more flexible to single line value name or offer another content type to handle multiple types of event performers.

**Comment by joewhitsitt** [comment]
Summary:

- Investigate the Event feature, what could be used and what would need to be modified.
  - I believe we can use this content type and extend it to be used for Festival, Session, Workshop as long as we keep the comments of this issue in mind.
- Investigate the Event Series content type that exists in the Admissions split to see how similar/different it is from from the requirements of ISWF.
  - I think this is not worth trying to salvage. It was very specific to Admissions and doesn't quite match with the schema.org mindset. 
- Investigate the Person content type to see what modifications would need to be made to it to use it as the basis for instructors on ISFW.
  - I think the content type is ready for instructor unless a custom person type is needed.
- Make a recommendation to the team about how to proceed.
  - CLAS approval to move forward with single event content type
  - Decide what changes should be made in terms of ISWF workflow for entering this content. Parent->Child or Child->Parent and where the reference should be. I think inferring one of the relationships can be programmatic and displayed with views on the content type and altered as it pertains to the json-ld.
- If you make code updates that are potentially useful to your proposed path forward, put them into a PR for future use.
  - Work has been started in https://github.com/uiowa/uiowa/pull/5869 but needs cleanup.

**Comment by briand44** [comment]
Going to close this because it feels like this probe is complete. The next slice includes getting CLAS approval and cleaning up the existing PR.
