### ISSUE TITLE
https://uc.prod.drupal.uiowa.edu/ content review

### ISSUE THREAD

**Issue by mkyoder** [uiowa/uiowa#5865]
# Additional Information
Content review for uc.prod.drupal.uiowa.edu before launching. Will run Screaming Frog scan and look for missing meta descriptions, pages with broken links, etc. 

# Proposed Solution

- [ ] Run some pre launch screaming frog reports to check for 404's meta descriptions, .prod links, etc and provide reports to Annette
- [ ] Content and Design review for https://uc.prod.drupal.uiowa.edu and provide feedback to Annette

**Comment by mkyoder** [comment]
Here is a content review of University College after running Screaming Frog. Let me know if you think I missing any information here.

**Comment by mkyoder** [comment]
[https://iowa.sharepoint.com/:w:/s/OSCWebTeam/ET88xkkeROJEhO0yzPoIvbQBoeb0AtwYhi-8AbURJ3o-fg?e=l0ioVQ](url)

**Comment by mkyoder** [comment]
[Content Review for University College Website - F2022.docx](https://github.com/uiowa/uiowa/files/9824591/Content.Review.for.University.College.Website.-.F2022.docx)

**Comment by bspeare** [comment]
Here are some content and design notes.   

@mkyoder do you want to upload your document to office 365 and I can integrate these into your document?

https://uc.prod.drupal.uiowa.edu/our-organization-0
- Use people lists to manage these listings?

https://uc.prod.drupal.uiowa.edu/k-12-opportunities
https://uc.prod.drupal.uiowa.edu/message-our-dean 
- Don’t use tables for layout

https://uc.prod.drupal.uiowa.edu/about
https://uc.prod.drupal.uiowa.edu/students
https://uc.prod.drupal.uiowa.edu/faculty 
- Empty page with duplicate links, consider using `<nolink>` in menu. 

https://uc.prod.drupal.uiowa.edu/admitted-university-college-programs
https://uc.prod.drupal.uiowa.edu/taking-university-college-courses 
- Use narrow column instead of text area block with padding
- Use image block

https://uc.prod.drupal.uiowa.edu/professional-policies-and-responsibilities
- Use a consistent grid, 3 columns for each section. 

https://uc.prod.drupal.uiowa.edu/teaching-instructional-policies
- Empty 

https://uc.prod.drupal.uiowa.edu/class-lists-submitting-grades
- Add container space padding between page title and content 

https://uc.prod.drupal.uiowa.edu/exam-information
- All menu items are hard-coded with prod url.  Each page needs to be attached to the menu through the node menu settings.  

Search for `.prod` in https://uc.prod.drupal.uiowa.edu/admin/find-text and fix all usages of prod url.

**Comment by mkyoder** [comment]
Sure, @bspeare! Here is a link:[ ](https://iowa.sharepoint.com/:w:/s/OSCWebTeam/ET88xkkeROJEhO0yzPoIvbQBoeb0AtwYhi-8AbURJ3o-fg?e=rapocl)

**Comment by mkyoder** [comment]
Sure! @bspeare here is a link: https://iowa.sharepoint.com/:w:/s/OSCWebTeam/ET88xkkeROJEhO0yzPoIvbQBoeb0AtwYhi-8AbURJ3o-fg?e=rapocl

**Comment by bspeare** [comment]
Thanks @mkyoder!  I've finished adding my comments to the sharepoint document.

**Comment by bspeare** [comment]
I've created a follow-up issue (https://github.com/uiowa/uiowa/issues/5905) based on the content review.   I have updated the sharepoint doc after reviewing Annette's changes from today.   @mkyoder is going to review the changes tomorrow and get back to Annette on the remaining items that need to be fixed.

**Comment by mkyoder** [comment]
Responded to Annette with additional changes still left to do for this site.
