### ISSUE TITLE
Scroll to top option for D8 Sites

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#587]

**Comment by joewhitsitt** [comment]
I remember education having an a11y approved scroll to top button.
https://github.com/ITS-UofIowa/education.uiowa.edu/blob/master/themes/radix_education/js/scrollTop.js

https://github.com/ITS-UofIowa/education.uiowa.edu/blob/master/themes/radix_education/templates/page/page.tpl.php#L20

**Comment by dnkemper** [comment]
Thank you very much, @joewhitsitt

**Comment by richardbporter** [comment]
Could/should this be configurable? A module seems overkill but a theme setting might be nice. Otherwise, overriding the template works.

**Comment by dnkemper** [comment]
> Could/should this be configurable? A module seems overkill but a theme setting might be nice. Otherwise, overriding the template works.

Could we maybe provide that option for customized sites? Just a thought.

**Comment by richardbporter** [comment]
Ultimately, this should be a theme setting. However, doing it in uiowa_bootstrap isn't possible because webmasters cannot and should not access theme settings right now since they BS-related.

If we want to get this in now, we could do what uiowa_footer is doing and alter the site info form: https://github.com/uiowa/uiowa_footer/blob/master/uiowa_footer.module#L22 Then just move it later when an HDS theme is done. 

Otherwise, I would probably postpone/block this until #371 is done.

**Comment by dnkemper** [comment]
@richardbporter Kind of confused. Should I just delete what's on the branch/current pull request and remove my assignment?

**Comment by richardbporter** [comment]
Nope, the work you did is fine but I think #640 is blocked until #371 is completed.

**Comment by joewhitsitt** [comment]
Closing in favor of #2755 where the momentum is.
