### ISSUE TITLE
Law Library InfoHawk+ Search

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5875]
# Story

As an owner of library.law.uiowa.edu, I would like to have a search box on my website where users can search InfoHawk+.

# Additional Info
Existing code on 703 in /docroot/sites/library.law.uiowa.edu/modules/custom/custom_widgets/plugins/content_types/custom_widgets_search_block.inc.

# Proposed solution

**Comment by joewhitsitt** [comment]
I sat in with Brian for this meeting and it sounded like the v3 search block could be extended to append additional query parameters (preferably developer fixed for MVP) or that it is one open text area (plain) on the block config that site owners can see/fill in.

Then it is just figuring out how to support both internal and external.

**Comment by briand44** [comment]
grooming conversaton... adding a text area for query parameters so others can use this seemed to be the preferred method.

**Comment by joewhitsitt** [comment]
@e-marie-w, I would work off https://github.com/uiowa/uiowa/pull/5922 to add the additional plain text area. Let me know if you have questions.

**Comment by joewhitsitt** [comment]
we might need an additional text field to capture `any,contains,` like `query prefix` so that we don't disrupt the existing search blocks out there

**Comment by joewhitsitt** [comment]
As for the encoding issue, maybe we should instead take in key/value items. Instead of using paragraphs, a compound field like https://www.drupal.org/project/key_value_field might be worth looking at

i think we have navigated around this before though to provide "add more" functionality to a field or group of fields.

otherwise, we should be able to append whatever is provided as-is to the $url->toString() functionality. Might need to do a XSS check. `filter_xss()`
