### ISSUE TITLE
ISWF event customizations

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5886]
- [x] Add "presenters" list to subEvents blocks between date and short description - icon
- [x] Move "presenters" above description in event display.
- [x] Change short dates to long dates to match standard moving forward: l, F j, Y - g:ia
- [x] event type - Select list custom to ISWF - allowed values (no longer necessary??, as per https://github.com/uiowa/uiowa/issues/5732#issuecomment-1263915168, unless we need this for conditional display of fields later)
- [x] Add Genre - only for workshops??
- [x] Display genre(s) below descriptions in a comma-separated list.
- [x] Representing Performers - label as presenter for now - future slice to make this customizable
- [x] Add registration link and add as button below details in right column

**Comment by joewhitsitt** [comment]
I think the event categories (festival, session, workshop) are created in PROD (to get tids) and then protected from deletion.

Iowa Now has some protected term functionality that I would like to see made reusable and stored in the db so that a deployment is not necessary to add/update/remove them. Maybe an admin only fieldset to configure on admin/config/sitenow/uiowa-core ?

**Comment by joewhitsitt** [comment]
@pyrello do you have time to write out your vision for handling schema.org event types with custom mapping?

**Comment by pyrello** [comment]
> @pyrello do you have time to write out your vision for handling schema.org event types with custom mapping?

My idea is that we have some custom configuration defined, possibly in `sitenow_events.settings.yml` that provide a map of default event types:
```yml
event_types:
  "Education Event": EducationEvent
  Festival: Festival
  # ...
```

This config would be loaded into each site when the event feature is turned on, but the config would be ignored so that it could be changed per site. This feature would be managed by developers only to start, so we could probably get by with just using the config export + config import UIs to export, alter, then re-import the labels to match what the site owner wants. We could populate the values in a "List: Text" field via an allowed values function.

@joewhitsitt also suggested this could be handled via custom config entities and an ER field referencing them. That seemed like a bit more overhead to me, but is probably more user friendly and flexible.

_Edited to flip the keys and values in the YAML to allow for multiple maps of custom labels to a single Schema.org event subtype._

**Comment by briand44** [comment]
Try moving forward with ^^ reversed and if run into issues go with config entities.

**Comment by bspeare** [comment]
Is this work expected to be done through an `iowasummerwritingfestival` site split and custom `iowasummerwritingfestival_core` module?

**Comment by joewhitsitt** [comment]
yes. @mark-bennett-uiowa was concerned the domain may change in the future. site split should be named `site` and that module name should work just dandy.

**Comment by mark-bennett-uiowa** [comment]
Thank you again @GaryRidgway @makurj @pyrello @joewhitsitt and everyone else who worked on this major issue!
