### ISSUE TITLE
Related by tag functionality shows on non-default content types

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#5909]
# Problem
The related by tags functionality is showing on the non-default event content type (possibly others?) and there are no controls to turn it off.

<img width="618" alt="Screen Shot 2022-11-02 at 12 47 13 PM" src="https://user-images.githubusercontent.com/4663676/199563693-c758d28a-bedc-42de-95f2-89c66ef059bf.png">

# Steps to reproduce
With the event feature split enabled, add a tag to an event. See the tag show on the rendered entity.

# Proposed solution
- [ ] Check the logic that is used to determine the visibility of this functionality so that content types without control setup don't display these blocks.

**Comment by e-marie-w** [comment]
So, I think I found a possible solution. In the views for the tag list and referenced content (that also displays at the moment), I can add a filter so that tags/referenced content only appear on an entity if that entity is an article, person, or page. This doesn't affect sitenow settings - tags are allowed on a page but won't appear unless set to display tags on pages. 

Right now working on exporting it for default & creating the PR, but assuming we like this solution my next step would be looking at custom content types beyond events and making sure the tags are still showing or not showing as expected.

**Comment by joewhitsitt** [comment]
Before we go this direction, I'd like to know why our logic is not working for this

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L208
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L231

**Comment by e-marie-w** [comment]
Ohhh that's the logic Cory was talking about, okay. Will check it out when I have a chance.

**Comment by e-marie-w** [comment]
So I've been working on the 91st Meridian stuff instead this afternoon and don't want to prevent anyone else from working on this so I will gracefully unassign myself and say you can completely ignore that PR.
