### ISSUE TITLE
Ability to route user after login to a specific page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5911]
https://github.com/uiowa/uiowa/pull/5893#issuecomment-1295052384

Currently when a user authenticates to an intranet, they are routed to the home page (see https://github.com/uiowa/uiowa/pull/5893).

It would be great if someone was able to share a link to https://studentlifeconnect.prod.drupal.uiowa.edu/training-and-development and after the user logs in they would be routed to that page.

**Comment by briand44** [comment]
Collect route prior to restrict ip taking over and modify

**Comment by briand44** [comment]
Possibly an opportunity to add a patch to the module

**Comment by joewhitsitt** [comment]
Adding thoughts from grooming:

When a URL is requested on the site (from an email, bookmark) restrict_ip doesn't serve the original URL request's 403. It reroutes the request to their generic 403 page /restrict_ip/access_denied so the path we have used for our normal login link is not available. Some possible options:

- Look to harvest and store this information through a patch to the module and then wire up our login button based on that stored value.
- Custom JS that captures and stores the URL to then wire up our login button with.

**Comment by quamsta** [comment]
@joewhitsitt 
Explored these options in a bit more detail today:

> Look to harvest and store this information through a patch to the module and then wire up our login button based on that stored value.

This would likely have to be done in a patch to `docroot/modules/contrib/restrict_ip/src/EventSubscriber/RestrictIpEventSubscriber.php`, more specifically the function `checkIPRestricted`.

We could store the original request near the top of this function:

```php
//RestrictIpEventSubscriber.php
//...
public function checkIpRestricted(GetResponseEvent $event)
  {
    unset($_SESSION['restrict_ip']);
    $originalRequest = \Drupal::request()->getRequestUri();
    $this->restrictIpService->testForBlock();
//...
```
Did some testing and this section of code around line 110 appears to send the response where `restrict_ip.access_denied_page`is presented to a disallowed user:

```php
//RestrictIpEventSubscriber.php
//...
        elseif(in_array($this->config->get('white_black_list'), [0, 1]))
        {
          $url = Url::fromRoute('restrict_ip.access_denied_page');

          $event->setResponse(new RedirectResponse($url->toString()));
        }
//...
```
We could adjust `$url` in this context to preserve the url's original path before sending them to `restrict_ip.access_denied_page`:

```php
//RestrictIpEventSubscriber.php
//...
        elseif(in_array($this->config->get('white_black_list'), [0, 1]))
        {
          $url = Url::fromRoute('restrict_ip.access_denied_page');

          $event->setResponse(new RedirectResponse($url->toString().'?destination='.$originalRequest));
        }
//...
```

From there, we'd hook up this patched module to our `restrict_ip.access_denied_page`, either by further altering it via `sitenow_intranet_restrict_ip_access_denied_page_alter` like so:

```php
//sitenow_intranet.module
//...

if (isset($page['login_link']) && $exists) {
    $destination = '/';

    if($_GET['destination']){
      $destination = $_GET['destination'];
    }


//...
```

or... by altering `restrict_ip.access_denied_page` by patching it too? Not sure if we should be patching it too  if we're already considering patching `restrict_ip` anyway. Unclear about this, feedback welcome.

> Custom JS that captures and stores the URL to then wire up our login button with.

I'm a bit unclear about how this one would work? Would this involve injecting additional JS via patching the module? It seems that `RestrictIpEventSubscriber.php` is where most of the redirecting takes place, and I'm worried that we can never inject any custom javascript via our own module (aka `sitenow_intranet_restrict_ip_access_denied_page_alter`) that would be in an ideal spot to get the original destination.

**Comment by joewhitsitt** [comment]
I just threw the JS idea out there thinking maybe there is a hook (preprocess_html?) that is called before restrict_ip's event subscriber that could attach JS to that grabs the original window.location that could be stored and referenced. We have the sitenow_intranet module that can house it without any modification to the restrict_ip module.

That said, I think a feature request issue for the request_ip module sounds better. I think it would be just to capture/store the original destination info. Then on our end, the alter in sitenow_intranet would handle wiring it up to the button.

**Comment by bspeare** [comment]
Grooming notes for proposed solution:
- Read through https://github.com/uiowa/uiowa/issues/5911#issuecomment-1324339821 for notes about MR and patch for restrict IP module
- Utilize that file immediately in codebase
- Take the stored destination and wire it up to our login buttons within intranet module

**Comment by pyrello** [comment]
In debugging how the `RestrictIpEventSubscriber` works today, I noticed that it runs multiple times when you hit a page and the user is not authenticated. When you view the current path when the subscriber is called, at first it is the path that you attempted to go to (e.g. `/welcome`). The second time it fires, the path is `/node/1`. Finally it fires a last time and the path is `/restrict_ip/access_denied`, which is where you end up.

The redirect that happens to `/node/1` is troublesome because it means that we have to figure out how to persist the destination over two redirects. I can't figure out what is causing that first redirect. I thought it might be some other contrib module or the way our system is set up, but I ended up spinning up a DrupalPod with the Umami demo profile and only two other modules enabled. In that case, I observed the same behavior (although the first redirect went to `/node` instead, which is the default front page setting).

Originally, I thought we could do this with our own event subscriber, but so far in my testing the custom event subscriber only fires once the path gets to `/restrict_ip/access_denied`. This may be a local issue I've created somehow, so would be good to validate by someone else.

Without being able to get rid of that intermediate redirect to the home page, we'll probably need to patch the module. Otherwise, by the time we can add a destination, it has been lost on the redirect to the home page.

**Comment by joewhitsitt** [comment]
>Originally, I thought we could do this with our own event subscriber.

Was there something that turned you away from patching originally or were you just curious?

>This may be a local issue I've created somehow, so would be good to validate by someone else.

I set a breakpoint on the `SitenowIntranetSubscriber.php` but it doesn't seem to trigger. Are there additional setup steps beyond the sitenow_intranet instructions in config/features/sitenow_intranet/README.md?

**Comment by joewhitsitt** [comment]
FWIW, following https://github.com/uiowa/uiowa/issues/5911#issuecomment-1324339821 and constructing the Url:fromRoute with the destination parameter instead of trying to append the destination to the resulting string seemed to work in `RestrictIpEventSubscriber.php` for me.

```php
$url = Url::fromRoute('restrict_ip.access_denied_page', [], [
  'query' => [
    'destination' => $originalRequest,
  ],
]);
$event->setResponse(new RedirectResponse($url->toString()));
```

**Comment by pyrello** [comment]
> > Originally, I thought we could do this with our own event subscriber.
> 
> Was there something that turned you away from patching originally or were you just curious?

Before committing to a patch, I'd generally like to see some signal from the maintainers that they would have interest in eventually merging it in. Otherwise, it just becomes a thing that we are forever responsible for. So, I was interested in our own event subscriber because that was potentially a way of doing it without a patch for the time being.

> > This may be a local issue I've created somehow, so would be good to validate by someone else.
> 
> I set a breakpoint on the `SitenowIntranetSubscriber.php` but it doesn't seem to trigger. Are there additional setup steps beyond the sitenow_intranet instructions in config/features/sitenow_intranet/README.md?

For setup, I synced connect.studentlife.uiowa.edu.

**Comment by bspeare** [comment]
I created a feature request at https://www.drupal.org/project/restrict_ip/issues/3328079.  Let me know if you have any further details that you would like me to add/remove.
