### ISSUE TITLE
Consider migrating all image_background media types back to image.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#596]
## Problem
The original reasoning for using this media type has become unclear and has only created unnecessary complications.

Poor media file management/selection UX
Migration issues #379 

## Proposed solution
Migrate image_background entities back to image, use the sitenow_16_9 responsive image style, and update section background code/field.

**Comment by joewhitsitt** [comment]
Any thoughts on why we shouldn't do this besides the amount of work to accomplish?

**Comment by cory-skeers** [comment]
I am all for the change in order to reduce complexity. From a user standpoint, I've found myself forgetting about the separation, and at least in working with the Protostudios site, having several instances where an image has either been 'promoted' from a standard image to an image_background, or vice versa, and that process is a minor but noticeable hassle.
