### ISSUE TITLE
Transition named building content from page to named building

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5963]
As a Facilities site owner, I would like our named building pages moved to the new structure so that we do not have to create those pages again.

# Additional Information
Capture the existing information from the pages in the appropriate structured fields along with the building id related to that Facility from https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings.

V3 prod site: https://facilities.prod.drupal.uiowa.edu/

**Comment by briand44** [comment]
Blocked until https://github.com/uiowa/uiowa/pull/5934 is deployed

**Comment by joewhitsitt** [comment]
~>Since existing page content already exists, unless those are deleted first as part of the process, named buildings are going to get a -0 url alias (e.g. philip-d-adler-journalism-and-mass-communications-building-0) - https://github.com/uiowa/uiowa/pull/5934#issuecomment-1330963695~

This has been addressed by adding the same alias pattern as their current website. https://github.com/uiowa/uiowa/pull/5934/commits/b0407d35d3c51126bae5dec76ab2b7383a362c02

**Comment by pyrello** [comment]
I'm going to work on getting the site split turned on for the site.

**Comment by briand44** [comment]
Sounds good, is this blocked based on https://github.com/uiowa/uiowa/issues/5472 or do you think it makes sense to do what can be done now and come back once https://github.com/uiowa/uiowa/issues/5472 is done?

**Comment by pyrello** [comment]
Drat. I think it is blocked based on #5472

**Comment by maramcconnell** [comment]
Once building has a named building page, archive the original page

**Comment by briand44** [comment]
I am going to close this issue since the work here is complete. Thanks Mara!
