### ISSUE TITLE
Card: template and block template updates with layout builder styles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5970]
The PR associated with this work will not be merged until all slices of #5849 are complete.

- [x] Update new card template: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/uids/card.html.twig.
- [x] ~Update the block card template to work with the new card template.~ Implement card render element.
- [x] `Card:border` needs to change to `Remove border` now that cards have borders by default.  
- [x] `Stacked:default` should still be an option, but it no longer adds a modifier class.  
    -  How should we handle this?
- [x]  Update layout builder styles as needed with updated classes.

**Comment by briand44** [comment]
From epic https://github.com/uiowa/uiowa/issues/5849

**Comment by GaryRidgway** [comment]
I think we really need to make sure we are going through and setting up templates in ways that inherit from each other. At the current moment, I am working on ISWF stuff and I am getting super confused with the multiple templates we have. I would lvoe to see some better inheritance organization and whatnot.

I dont know, maybe I am just ranting lol. ISWF has been melting my brain.

**Comment by pyrello** [comment]
Today in our mid-sprint demo, I showed progress on the implementation of a card render element, which allows for automatic setting of a template and preprocessing data into it via something like this:
```php
$build['card'] = [
  '#type' => 'card',
  '#media' => $entity->get('field_image'),
  '#title' => $entity->get('title'),
  //...
];
```
This is a contrived example, but what it allows for is being able to specify the template that should be called by setting `'#type' => 'card'` and then mapping the correct fields/values to the correct render element property. This means that we don't have to create a block template and then implement the card template, we can just directly have it use the card template. The above is essentially what we are already doing in various places, but with many extra template files that map the variables and then call the card template. Example: https://github.com/uiowa/uiowa/blob/5766b73628fbf4a471c239891995d50a9ef9b0c2/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-card.html.twig

#6054 has an early working version of this.

As the template link above shows, we are currently deconstructing the `field_uiowa_card_title` heading field to grab the text and size, then loading those into our headline template. I'd like to figure out how to just let the heading field display the correct classes instead of working around its template. Or if we prefer to use our own solution, switch it to using a formatter based on our homegrown headline field.

**Comment by bspeare** [comment]
I pulled this down and took a quick look at it.  @pyrello here are a few notes which you may already be aware of:

- We still need these classes attached to the block https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-card.html.twig#L28-L34.
- There are `Card: border` and `No border` style options in the card block. 
- Media sizes styles are all showing up as `Small`.
- Image size style is showing a `-Select-` option where it wasn't previously.
- It doesn't appear that `card--layout-right` classes are being added for left/right aligned cards (scroll to bottom of https://sandbox.uiowa.ddev.site/cards) to check it out.

**Comment by pyrello** [comment]
> We still need these classes attached to the block https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-card.html.twig#L28-L34.

@bspeare Do we use all 3 classes?

**Comment by bspeare** [comment]
@pyrello We just need `block` I believe, that's how we are targeting block spacing within the same column.

**Comment by bspeare** [comment]
After testing this out today, I'm noticing some issues for the button shapes: 
- [x] Updating an existing card block will apply the `bttn--circle` class
- [x] Updating an existing block and setting the "Show button" to hide will display button

**Comment by pyrello** [comment]
> Updating an existing card block will apply the `bttn--circle` class

Actually I don't think the update was necessary. It might not have been showing before because of caching. I added a test page to debug this: https://sandbox.prod.drupal.uiowa.edu/debug-card. When I synced it was already showing the circle button.

This is fixed in https://github.com/uiowa/uiowa/pull/6054/commits/33849f7a75430373e09b5c37753417cbbd0ab567

**Comment by bspeare** [comment]
Starting a checklist of things here that I don't want to forget. 

- [x] Image sizes are all rendering widescreen
- [x] Image/Media widths are being overridden by `media--widescreen` class
- [x] Need a `card--media-padded` layout builder style.
- [x] Update card button bottom position to `card--button-align-bottom` class. 
- [x] When creating a new block `× 1 error has been found:
[Media size]`
- [x] Card media sizes don't seem to be set on https://home.uiowa.ddev.site/admissions vs https://uiowa.edu/admissions
- [ ] Buttons seem to be broken. 
- [ ] Existing card markup not being rendered in HTML tag some sites like uiowa.edu/admissions. 

<img width="1148" alt="Screen Shot 2023-01-25 at 12 55 06 PM" src="https://user-images.githubusercontent.com/1036433/214657135-4e72e594-5656-4b66-af57-dc7ce1c22d60.png">

**Comment by pyrello** [comment]
> When creating a new block × 1 error has been found: [Media size].

This is fixed. Below are the show/hide settings for this field widget. We should review that this is what we still want.

```php
            $form['layout_builder_style_media_size']['#states'] = [
              'visible' => [
                // Always show when media format is set to 'circle'.
                [
                  ':input[name="layout_builder_style_media_format"]' => [
                    'value' => 'media_format_circle',
                  ],
                ],
                // Show when a media position is selected.
                [
                  ':input[name="layout_builder_style_card_media_position"]' => [
                    '!value' => '',
                  ],
                ],
              ],
            ];
```
