### ISSUE TITLE
Classrooms - Fields populated by API

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6032]
Split off from https://github.com/uiowa/uiowa/issues/5769

# Proposed solution

Add the following fields, which will be populated via API.

- [x] **Classroom Type - single value
    - Used as filter
    - Data comes from roomType in https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomData/Abw/240
    - https://classrooms.uiowa.edu/admin/structure/taxonomy/classroom_type
    - we should link these room types to https://classrooms.prod.drupal.uiowa.edu/types-university-classrooms
- [x] **Max Occupancy - this should only contain a number
    - Used as a filter
    - comes from maxOccupancy https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomData/Abw/240
- [x] **Features
    - They would like to break this into two groups - Room Features and Technology features
    - Currently represented as one filter in mockup but two separate would be ideal
        - https://classrooms.prod.drupal.uiowa.edu/home/find-university-classroom#feature
    - MAUI just contains all of these in one data set, not differentiated between room and technology
    - Not linking to these, rabbit hole if using a reference?
    - I've asked them to provide us a list of all of the room features and all of the tech features so we have a way to determine the mappings
    - There will be a couple features in MAUI they we will want to avoid displaying for security/safety purposes. I still have a question out related to this. Ideally, they have control of the list of tech features and room features on the website (taxonomy, etc.) so that if a new feature is added to MAUI they can add that to the site so that the mapping will work for the new feature. Same if they decide to remove a feature. They could delete the item from the list (taxonomy term, etc) and then that feature would no longer be mapped or show on the site.
- [x] **Responsible Unit - List of Department/Units
    - Fields 
        - Name
        - Description - not sure if used currently - they would like to keep but not output if empty
        - Scheduler - text
        - Email
        - Phone
        - Link - title and URL
    - Responsible unit comes from MAUI acadOrgUnitName. Additional unit information will be manually managed by Classrooms folks - can this additional unit info be brought over in the content migration?
- [x] **Room Name - text field - i believe this is if there is an alternative name for a room (e.g. Faculty Studio https://registrar.uiowa.edu/vox-5468) - Yes and will need to be included on room display - w10 PBB example.
- [x] **Instructional Room Category? - This can be the field used internally to designate University Classroom vs Programmed Classroom.
- [ ] Room schedule - from Astra - may not need any structure for this but will need displayed? If no structure needed this may make sense to be in a future slice.

**Comment by joewhitsitt** [comment]
@e-marie-w if you want to sync down, get setup to start creating local fields for these that would be the first step. I think type, room features, technology features and units should be taxonomy vocabularies that is setup to reference existing instead of creating new.

i will check in after i review the contact PR

**Comment by joewhitsitt** [comment]
@briand44 can you elaborate on the Instructional Room Category field. Should that be a select, textfield or taxonomy? Depending on your answer could you also explain where that info should be grabbed from in the feed? https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomData/Abw/240

**Comment by joewhitsitt** [comment]
In talking this out with Marie, I think we need to do this in two parts. Part one, we get the fields (vocabs created) and out to PROD where we can establish a `tid` to target and possibly protect for each feature, type, etc. to map to. Locally, we can continue with temp tids, but before the second part goes out we will want to finalize those in code.

Not sure if the classrooms staff has initial terms for each bucket that they want mapped.

**Comment by briand44** [comment]
>can you elaborate on the Instructional Room Category field

So this was a field that is currently used on the Registrar site for the UCS/SPS page. It is no longer needed by the customer but my understanding is we are going to need a way to flag a room as either "University Classroom" or "Programmed Classroom" in order to determine if the rooms are part of the main Classrooms search page (https://classrooms.prod.drupal.uiowa.edu/find-university-classroom) or the other page for Programmed Classrooms.

From Renee:
>we are still interested in pulling over the classrooms that we call, Programmed or Level 2, on to a different page that a user can navigate to from the main UCR information in order to see data and daily room management.  But we don’t want to mix the classrooms on the same pages so we’re thinking making them have to go to that page for that subset of the classrooms helps with confusion.

So, I think it is up to the team to determine if this field is a select, taxonomy, etc. I don't think we want a textfield since we will want to have a view that pulls in all University Classrooms as well as a view that pulls in all Programmed Classrooms.
As far as where this info comes from. I think it can come from 2 different places in the API, whatever makes sense from a dev perspective. roomCategory in https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomData/Abw/240 or similar code to how we are grabbing the buildings using this endpoint https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list and looking at the regionList.

```
"1) University Classrooms - Level 1",
                    "1) University Classrooms - Original",
                    "1) University Classrooms",
                    "1) University Classrooms - Study Space",
```

vs

```
"1) Programmed Classrooms - Level 2",
"Classroom-Programmed",
```

**Comment by briand44** [comment]
>Not sure if the classrooms staff has initial terms for each bucket that they want mapped.

Is this referring to the different types of features? Room features and technology features? If so, they are working on the list and will provide it to us when it is ready

**Comment by joewhitsitt** [comment]
Suggested todos:

- ~~Change roomType logic to do the same as Responsible Unit. They seem to be okay with the value formats for these: https://classrooms.uiowa.edu/admin/structure/taxonomy/classroom_type~~
- ~~Change `Name` to `Room Name` (leave machine name)~~
- ~~Move the API fields to a disabled field group so that editors can see the fields but not mess with them. Help text for the group would be a wise addition explaining that the values are populated on save.~~

**Comment by joewhitsitt** [comment]
The bit we haven't done is establishing a new API call https://github.com/uiowa/uiowa/issues/2184#issuecomment-1358438419 which is a port left to do from the d7 uiowa_maui module. Wondering if that should be in-scope for this issue or a follow-up issue since it would not be stored in field data like the other fields of this issue.

**Comment by joewhitsitt** [comment]
For the room schedule, we will want this to be JS or we need to cache bust a block similar to the time hourly cache tag used by UI Events block.

**Comment by briand44** [comment]
@joewhitsitt @e-marie-w I got some clarity on outstanding fields from Classrooms. I've added some info https://github.com/uiowa/uiowa/issues/6041. The tile details, room design details and furniture can be text fields (not field collections or paragraphs). There is another field that we will need to get from the API as well and that is the scheduling region. Seems like it will need to be similar to the way we are handling features. Not sure if we tackle that in the separate issue or if it is similar enough to the features that we want to tackle it as part of this issue?

**Comment by joewhitsitt** [comment]
>There is another field that we will need to get from the API as well and that is the scheduling region

What feed is that info in? I don't see anything like that here: https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraRoomData/Abw/240

Nevermind. I see that you added details for this on #6041

**Comment by e-marie-w** [comment]
Working on adding the Scheduling Region field to current PR since it is another API field.

**Comment by briand44** [comment]
I want to mention one more thing about the Scheduling Region. I don't know for sure if/how this is going to be output on a room. I have an outstanding question to understand if it needs to output on a room and if so, if it is just text or a link to https://classrooms.prod.drupal.uiowa.edu/university-classroom-scheduling-regions or somewhere else. That can likely be handled on the theming issue.
