### ISSUE TITLE
Probe making all articles use a narrow container

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6042]
From https://github.com/uiowa/uiowa/issues/2784

# Story
As a member of the web team, I would like to understand any negative effects on existing articles when switching to a narrow container so that we can determine if we can make this switch for all articles or if we need to add an option where folks can choose to turn this on.

# Proposed solution

**Comment by joewhitsitt** [comment]
Knowing that this is similar to a page LB narrow section with a filtered_html text area, if I were to pick this up, I'd start with a kitchen sink dump of content (all the wysiwyg buttons, media types and their variations, allowed html tags and properties that don't have a wysiwyg button) in one of those to see how things squish. We should be preventing the use of style attributes (e.g. width, height) so there shouldn't be issues with fixed widths. If there is, we have text areas in four column sections in lb that will have to be addressed.

I think asking about it in demo is a good idea if we haven't previously done so.

**Comment by bspeare** [comment]
I think if we do this, we should either use the 67/33 layout or follow Tippie's design lead and center the featured image text and page title and remove the breadcrumbs: https://tippie.uiowa.edu/faculty-research/research-expertise-interests/research-organizations/experimental-economics.

Other good examples of narrow article design with centered page titles:

- https://www.marylandhall.org/classes/studios/
- https://www.stonehill.edu/news/details/supporting-skyhawks-sacramentally/
- https://www.kenyon.edu/news/archive/leaving-home-is-never-easy/
- https://home.dartmouth.edu/news/2022/12/dartmouth-experts-weigh-threats-nh-primary

**Comment by bspeare** [comment]
Here is a quick mockup of what the article could look like with a centered page title:
- https://sandbox.prod.drupal.uiowa.edu/test-narrow-article
- https://sandbox.prod.drupal.uiowa.edu/test-narrow-article-w-image
- https://sandbox.prod.drupal.uiowa.edu/test-narrow-article-w-gray-background

**Comment by briand44** [comment]
@bspeare in the second example can you provide thoughts on moving the created date and organization to the bottom?

**Comment by bspeare** [comment]
@briand44 that is just an artifact of using the replicate function.  It jumbles up the order of blocks.  It should be updated now.

**Comment by briand44** [comment]
Thanks for putting those together!

**Comment by cory-skeers** [comment]
> Knowing that this is similar to a page LB narrow section with a filtered_html text area, if I were to pick this up, I'd start with a kitchen sink dump of content (all the wysiwyg buttons, media types and their variations, allowed html tags and properties that don't have a wysiwyg button) in one of those to see how things squish. We should be preventing the use of style attributes (e.g. width, height) so there shouldn't be issues with fixed widths. If there is, we have text areas in four column sections in lb that will have to be addressed.

Should check to see if it is up-to-date or if there are options that are missing, but https://sandbox.prod.drupal.uiowa.edu/kitchen-sink is available to play with locally. Everything is in a single lb container, so you can directly apply section styles to the full page and/or adjust styles using the inspector and see how things interact.

Edit: it looks like media embeds are not included, so those would need to be added as well.

**Comment by bspeare** [comment]
I think the majority of the issues will be with media embeds.  If an editor placed a large image/video based on our wide layout, the narrow container will create some undesired text wrapping.  See the details below. 

<details>
<img width="1078" alt="Screen Shot 2022-12-22 at 8 59 54 AM" src="https://user-images.githubusercontent.com/1036433/209162099-62885c7c-762d-41f7-9973-b0e76f2d72ce.png">
<img width="1379" alt="Screen Shot 2022-12-22 at 8 58 49 AM" src="https://user-images.githubusercontent.com/1036433/209162116-aa18bd59-07d6-4e31-a364-904fabc365a3.png">

</details>

**Comment by bspeare** [comment]
I think if we were going to switch this platform wide, we would want to run an update hook checking for large media aligned left or right and set it to center.  Example below in details. 

<details>
Before:

<img width="1039" alt="Screen Shot 2022-12-22 at 1 08 36 PM" src="https://user-images.githubusercontent.com/1036433/209208995-7674d681-613f-4806-878d-be74e6255b40.png">

After:
<img width="1082" alt="Screen Shot 2022-12-22 at 1 08 56 PM" src="https://user-images.githubusercontent.com/1036433/209208987-ba75db3d-72ab-4d44-a8c0-836e781cf294.png">

</details>

**Comment by cory-skeers** [comment]
> I think if we were going to switch this platform wide, we would want to run an update hook checking for large media aligned left or right and set it to center. Example below in details.

Interesting...I like this as a way to handle those cases. After, I'm okay with the possibility of content editors choosing to do this in places they deem appropriate, but this is a good way (I believe) to not force anyone into a poor experience.

**Comment by cory-skeers** [comment]
I used #6064 to sync down international, and at least on the update as a narrow section (might be different if we go 67/33 instead), there are some instances where a large media was updated to center align where it might not have needed it.

Original https://international.uiowa.edu/news/2017/10/commitment-internationalization-qa-madeleine-green
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/49074566/210113523-b847ae71-3052-4ba6-b55e-4f10f793e3b3.png">

updated:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/49074566/210113554-af849bd0-9863-49df-aff3-68b62942c9d0.png">

If it hadn't been updated:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/49074566/210113594-ba4eccb7-ee4e-4993-9e4e-bf9eca188ff5.png">

Similarly, they have a good number of "Dean's message" type articles, where the signature is an image set to "large"
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/49074566/210113654-0979e31f-b0da-47fe-a082-801b99619c89.png">

On the other hand, it works great for truly large media. From
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/49074566/210113785-e12a43d8-3254-4812-ba20-72ab01006526.png">

to
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/49074566/210113847-cf927b30-bffa-47c2-b8f4-017f75f41e31.png">

We could do something like we've done with migrations and find out the true dimensions of the image, and whether or not having it set to 'large' will be an issue or not based on some cutoff minimum width by using the media uuid (available as an attribute in the `drupal-media` element in the update hook) to fetch the dimensions. Dimensions can be retrieved directly from the DB from the `media__field_media_image` table if it's an image, or from the `field_media_image` property of the media element if that gets loaded. It would be one step easier with Remote Videos, because we know that if it's large, it'll be the full dimensions like in the example above. (And if it's not a remote video or an image, then we should be able to ignore it, I think.)

So...It's something I think we could do, but 1) we need to determine what that threshold of "too wide" is and 2) decide if this is the best way to handle these possible consequences. 

For the PR, so far I only targeted `large` media, but a similar check should be done for the large variants like squares, as well as `original`.

**Comment by cory-skeers** [comment]
> We could do something like we've done with migrations and find out the true dimensions of the image, and whether or not having it set to 'large' will be an issue or not based on some cutoff minimum width by using the media uuid

I pushed up a start to this in #6064. It would need adjusting for the image case for the view_modes on when it should or should not be applied, but it accounts for whether it's an image or remote video and has an example of (in the image case) grabbing the source width for those view modes (eg `original`) where it may make the difference.

**Comment by joewhitsitt** [comment]
Good eye in finding instances where center is not always ideal either.

In coming up with a number I think we should treat it similar to our layouts. For a two column layout we have a 25/75 option, so if we force this change we could point to that instead of some other random number in our communication about it. 75% of 1020px = 765px.

I think always doing it to large videos make sense.

**Comment by bspeare** [comment]
Maybe we would only want to make the change if it was a large video that is aligned left or right? Mostly because that might be the most consistent example where this will work great as @cory-skeers notes above.  Perhaps programmatically changing this for all images might not be ideal.   If we do change this for everyone and only make this change for videos, we can provide some documentation on where they might want to adjust their image alignment.  

Articles that currently exist like https://tippie.uiowa.edu/news/2020/05/love-numbers-diamonds, make use of floated images to create a better reading experience and shorter line-lengths.   Seeing an example like that makes me think that the narrow article should be an option that we set in the article settings allowing users to keep the wider page designs that they have built and opt-in to this change.

**Comment by joewhitsitt** [comment]
>Seeing an example like that makes me think that the narrow article should be an option that we set in the article settings allowing users to keep the wider page designs that they have built and opt-in to this change.

Can you remind me the technical steps for that option? Would it just be a parent class in the DOM that adjust styles further down or would the setting swap layout config?

**Comment by bspeare** [comment]
@joewhitsitt I think we were talking about a parent class originally.

**Comment by bspeare** [comment]
Based on our discussion this morning, my impression is that this probe is complete and that we are now working on writing out the next slice of the work that includes these pieces:

- Summary of plan for rolling out narrow articles.
- Summary of plan for making media styles more adaptive to the narrow container.

**Comment by GaryRidgway** [comment]
Probe complete and documented in #2784
