### ISSUE TITLE
Implement container query work for image styles and other inline elements in uids_base

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6074]
# Story

As a SiteNow content editor, I would like image sizes and other inline elements (callout) to be defined based on the size of their container so that I can have more consistent styling of images in different column widths.

# Proposed Solution

- Update to a commit of UIDS 4 that includes updates in uiowa/uids#845.
- Figure out how to add a relevant sizing class based on the responsive image option that is selected.
- [x] How do we deal with `Small`, `Medium`, and `Large` image styles/view modes?
    - [x] Investigation
    - [x] Implementation
- [x] After completing the `<figure>` refactor [here](https://github.com/uiowa/uids/issues/844#issue-1519630880), rectify the changes in uiowa
- [x] Figure out how to refactor `align-ORIENTATION` to `inline--align-ORIENTATION`
- [x] Move inline sizing classes to the figure element. This may be done with something similar to `filter_caption_preprocess()`
- [x] [Contact tippie about pages like this](https://tippie.uiowa.edu/melissa-pepper-story-iowa-mba), perhaps see if Mara can convert these pages for tippie before the update?
- [x] Add new aspect ratio classes `media--16-9` and `media--21-9`.
    - [x] [Is this needing to be refactored?](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Plugin/Filter/FilterIframe.php#L86-L101)

<details>

- Example `@container (min-width: 768px) and (max-width: 855px) { .media--view-mode-large__* { width: 600px/65%}};`
- You can view an example of a container query like this at https://codepen.io/bspeare/pen/QWBKxzO (view in Safari or Chrome for it to work)
- Test this out in all the layout columns

</details>

**Comment by bspeare** [comment]
After talking this through with @pyrello, I have updated the proposed solution.

**Comment by briand44** [comment]
We will size this before pulling in as planned based on any scope changes when we complete https://github.com/uiowa/uids/issues/844

**Comment by briand44** [comment]
blocked until https://github.com/uiowa/uids/issues/844 is completed

**Comment by briand44** [comment]
We are not including the work to make callouts available for users in the WYSIWYG.

**Comment by joewhitsitt** [comment]
Left to do?


- [Contact tippie about pages like this](https://tippie.uiowa.edu/melissa-pepper-story-iowa-mba), perhaps see if Mara can convert these pages for tippie before the update?
  - In some cases it will be to set the image to original to fill the space regardless of viewport, but others it will be to adjust to a larger version of the current cropping.
  - https://github.com/uiowa/uiowa/issues/6074#issuecomment-1448733052
- Communications draft - Make mention of the non-entity WYSIWYG and the similar Tippie situation issues above?
  - There are non-entity WYSIWYGs https://github.com/uiowa/uiowa/pull/6120#issuecomment-1447100298, https://github.com/uiowa/uiowa/issues/6074#issuecomment-1448732143 that we are just going to note that folks take a look at after deployment
  - Though we are trying to address Tippie's issues, communicating the same situations and solutions so that others can make adjustments after deployment.
- Check how this affects tables
- Schedule deployment/update uids/approve percy/merge/???/profit

**Comment by joewhitsitt** [comment]
I am going to scan to see possible other WYSIWYG areas that might be impacted ^^ to see if we need to address in the update hook or just communicate about.

Update:

apr, directory profiles, articles and people header wysiwyg config would be affected. During grooming, it was decided to just mention these within the communication to fix after deployment.

**Comment by makurj** [comment]
I will test these locally and reach out to Nikki letting her know about the changes coming, so she can update these before it goes live. I will let her know nothing will break when this goes live, but will change visually.

**Comment by briand44** [comment]
should deploy off hours

**Comment by joewhitsitt** [comment]
Started a draft of comms: https://iowaweb.slack.com/archives/C0164FNN1PV/p1677620040955149

**Comment by joewhitsitt** [comment]
Desktop width table with large - widescreen left aligned
<img width="694" alt="Screenshot 2023-02-28 at 4 32 42 PM" src="https://user-images.githubusercontent.com/4663676/222000677-e26c9d2f-71c5-4442-bd4a-2ac8740187a2.png">
<img width="698" alt="Screenshot 2023-02-28 at 4 32 56 PM" src="https://user-images.githubusercontent.com/4663676/222000680-951ab885-6f0c-4353-b12e-886e340fa508.png">

iPad width table with large - widescreen left aligned
<img width="581" alt="Screenshot 2023-02-28 at 4 34 24 PM" src="https://user-images.githubusercontent.com/4663676/222000675-cc312c30-8f46-4a18-a2b2-1f0ea4a7f00d.png">
<img width="507" alt="Screenshot 2023-02-28 at 4 33 41 PM" src="https://user-images.githubusercontent.com/4663676/222000682-d5e0355a-a906-41eb-ae27-8085773180c5.png">

https://sandbox.prod.drupal.uiowa.edu/tables

Didn't do mobile because the table starts a horizontal scroll. The image for both PROD and LOCAL fills the cell. Does this look correct to folks? Obviously there could be an instance where they will want to remove alignment if they were previously expecting it to fill the width of the cell.

**Comment by pyrello** [comment]
> The image for both PROD and LOCAL fills the cell. Does this look correct to folks? Obviously there could be an instance where they will want to remove alignment if they were previously expecting it to fill the width of the cell.

This looks good to me. I don't think any further work is necessary at this point. If there are edge cases, they'll bubble up.

**Comment by GaryRidgway** [comment]
I would prefer if we removed the margin on images in tables, but I could live without it as well. I just think that, proportionally, that amount of REM takes up a fair amount of space.


![MarginTime](https://user-images.githubusercontent.com/23122142/222196013-2a935a9f-639a-4e29-835c-83555fddbbf3.gif)

**Comment by pyrello** [comment]
> I would prefer if we removed the margin on images in tables, but I could live without it as well. I just think that, proportionally, that amount of REM takes up a fair amount of space.

Follow up issue!

**Comment by GaryRidgway** [comment]
Ship it.

**Comment by bspeare** [comment]
Here are 3 separate issues that are blocking this work from moving forward:
- Implement container queries in `uids_base` with a bug fix for absolutely positioned items: https://github.com/uiowa/uiowa/issues/6386
- Fix the responsive images bug: https://github.com/uiowa/uiowa/issues/6263
- Media roadmap: https://github.com/uiowa/uiowa/issues/6262

**Comment by bspeare** [comment]
Closing this as not planned, but we will still want to reference the pr at https://github.com/uiowa/uiowa/pull/6120 when the above issues are resolved.
