### ISSUE TITLE
Clone VPMA site and provision for new Dean search

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#6087]
As a Kyle Hughes in office of the provost, I have a clone of the VPMA site provisioned for me to start crafting my College of Engineering Dean Search

Note:
- Eventual live URL will be engineering-dean.jobs.uiowa.edu

**Comment by joewhitsitt** [comment]
Perhaps this time, we clone first to a placeholder type site so that future clones of this winning formula of content won't have to be stripped of webform data, etc.

I imagine timing is important on this one but then maybe spend some more time looking into alternative "default content" type installs. https://github.com/uiowa/uiowa/issues/3473, https://github.com/uiowa/uiowa/issues/5418

**Comment by mjoneill** [comment]
I suspect it may be better to wait for Kyle to finish his work, then snapshot it and make that the default. VPMA is optimized for healthcare.  Kyle will have to undo some of that work and turn it back into east-side-of-river content.

**Comment by bspeare** [comment]
The new site has been cloned at https://jobsengineering-dean.prod.drupal.uiowa.edu/
- Users removed
- Articles deleted
- Kyle added as a user
- Webform submissions purged
