### ISSUE TITLE
OnIowa Development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6121]
# Story

As a site owner for oniowa.uiowa.edu, I would like my SiteNow v3 site to function similarly to our existing site so that we can continue promoting OnIowa in a similar fashion.

# Additional Information

They are planning on launching in May but won't create the events until sometime after that. Ideally we would deliver on these requests prior to July 1, 2023.

https://oniowa.prod.drupal.uiowa.edu - v3
https://oniowa.uiowa.edu - v1

# Proposed solution

- [x] Cancelled feature and badges on teaser and entity #5939 
- [x] #6364
- [x] #6402
- [x] Event type for Virtual, In Person and Hybrid - https://github.com/uiowa/uiowa/issues/5940?
- [x] #6469
- [x] #6365
- [x] #6363
- [x] #6607
- [x] #6608

**Comment by briand44** [comment]
I still need to break out these into appropriate sized slices. I think the API/feed can be one slice but not sure what is appropriate size for remaining items. Any feedback would be appreciated.

**Comment by joewhitsitt** [comment]
At some point we had JSON output of all of our default content types. I think we disabled it because was affecting one of our patches or something. I'd like to get back to that at some point which would allow more decoupled, content hub like functionality. Maybe this could be that initial slice back to that starting with the event content type.

**Comment by joewhitsitt** [comment]
Event status would handle cancelled events: https://github.com/uiowa/uiowa/issues/5939

**Comment by pyrello** [comment]
Capturing part of the conversation from grooming:
For ISWF, we put in place a category field for the event content type that is not part of the default. I *think* we did that because we eventually wanted to put in place categories that line up with schema.org's event categories. However, it seems like that constraint might be making actual development of a event categorization too complicated and difficult for people to actually adopt. So, I suggest that we bring some form of the ISWF functionality into the default event feature, possibly switching out a hardcoded list with a vocabulary and term reference field and updating ISWF at the same time.

**Comment by briand44** [comment]
Closing this. There is still one development item in process but that was never referenced here or discussed here so I don't see a need in keeping this open.
