### ISSUE TITLE
Implement a narrow article feature for the law journal sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6128]
# Story

As a Law Journal website owner, I would like to see our articles in a narrow container to increase readability for users.

# Additional Info

- The slice of turning on the narrow container for Law Journals and possibly Writing University should implement a feature split since there are multiple sites. (ilr.law.uiowa.edu, jgrj.law.uiowa.edu, writinguniversity.org)
- Include header area in scope of this based on mockups in https://github.com/uiowa/uiowa/issues/2784#issuecomment-1371369369.
- Need to account for css differences in this feature, possibly preprocess similar to other examples.
- We'll likely want to turn this on in a non-production environment and get approval before turning this on in prod.
- If we learn this is way too big once we get into it, lets discuss.

Epic https://github.com/uiowa/uiowa/issues/2784 

# Proposed solution

**Comment by bspeare** [comment]
Starting on this issue and I have a few questions.  Do we need an `articles_narrow` feature and a new custom module or do we just do the custom preprocessing in the `uiowa_articles` module after checking if the feature split is enabled?

**Comment by joewhitsitt** [comment]
If the goal is to eventually move this to the default, I am fine with the split check in uiowa_core or sitenow_articles temporarily.

**Comment by bspeare** [comment]
After working through the designs in https://github.com/uiowa/uiowa/issues/2784#issuecomment-1371369369, I think it might be best if we shifted our approach and set the articles narrow through a 67/33 layout instead of centering the entire layout. 

The benefits of this approach are:
- Creates a narrow line-length container for content area
- Moves most of the meta information to the sidebar putting the focus on the content area
- Keeps our page title and featured image designs consistent until we can offer further enhancements (see below)

Future enhancements that were originally in the mockup:
- Centered heading option
- Centered content area option with no sidebar
- Breadcrumb path that only displays parent item link
- Background color/pattern container options for page title


<img width="1449" alt="Screenshot 2023-02-06 at 10 30 03 AM" src="https://user-images.githubusercontent.com/1036433/217030134-85c39687-4dd1-45c9-afeb-bbaa0895fad5.png">



<img width="1528" alt="Screenshot 2023-02-06 at 10 32 19 AM" src="https://user-images.githubusercontent.com/1036433/217030123-514c2a27-1d46-4869-b09a-86b3700fae34.png">

**Comment by joewhitsitt** [comment]
@bspeare, with the info you got from @briand44 has this been turned on for those sites?

**Comment by bspeare** [comment]
I turned it on for ilr.law.uiowa.edu and notified Kate and Emily.   @briand44 if you are in communication with the other law customers, do you want to contact them?

**Comment by briand44** [comment]
I reached out to Hannah and Grace about jgrj.law.uiowa.edu
