### ISSUE TITLE
Add "subhead" field to default article content type

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6147]
- Outside the featured image
- Use intro-light class for styling
- Plain long text
- Need to consider blending into RSS feeds as one body

**Comment by cory-skeers** [comment]
Wondering if the subhead should be set as the "alternativeHeadline" in the schema, and then avoid trying to blending it in with the body for RSS feeds, and let the individual reader handle it or not.

"A secondary title of the CreativeWork." in https://schema.org/NewsArticle.

**Comment by joewhitsitt** [comment]
thanks for thinking about the schema.org relationship. i think it could be put there for now and if we find out it should be something different, i think it is easy to re-map. not sure if these are being written as an alternative headline though. seems more like an expansion on the headline or a transition before the lead of the article.

as always, I am curious if @mjoneill has thoughts on the schema.org mapping for this.

also, not sure how it relates to the RSS feed. the schema.org markup is not sent in the RSS feed. i can ignore the RSS bit for now because it is currently title/teaser that is sent. but eventually we will have summary/body trimmed #5025 instead and that will complicate how it is read by the user if is supposed to be read as a transition paragraph.

**Comment by cory-skeers** [comment]
> also, not sure how it relates to the RSS feed. the schema.org markup is not sent in the RSS feed. i can ignore the RSS bit for now because it is currently title/teaser that is sent. but eventually we will have summary/body trimmed #5025 instead and that will complicate how it is read by the user if is supposed to be read as a transition paragraph.

Ah, shoot. Bad assumption on my part.

**Comment by cory-skeers** [comment]
Couple questions here. @mjoneill and @mkyoder I'm especially interested if you have thoughts on the latter two for where to map the "subhead" and whether we should continue to use "NewsArticle" or change to "Article."

- First, looks like we currently have Articles set up for schema.org mappings through Metatag, and enabling the Schema.org module ends up with two versions in the Source. 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/49074566/217023711-65f9fb32-cc58-4238-bd3a-d067695b8c7c.png">
That seems off, even if it's not technically a problem, but it also has the added complication that editors can edit the Metatag settings but not the schema.org, so there's potential that these wouldn't match, unless we disabled the ability to change it through Metatag.
    - And it looks like People currently are using both?
  
- I was thinking the subhead would map to the "alternativeHeadline" schema. It seems the best fit for things like https://now.uiowa.edu/2023/02/10-tips-beating-winter-blues or https://clas.uiowa.edu/news/dance-gala-returns-hancher-themes-mental-health-inclusivity. But I'm curious what people closer to content might think.
  - This is an optional mapping if we enable Schema.org, but not available by default in using Metatag.
- Article schema is currently using "NewsArticle", but I'm wondering if maybe "Articles" would be a better fit. https://schema.org/NewsArticle vs https://schema.org/Article. As my understanding goes, NewsArticle is a subset of Articles related specifically to "news," which I'm not sure fits our use cases. This would only effect the categorization; all the actual fields map the same either way.

**Comment by mjoneill** [comment]
> multiple identical schemas on the page

That’s noise.  We’re going to want to have 1.  I’d be curious to know what the tradeoffs of one over the other are.

**Comment by mjoneill** [comment]
> I was thinking the subhead would map to the "alternativeHeadline" schema.

I think that’s likely an element mismatch.  That’s not really an alternative headline…so it’s not the right fit.  Not a huge problem if we do it however. Purists will argue.

**Comment by mjoneill** [comment]
> NewsArticle vs. Article

NewsArticle is a subtype of Article.  When in doubt, go broader (Article).  I suspect that there is content on IowaNow that’s not strictly NewsArticle.

However, it is kind of unusual that content editors have to choose one and can’t change it.  Typically I’d expect a selector so that the correct type of schema for the content is applied.  If they don’t make a selection, then again, the more general type (Article) would be the correct default.  

Article SubTypes (currently) include: 

- [AdvertiserContentArticle](https://schema.org/AdvertiserContentArticle)
- [NewsArticle](https://schema.org/NewsArticle)
- [Report](https://schema.org/Report)
- [SatiricalArticle](https://schema.org/SatiricalArticle)
- [ScholarlyArticle](https://schema.org/ScholarlyArticle)
- [SocialMediaPosting](https://schema.org/SocialMediaPosting)
- [TechArticle](https://schema.org/TechArticle)

**Comment by joewhitsitt** [comment]
>However, it is kind of unusual that content editors have to choose one and can’t change it.

It is possible if we capture it from the editor. Right now we are headed down the path with two approaches. We have the "SEO Settings" article schema.org settings available on the article content type and then we have the field-based approach (set it and forget it) where we map certain fields automatically to generate the schema.org markup. We have an issue to dial this in but for now we have been trying to cover the content type with both. Way back when, we set NewsArticle as the default for the SEO settings, but we can modify that if necessary.

https://github.com/uiowa/uiowa/issues/5933

<img width="514" alt="Screenshot 2023-02-07 at 8 31 52 AM" src="https://user-images.githubusercontent.com/4663676/217273424-b64f2029-932f-4074-9ed0-f45f79589db7.png">

**Comment by cory-skeers** [comment]
> That’s noise. We’re going to want to have 1. I’d be curious to know what the tradeoffs of one over the other are.

Joe covered this well: "We have the "SEO Settings" article schema.org settings available on the article content type and then we have the field-based approach (set it and forget it) where we map certain fields automatically to generate the schema.org markup."

Additionally, there are certain properties that might be covered in one and not the other. If we used `alternativeHeadline`, for instance, it's not available in the editor-controlled version. 

Also for clarity, In production for Articles, there is currently only one markup generated. It's part of this work and adding an extra field that's leading to the double.

> I think that’s likely an element mismatch. That’s not really an alternative headline…so it’s not the right fit. Not a huge problem if we do it however. Purists will argue.

Is there a better fit for it? I didn't see anything that was more suitable. Alternatively, do we want/need to include it in the schema?

> NewsArticle vs. Article

For this part, as long as we continue using Metatags with the editable approach for Articles, it's selectable but defaults to NewsArticle. I guess the question is more should we update the default to Article going forward, or leave it defaulted to NewsArticle as likely the most common use case, and leave it to the editor to change it if otherwise. Since the field is kind of buried, I would expect that more often than not, outside of certain super users (and not always then) it's not going to be changed from whatever we default to.

**Comment by cory-skeers** [comment]
Maybe the schema/meta discussion should move to part of #5933 and prioritizing that as an audit/cleanup, so it doesn't hold this piece up.

**Comment by mjoneill** [comment]
> > However, it is kind of unusual that content editors have to choose one and can’t change it.
> 
> It is possible if we capture it from the editor. Right now we are headed down the path with two approaches. We have the "SEO Settings" article schema.org settings available on the article content type and then we have the field-based approach (set it and forget it) where we map certain fields automatically to generate the schema.org markup. We have an issue to dial this in but for now we have been trying to cover the content type with both. Way back when, we set NewsArticle as the default for the SEO settings, but we can modify that if necessary.
> 


All things being equal, I’d prefer the approach where users _could_ get in there and specify the exact values for various elements (if they wanted).  If they didn’t, it would pull some defaults and populate.  However, all things are seldom equal.
