### ISSUE TITLE
Make the "In this Section" label customizable

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6164]
Make the "In this Section" label customizable in the horizontal menu so user can enter whatever text they want. The default would be "Section Menu".

Old Issue: https://github.com/uiowa/uiowa/issues/6090

**Comment by pyrello** [comment]
We'll need to add a field and store the variable in the block/component third party settings.

**Comment by bspeare** [comment]
Summary of work completed: in https://github.com/uiowa/uiowa/pull/6353, we ended up exposing the `menu_block` "Use as title" options to set alternative label options.  We decided to not make it truly "customizable" so that we could keep the UX labeling consistent based on the `Fixed menu parent title`, `Active item's title`, `Active item's parent title`, and `Active item's root title` to avoid human error that would come from an open text field.
