### ISSUE TITLE
Prepare for external Sitenow v3 demo - Thurs, 2/9

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6165]
>We’ll share our low code/no code platform, show the editor interface, answer questions, etc…

- Michael provides brief introduction
- Editorial experience (layout builder "as a site editor...create a page")
- Could be questions about development practices/workflow
  - Multisite config management strategy

If there is prep-work, we should try to plan time to prepare.

Add suggested topics here:

- Config management
- Design system

Volunteers to speak to a specific part vs be on-hand for questions:

- joe (general questions)
- cory (find text, on-deck for questions re: migrations and p2lb)
- makur (campus collab)
- sean (config management)
- alan (layout builder interface)

**Comment by joewhitsitt** [comment]
In grooming we deemed preparation for this task times the number of folks speaking puts this in the "medium" range

**Comment by joewhitsitt** [comment]
Jotted these down:

- Intro (our team and how campus works with us)
- Our hosting setup (Acquia cloud with poor-mans SiteFactory (mono public repo deployed to multiple applications running a Drupal 9 multisite))
- CS2 consists of default, environment, feature and site splits. https://github.com/uiowa/uiowa/issues/6165#issuecomment-1421920229
- Single theme powered by a design system and customized per site/feature using yarn workspaces.
- Layout builder after trying Paragraphs (p2lb plan to move off completely)
- Layout builder comprised of block plugins, block content, layout builder styles/restrictions and extended ctools views all looking pretty due to the design library.
- Phasing out D7 slowly like everyone else.

**Comment by joewhitsitt** [comment]
I wonder if folks have specific pages on sandbox that are put together nicely that could be shown/modified in this demo.

**Comment by mjoneill** [comment]
I’ve pulled together a (still rough) deck to cover some intro material and then segue into the Stories.  So far we know there is interest in seeing/understanding the editorial experience (what it’s like for an editor to create pages/sites using layout builder) and additional interest in technical architecture.  

I think this gives a lot of latitude in what we want to cover.

Anyone on the team should be able to edit/add:

https://iowa-my.sharepoint.com/:p:/g/personal/mjoneill_uiowa_edu/Eb6_EPErw9xNopeyQ6Gyjb0Bvi0V_WZzMtyndvZbpEeOHQ?e=muzIcn

**Comment by pyrello** [comment]
Configuration Management notes

- SiteNow mostly uses a managed configuration strategy. That means that we commit most of our configuration to our repo and that configuration is the point of truth for how the system works.
- We use Config Ignore to allow per-site overrides of the very few things we allow that for.
- Most of our sites run on the SiteNow platform without customizations.
- Customizations are handled using the Config Split module. Internally we define two types of config splits for site customization:
	- Feature splits - Can be shared between multiple sites. These typically define new functionality that is packaged together around a central premise. Typically a new content type and the fields, view and form displays, and views that make them useful.
	- Site splits - Limited to just a single site and set up in such a way that it is impossible to register more than one with a site (through single machine name for all site splits). Site splits define some new functionality and alter existing functionality. They are most often used for adding fields to existing content types or defining views that are very purpose-specific.
- Feature splits can be applied in tandem. Site splits can also be applied alongside features splits.
- We write custom modules to handle logic that is specific to config splits and part of the config split definition is turning on the custom module.
- When we need to change configuration to define features and functionality differently, we do that work locally, then export and commit the changes. 
- Update hooks are required to sync up content with configuration changes. We write a lot of them. We've developed a helper function for writing update hooks for updating layout builder block content, since that is the most complicated thing we do regularly to update content.

**Comment by pyrello** [comment]
I updated instances of "Sitenow" to "SiteNow" in the slides where I found them to be consistent with our product branding.

**Comment by makurj** [comment]
I am happy to answer any questions/talk about campus collaboration, from a non-OSC team member's perspective.

**Comment by GaryRidgway** [comment]
I will be doing:
- Layout builder interface Demo
- A talk about our usage of a design system

**Comment by cory-skeers** [comment]
I've been updating the issue summary as people have brought up topics. Has a mix of both presentation plans and availability for questions.

**Comment by pyrello** [comment]
# Layout Builder setup
- We use Layout Builder in two different ways: As content type "templates" that define the layout for every piece of content of a particular node type; and to allow per-item customizations for page content.
- To be able to accomplish the types of layouts we want, we had to make a decision to incorporate the breadcrumbs, page title, and content moderation into our layouts (instead of using the global block system). This is no big deal for content types where we are only using Layout Builder as a template (not editable by content editors). But gets trickier with our page content type where the layouts can be edited by a content editor.
- Our starting page Layout Builder template works for basic page content (not using per item customization).

## Modules
- Layout Builder Direct Add - Provides a widget for selecting the component being added directly from the layout without having to open the sidebar.
- Layout Builder Lock - Allows you to "lock" a section in a variety of ways. We use this to "lock" our moderation control section so that nothing can be added before it (first element on the page), no other blocks can be added to it, and the content moderation control block can't be removed from it. Similarly locks the default header section if it hasn't been removed.
- Layout Builder Operation Link - Adds a "Layout" link for appropriate content on the content administration page.
- Layout Builder Restrictions - Allows you to limit which blocks and layouts are available for a given entity (node) type. We use this to filter out core layout templates (which we don't use) and all the various system-provided blocks that we don't want people to be able to place.
- Layout Build Shortcuts - Allows for double clicking a block to go to its edit screen.
- Layout Builder Styles - Provides a flexible framework for building style options for blocks and sections and using them to apply classes to the relevant HTML element.

**Comment by pyrello** [comment]
I think we can close this?
