### ISSUE TITLE
Image styles not rendering locally

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6213]
# Problem
When a site is synced down, the image crop used on the prod site works, but some new crops don't render locally, even if you upload a new image.

Example: https://tippie.uiowa.ddev.site/melissa-pepper-story-iowa-mba 

# Steps to reproduce
1. Sync down tippie.
2. Go to https://tippie.uiowa.ddev.site/melissa-pepper-story-iowa-mba
3. Change the image at the top of the page to original, that works.
4. Change to `Full - no crop`, it does not render the image. Same with `Full - widescreen`, etc.
5. The same behavior occurs even if you upload a new image with the same name.

Also, https://github.com/uiowa/uiowa/pull/6120#issuecomment-1442361602

# Proposed solution

**Comment by joewhitsitt** [comment]
Can't reproduce with uploading a new image locally.

I can reproduce with stage_file_proxy remote images because either stage_file_proxy downloads the generated image style being viewed or hotlinks the file from PROD. In either case, it does fetch the original image, so any further triggers to generate a new style without the original with fail (broken image).

<img width="517" alt="Screenshot 2023-03-01 at 10 06 09 AM" src="https://user-images.githubusercontent.com/4663676/222195679-8578b822-7410-4704-b83a-ff6574e68693.png">

rsync files will pull original images to use and solve https://github.com/uiowa/uiowa/pull/6120#issuecomment-1442361602

I think this is working as expected.

**Comment by makurj** [comment]
If I upload an image with the same name as the original through LB, then the issue persists. If I upload the same image with a new name or a completely different image, then the issue no longer exists.

**Comment by joewhitsitt** [comment]
>If I upload an image with the same name as the original through LB, then the issue persists.

Replace file or separate upload?

**Comment by makurj** [comment]
Separate upload through LB WYSIWYG in text area.

**Comment by joewhitsitt** [comment]
So you removed the previous image from the text area and uploaded/selected your new upload (same file name but new fid)?

**Comment by makurj** [comment]
Yep, same file, new file name.

**Comment by makurj** [comment]
Retried and the styles are rendering fine locally. If this comes up again, will re-open issue and capture screen.
