### ISSUE TITLE
Custom metatag functionality for regents sites

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6232]
# Story

As a site owner of a SiteNow v3 website using regents theme option, I would like to still have the ability to adjust the metatag information.  

Our default metatag information has custom favicons and title: https://github.com/uiowa/uiowa/blob/main/config/default/metatag.metatag_defaults.global.yml#L12.   We will need a way for regents site owners to adjust the title and favicons.

**Comment by joewhitsitt** [comment]
Good catch. This reminded me of https://github.com/uiowa/uiowa/issues/859#issuecomment-614193528 where we could identify instances where we needed to adjust the top SEO settings but didn't want to completely open it up. Regent sites might be a different situation, but maybe it is just some permission adjustments.

**Comment by briand44** [comment]
Grooming conversation... Do we have schema markup referencing the University of Iowa on all sites?

**Comment by joewhitsitt** [comment]
>Do we have schema markup referencing the University of Iowa on all sites?

I think we stopped short of doing that.

og_title also has University of Iowa appended.

All of this is currently stored configuration, so permissions aside, this means site/feature split OR moving metatag info (full or partial) to ignored

**Comment by cory-skeers** [comment]
Getting a general writeup of another option, limiting the amount of config that would need to be split (probably needs some edits/tweaking)

Config to set values such as:
`org_name: The University of Iowa`
`path_to_favicon_assets: /profiles/custom/sitenow/assets/`
Code to map that config to tokens
Replace those elements with their tokens in the existing metatag config
Config splits just the config above instead of metatag

**Comment by pyrello** [comment]
Related to the option specified in the previous comment, here is an example where we are creating a token already: 
https://github.com/uiowa/uiowa/blob/740309e8c82b655210a5083e9a4acce935b022db/docroot/modules/custom/sitenow_people/sitenow_people.module#L964-L1020

**Comment by joewhitsitt** [comment]
I think that would work in that narrow use-case. A situation I brought up with Sean in DM however is what if they needed to populate other fields like the homepage does since they are their own org? The list of tokens expands?

[config/sites/uiowa.edu/config_split.patch.metatag.metatag_defaults.front.yml](https://github.com/uiowa/uiowa/blob/main/config/sites/uiowa.edu/config_split.patch.metatag.metatag_defaults.front.yml)

**Comment by joewhitsitt** [comment]
It was also mentioned in grooming that we need a place for the favicon related files to live. We thought that the managed file system in drupal is not desirable because they would show up in media and that we don't currently allow extensions like .ico and .webmanifest. rsyncing or a theme settings upload field to a specific directory within /files was talked about.

**Comment by briand44** [comment]
Grooming conversation... Seems like this comment represents what we've discussed as a first pass forward. https://github.com/uiowa/uiowa/issues/6232#issuecomment-1487470741

Let's commit to the minimum needed for the few sites we are aware of.

**Comment by pyrello** [comment]
If we don't build a UI for this, we'll need to actually set the variables in the DB that are used by the tokens.

**Comment by joewhitsitt** [comment]
I think the initial token work is done. Starting to look into how best to manage alternative favicons or the thinest slice. I think rsync is possible if we figure out the right chmod settings for the directory and contents.

**Comment by joewhitsitt** [comment]
Resolved by #6378 and #6367
