### ISSUE TITLE
Run Iowa Now News Migration in Dev

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6241]
# Story

As an Iowa Now website owner, I would like to see our news migrated in our development environment after all the changes have been put in place so we can review and get them onto the prod site.

# Additional Info

# Proposed solution

- [x] Sync from prod to dev for both d7 and d9 sites and run the migration again
- [x] Let partners know this is available in dev for review again.

**Comment by briand44** [comment]
lets plan to sync prod db to dev prior to running migration in dev. Sync files down as well. Migration will skip migrating files that already exist.

**Comment by joewhitsitt** [comment]
similar to the other migration work for IowaNow, a smaller query to test against would be super nice

**Comment by cory-skeers** [comment]
> lets plan to sync prod db to dev prior to running migration in dev. Sync files down as well. Migration will skip migrating files that already exist.

Also a reminder that the d7 site needs to be synced from prod to dev as well. The migration connections only work dev to dev, prod to prod.

**Comment by cory-skeers** [comment]
A couple samples so far from the Achievements migration with the current updates in #6257 

These are with `image--align-medium` as the default, but we may want to adjust to small. The sources provide the alignment, but don't have any indication of size, so a migration-wide option needs to be provided.

Source
<img width="703" alt="image" src="https://user-images.githubusercontent.com/49074566/225138998-49985d9d-1db9-4a7d-ab83-21e9512e6047.png">
Destination
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/49074566/225139299-e7d3e1f7-cfaf-4f87-aab5-096eccd39e4e.png">

Source
<img width="581" alt="image" src="https://user-images.githubusercontent.com/49074566/225139731-5bc94ea6-45fa-4c0d-ad25-eedc348176a3.png">
Destination
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/49074566/225139819-30097a87-792a-48db-a006-8fb9640bf142.png">

And lastly, a bit of an edge case for the headline construction logic that needs to be accounted for, and check to make sure the `<strong>` element is at the beginning, otherwise don't make a headline out of it.
Source
<img width="703" alt="image" src="https://user-images.githubusercontent.com/49074566/225139148-d6d8bb02-b81d-4d0e-bb2d-55c3d037c34f.png">
Destination
<img width="960" alt="image" src="https://user-images.githubusercontent.com/49074566/225139202-4d1cf8ef-461c-4c8e-938c-323f439ba279.png">

**Comment by briand44** [comment]
Scoping this slice to just syncing both to dev and running migration and letting our partners know that it is available for review.

**Comment by briand44** [comment]
blocked based on https://github.com/uiowa/uiowa/issues/6018

**Comment by cory-skeers** [comment]
This has been run in dev on 2023/03/27 and partners notified.
