### ISSUE TITLE
ISWF Events: Presenters in a dropdown

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6413]
Mike Cranston: https://iowasummerwritingfestival.prod.drupal.uiowa.edu/events First question…   On the search filter on the Events page, they thought the “Presenters” field would be a drop down of all the presenters. I explained that it doesn’t appear it was set up that way, but if you start typing in the field, it does bring up suggestions to choose from. They would like to know if it can be changed to a drop down with all the names. I told them I would check.

Also see #6414

**Comment by GaryRidgway** [comment]
From parking lot: When coming to the site, there are two options:
1. You know the presenter
2. You do not know the presenter.

In case 1, if you do know the presenter, then an autocomplete is better, because you can just begin typing letters and find the person you want.

In case 2, you aren't searching for an event by presenters, so then there is no reason to interact with the presenter filter.

Therefore, the best widget is an autocomplete, IMO

**Comment by makurj** [comment]
Closing this after hearing back from Mike: "I spoke with them after sending the initial email to you think I’ve decreased their concern about not having the presenters listed in a dropdown. I offered the same concerns you brought up. I agree, the autocomplete seems to be the best option – they either know the presenter or don’t. If they don’t, they’re probably not going to use the “Presenter” filter."
