### ISSUE TITLE
Classroom guides on teach.its

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6420]
# Story

As an owner of teach.its.uiowa.edu, I would like a more user friendly way of displaying classroom guides so that users can more easily find the guide they are looking for.

# Additional Info

https://itsteach.prod.drupal.uiowa.edu is their v3 site they are working to transition to. They would like to launch by August 1st.

They currently have just a long list of titles that link to each guide https://teach.uiowa.edu/classroom-guides

Here is an example of a potential classroom guide page https://itsteach.prod.drupal.uiowa.edu/art-building-west-116-classroom-guide. They have ~30 different possible fields/sections.

They could be open to other ways of handling this but they said they would be happy with having a search filter to search by title.

# Questions

Do we need a separate content type for these or is there a way we can make this work using the basic page content type and denoting specific pages as classroom guides?

# Proposed solution

**Comment by bspeare** [comment]
For the actual guide (https://itsteach.prod.drupal.uiowa.edu/art-building-west-116-classroom-guide), I think we should look at the search analytics and adjust the design hierarchy based on the most viewed content on the guides. 

A couple of ideas for the long list page https://teach.uiowa.edu/classroom-guides:

- Create an A - Z anchor list to break up the content and make it easier so scan as a user. 
- Use something like the "Scholarships Jump Menu" from https://admissions.uiowa.edu/finances/scholarships.  It might be great to offer a custom jump menu block for the service or add it as an addon to the search block?
  - If they had a jump menu, users could select a building to go to a page with guides listed only for that building. 
<img width="493" alt="Screenshot 2023-05-15 at 3 31 48 PM" src="https://github.com/uiowa/uiowa/assets/1036433/5029b73f-da58-46e3-82a6-d8335b4b9e39">

**Comment by bspeare** [comment]
In grooming we talked about: 
- Using a webform block like on https://wellbeing.prod.drupal.uiowa.edu/ to create a jump menu.
- A listblock for the "page" content type with exposed filters for title search and tag filtering. 
- Featured content block with exposed filters for title search and tag filtering. 

Could we rebuild the featured content block to be a views list block?  I like the idea of the featured content block because users could make use of the source link field in the article and there would be enough options between the two content types that we wouldn't need an "areas of study" like feature.

**Comment by joewhitsitt** [comment]
>Could we rebuild the featured content block to be a views list block?

i think we could deprecate the featured block if we don't like it anymore. if it was replaced by a view, i am not sure how we would be migrate existing (manual selected nodes of different types in arbitrary order)? Speaking of deprecated blocks, should we finally kill off hero and separator?

if we move forward with a view, i'd love to add sort by tag functionality... https://github.com/uiowa/uiowa/issues/4135

**Comment by pyrello** [comment]
Capturing some details about an idea we just discussed:
- Create a new node type called "Resource link" or something similar.
- The purpose of this node type is to handle the case where content editors want to have a list of content with titles, image, teasers, but that link to an external link or an internal resource (like an article, page, or media element).
- Someone mentioned that there are content editors that are essentially using the article content type to set up a redirect to a page or external resource. The Resource Link would be a generic way of doing that without having to tap into the rest of the article content types features.
- This content type is essentially a redirect + meta/teaser data.
- Because its a node, it can appear in lists and play nicely with existing content types.

**Comment by briand44** [comment]
We discussed recommending basic pages and tags for now and in the future enhance by adding a page list block and exposed filters for list blocks so they could search by title and filter by tag
