### ISSUE TITLE
91st Meridian - List of writing by person view

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6451]

**Comment by maramcconnell** [comment]
### Story
As an owner of the 91st Meridian website, I would like to display a list of links to a writer's works on a writer's person page so that site visitors can easily find works written by a specific writer.

### Additional Information
Customer Request: "For the separate pages (or the “content type”) that are only the writer’s bio, I would link to all of the pieces contributed by that author"

Example: https://uipress.uiowa.edu/people/matthew-j-c-clark

**Comment by joewhitsitt** [comment]
Duplicate of https://github.com/uiowa/uiowa/issues/4261 since writings are articles

**Comment by briand44** [comment]
Closing this in favor of #4261
