### ISSUE TITLE
Housing site duplicate

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6453]
# Story

As a web team member presenting at Higher Ed Web, I would like a copy of the Housing website that I can make changes to without affecting the live site so that I present during the conference.

# Proposed solution

- Syncing the site to STAGE and block access
- Let Megan know!

**Comment by joewhitsitt** [comment]
Syncing the site to STAGE and block access (drush users:toggle) then add Megan back seems the simplest

**Comment by mkyoder** [comment]
@briand44 As an update to this, the housing team is currently considering removing this custom page (https://housing.uiowa.edu/residence-halls). I advised housing to reconsider the removal of this page for several reasons. 
 
I would like to be able to demonstrate the custom work the team did on this page in my presentation. If housing decides to remove this page, it is possible to duplicate the site sooner rather than later?

**Comment by briand44** [comment]
I updated the priority.

**Comment by joewhitsitt** [comment]
@mkyoder this is done.

https://housing.stage.drupal.uiowa.edu/ (blocked all users except you and user 1)

did not sync private files (webform submission files)
