### ISSUE TITLE
Find text can run out of memory and error out

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6552]
# Problem
SiteNow Find Text can run out of memory.

# Steps to reproduce
https://onenr.io/0BQrxp4ynRZ

# Proposed solution
~Update the `searchButton` callback to exit early if the `needle` is less than 3 characters. The form validate function can be left in place to add the actual error, but this will prevent the processing from (wrongly) occurring.~
Update is in place in https://git.drupalcode.org/project/find_text/-/commit/781ad170f30860c1e22c8515299ddfdb88251219

Next steps--create a release for Find Text, then update composer to pull in the newly updated version.

**Comment by briand44** [comment]
may need to batch query and/or results

**Comment by briand44** [comment]
I think I triggered this error somehow? There is a 3 character limit in place currently

**Comment by briand44** [comment]
I can submit the form without any text. If I enter a single character, I get form validation errors but I still get results.

**Comment by briand44** [comment]
follow up issue would be to prevent out of memory errors altogether, scope this to solving validation bugs.

**Comment by cory-skeers** [comment]
Looked into this a little bit, and it looks like a bad combo of using the validate function with an AJAX callback. The validation is there and gets called, preventing a "submit," but because the results calculation and table display all happen as part of the AJAX callback, it fires regardless.

I'll update the proposed solution.
