### ISSUE TITLE
GA4 migration

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#6555]
- [x] Migrate all these sites' UA to GA4

![Image](https://github.com/uiowa/uiowa/assets/52135878/1efb6adc-fb11-413f-b0ea-81c4bd7e11e6)

- [ ] Add GA4 IDs to D9 sites
- [ ] Export old UA data

**Comment by makurj** [comment]
Need more info about clip.grad.uiowa.edu before migrating its property. @johnriehl1971

**Comment by johnriehl1971** [comment]
I haven't see this website before. Is it one of ours?


John Riehl
Web Content Strategist, Graduate College
420 Gilmore Hall, Iowa City, IA 52242
Office: 319-384-1309, Mobile: 319-430-9419
www.grad.uiowa.edu<http://www.grad.uiowa.edu/>
[The University of Iowa]

From: makurj ***@***.***>
Sent: Thursday, June 15, 2023 2:56 PM
To: uiowa/uiowa ***@***.***>
Cc: Riehl, John C ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [uiowa/uiowa] GA4 migration (Issue #6555)


Need more info about clip.grad.uiowa.edu before migrating its property. @johnriehl1971<https://github.com/johnriehl1971>

-

**Comment by makurj** [comment]
No idea. It was listed in our Google Analytics account:

![image](https://github.com/uiowa/uiowa/assets/52135878/a1b48a59-5b1d-49d2-906b-475896aace9c)

Leaving it alone for now.

**Comment by mjoneill** [comment]
FYI: the URL field in the Google Analytics setup does not always correlate
with the properties that it's actually deployed to. This is because Google
Analytics can be deployed to multiple properties, and the URL field only
reflects the property that was used to create the tracking code.

A more reliable way to see where Google Analytics is deployed is to look at
page views and add a second dimension of hostname in GA reporting. This
will show you the hostname of each page that has been viewed, which can be
used to identify the properties that are being tracked.

Michael

(Ps: text revised by Google Labs AI integration)

**Comment by makurj** [comment]
Thanks, Michael. Also, doesn't look like a busy site.

![image](https://github.com/uiowa/uiowa/assets/52135878/4d9ea460-cbf8-4d64-85ac-fc1f81518b79)

**Comment by joewhitsitt** [comment]
Couldn't help but listen in (gh notifications) - clip.grad.uiowa.edu redirects to https://carnegielibrariesiowa.org/ so is GA work even necessary for clip.grad?

**Comment by makurj** [comment]
> Couldn't help but listen in (gh notifications) - clip.grad.uiowa.edu redirects to https://carnegielibrariesiowa.org/ so is GA work even necessary for clip.grad?

I'd say no. I think I'll leave it as is for now and continue migrating the GC ones I know about.
