### ISSUE TITLE
Probe scheduling node content

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6585]
# Story

As a web team, we would like to understand if and how we can move forward with scheduling node content to be published/unpublished.

# Additional Information

Probe https://www.drupal.org/project/scheduler and https://www.drupal.org/project/scheduler_content_moderation_integration and understand if we want to move forward with those modules or something custom that is not based off cron.

There are concerns with our cron process and if implementing this for default content types would cause performance issues or errors.

The current request related to this is to allow scheduling SiteNow alert content to be published/unpublished.

#723 

# Proposed solution

- Probe https://www.drupal.org/project/scheduler and https://www.drupal.org/project/scheduler_content_moderation_integration 
- Understand if `Scheduler provides drush commands to run Scheduler's lightweight cron` helps address our cron concerns
- Determine recommendation for moving forward with scheduling alert content and potentially other content in the future.

**Comment by briand44** [comment]
Grooming convo... We'll need to use the drush command or some other mechanism (e.g. curl) to trigger rather than undoing our current cron offsets.

**Comment by pyrello** [comment]
> Understand if `Scheduler provides drush commands to run Scheduler's lightweight cron` helps address our cron concerns

What exactly are our cron concerns? In reading through #723 I'm not clear if it is a resource issue or we're worried that the last cron job won't be done running before the next one runs

**Comment by joewhitsitt** [comment]
I think if this is a facilities only thing, I am not too worried. Originally #723 was meant for all sites for like scheduling article content.

I think my concerns are:

- Given the offset scheduled jobs, is there a possibility of the cron runs conflicting (a uiowa app site, running this and regular cron at the same time on the hour)
- If more than one website had this lightweight cron triggering on the hour or whatever, will there be performance issues (e.g. out of memory issues for uncached requests on other websites)?

The background I am coming from is that IowaNow used to have a noon Rules based job on D7 that would bring down sites. Additionally, Rick implemented these offset cron runs in the first place so that not every site runs on the hour (same hardware) because he had concerns about the impact.

So far our scheduled jobs have been site specific and function specific (not cron) and there are only 3 of them (brand, classrooms, facilities).

So understanding how "lightweight" it is compared to normal cron would help me feel better about expanding our use of this.

**Comment by pyrello** [comment]
> I think if this is a facilities only thing, I am not too worried. Originally https://github.com/uiowa/uiowa/issues/723 was meant for all sites for like scheduling article content.

My understanding of this probe is that we are trying to understand both the immediate request for scheduling alert content and the longer term possibility of scheduling other types of content. So limiting it to just facilities might be okay for the short term but doesn't help inform the longer term possibilities.

> Given the offset scheduled jobs, is there a possibility of the cron runs conflicting (a uiowa app site, running this and regular cron at the same time on the hour)

As far as I can tell, we are running cron on every application and every site. From my testing so far, it appears as though running cron or running the "alternative to cron" causes nodes to publish/un-publish. I think the cron alternative is meant for situations where you are not running cron already.

> If more than one website had this lightweight cron triggering on the hour or whatever, will there be performance issues (e.g. out of memory issues for uncached requests on other websites)?

The previous comment is relevant to this, but I think maybe the concern would be the same regardless of whether this is being triggered by cron other the alternative. That being said, I'm not sure I understand exactly what the concern is here. Publishing previously unpublished content would likely involve a hit for that item not being cached previously, but I'm not sure how you get around that. Is there a concern about other content that is unrelated having its cache cleared?

> The background I am coming from is that IowaNow used to have a noon Rules based job on D7 that would bring down sites.

Am I understanding that because of this previous instance, there is a concern about adding any sort of extra cron tasks?

**Comment by joewhitsitt** [comment]
During EoD, we were still unsure what the lightweight cron consisted of.

```
/**
   * Run the lightweight cron.
   *
   * The Scheduler part of the processing performed here is the same as in the
   * normal Drupal cron run. The difference is that only scheduler_cron() is
   * executed, no other modules hook_cron() functions are called.
   *
   * This function is called from the external crontab job via url
   * /scheduler/cron/{access key} or it can be run interactively from the
   * Scheduler configuration page at /admin/config/content/scheduler/cron.
   * It is also executed when running Scheduler Cron via drush.
   *
   * @param array $options
   *   Options passed from drush command or admin form.
   */
```
https://git.drupalcode.org/project/scheduler/-/blob/2.x/src/SchedulerManager.php#L816

https://git.drupalcode.org/project/scheduler/-/blob/2.x/scheduler.module#L1009-1012

**Comment by pyrello** [comment]
Summary of findings:
- Functionally, the module provides what we need, which is the ability to queue a node to be published on or after a particular time.
- The module provides a lightweight alternative to cron, which includes a URL to trigger a drush command which is just the scheduling job. However, there is no mechanism to exclude the scheduling job from an existing cron run. All of our sites have a cron run scheduled hourly.
- The presentation of the publish/un-publish setting don't exactly line up with what we would be able to provide. The form widgets provide granularity down to the minute or second, but at best we could only provide 1 hour windows during which an item would be published. 
- To move ahead with this for the alerts feature (which would only be live on the facilities site for the. time being) we probably can just have the customer use it as is with the understanding that their alerts will be published within one hour of when it was scheduled.
- If/when we expand this functionality (more sites turn on the alerts feature or we provide the ability to schedule publishing of additional content types) we may want to alter the form widget to allow selection of 1 hour windows so there is less chance of confusion on the part of the user.
- The [scheduler_content_moderation_integration](https://www.drupal.org/project/scheduler_content_moderation_integration) module isn't strictly necessary yet because we haven't added content moderation to the alerts content type yet. We would want to add that module if/when we add content moderation to the alerts content type.
- Going forward with using these modules for now represents the least amount of work to be done to provide value the soonest.
- It also provides us the opportunity to continue to evaluate whether this is the best route forward for eventually being able to schedule publishing other content or whether we want to invest in another option.
- We may want to discuss with facilities the possibility of us rolling this out then discovering that it is using too many resources or running too long and causing downtime issues for their site or other sites. How would we respond to that? Would they be okay with temporarily having to manually schedule alerts if while we built another solution?

**Comment by pyrello** [comment]
Closing this based on above findings.
