### ISSUE TITLE
CCOM Provisioning

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6615]
# Story

As a member of the UIHC MarCom team, I would like to understand the site provisioning process and be able to provision sites so that we can start learning SiteNow processes and tools and avoid adding extra burden to the OSC Web Team. 

# Questions

What should the provisioning process look like for CCOM sites?
    - Does there need to be a site request for these sites?
    - How is DNS requested?
    - SSL certs?

What needs to happen to get there?
    - Do they need access to our applications, site request results, D9 role mappings, etc.?

Should we handle provisioning CCOM sites?

 # Proposed Solution

- [x] New application and verify sizing with Acquia
- [x] #6675
- [x] #6690
- [x] #6797
- [x] #6798
    - They should submit a site request
    - They should process the site request according to our normal processes (Wednesday provision deployment)
    - They should request DNS/SSL certs, etc.

**Comment by pyrello** [comment]
A few questions/observations:
- How are we going to handle theme differences as indicated in #6629 and #6630? The quick and dirty way is probably to do something similar to what was done with the regents site to allow for changing the logo. However, long term is a complication in terms of testing and deploying theme updates.
- Do we want to have a way of indicating on the SiteNow request form that a site is for CCOM? Possibly with a checkbox? That could potentially lead to being able to deploy a slightly different setup during provisioning/installation instead of having to manually make those changes. Over 60-80 sites, it could be worth it to automate those steps from the beginning.
- Based on the above, we could potentially route emails based on the above setting.
- Or, is it worth considering them having their own site and request form?

**Comment by briand44** [comment]
Another concern... our dev, stage and prod wildcard DNS won't work on this application because it is on different hardware so we won't be able to provision sites at *.prod.drupal.uiowa.edu here https://github.com/uiowa/uiowa/issues/6625#issuecomment-1634431938

**Comment by pyrello** [comment]
> Another concern... our dev, stage and prod wildcard DNS won't work on this application because it is on different hardware so we won't be able to provision sites at *.prod.drupal.uiowa.edu here [#6625 (comment)](https://github.com/uiowa/uiowa/issues/6625#issuecomment-1634431938)

I think that this potentially points to having either a) a separate form/site for UIHC intake, or b) a checkbox for differentiating on the existing site form.

One benefit of *a* is that it would be less likely that a user filling out the form would fail to check the box.

Regardless of how we handle intake, a downstream consequence of this is that we are going to have do some amount of refactoring of the codebase to handle switching the dev, stage, and prod domains based on which system the site is going into.

**Comment by joewhitsitt** [comment]
>we are going to have do some amount of refactoring of the codebase to handle switching the dev, stage, and prod domains based on which system the site is going into.

Just throwing this out there, could we "own" the application under our load balance IP but designate it for CCOM usage/sites?
