### ISSUE TITLE
Review URL structure for new application

### ISSUE THREAD

**Issue by ethan-fry** [uiowa/uiowa#6625]
Need to look in further to setting up the subdomain structure to use *.medicine.uiowa.edu for uihcsn01

- [ ] currently using medicine.uiowa.edu on CCOM application, how can we use that same url on this application since CCOM is using subdirectory

**Comment by briand44** [comment]
Not sure I understand the concern here but will be happy to talk through it. My assumption is that you would plan to move all of the subdirectory sites to subdomains first and the actual medicine.uiowa.edu site would need to move last.

For a subdomain site (let's use shpep.medicine.uiowa.edu as an example) the site could be provisioned on the new application using an internal prod domain (medicineshpep.prod.drupal.uiowa.edu) and when it is ready to go live DNS would need to be setup for shpep.medicine.uiowa.edu to point to 52.71.120.224 if using an A record. Then you could use the match redirect module or .htaccess redirects to redirect medicine.uiowa.edu/shpep and medicine.uiowa.edu/shpep/* to shpep.medicine.uiowa.edu.

We have an A record we use (acquia-dlb.its.uiowa.edu) that is setup to point to our load balancer and then we normally create CNAMES that point to that A record rather than using A records for all the DNS records pointing to Acquia. We did this in case our load balancer IP would ever change we could just update the one A record rather than having to update hundreds.

**Comment by ethan-fry** [comment]
@briand44 

This actually answers my question, the only thing I am somewhat unclear on is the provisioning process, does the blt script add the urls into the domains in acquia or is that a manual process e.g. when shpep is provisioned will the domain be added to dev and stage as shepep.dev.medicine.uiowa.edu and shpep.stg.medicine.uiowa.edu or is the domain used medicineshpep.dev.drupal.uiowa.edu and then adding the before mentioned urls is a manual process?

**Comment by briand44** [comment]
>does the blt script add the urls into the domains in acquia or is that a manual process

That is manually done.

>when shpep is provisioned will the domain be added to dev and stage as shepep.dev.medicine.uiowa.edu and shpep.stg.medicine.uiowa.edu or is the domain used medicineshpep.dev.drupal.uiowa.edu

Ahhh.... Good question. I think we are going to need to have a conversation about this. Currently we use the patterns of *.dev.drupal.uiowa.edu, *.stage.drupal.uiowa.edu and *.prod.drupal.uiowa.edu as we have wildcard DNS setup for those pointing to our Acquia load balancer. Since this application is on different hardware our normal naming conventions won't work on this application. I'll make this visible in our CCOM provisioning issue so we can have conversations about this as we groom that issue.

Also, we don't setup dev and stage sites by default for all sites in order to save space.

**Comment by briand44** [comment]
^^ This is likely a large hurdle in getting a CCOM site provisioned on uihcsn01. Glad you got me thinking about this, thanks for asking these questions.

**Comment by ethan-fry** [comment]
@briand44 I am gonna move this to done,  this is now been solved by the creation of uiowa06 and not hosting on the healthcare subscription.
