### ISSUE TITLE
Too many blocks within a section/page causes layout builder move functionality to not work

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6644]
# Problem

Created from Cherwell 1821014

As an editor, using the "move" operation link within layout builder on a block, the block does not relocate to the designated position.

Pulled the site down locally to find all of these blocks were within the same section and that after removing several of them, I was able to get the functionality to work as expected.

# Steps to reproduce

Go to https://dentistry.uiowa.ddev.site/node/2401/layout and try to move an image gallery block to the bottom of the page.
Go to another layout builder page with less section items and try the move functionality.
Remove majority of image gallery blocks on node/2401 and try the move the image gallery block again.

# Proposed solution

- [ ] Look for upstream issues related to number of blocks and the move/tabledrag functionality.

**Comment by joewhitsitt** [comment]
Created known issue https://sitenow.uiowa.edu/known-issues#uiowa-issue-6644

**Comment by joewhitsitt** [comment]
@pyrello could https://github.com/uiowa/uiowa/issues/6730 have possibly solved this issue? Tim Plunkett asked me to create a d.o issue about this, but I wasn't able to recreate the problem on the dentistry page (~46 blocks in a section) and there have been no revisions made since I opened this issue.

**Comment by pyrello** [comment]
Seems possible. This might also be related: https://www.drupal.org/project/drupal/issues/3160785

**Comment by pyrello** [comment]
There were at least 3-4 people who chimed in that they had experienced this during our demo yesterday. It came up because James H. from ITS mentioned it as being a problem on https://its.prod.drupal.uiowa.edu/services/available-software

**Comment by briand44** [comment]
Grooming conversation... Not committing to solving this but would like to investigate to see if we can learn more. Does it help if you spread the same amount of blocks across more sections? Any issues/patches upstream?

**Comment by cory-skeers** [comment]
I checked through the layout builder issue queue and didn't find anything that looked related to this (though another set of eyes could be good to double-check).

I also haven't been able to recreate in either the dentistry or more recent ITS examples, though the ITS page has been edited recently so that may have changed things. I'm going to try moving all the blocks into a single section to see if it's a blocks per section only situation.

I will say that moving blocks can get awkward when it's being moved a long ways, as it can pop into a section changing that section's height momentarily or shifting other things around, but everything always ends up in the correct spot as far as testing has gone. Clicking 'move' and using that interface, aside from duplicate labels of blocks, is by far easier imo, and could be an option for people. Even using that to get it to the right section and then dragging-and-dropping within the section could alleviate some of the awkardness.

**Comment by cory-skeers** [comment]
I did then start wondering if it might be less of an issue locally, depending on how actively LB tries to update the tempstore, any other calls and events that might fire while re-rendering things as they move, etc.

**Comment by cory-skeers** [comment]
> I did then start wondering if it might be less of an issue locally, depending on how actively LB tries to update the tempstore, any other calls and events that might fire while re-rendering things as they move, etc.

Completely rearranging a page with lots of blocks that had been in separate sections (4 to each 4 column section) into a single section and doing some moving around from there, I did end up with one block in a place other than I expected, above another block rather than below.

With that, I'm thinking it's an issue with how things can jump around when blocks are being moved, especially when many sections and/or blocks are involved, as adding even one more card to a full section can cause a lot of things to need to shift, re-render, and potentially change heights, and that the placement is probably "correct", but doesn't match what the editor was seeing on screen the moment before they dropped the drag. Depending on an editor's computer specs, connection speed and stability, etc., if this is the issue I could imagine it compounding pretty quickly and some pages to become completely unmanageable editing with the drag-and-drop.

If blocks all had unique labels, I could see unchecking "show content preview" as being a potential workaround, as removing the rendering aspect eliminates the whole jumping around experience, but rearranging things with 50 `"Card" block` blocks is less than desirable.

I'd love if someone else could try recreating the issue in case there's something I'm missing or who might have better luck being unlucky with it.

**Comment by GaryRidgway** [comment]
I have tried a few different ways including; pulling the site locally and moving a block, moving one on prod and then reverting my changes, and manually dragging the block from the top of the page to the bottom.

I am struggling to get this to break for me, so I seem to be having similar issues to Cory :(

**Comment by bspeare** [comment]
I just tried this on https://sandbox.prod.drupal.uiowa.edu/node/2506/layout and if you try to move the cards up to the single section it will fail from time to time giving out these errors:

<img width="1542" alt="Screenshot 2024-08-19 at 10 46 15 AM" src="https://github.com/user-attachments/assets/caf979f0-0e22-4208-ba75-dd7d5fc9063e">

The console log messages lead me to https://www.drupal.org/project/drupal/issues/3160785. 

https://github.com/user-attachments/assets/91813649-17ca-429b-9c3f-8f7806a13cb3

I'm not sure if the moving fails exactly, if you move it up you will get a brief preview of the move and then it flashes back to it's original spot and then 5 seconds later shows up in the spot that you originally selected for the move. 

https://github.com/user-attachments/assets/a3cdc6ea-6a91-48ce-bf64-ad74a10cf199

**Comment by cory-skeers** [comment]
> I just tried this on https://sandbox.prod.drupal.uiowa.edu/node/2506/layout and if you try to move the cards up to the single section it will fail from time to time giving out these errors:

Glad you checked that out! I tried it, and could also recreate in prod, but was not able to recreate it locally using the same site/page.

**Comment by bspeare** [comment]
It looks like it happens if you move a block immediately after moving a block.   The delay is much longer on prod. 

Local:

https://github.com/user-attachments/assets/66d6a0b5-701b-48c0-93a7-9b86c272b237

Prod:

https://github.com/user-attachments/assets/aad39a53-329a-4f51-a9b8-4bd5ae4f43b4

Perhaps this delay after moving the block and seeing it bounce back to the original spot is seen as the block not moving?

**Comment by joewhitsitt** [comment]
planning on poking at this a bit. @bspeare any tips to recreate on local?

**Comment by joewhitsitt** [comment]
i uninstalled siteimprove on sandbox prod which seemed to have been giving me null undefined errors in console during my interactions in layout builder. it would be nice if we could limit siteimprove to not load on admin paths..

anywho, that seem to allow me to move even more blocks up to the one section. cleared out down to section 13.

that slow refresh seems to make a difference in whether another block can be moved. i encountered some 503 errors (temporarily unavailable) for ajax calls to things like `/layout_builder/move/block/overrides/node.2506/8/2/third/6282615c-7ff6-40fa-9914-d8dcc7a41461/170516f9-a23e-4a3d-b2c0-8529a5ea006c` when trying to move too quickly. waiting for the flash before moving seems to help.

update: i guess i don't really know when/where folks use the siteimprove overlay functionality. the module is currently setting for all pages based on the `use siteimprove` permission via `hook_page_attachments`. i've never really used it. would it be too bold to prevent it from loading on layout builder paths?

**Comment by bspeare** [comment]
@joewhitsitt let me know if you want help recreating it locally.  It sounds like you have found it.

**Comment by joewhitsitt** [comment]
Well, i found the undefined error on prod. Which might be fixed in the latest release of the siteimprove module. Is it because local is faster that I wasn't able to cause the 503 before the flash?

https://www.drupal.org/project/siteimprove/releases/2.0.2
https://www.drupal.org/project/siteimprove/issues/3376230

**Comment by bspeare** [comment]
I still get the delay locally when siteimprove is turned off, but yes it is faster locally to update.

**Comment by briand44** [comment]
Didn't find any upstream issues. Possibly made a small improvement. Closing this and we can open a new issue.

**Comment by joewhitsitt** [comment]
Looks like @bspeare already updated the known issue. Thanks much!
