### ISSUE TITLE
Changes to site request form

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6690]
# Story

As a UIHC MarCom team member submitting a site request, I would like the ability to designate that the site I am requesting is a Carver College of Medicine site so that we can receive the site request email in addition to the OSC web team receiving the email and both teams will understand how to process that request.

# Additional Info

- A way to designate this is a CCOM site request
    - Should this be available to all folks submitting a site request or just for folks that are webmasters/administrators since it sounds like the UIHC MarCom team will be submitting the requests?
- Site request email should contain information to denote the site request is a CCOM site and should be provisioned on the application designated for CCOM sites
- UIHC MarCom team should also receive the site request email

# Proposed Solution
Ask Marcom if they have a shared inbox yet?
Create a checkbox to designate CCOM site
Limit visibility to that checkbox to admins or relevant users
Use that checkbox to set up routing rules
Test in stage so that we don't muddle submissions to webforms while testing.

**Comment by GaryRidgway** [comment]
### Ask Marcom if they have a shared inbox yet?
- I asked marcom what shared email they wanted, and they told me one. I won't list it here just in case.
### Create a checkbox to designate CCOM site
- I created radios, as checkboxes have much poorer interaction with the routing options in webforms. I just set two options for site type, setting OSC as the default, and setting up the options for the routing to have that option function no different to the previous implementation.
### Limit visibility to that checkbox to admins or relevant users
- Visibility limited to admins and webmasters.
### Use that checkbox to set up routing rules
- Routed emails based on selected value from the radios
### Test in stage so that we don't muddle submissions to webforms while testing.
- Tested in Stage with reroute email and it worked as desired.
