### ISSUE TITLE
Dining - update Allergen and Nutrition legend on market places

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#6754]
Request to update icons on 
https://dining.uiowa.edu/burge-market-place
https://dining.uiowa.edu/catlett-market-place
https://dining.uiowa.edu/hillcrest-market-place

**Comment by GaryRidgway** [comment]
I made a mockup of what these would look like in those areas. I don't think that these seem legible enough at this size to provide additional value to users.
Note: I did not add the white backgrounds, they were in the assets that were provided.
![Screenshot 2023-08-07 at 10 21 48 AM](https://github.com/uiowa/uiowa/assets/23122142/521cdeeb-8570-4347-b91e-2961984d7794)

**Comment by e-marie-w** [comment]
Thanks for the mockup and explanation of the issues with doing this @GaryRidgway!

**Comment by bspeare** [comment]
Since the icons are labeled in nutrislice (https://dininguiowa.nutrislice.com/menu/burge-market/dinner-3/2023-08-12)  perhaps we should suggest removal if this legend from the dining webpage?  Will users really have the dining menu open in nutrislice and switch back to the dining website to consult a legend that already exists on the menu?  Is this legend a holdover from once displaying the menu items on this page?

**Comment by joewhitsitt** [comment]
>perhaps we should suggest removal if this legend from the dining webpage

We talked briefly about this in grooming yesterday and that was what we were thinking. Additionally, these aren't images currently (currently taxonomy field values, css) and would take a bit to switch to.

**Comment by e-marie-w** [comment]
For visibility: I responded to user Wednesday, suggesting removal of legend and explaining why. Have not received response yet so ticket still open.

**Comment by briand44** [comment]
I met with Dining today and they were ok with removing the allergen legend from the market places. I went ahead and did this.
