### ISSUE TITLE
pagination has a comma next to page number

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6766]
# Problem
I'm noticing a comma is being included right before the page number when using the events pagination. This is also causing the javascript to not work correctly since it refreshes the page instead of scrolling you back up to the top.

example page:
https://sandbox.prod.drupal.uiowa.edu/events-test-0

<img width="375" alt="image" src="https://github.com/uiowa/uiowa/assets/731952/d3768cbc-98d5-4573-adab-75d141a26e58">

<img width="368" alt="image" src="https://github.com/uiowa/uiowa/assets/731952/bc48c451-78df-4dc1-b1cc-3babffd6f2d9">

**Comment by joewhitsitt** [comment]
@bewoldt, UI Events, Aggregator and a few other blocks are not using an AJAX pager like Articles and People. I think this is working as expected (not the ideal i agree) and not a bug because this is external content that is programmatically put together instead of served by Drupal Views. The notation there is to provide pager index id (for multiple on a page) as well as the pager page number.

**Comment by bewoldt** [comment]
The article pager has URL's like: href="?view_query=page%3D0%252C0&field_tags_target_id%5B0%5D%5Btarget_id%5D=56&field_tags_target_id%5B1%5D%5Btarget_id%5D=1&block_config_key=oIRFBxlQm5JUliz3FDJKK_0ahki3NxQPosKIi1eTXb4&age=0%2C0&%3Fpage=0%2C0&field_person_type_status_value&field_person_type_status_value_op&page=2". 

Is that how it's supposed to be?

**Comment by joewhitsitt** [comment]
Should the article list block include all of that? Probably not since there are person related fields included, but in general that is how the arguments are passed in and some some of those apply (e.g. field_tags_target_id, page). With the AJAX/javascript enabled browsers that should all stay hidden in the link and not reflect in the address bar.

Do you want to open a separate issue for the inclusion of unrelated field filters or repurpose this one?
