### ISSUE TITLE
Pass Facility alert information into Dispatch Communication

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6823]
# Story

As a Facility website owner, I can have my alert information passed into a Dispatch communication so that alert info can be sent to our Dispatch population.

# Additional Info

Make all Facilities alert fields available to be used in a Dispatch template

# Questions

Do we need a duplicate template to accept v3 fields and allow v1 template to still function until launch?
Do we need access to their Dispatch?

```[tasklist]
# Proposed Solution
- [x] Create routing and controller to handle per node logic for creating a dispatch form/log tab
- [x] Duplicate the existing template and use the copy to make necessary changes to line up with current fields
- [x] Wire up all alert fields to be sent to dispatch
```

**Comment by pyrello** [comment]
> Do we need access to their Dispatch?

Yes.

**Comment by pyrello** [comment]
> Do we need a duplicate template to accept v3 fields and allow v1 template to still function until launch?

It seems like having a duplicate template would be the least complicated way of switching over.

**Comment by briand44** [comment]
Grooming conversation... Access to their Dispatch would be helpful. Duplicate template makes sense. Wire node-specific scaffolding (routing and controller for per-node logic) and Facilities alert fields up so they are available to Dispatch templates.

**Comment by joewhitsitt** [comment]
You can add multiple people to the request https://workflow.uiowa.edu/entry/new/6564/13963472



![Image](https://github.com/uiowa/uiowa/assets/4663676/bf6cffb1-0348-4766-aa0d-e26da8641ace)

**Comment by briand44** [comment]
This may be a separate slice from this but capturing it here for now.

>The email portion is more straight-forward than our email (text wise) and thinking we can pare down our language and use a different font if that is possible.

>Here's the P&T template per my other email. I like a couple of things about this, but not an exact match to what we need. We can discuss in our meeting. Thanks.


![Image](https://github.com/uiowa/uiowa/assets/1017022/8cb7a55f-da92-4bec-9bf9-ccfa63325131)

**Comment by pyrello** [comment]
Dispatch establishes a relationship between some of its parts as such: **Campaign > Communication > Message**. A campaign is a general grouping/categorizing mechanism. A communication provides a link between a population and a template. A message is an instance of a communication that can be sent more than one time.

The D7 implementation is set up to create a new communication inside the "UI Access & Construction Alert Drupal Integration" campaign every time a request is sent. Each communication than has one message in it. I'm not sure if this design decision was deliberate for another reason, but the only reason I can find for it is that it provides the ability to set a unique subject line for each email message.

Another way of designing this would be to have one Communication established in the campaign that has a dynamic subject line using a variable. This is one approach that Michael A suggested. I've tested it out and I think it would work. In this approach, we would have one campaign, one communication, and many messages in that communication. It also would not require us to have a config selection and storage for the population and template for the facilities communication because those are already defined with an existing communication.

**Comment by pyrello** [comment]
Here is the body of a successfully sent email message:
```
The following Access & Construction Alert has been issued from Facilities Management at the University of Iowa. Construction activity may impact road, sidewalk, parking lot, elevator or building entrance access. Please review the alert below for specific details. Contact Facilities Management at 319-335-5500 if you require additional information.

Closure Category:
Road Closure
Sidewalk Closure
Date:
Tuesday, March 21, 2023, 7am - Friday, September 15, 2023, 5pm
Building:
[Carver-Hawkeye Arena](https://github.com/building/0374)
Location:
Traffic Control:
No
Traffic Control Plan:
[Traffic Plan](https://github.com/sites/facilities.uiowa.edu/files/2023-07/Test.pdf) (11.71 KB)
Accessible Route:
N/A
Alternative Route:
N/A
Affected Bus Routes:
Reason for Closure:
Newton Road, west of Elliot Drive, one lane will be closed. East bound traffic will be permitted on the remaining lane; west bound traffic will be detoured to the south,starting on or after March 20, 2023 through approximately August 18, 2023.
Sidewalk on Newton Road, west of Elliot Drive, will be closed, through approximately August 18, 2023. 
You can view [a list](https://link.uiowa.edu/l/3dffc9a4-9a63-4e3d-9769-7f98fcc26846?m=2ef9b873-d18d-481a-9f0e-5c08d4225573&c=d.facilities.outreach&i=202309) or [an interactive map](https://link.uiowa.edu/l/0565cf19-599d-47ae-b35e-a4f3bc85db97?m=2ef9b873-d18d-481a-9f0e-5c08d4225573&c=d.facilities.outreach&i=202309) of current UI Access & Construction alerts on the Facilities Management website. If you do not wish to continue receiving these automatic e-mail notices and are not a Building Coordinator, please [Unsubscribe](https://apps.its.uiowa.edu/dispatch/subscriptionLists/574800051/unsubscribe/2ef9b873-d18d-481a-9f0e-5c08d4225573) .
```

This uses a copy of the original template with placeholder names updated to reflect field names that changed. It has not been altered beyond that. I need to fix the links to use absolute URLs.
