### ISSUE TITLE
Pharmacy alumni directory

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6832]
# Story

As a College of Pharmacy website owner, I would like to have an alumni directory with the ability to filter by name, state and research area so that students can find and connect with alumni.

# Additional Information

They currently have a Palliative Care directory and would like to keep that how it is https://pharmacy.uiowa.edu/pharmd/dual_cert/palliative/certificate_graduates.

They currently use Academic profiles for their person directory so all people currently added to their website are technically alumni.

They do not need the map like the Palliative care directory.

They basically want our built in person directory (https://sandbox.prod.drupal.uiowa.edu/people) with the ability to filter by state.

State is currently a field available on Pharmacy person content type.

They currently have overridden the label for "Research Areas" to "Practice Areas" but they may want to change that label again.

# Proposed Solution

**Comment by pyrello** [comment]
Seems related to #7030

**Comment by joewhitsitt** [comment]
Yes, #7030 could be a solution for this.

One point to keep in mind is that this site already has a site split and so it would be a small slice to just deliver this as a custom view in config.

Another option would be to start to move articles/people back to tracked configuration and implement more of what was done in https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_events/sitenow_events.module#L128 with prebuild to change views on the fly instead of swapping config on save. Then this site could just have a partial view split item to include their custom field filter.

**Comment by joewhitsitt** [comment]
Grooming convo: After considering a happy medium approach, the team thought the smaller slice of establishing a custom view page per their requirements (path, filters, etc.) and making the filters look decent should be done but that we consider the other work at a later date.

**Comment by joewhitsitt** [comment]
Stubbed out an issue for the work to consider later: https://github.com/uiowa/uiowa/issues/7101
