### ISSUE TITLE
showing dispatch log

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6855]
# Story

As a Facilites alert creator, I can see a log of scheduled dispatch emails from my alert node.

# Additional Info

Based on how this functionality is currently setup, we will want to link the log to a message rather than the communication like their existing site does.

Existing site example https://www.facilities.uiowa.edu/node/5816/dispatch

# Proposed Solution

- [ ] Output dispatch log on node tab where scheduling happens
- [ ] Link to Dispatch message
- [ ] Show count in node tab

**Comment by pyrello** [comment]
I went ahead with working on this because I thought I was close to a solution and, in fact, I was most of the way done. However, I've realized that the way I was planning on handling this (similar to the D7 solution) has a potential issue that I would like to discuss with the team.

In the D7 application, when a dispatch request is sent, the timestamp, user ID, and communication ID are stored in a serialized array as an entry in a multi-value field. I haven't specifically tested it, but I don't believe this causes a new revision to be created. However, if there were previous revisions before the dispatch request was sent, they will not contain the dispatch log. If someone was to revert to a previous revision, the dispatch log would disappear.

As far as I can tell, this issue existed but was never a known issue in the D7 Facilities site. So maybe we just go ahead with similar logic in the new version of the Facilities site and don't worry about it. However, the possibility of having the log functionality become inoperable through a user action worries me a little bit.

Some possible solutions:
- Disable the ability to create new revisions for the Alert content type and disable the Revisions tab in the UI
- Store the dispatch log using the [Drupal State API](https://www.drupal.org/docs/8/api/state-api/overview)
- Figure out some other way to store the log

Based on the need for more discussion on this, I'm going to pull out the work I started doing in #6833 related to this issue.

**Comment by pyrello** [comment]
Here is the code I was using to get the message ID and update the log:
```php
// Drupal\facilities_core\Form\NodeAlertDispatchForm::submitForm

    // $result_endpoint is returned as a location header when the schedule request is sent.
    $message = $this->dispatch->request('GET', $result_endpoint);

    // @todo Finish setting up the log.
    $this->node->field_dispatch_log[] = serialize([
      'timestamp' => $schedule_start,
      'username' => \Drupal::currentUser()->getAccountName(),
      'message_id' => $message->id,
    ]);
```

Here is the code I adapted from the D7 version for displaying a table of the Dispatch log entries:
```php
// Drupal\facilities_core\Form\NodeAlertDispatchForm::buildForm

    // Only render table data if there's field data.
    if (!empty($node->field_dispatch_log)) {
      $form['notification_log'] = [
        '#type' => 'details',
        '#title' => $this->t('Dispatch Log'),
        '#open' => TRUE,
      ];
      // Build table header.
      $header = [
        [
          'data' => $this->t('Date Requested'),
          'field' => 'timestamp',
          'sort' => 'desc',
        ],
        [
          'data' => $this->t('User'),
          'field' => 'username',
        ],
        [
          'data' => $this->t('Message ID'),
          'field' => 'message_id',
        ],
      ];
      // Build table rows.
      $rows = [];
      foreach ($node->field_dispatch_log as $delta => $log) {
        $row = unserialize($log->value);
        foreach ($row as $key => &$d) {
          switch ($key) {
            case 'timestamp':
              $d = new FormattableMarkup('<span class="sr-only">@timestamp</span>@date', [
                '@timestamp' => $d,
                '@date' => \Drupal::service('date.formatter')->format($d, 'custom', 'M j, Y - g:i:sa'),
              ]);
              break;

            case 'message_id':
              $communication_id_slug = basename($communication_id);
              // https://apps.its.uiowa.edu/dispatch/communications/1238605612?showBatch=1241267773
              $url = Url::fromUri("https://apps.its.uiowa.edu/dispatch/communications/$communication_id_slug?showBatch=$d");
              $d = Link::fromTextAndUrl($d, $url)->toString();
              break;
          }
        }
        $rows[] = $row;
      }

      // Render table results.
      $form['notification_log']['table'] = [
        '#theme' => 'table',
        '#header' => $header,
        '#rows' => $rows,
      ];
    }
```

**Comment by joewhitsitt** [comment]
>Disable the ability to create new revisions for the Alert content type and disable the Revisions tab in the UI

I could get behind this. To me this is a use-case where updates to content should be logged and transparent. Even something as simple as a typo would be a push forward, not a revert back. Rarely will they be "staging" content changes. I think this could be set on the default feature.

**Comment by briand44** [comment]
Grooming conversation.... Could remove the abiltiy to revert a revision that way we could still see the revision history. Could verify this is an issue in D7? May want to create our own db table rather than using state API. If we want to not allow revisions we would want to discuss with our Facilities partners. Also, we may still run into this if/when we visit this functionality with articles.

May make sense to find out if not having revisions would be a problem for Facilities/ITS but start investigation different options first.

**Comment by joewhitsitt** [comment]
if we create our own table for this data, here is a drupal example with some of the stuff we could need: https://git.drupalcode.org/project/examples/-/tree/4.0.x/modules/dbtng_example?ref_type=heads

**Comment by joewhitsitt** [comment]
>Show count in node tab

Not sure what this means. Is this a message like "There have been X dispatch messages scheduled for this alert."? Is the node tab the edit tab or the view tab?

**Comment by joewhitsitt** [comment]
At EoD it was mentioned that it might be worth capturing the revision id if it exists as each message is a point in time. If they update the alert they may need to unschedule and reschedule a message if enough content changes. The workaround right now would be to compare timestamps and/or inspect the message in Dispatch. ITS and Facilities both said they don't need revisions for alerts, but this could be more important if the same functionality is used for articles. If the need is there in the future, a revisions column could be added to the table through an update hook.
