### ISSUE TITLE
gis.sites.uiowa.edu has some orphaned paragraph items that can't be removed through UI

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#6861]
# Problem
While working on https://github.com/uiowa/uiowa/pull/6830, I noticed that ERR was unable to remove all of the orphaned paragraphs. Looking at the database tables they look like old Devel type content. These will have to be cleaned up through a separate process before the site can transition away from v2.

# Steps to reproduce
Run the process of https://github.com/uiowa/uiowa/pull/6830 and note that it chokes on deleting config due to existing entities.

# Proposed solution
- [ ] Transition this site manually to v3 or drop these entries programmatically to prepare for P2LB.

**Comment by pyrello** [comment]
I think this is the issue where the added the code that we are running into now: https://www.drupal.org/project/entity_reference_revisions/issues/3158156

**Comment by pyrello** [comment]
This looks like the start of a potential change that could allow the orphaned entities that are being skipped right now to be removed: https://www.drupal.org/project/entity_reference_revisions/issues/3201705. Going to test this out in #7025 next week.

**Comment by pyrello** [comment]
What I was looking into above is only part of the problem. The lack of `parent_type` and `parent_field_name` values (set to `NULL`) on a paragraph leads the orphaned paragraph cleanup tool to stop. There are apparently conditions that can exist where those are not filled in but there is still a valid reference and therefore the paragraph in question is not an orphan. Those cases are not relevant to us because they involve custom content entities (meaning the entity is defined in code, not created through the UI). The orphaned paragraphs tool is cautious in this case and just skips those entities.

However, we have additional paragraphs that are not being removed that don't meet the above criteria. This query shows the items that meet the above conditions:
```
ddev drush @hawkeyemarchingband.prod sqlq "SELECT * FROM paragraphs_item_field_data WHERE parent_type IS NULL OR parent_field_name IS NULL" 
1321    17116   section en      1       1609000384      NULL    NULL    NULL    a:0:{}  1       1
1466    19716   section en      1       1624633623      NULL    NULL    NULL    a:0:{}  1       1
```
After running the cleanup script on HMB, there are a handful of other paragraphs in the `paragraphs_item_field_data` that should have been removed.

I'm think that we might be able to just delete any Paragraph that remains that matches one of the V2 types (assuming that our naming conventions for Paragraphs in V2 and V3 don't overlap).

**Comment by briand44** [comment]
Closing because #7025 resolves this
