### ISSUE TITLE
Probe migrating media assets from v1 to v3 for CCOM sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6868]
# Story

As a CCOM site owner transitioning to SiteNow v3, I would like to have my media assets from my existing site easily available to me so I don't have to try and find the asset on my existing site and try to figure out how to download the original file in order to upload it to my new site.

# Questions

Would it be possible to migrate files to the new sites after provisioning?

Copy existing files directory to a more accessible location?

Other thoughts/ideas?

# Proposed solution

- [x] Probe using our existing file migration for CCOM sites
- [x] Any updates needed to existing migration for this to work
- [x] Can we connect or do we need to sync locally
- [x] Outline what the process would look like
- [x] Other options that could make transitioning media easier

**Comment by cory-skeers** [comment]
It hasn't been used in a long time, but we have a default file migration as part of `sitenow_migrate`; https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/Files.php

Because files are fairly standard, this should more-or-less just involve enabling the `sitenow_migrate` feature split, setting up the config, and checking for the `d7_file` migration registered correctly.

The other migrations we've been doing are based off of https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/CreateMediaTrait.php instead, so part of this we'd probably want to look into the trait and see if there are updates that should be made to the Files if we went that route.

Alternatively, there's a process plugin https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/process/CreateMediaFromFile.php that could probably be used with a basic migration definition YAML using some of the core migration stuff.

The original process we synced the d7 and d9 sites and files locally, did the migration, then synced the d9 sites/files back up, and could be a backup option if there's any difficulties connecting between applications.

**Comment by briand44** [comment]
Grooming conversation... downside is that we may be storing a bunch of files that never get used or are not optimized. Files migrated would not be cleaned up by core processes.

multi-file upload?

If we did a file migration, would need to enable the feature split, configure the db info and run the migration and then turn it off. We may run into issues connecting to the db which would require us to sync the files locally first.

If articles were to be migrated, files associated with the articles would come over as part of that migration.

**Comment by joewhitsitt** [comment]
I think dusting it off the migration for this use-case and seeing if it can connect to the other org would be a good probe, if not for UIHC-Marcom, someone else that needs to move to v3

**Comment by bspeare** [comment]
I spent some time today trying to connect to a CCOM dev site (with Brian's help) from `@default.dev` and got `SQLSTATE[HY000] [2002] Connection timed out` every time I ran `drush ms`.   I tried connecting to `701` dev site for comparison and received a `SQLSTATE[HY000] [1044] Access denied for user 'username' to database 'standard_database'`   I'm happy to screenshare the process or the credentials if someone wants to take another look.

**Comment by pyrello** [comment]
> downside is that we may be storing a bunch of files that never get used or are not optimized. Files migrated would not be cleaned up by core processes.

I would like to reiterate this point. It may make it easier for the user, but results in cruft that we probably will never be able to get rid of. It also means that the user potentially has a lot of files they have to search through if they want to use an existing one even though many of those files may never get used.

**Comment by bspeare** [comment]
Update: @briand44 helped me connect to a 701 site on `@default.dev`.  Next step is to try a local connection with DevDesktop.

**Comment by bspeare** [comment]
I paired with @seandui on this to test out a local migration and he was able to connect to a local DevDesktop site through the SiteNow migration, but when we tried to run the file migration it failed with the notice `d7_file Migration - 1494 failed`. There is a Slack thread with a little more info: https://iowaweb.slack.com/archives/C0164FNN1PV/p1695675067800499. 

Next step, I'll be out Tue-Thu so the person to take this on will need access to Marcom Acquia's application and try to run a file migration locally to see if you get the same results.   @ethan-fry is able to grant permissions there if we need it.

**Comment by joewhitsitt** [comment]
What site from what application @seandui? I might have some time to poke at this.

**Comment by seandui** [comment]
We were just trying to pull 'default' public files @joewhitsitt

**Comment by briand44** [comment]
>What site from what application @seandui? I might have some time to poke at this.

I had also given Ben connection details to https://www-dev.medicine.uiowa.edu/anesthesia/, which he was unable to connect. I just picked a subdirectory site that had a decent amount of files from the CCOM application.

**Comment by seandui** [comment]
He mentioned 'anesthesia' but then he changed it over to 'default' @briand44

**Comment by cory-skeers** [comment]
It looks like the issue is coming from the construction of the filepath to the source file.

Example the migration ends up looking for:
`https://medicine.uiowa.edu/anesthesia/sites/default/files/wysiwyg_uploads/Chudzik-Deborah1.jpg`

Actual file location:
`https://medicine.uiowa.edu/anesthesia/sites/medicine.uiowa.edu.anesthesia/files/wysiwyg_uploads/Chudzik-Deborah1.jpg`


Specifically, we're extending the [core d7 file source](https://api.drupal.org/api/drupal/core%21modules%21file%21src%21Plugin%21migrate%21source%21d7%21File.php/class/File/8.9.x), and this bit of code is defaulting the path to be "sites/default/files"

```
  protected function initializeIterator() {
    $this->publicPath = $this->variableGet('file_public_path', 'sites/default/files');
    $this->privatePath = $this->variableGet('file_private_path', NULL);
    return parent::initializeIterator();
  }
```

Looks like, at least for medicine.uiowa.edu/anesthsia, there is no `file_public_path` in the `variables` table. I'm assuming this is part of the subdirectory multi-site setup. 

We can write our own `intializeIterator` in `Files.php`, but I'm not sure yet where best to go to get this. One quick and dirty solution could be to include it in the migrate setup form, similar to the base URL field. For setting up anesthesia, for instance, we'd have
Site URL = `https://medicine.uiowa.edu/anesthesia`
Public File Path = `/sites/medicine.uiowa.edu.anesthesia`

And in `Files.php` something like
```
  protected function initializeIterator() {
    $this->publicPath = $this->variableGet('file_public_path', NULL);
    if (is_null($this->publicPath)) {
      $this->publicPath = \Drupal::config('migrate_plus.migration_group.sitenow_migrate')
         ->get('shared_configuration.source.constants.public_file_path');
    }
    $this->privatePath = $this->variableGet('file_private_path', NULL);
    return parent::initializeIterator();
  }
```

**Comment by joewhitsitt** [comment]
>One quick and dirty solution could be to include it in the migrate setup form

I like quick and dirty if that is all that needs to be done

**Comment by cory-skeers** [comment]
As a quick example, these are the first 8 media files imported for medicine.uiowa.edu/internalmedicine.

![Image](https://github.com/uiowa/uiowa/assets/49074566/b7d99198-5d15-4bdd-8729-ad8fc205456e)

Out of the 8 files, 3 of the 5 represented are duplicates (in the database, they have slightly different filenames, eg `Cryoablation_3-2-15.jpg` and `Cryoablation_3-2-15_0.jpg` or `RheumatologyConf11.pdf` and `RheumatologyConference.pdf`, and so all get brought over).

If we can limit it to only certain files, that would be great. BUT the work in #6964 should get this working for CCOM sites.

I've personally run it locally, and I would expect to be able to run it directly in place as well, though with the Acquia cloud caveat that the migration must be from stage/dev=>stage/dev or prod=>prod (for example, we can't sync from a d7 site in production to a d9 site in dev. The d7 site needs to be synced down first, and then migrated from dev to dev.)

**Comment by cory-skeers** [comment]
Current progress here:
The PR in #6964 offers a path forward to get the connection working and migration running.

Todo:
Check out current documentation and/or create new documentation on the process
Test a connection in dev to see if we can connect from the CCOM application to uiowa0x
^ if the above doesn't work, document the local => sync process

**Comment by cory-skeers** [comment]
Docs on the process for the local route have been updated: https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/Using%20SiteNow%20Migrate/Using%20SiteNow%20Migrate.aspx

Will update with the process for direct connections after testing for that has wrapped up.

**Comment by cory-skeers** [comment]
> Docs on the process for the local route have been updated: https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/Using%20SiteNow%20Migrate/Using%20SiteNow%20Migrate.aspx
> Will update with the process for direct connections after testing for that has wrapped up.

Did some more probing on this, and the going local route is probably the way to go. As far as I can tell, connecting to the CCOM app from one of the uiiowa0x apps would require an SSH connection, and while there's likely a path forward that could handle that, it'd take some investment to sort out, whereas the syncing locally has a defined process in place already.

If we're looking at running lots of migrations for lots of CCOM sites where the extra local syncs would start to add up, it still might be worth looking into getting a direct connection working, but it doesn't look like it'll "just work" without a bit of investment.

**Comment by cory-skeers** [comment]
With #6964 merged, we have the updates needed to get the file migration and/or other migrations working for CCOM. From testing, it also looks like the [local approach](https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/Using%20SiteNow%20Migrate/Using%20SiteNow%20Migrate.aspx) is the way to go at least for now.

Going to close this out as probing for now is complete.
