### ISSUE TITLE
Bulk update moderation states

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#696]
Customer created all content in draft and wants to bulk update to published. This currently isn't available.

**Comment by cory-skeers** [comment]
In alpha currently, but there might be others that are more complete/tested: https://www.drupal.org/project/workbench_moderation_actions

Removes the Unpublish/Publish bulk actions (which don't work with Workbench) and replaces them with the established moderation states.

**Comment by cory-skeers** [comment]
Committed initial branch bulk-modstates which unsets bulk publish/unpublish actions (which are broken with content moderation anyway). Groundwork for finding available states/transitions and adding them to available actions.

**Comment by joewhitsitt** [comment]
This might be a solution forward and could be done in conjunction with #781 
https://www.droptica.com/blog/custom-actions-views-bulk-operations-module-drupal-8

**Comment by quamsta** [comment]
+1  on this, we often have content campaigns that need to be bulk unpublished/published and we rely on this heavily on our current platform.

**Comment by cory-skeers** [comment]
https://www.drupal.org/project/workbench_moderation_actions was a no-go, but a good reference. Started an exploratory PR, but more digging could be done for other pre-existing solutions.

**Comment by cory-skeers** [comment]
Patch https://www.drupal.org/project/drupal/issues/2797583#comment-13235791 and module https://www.drupal.org/project/moderated_content_bulk_publish available for some of this. Needs some testing, but off the bat, there's some confusion because the default publish and unpublish actions remain available, leading to multiple publish, publish latest revision, etc. actions that are similar, may or may not work, and may or may not work differently than expected.
