### ISSUE TITLE
Facilities building API calls

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6999]
Questions about how we are calling the Facilities Building API endpoints.

> We have 2 APIs related to Buildings that is used by the FM Website. The first one is for all Buildings and the second one is for specific Building selected by user.
>
>1. All building Api: https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
>
>2. Individual building Api: https://bizhub.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0042
>
> My recollection is that FM Website (has a cron or scheduled job – Drupal config) that execute the 1st API periodically, but could you please confirm that?
>  
> I thought the 2nd API is only invoked when user intend to see the Building detail… but the devs are suggesting that they are seeing it being invoked in a loop.. Is it possible for you to check on your end and confirm?

> This was discovered last Thursday 10/5 when we started seeing nonstop exceptions because of the API dependency with ITS  ‘Files’ system to generate temp URL for the Building image..
> 
> We can only generate finite number of temp url’s so wanted to make sure that the API is invoked only when the user is requesting..
>
>The “ITS FILES” system was having issue for a few hours on 10/5– then it started working again.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/5823 's comments detail the issue the the image URL which then requires the additional call to the individual building

**Comment by briand44** [comment]
Not seeing anything that stands out in D7 except possibly facilities_artwork_map.inc seems to loop through all artwork nodes and if they have a building reference it seems to call the individual building API for each of those. I'm not sure that functionality is even being used anymore though because it seems like the Facilities Artwork Maps all link out to https://uiadmin.maps.arcgis.com/apps/webappviewer/index.html?id=c4bcf56619a241deb3e8f490ce1b9ed6

**Comment by briand44** [comment]
@joewhitsitt so basically, every morning at 7am a scheduled job runs that calls the all buildings endpoint and then loops through each building and calls the individual building endpoint to get additional information (image, lactation rooms, rest room info, etc.) and updates the facilities buildings with the information from the APIs?

**Comment by joewhitsitt** [comment]
That is my understanding, yes. @pyrello may recall more specifics

**Comment by briand44** [comment]
> The main challenge we face relates to the image URLs. Image URLs from ITS Cloud is only valid for 60 minutes. The recommendation from ITS Files team is that we generate the Time-To-Live (TTL) for URLs when a user has requested them.
> They have previously contacted us, advising against generating TTL in a for loop as it places a burden on their resources.
>  
> Any way we can get around that and load individual building real time using the API?

We are probably going to need to have a call to discuss this.

**Comment by joewhitsitt** [comment]
pre-meeting thoughts:

the drush command is run nightly which loops through the individual building endpoint, but what is stored on the node is the image url in the api and is then fetched rendered using imagecache external (cache for those are cleared by the module every 7 days unless something else clears it)

It must mean that after the URL expires and image cache expires, it is going to try to fetch the new building image, but at the expired URL until a new URL is fetched and stored.

So does this mean we should store the image (not the URL) every __ days instead of nightly, then assume the image doesn't change for a period of time unless editors notice and we need to manually trigger an individual building?

Ultimately, we want building nodes and the attached images to be cached longer than 60 min so the idea of fetching the new URL each hour and thus expiring the building node seems a bit much.

We will still be hitting the individual building URLs for more info like restroom/lactation room info.

**Comment by joewhitsitt** [comment]
It sounded like we could create/store a file/media entity nightly, but I am not sure we want to. Maybe our current call skips and only fetches X number of days and then we can add a flag, `--force-image` to the drush command to ignore that restriction.

Otherwise, we might benefit from a image_last_updated property on the bizhub individual building endpoint to help us decide whether to fetch a bizhub image specific endpoint. ITS would be happy then that they don't produce 300+ URLs each morning. Not sure if this data is available to add though.

Otherwise to determine if the image has changed we would still need to grab the image from the temp URL and inspect exif data or something before creating the file/media entity on the site.

**Comment by pyrello** [comment]
> It sounded like we could create/store a file/media entity nightly, but I am not sure we want to. Maybe our current call skips and only fetches X number of days and then we can add a flag, --force-image to the drush command to ignore that restriction.

I would only go this route if there is some clear benefit to us or if we are being told that the proposed change to store the file locally instead of the URL to the file is not enough. It's going to add complexity to the logic and will be more work to implement/test

**Comment by joewhitsitt** [comment]
Maybe I don't understand your comment but I believe the benefit would be that we aren't creating/deleting a file and media entity every day. 

Separate but related, given how imperfect the media replace functionality is currently, I would hesitate to rely on that through programmatic means and do a completely different entity for both file and media.

**Comment by pyrello** [comment]
My point is that adding in logic that checks a schedule to see whether to re-download the image or not is going to make this a more complex slice than just switching the logic to downloading and serving the downloaded image. I would assume that we are not going to keep every copy of the image, so doing it every day isn't a concern from a perspective of storage. Possibly we would be concerned about a spike in resource usage while all the images are being downloaded, but it's not clear that that would actually be an issue worth programming around.

I wasn't intending to suggest that we would use media replace functionality for this. I'm not sure yet what the best mechanism would be, but I think we could just use PHP or Drupal core file-handling logic to overwrite a file if needed.

**Comment by joewhitsitt** [comment]
Okay right. Increase in complexity (time period check, optional drush flag) with the benefit of reduced resource consumption on our end since they said these don't change often.

That said, I was originally thinking file/media entities but since these could potentially be blown away each night, maybe they shouldn't be in the file_managed table so that other content doesn't reference them.

**Comment by briand44** [comment]
Grooming conversation.... Need to store the image rather than the temporary url. Discussed it might be best to not have it a managed file so it is not used elsewhere throughout the site. Discussed a few different options such as file field or potentially still using remote image but pointing to our locally hosted path to the file. Grabbing nightly still fine for now. We can revisit if we start seeing performance or other issues.

**Comment by pyrello** [comment]
Relevant section of code:

https://github.com/uiowa/uiowa/blob/cece8fb50da0e97244e21e95246a6bfb7077542d/docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/BuildingsProcessor.php#L43-L66

**Comment by joewhitsitt** [comment]
If we want to keep the field as-is (imagecache_external), we could just bring the file in using something similar to the static map thumbnail: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/media/Source/StaticMap.php#L142

**Comment by joewhitsitt** [comment]
If there are too many hurddles with using imagecache_external for what is technically an internal image path, then I probably feel strongest towards using a media reference and not "worrying about the bomb" or using file field to make sure the image isn't touched outside of the node it is on. sitenow_dcv has a file field so it wouldn't be a completely new thing to work with. just the file type is different docroot/modules/custom/sitenow_dcv

**Comment by pyrello** [comment]
It's not so much the imagecache_external part of it. It's that using the existing link field would require us to set a value that includes the `sites/site.uiowa.edu/files` path, which will get set for 100's of records in the database. Should we ever need to move this site to another domain, that is extra work to remember they are there, find them all, and update them. The `public://` and `private://` schemes were introduced in part to avoid having to hard code the files path anywhere, so doing this would be an anti-pattern.

Moreover, since this is a feature for a site that is still in progress, I think we should just go ahead and build the part of it as though we were starting from scratch rather than trying to contort ourselves around previous decisions to try to get it to work. We might have already spent more time trying to get the solution with the existing field to work than it would have taken to just replace the field with a new field. Let's not let what we did before cloud our judgement about coming to the right solution here.

If we are going to use a media field, then I think we need to understand what can happen if the media item is referenced somewhere else. That gets us also into having to use media replace functionality, which @joewhitsitt had previously indicated he thinks is buggy. I had suggested an alternative plan to allow for excluding media items from lists, but I think moving forward with a file field makes the most sense.

**Comment by pyrello** [comment]
@GaryRidgway Here is an example of fetching a remote file and storing it in the file system: https://drupal.stackexchange.com/a/288004


I added an inline comment that attempts to illustrate how this would be implemented.

**Comment by pyrello** [comment]
In the following line, 

https://github.com/uiowa/uiowa/blob/4427598c1f50791c8d2874a87bfc0e02423c5d73/docroot/modules/custom/uiowa_core/src/EntityItemProcessorBase.php#L36

when the `$to` field being processed is `field_building_image` (which is newly added in #7093), the `static::resolveFieldValuePropName($entity->getFieldDefinition($to))` portion returns `value` when it seems like it should be returning `target_id`.

In the case where a building already has an image and the api call to the building endpoint does not contain an image URL, we would expect that the image would be removed. However, because the comparison is checking the `$entity->get('field_build_image')->value` property, which doesn't exist on reference fields, the result is `NULL` which matches the empty string and resolves to `FALSE` in the `!=` check and therefore the entity is not updated.

So, it seems the first step is to figure out why `static::resolveFieldValuePropName($entity->getFieldDefinition($to))` is returning `value` when `$to` is `field_building_image`.

Next, after some consideration, it becomes clear that when we are pulling in a new image every time we call the API there is no reasonable way for us to know that the image file is the same or different than a previous image file that was pulled in. In the equals check in the linked code snippet, the file will have a file entity ID which becomes the target ID of the `field_building_image` field. When comparing the IDs, the values will always be different. Therefore, in those cases the check is kind of useless. It doesn't hurt anything, but it doesn't really do what it seems like it is doing. Maybe that is fine. It might be worth thinking through what could go wrong if we leave code that will always fail in place because it still functions correctly.

**Comment by joewhitsitt** [comment]
Planning on taking a look at this today

**Comment by joewhitsitt** [comment]
`field_building_image` is returning `value` because `$definition->getType()` is returning `image` and the default catch is `value` if not otherwise mapped.

I've updated `resolveFieldValuePropName` to map the `image` type as well and I am seeing my local image replaced by the API version. https://github.com/uiowa/uiowa/pull/7093/commits/2b41ffdc170b01e453233ce629e53a6966536e63

<img width="704" alt="Screenshot 2023-11-17 at 9 54 56 AM" src="https://github.com/uiowa/uiowa/assets/4663676/38a853ab-2064-448d-8b20-f348b2d2205a">
<img width="531" alt="Screenshot 2023-11-17 at 9 57 10 AM" src="https://github.com/uiowa/uiowa/assets/4663676/f2df4446-e971-4f96-8ba5-7de37733be19">

**Comment by joewhitsitt** [comment]
I think the only way to prevent everything from being updated all of the time is to pull the image into tmp and inspect exif or something to determine if it should replace the existing.

**Comment by pyrello** [comment]
> I think the only way to prevent everything from being updated all of the time is to pull the image into tmp and inspect exif or something to determine if it should replace the existing.

I don't think we should do this.

**Comment by joewhitsitt** [comment]
Sorry, I was heading down a path by your previous comment:

>it becomes clear that when we are pulling in a new image every time we call the API there is no reasonable way for us to know that the image file is the same or different than a previous image file that was pulled in.

If we don't want to do anything further, I think https://github.com/uiowa/uiowa/commit/2b41ffdc170b01e453233ce629e53a6966536e63 resolves the first part of https://github.com/uiowa/uiowa/issues/6999#issuecomment-1815401923

Was that the only outstanding issue?

**Comment by joewhitsitt** [comment]
FWIW, originally I started down a path of [using file_mdm to inspect certain exif data](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_media_wysiwyg/sitenow_media_wysiwyg.module#L80), yada yada, but the following would probably work too:

```
In processResultImage:

$data = file_get_contents($building_image_url);
$original_data = file_get_contents("{$destination}{$building_number}.jpg");
if ($data !== $original_data) {
  // Replace file/obtain new file id.
}
else {
  // Move forward with original $file->id().
}
```

**Comment by pyrello** [comment]
@briand44 Can you weigh in here? @joewhitsitt has provided some examples of how we could implement some logic to prevent unnecessarily saving a new file entity if the image content has not changed. It is not strictly necessary, but could be considered good housekeeping. I'm just wondering if we want to make the extra investment here or call it good (in which case, I think this PR is approved).

**Comment by briand44** [comment]
I'm fine with calling it good and we can revisit if we are seeing performance issues or this resurfaces for some other reason.
