### ISSUE TITLE
P2LB - Disable v2-isms for a page after v3 revision has been published

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7049]
# Story

As an editor after I have converted a page to v3, there is nothing stopping me from creating new v2 content within the v3 revision.

# Background

- I had to fix a site before turning off the functionality because the editor had gone back to old ways and added v2 content again to the now v3 content.
- Larger sites that will need more time converting (HR 1100+ pages) will allow them to convert without creating a mess again.

# Proposed solution

- [ ] Figure out the best way to identify if the current revision is v3 or v2. Account for the possibility of the page being converted to v3 and then reverted back to v2.
- [ ] If current published revision is v3, disable the paragraphs functionality on the edit form. The add form shouldn't be necessary as the body is available for new pages.

**Comment by pyrello** [comment]
This is probably still worth doing.

**Comment by briand44** [comment]
Grooming conversation... What about new content? Would that have paragraphs functionality enabled? Would we want that? Would the body field be available during this transition phase? Joe confirmed on brand.uiowa.edu that the body field is available and that new content doesn't have paragraph functionality.

How can we make sure we are only targeting v3 revisions with this? Any revisions newer than the protected revision or are there v3isms we can look for? May not be able to go off of newer revisions than the protected revision because they could revert to the protected revision.

Once we identify what revisions we are targeting, it should just be disabling the paragraphs functionality.

**Comment by joewhitsitt** [comment]
This might be a non-issue now. `sitenow_p2lb_form_node_page_edit_form_alter()` seems to be doing enough here. Going to poke more to make sure there isn't a gap somewhere. Perhaps I had misidentified what went wrong:

>I had to fix a site before turning off the functionality because the editor had gone back to old ways and added v2 content again to the now v3 content.

**Comment by joewhitsitt** [comment]
Unless someone else recalls how this might have been exposed, I am marking this up as a non-issue.

<img width="1142" alt="Screenshot 2024-03-22 at 11 30 19 AM" src="https://github.com/uiowa/uiowa/assets/4663676/5c4b58b1-0b6a-43c9-ac31-705b540e55dc">


https://github.com/uiowa/uiowa/blob/aeb2ea6372286a7161d68f140c989e1909df1c1c/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module#L40-L55

**Comment by joewhitsitt** [comment]
FWIW, I am encountering this today. In a bit of a revisions snafu, law was building out v3 content in layout builder but the page is saying it has not yet been converted and the v2 paragraphs fields show on the node edit page. I am pulling down to look closer

Update: this particular node/10721 doesn't have a protected revison id set. it is caught between v2/v3.
