### ISSUE TITLE
Mockup of Alerts landing page

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7059]
# Story

As an OSC web team, we would like to have mockups of an alert landing page so we can get feedback on design and better understand how we should move forward with development.

# Additional Info

- They like their existing page https://its.uiowa.edu/alerts
- Show outages/Degredation of Service first
- Planned maintenance in the next 7 days
- Service Announcements in the next 7 days
- Status History over the last 5 days (currently feature some and link to all so possibly some flexibility here but they will need the all status history page)
- No longer need Ongoing Issues
- Ability to add additional links, content, etc.
- Legend - (will need a legend on calendar display as well)

# Proposed Solution

**Comment by joewhitsitt** [comment]
In grooming it was brought up that styling for alert teasers after initially doing work in the default feature might change to show off the different types, states, information provide and where it is placed. With that in mind we decided to move forward with this mockup first to see how this page might define those different styles and how they are presented. If we realize more thought needs to go into the alert style and where all it is placed we can shift from this slice to that. We may still be able to provide direction/deliverable for this slice in the way of layout placeholders and the type of content found in each area.

**Comment by joewhitsitt** [comment]
Starting work over here: https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing

Mockups are crazy difficult.

**Comment by bspeare** [comment]
Late to the general grooming question:  does the full alert info need to be on there?  Or can we just list the alert teaser that will link to the full node without a details or accordion element?  I think we moved away from the detail toggles for Facilities on their alerts and I am wondering if we can propose the same here.

**Comment by joewhitsitt** [comment]
>does the full alert info need to be on there?

Not necessarily. I was thinking of doing one without once I done with this one. In our meeting with ITS recently I don't know if we touched on their preference for how much of the alert info was presented here but that they generally liked what they currently have. In thinking about the instances of multiple services or multiple buildings, without providing more of the info, I could see that either causing really long alert titles or links with very little context.

Grooming did touch on the realization that alerts showed up in more places and ITS has different levels of severity to convey some how unlike the facilities alerts page https://facilities.uiowa.ddev.site/alerts

My goal so far is to present something that doesn't create too many new patterns. I get that details in an alert is new, but we have started to use details elsewhere to avoid using accordions.

**Comment by bspeare** [comment]
I imagine that they do like their current page. :) 

Since alert components are meant to convey quick and specific information in one glance, perhaps instead of introducing `<details>` inside the alert, we look into developing a "view more" or arrow button that links to the full node?

<img width="831" alt="Screenshot 2023-11-03 at 1 42 19 PM" src="https://github.com/uiowa/uiowa/assets/1036433/bb585b29-e859-4d68-b2e5-72a567f28fc2">

If they do need the page to be like https://its.uiowa.edu/alerts, maybe accordions would be more appropriate?

**Comment by bspeare** [comment]
> I get that details in an alert is new, but we have started to use details elsewhere to avoid using accordions.

Sure, maybe we should just set a limit on what we want to put inside a `<details>`?  Maybe we use `<details>` single fields like "fees" on https://its.prod.drupal.uiowa.edu/services/gartner or "directions" on https://oniowa.uiowa.edu/events/1276/university-iowa-clothing-closet-food-pantry-grand-opening and an accordion if we are displaying multiple fields/large amount of structured content?

**Comment by joewhitsitt** [comment]
Put together a non-details version with other tweaks. https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-2

I am willing to help produce more options Monday.

I think it is important to have the important details visible without clicking them. They had feedback that they have to click into several alerts just to find the one they are looking for.

**Comment by bspeare** [comment]
Thanks for the mockups @joewhitsitt.   I think this task exposes that the alert design isn't very well suited for a lot of structured field data like this.   Based on seeing these mockups, I'd vote that we pursue one of these options:

- Use the card with a font awesome icon in the media slot: https://uids.brand.uiowa.edu/latest/?path=/story/components-card--image-using-uiowa-icon
  - We can use `card meta` for fields and badges for better field presentation
- Adjust the accordion design to allow [leading icons](https://design.gs.com/components/accordion#leading-icon)
  - There are alerts within the accordions on https://its.uiowa.edu/alerts
- Update the [Alert component](https://uids.brand.uiowa.edu/latest/?path=/story/components-alert--info&args=type:info;centered:false;iconVisible:true;dismissible:false;verticallyCentered:false) to be collapsible.

**Comment by joewhitsitt** [comment]
Thanks for the feedback @bspeare. I'll try some other things. There is an open-invite to others as well ;)

Personally, I am going to continue to avoid the accordion as I just don't think enough info can be displayed before the click. We can show off https://admissions.uiowa.edu/cost-aid/first-year-resident-scholarships (accordions with more initial detail), but it felt hacky at the time.

**Comment by joewhitsitt** [comment]
Here is a card based example with the calendar on the same page: https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-3

**Comment by e-marie-w** [comment]
These are looking great! Assuming the invite is still open I'm going to try my hand at one.

**Comment by joewhitsitt** [comment]
Based on further EoD feedback, https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-4 where more was moved into card__meta from https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-3.

I also mentioned I was setting things up so that "Service(s) affected," "Building(s) affected" would only display if multiple which is why the SiteNow one is just part of the constructed title. Not sure how the constructed titles will change for this, but something to keep in mind.

**Comment by joewhitsitt** [comment]
Overnight the one thing I was thinking about is that alerts will be displayed in other areas. Do these teaser styles still hold up when placed within a service? I think this was part of the concern when we groomed this work. Is there one teaser that works in different spots? Looking back, I noticed I have three types of renderings on the 4th version not counting the alert calendar. (outage/degradation (title, start date, what is affected if multiple, alert type), maintenance (title/date range), service announcement (title/start date/short desc)).

The alert type seems to be the main distinction from an article, event, etc.

**Comment by pyrello** [comment]
> Do these teaser styles still hold up when placed within a service? I think this was part of the concern when we groomed this work.

This was exactly the concern I expressed when we groomed this. I even suggested working on the mockup for the teaser/full page first so that we'd have that to use in this context. It is my understanding that the team chose to use this mockup task to do some of that teaser definition work here and that what is designed should be considered as to the other locations it will be displaying. 

I think we should try to achieve as consistent a treatment of the alert teaser in the various places it shows up as we can.

**Comment by pyrello** [comment]
For 3 and 4 (which appear to be the only versions that include the legend), I think the legend is too far away from the content that it appears to apply to.

**Comment by joewhitsitt** [comment]
The legend is more for the calendar only now since the cards aren't using colors/symbols and instead have the alert type as text within the alert. https://its.uiowa.edu/alerts/calendar

**Comment by joewhitsitt** [comment]
Worked with @bspeare to create this version: https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-5

- Style separation from most other teasers for degradation and outages. Will still look like an alert elsewhere.
- Title construction is tricky. It is an area to include details but depending on the content can get really long. Lead with alert type though.
- Services/buildings affected is still present to provide first-glance info without the click, but smaller and sans label.
- Move the header buttons down.
- Added view more button to alerts to take user to full alert details.
- Assumed pager for maintenance and service announcements to keep layout tight.

**Comment by joewhitsitt** [comment]
Uno màs: https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-6

- Attempt to reduce white space and increase calendar size for readability.
- Bring call to actions back up top.
- Styling service announcements similar and putting them with current alerts.
- Thinking ahead, when placed on a service page, I think planned maintenance should have a separate area since they are styled differently.

Started think about when there are no active alerts including service announcements:

<img width="1382" alt="Screenshot 2023-11-08 at 10 55 01 AM" src="https://github.com/uiowa/uiowa/assets/4663676/b99e2711-9e70-4e9f-97f9-4dff036936d8">

**Comment by bspeare** [comment]
@joewhitsitt that looks great! Do you mind if we use `fa-info` and `fa-check` instead of `fa-info-circle` and `fa-check-circle`?

**Comment by joewhitsitt** [comment]
Capturing feedback from the meeting (11/8) (mostly referenced https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-6 but touched on elements from other mockups.

- Page title is too big.
- Generally they like the styling but noted everything looks really big compared to before.
- Like the approach to call out the services and buildings to save a click, but thought that they should be unlinked. Focus should be on getting to the alert, not the service/building.
- Heading call to actions should be moved. Still eye catching but not taking up initial real estate
- Subscribe process is still currently clunky so using `Request access to alerts by emailing the ITS Help Desk.` language is preferred for now until they can automate it more. Need to make sure they are within the U and not outsiders.
- Instead of puzzle piecing different content together, lay it out with scrolling in mind. Planned maintenance is the least important, often biggest and can be placed at the bottom. No strong feelings about calendar being placed on the same page. Paging won't be used, just let it flow.
- Service announcements aren't many but they are the "big wow" for IT professional audience and are different than new services which get a news article. The SiteNow upgrade from d9 to d10 was probably a service announcement. Next time.
- Noticed the featured service history was not present, but liked the idea of an exposed filter page listing for both staff and visitors to filter on.
- Will need a spot for subscribing via RSS once that is added.

**Comment by joewhitsitt** [comment]
Initial take on the feedback in https://github.com/uiowa/uiowa/issues/7059#issuecomment-1802694020 https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-7

Also falls in order of priority for mobile.

Service announcements sound very much like news articles they want to send out in the email digest given that articles can reference a service and be scheduled now.

**Comment by joewhitsitt** [comment]
Looking for internal feedback on https://github.com/uiowa/uiowa/issues/7059#issuecomment-1802854109 before passing along to customers

**Comment by pyrello** [comment]
I like # 7. I think it does a better job of prioritizing the most important information and breaking things into sections to give the user clear segments to focus on. To further refine the information priority, I think we should swap the positions of the "Announcements" and "Alert Information" sidebars. Announcements seem lower priority on a page that is dedicated to service alerts.

> Noticed the featured service history was not present, but liked the idea of an exposed filter page listing for both staff and visitors to filter on.

Is this going to be a separate future task?

**Comment by joewhitsitt** [comment]
> Noticed the featured service history was not present, but liked the idea of an exposed filter page listing for both staff and visitors to filter on.
> >Is this going to be a separate future task?

There is a Status History task on the epic https://github.com/uiowa/uiowa/issues/5952

Based on what I described towards the end, Calendar/legend and Status History will be off this page. The mockup here has links for both.

**Comment by joewhitsitt** [comment]
Re-arranged the announcements and alert info and sent an email to the customers for review/feedback.

**Comment by joewhitsitt** [comment]
The ITS team has provided some responses via email and I just responded to a couple of the items.

Generally, I feel like the seventh iteration has been well received and there are just some minor items to sort out.

- Is the calendar still needed? If it is, should it be on the landing page or not.
- Alert history might need to be expanded to show upcoming as well, especially if a calendar is not provided.
- Making sure users know what type of alert is being shown needs to be finalized (section heading text, legend, title construction, other distinctions in the alert teaser).
- Any areas where the layout can be tightened up as the SiteNow v3 theme is a spacious departure from the current ITS website theme.

**Comment by joewhitsitt** [comment]
Though additional feedback might be incoming, IMO, the general styling surrounding the alert types doesn't seem to be a blocker anymore and that some views for the landing page could be developed based on the result of this issue.
