### ISSUE TITLE
Off-canvas tray default width is too wide in Safari and Firefox

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7115]
# Problem
Off-canvas tray default width is too wide in Safari and Firefox

# Steps to reproduce
Edit https://education.uiowa.edu/node/5076/layout events block in Safari or Firefox

<img width="1815" alt="Screenshot 2023-11-14 at 10 27 25 AM" src="https://github.com/uiowa/uiowa/assets/1036433/399e1510-e715-4839-b835-d5454b7ef389">

# Proposed solution

- There is a console error when the tray is first opened. Might want to start there. 
- Review Dustin's comments below to see if they point us in a direction https://github.com/uiowa/uiowa/issues/7115#issuecomment-1811443518.
- Potentially investigate cookies js to see if that could be causing any errors. 
- Check handle offscreen prevention calculation maybe.

**Comment by quamsta** [comment]
@bspeare 

Shot in the dark here, but could this be due to fields for the Events block like "Keywords" having really long values?

<img width="1619" alt="Screenshot 2023-11-14 at 1 51 21 PM" src="https://github.com/uiowa/uiowa/assets/472923/0e23b30b-0034-468c-b1ff-9873b8614b2f">

**Comment by quamsta** [comment]
That may be incorrect, tried a couple more sites, but it seems like almost any block will do this (e.g., Card block, Button block, not just Events) on both Safari and Firefox..

**Comment by bspeare** [comment]
Thanks for your testing @quamsta!

**Comment by quamsta** [comment]
A few more notes:

- It seems like opening the "Add section" dialog will reset the width of the off-canvas tray, so after opening and dismissing an "Add section" tray, then adding a block, this will "fix" the issue temporarily and the block's tray will be a reasonable size.
- Upon refreshing, adding blocks will cause the problematic behavior again.
- Upon refreshing or loading the page for the first time, blocks added by clicking "More..." and then selecting a block do not seem to exhibit the problematic off-canvas tray behavior,

**Comment by quamsta** [comment]
Sorry, this one was bugging me. After doing some local script debugging on [layout_builder_custom.overrides.js](https://github.com/uiowa/uiowa/blob/72b24c285d94194d718741f907b1817aae922b96/docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js), this line:

`if (Drupal.offCanvas.isOffCanvas($element) && $element.find('.layout-selection').length === 1) {`

Doesn't seem to ever return true, but if I remove the above conditional, the off-canvas tray seems to open at a reasonable size while still checking for a cookie preference (?) for the user's size preference. If I had to guess, the bug lies somewhere in that neighborhood.

https://github.com/uiowa/uiowa/blob/72b24c285d94194d718741f907b1817aae922b96/docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js#L29

**Comment by quamsta** [comment]
Additionally, if the check for `.layout-selection` is removed, e.g.:

`if (Drupal.offCanvas.isOffCanvas($element)) { `

The statement will return true and the tray will open at a reasonable size.

**Comment by briand44** [comment]
just mentioning, I had noticed this in Chrome as well so I don't think it is limited to just Safari and Firefox.

**Comment by briand44** [comment]
Grooming conversation... There is a console error when the tray is first opened. Might want to start there. Potentially investigate cookies js to see if that could be causing any errors. Check handle offscreen prevention calculation maybe.

**Comment by bspeare** [comment]
Took a "small" look at this.  I didn't see any console errors and Dustin's suggestions did not seem to have an affect on the functionality.  I unassigned myself if someone else wants to take a look.

**Comment by e-marie-w** [comment]
Quick summary of my investigation so far:

I do see the console errors, but only in certain browsers and only on prod, I don't ever seem them locally. Because of that and because the line the error points to mentions SiteImprove I'm going to say it's a separate issue.

While trying to figure out how the width is set I ended up in the same spot Dustin did. Removing the conditional also works for me. But I'm still not sure what it's supposed to be doing so I'm hesitant to remove it without knowing more. 

I dug back to see more about the conditional. It was previously set to 0 but changed to 1 in the Upgrade to Drupal 10.0 issue, specifically [this commit](https://github.com/uiowa/uiowa/pull/6994/commits/b08ef3832363170ac0693a9aab99531b006f2f0e). If I set it back to 0 I see the same behavior as removing it entirely. 

However, changing it to 0 or removing the conditional changes some styling randomly on Brave (Chromium) but not on Firefox. I can post screenshots. Again, I'd like to understand all this better before we commit to removing it.

**Comment by e-marie-w** [comment]
Summary of where I'm at now. 

I mostly can follow [this section](https://github.com/uiowa/uiowa/blob/535ed28f1e642939f4bd3f1113034a88f012c2f5/docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js#L29C3-L29C3). If I understand it correctly, this is what triggers when you open the tray, and the tray width is then set to the default or a previously saved value. 

The [next part](https://github.com/uiowa/uiowa/blob/535ed28f1e642939f4bd3f1113034a88f012c2f5/docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js#L41) is where I struggle. It does not fire every time I open the tray. It also does not update the width every time it does fire and I have changed the tray width. 

I thought it might rely on if I save the block, or the entire layout, but so far I can't connect anything to when it does or doesn't fire and/or updates the width. Also I know it only fires if justChecked = False but I don't understand why that if statement is necessary, just that when I tried to remove it it caused new problems. 

Maybe I'm looking at the wrong section of code. I'm going to check out the dragHandle functions next.

**Comment by joewhitsitt** [comment]
willing to take a look at this. thanks for the write-up

**Comment by joewhitsitt** [comment]
Similar to https://github.com/uiowa/uiowa/issues/7115#issuecomment-1811450608, Without the check on `layout-selection` this is working pretty well. I am not finding `layout-selection` anywhere in the DOM so I can't see why it would ever match the check. I think removing that is the main "fix" here unless we recall what we were acting upon and finding a suitable alternative to target instead.

For the most part I think this is working pretty well in a browser that allows cookies to be set. From my testing as-is, it doesn't set it the first time because `justCreated` is true initially, but then that is set to false and a cookie is established. So we could do a check for an existing cookie initially if we wanted this to work right away.

As for it not setting every time, it seems to be one set width behind which may have to do with the combination of listeners for mousemove and mouseup and the delay so that we aren't setting every millisecond.

**Comment by e-marie-w** [comment]
Thank you so much for taking a look at this!!

**Comment by pyrello** [comment]
I think the bug here is related to a core bug: https://www.drupal.org/project/drupal/issues/3359465

The behavior we see is part of our workarounds to try to adjust for the core bug. @GaryRidgway came up with some clever hacks to kind of get around the behavior. However, looking at the core issue, it seems like the bug was introduced as a fix to random test failures that were happening (and it is speculated in the original issue that the random test failures probably corresponded to random intermittent real world failures of the same variety). The change that caused the issue above was changing a boolean from `FALSE` to `TRUE` in a `Drupal.debounce` call. To me, this indicates that neither state works completely and probably the whole thing needs to be revamped to work coherently. 

I would eventually like to see us get to a point where our solution for this is as close to core's as we can get it. While our current set of "fixes" mostly works, it has been buggy (as evidenced by this and previous issues), it has a lot of moving parts that are difficult to understand, and because it depends on the core logic to some extent is probably always going to be at least a little bit buggy. I think the addition of the patch from the issue linked above could be a good enough solution for now.

**Comment by pyrello** [comment]
I opened https://www.drupal.org/project/drupal/issues/3411496 as hopefully the starting point for more long term solutions to this issue.
