### ISSUE TITLE
Admissions student profile select list updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7130]
> We need to update the dates listed in the “Anticipated graduation date” drop-down in the Admissions student profile content type.
> Remove: Spring 21, Fall 21, Spring 22, Fall 22, Spring 23, Fall 23.
> Add: Spring 27, Fall 27, Spring 28, Fall 28, Spring 29, Fall 29, Spring 30, Fall 30.

I think we painted ourselves into a corner on this one by not using the in-code allowed options function. Not sure we can add/remove options currently. config/sites/admissions.uiowa.edu/field.storage.node.field_student_profile_grad_date.yml - @joewhitsitt 

# Proposed Solution

- [ ] Add: Spring 2027, Fall 2027, Spring 2028, Fall 2028, Spring 2029, Fall 2029, Spring 2030, Fall 2030 through config

**Comment by joewhitsitt** [comment]
If it is the same situation, docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/pharmacy_core.install has an example.

From https://github.com/uiowa/uiowa/pull/6574

**Comment by joewhitsitt** [comment]
Grooming convo:

Not sure if this content is output anywhere. Bug perhaps from card_4x layout refactor?

Concern that this is just a short term solution because new semesters will be added/removed and that the current solution requires developer interaction. So with these options we need to consider if it is less work to change to a taxonomy based field.

- Try to make the changes through the config. If bumps...
- Try to delete the student profile existing content and see if that sticks then. If successful consult with customer to update existing content before deployment. If bumps...
- Move to allowed options method or long term solution, rabbit hole taxonomy or MAUI integration.

**Comment by briand44** [comment]
I reached out for clarity on how the anticipated graduation date field is being used and about removing old ones.

>It’s for internal tracking mainly. I’m ok with leaving in the old numbers - we just need to be able to have more future sessions listed in the drop-down.
