### ISSUE TITLE
Prioritize customized D7 site list

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7160]

**Comment by pyrello** [comment]
Is this still important? Should we plan it through our normal process? It seems to have entered zombie status.

**Comment by briand44** [comment]
I don't think this issue is useful currently. I have prioritized some of the sites needing custom development but don't think it is useful prioritizing every site at this point. Too many things change where the priority will continue to evolve over time. This is just something I need to be doing as part of my regular duties. Going to close this.
