### ISSUE TITLE
Bug report for the Genetics site that some menu items can't be deleted

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7230]
## Proposed solution
- Remove menu links from custom view.
- Add links on the Genetics site.

## Original report

UPDATE: there is a people custom view with the following paths/menu links hardcoded as part of config:

```
Page ([/people/faculty](https://genetics.grad.uiowa.edu/people/faculty))
Page ([/people/students](https://genetics.grad.uiowa.edu/people/students))
Page ([/people/students/former](https://genetics.grad.uiowa.edu/people/students/former))
```

From Makur:

> We noticed that the delete option doesn’t work for some of the enabled (Past Students) disabled (Faculty) menu items here: https://genetics.grad.uiowa.edu/admin/structure/menu/manage/main. See screenshot below.
>
> We also noticed in the past that disabled items were showing up in the menu. Right now, this is not an issue as it was fixed, but wanted to bring it up in case it was similar to the AMCS menu bug from earlier this year where the links were hard-coded and overwriting the UI.
>
> ![Image](https://github.com/uiowa/uiowa/assets/709009/cf0d85be-88aa-46bf-adcf-252d3fc55dc7)

**Comment by makurj** [comment]
User said the duplicate items were displaying again on 12/22. "They randomly all switched back to enabled, and reordered themselves within the menu structure…weird. I had all of the disabled links at the bottom." This was either automatically resolved or by one of my team members and fixed by 12/26.

![image](https://github.com/uiowa/uiowa/assets/52135878/7c9ce892-de4b-461b-95f1-2dd4871cdc1d)

**Comment by makurj** [comment]
From user: "I just ask that OSC fixes it [the bug] quickly. All of our applicants for 2024 are visiting our website right now and I want our best foot forward."
