### ISSUE TITLE
Send second email comms to SiteNow v1 Standard

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7296]
- We will need to re-run the report to get the population before sending.
- Schedule and send comms.

**Comment by briand44** [comment]
blocked until Jan 31st?

**Comment by pyrello** [comment]
I'm going to work on this today.

**Comment by pyrello** [comment]
The following happened today:
- I ran the email report command to generate a CSV of emails and domains
- I pasted in to the Dispatch population
- I validated the Dispatch population to get the list of invalid emails and created a CSV file from them.
- I used the python script I wrote previously for #7156 to remove the invalid emails.
- I realized that the branch I was on was out-of-date because it included idcard.uiowa.edu, which was recently provisioned. This meant I needed to start over. I went through the whole process again.
- There was some last minute conversation about changing the headline, which was changed to be the same as the previous email with `Reminder: ` prepended to it.
- I scheduled the communication and the emails went out.
