### ISSUE TITLE
CKEditor buttons hiding Add Block button

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#7300]
# Problem
Sometimes when I'm editing a block and scroll down, the editor fields will appear and block the button to Add Block.

Browser: Firefox

https://github.com/uiowa/uiowa/assets/731952/483108a7-2848-497e-9ddb-160186d37861

**Comment by quamsta** [comment]
@bewoldt This is also happening to me in Edge, but weirdly not Chrome

Edge version:

`Version 120.0.2210.144 (Official build) (arm64)`

**Comment by bewoldt** [comment]
It tends to happen when you leave mouse focus in the text area then scroll down.

**Comment by joewhitsitt** [comment]
Thanks for the report. I can confirm it too in Brave (chromium) depending on the length of the block config and the placement of the text area. If user clicks out of the editor, the tool bar and the ckeditor logo resets and the save/update button is visible. I haven't checked the upstream issue queues yet.

**Comment by quamsta** [comment]
@bewoldt @joewhitsitt 

Hi, so I've been working on a site redesign and CKEditor's toolbar covering up the Update Block/Add Block button has really been slowing me down. The toolbar covers up the button almost every single time now.

It appears that CKEditor is applying a class: 

`ck-sticky-panel__content_sticky_bottom-limit` when it detects that we're at the "bottom" of a wrapper containing CKEditor. It also applies the inline style: `width: 535px; bottom: 50px;` to the div containing the toolbar, aka `ck-sticky-panel__content` when we hit the "bottom." This div has also made "sticky" by it being set to `position: absolute;`.

This means the `bottom: 50px;` inline style being applied to `ck-sticky-panel__content` is absolutely positioning the toolbar at the bottom of the nearest-in-hierarchy div that is `position: relative;` which in this case I believe is `.ui-dialog-content`.

This seems like baked-in behavior from CKEditor that's expecting the div containing the editor to be `position: relative;` (or `position: absolute;`) so that the sticky toolbar can behave properly.

So, if we make the `.form-textarea-wrapper` `position: relative` so that the absolutely positioned div is locked to `.form-area-textarea-wrapper`, then the problematic behavior goes away:

```
.form-textarea-wrapper{
   position: relative;
}
```
I'm not sure what the far-reaching consequences of making this wrapper `position:relative;` may be but it does fix the issue and may deserve some testing.

**Comment by quamsta** [comment]
Added a forked PR here. Not sure how those work, really.

**Comment by bspeare** [comment]
Tested this on simplytest.me for Drupal 10.2.4 and this is still an issue.  Should we create an issue and patch on drupal.org instead of https://github.com/uiowa/uiowa/pull/7437?

**Comment by joewhitsitt** [comment]
Nice thought. I haven't looked for existing issues

**Comment by joewhitsitt** [comment]
>Tested this on simplytest.me for Drupal 10.2.4 and this is still an issue.

@bspeare I don't suppose you have a video, gif, screenshot of that test to use for an upstream issue? I'd be fine with this local fix that has a todo comment linking to the upstream issue to remove once something is in-place.

This would bring some immediate relief to site editors.

**Comment by joewhitsitt** [comment]
I did the one-click Umami Demo 10.2.4 and couldn't reproduce. What was noticeable was that the ckeditor branding was not there like we have on ours.


https://github.com/uiowa/uiowa/assets/4663676/4bb85130-56fe-4389-b976-57d2a192ac17

**Comment by joewhitsitt** [comment]
And I haven't seen any issues describing this in [drupal](https://www.drupal.org/project/issues/drupal?component=ckeditor5.module) [ckeditor](https://github.com/ckeditor/ckeditor5/issues) issue queues. I have see stuff about z-index (conflict with admin toolbar) and responsiveness (overflow on viewport resize) though.

**Comment by bspeare** [comment]
It happens on blocks with a lot of fields. 

1. https://simplytest.me/
2. Chose `layout_builder_styles` to install Drupal 10.2.4 site with layout builder enabled
3. Login and enable layout builder for page content type
4. Add 6-7 fields to the default block
5. Edit page
6. Set focus within WYSIWYG
7. Scroll slowly down the page
8. Could be Claro specific?

<img width="1675" alt="Screenshot 2024-03-08 at 11 05 50 AM" src="https://github.com/uiowa/uiowa/assets/1036433/7dbab0f8-ba50-46f1-8ae5-7b534cbbfd48">
<img width="1682" alt="Screenshot 2024-03-08 at 11 05 58 AM" src="https://github.com/uiowa/uiowa/assets/1036433/53ae7fb5-3a0a-40ba-be2a-fee75517597f">


https://github.com/uiowa/uiowa/assets/1036433/dbcc7553-3cfb-42e4-aefd-2a14fad7ba26

**Comment by joewhitsitt** [comment]
ugh. can't reproduce still in brave. i didn't have layout_builder_styles enabled because I was trying to pin this issue to core. also started with textfields but then added long text to try and make it long enough. normal viewport size too.

my worry it making it as simple as possible to reproduce for the upstream issue.

https://github.com/uiowa/uiowa/assets/4663676/28ce38aa-0fb9-4608-b47c-674ad734b275

**Comment by quamsta** [comment]
@bspeare @joewhitsitt 
That's a neat testing tool, I can play around with it too to see if I can more reliably reproduce the issue. IMHO it looks like the issue may be dependent on which fields are appearing and in which order?

**Comment by quamsta** [comment]
> I'd be fine with this local fix that has a todo comment linking to the upstream issue to remove once something is in-place. This would bring some immediate relief to site editors.

But I'd also agree that merging in this PR may be good idea for now, whatever our field/block setup is, it seems to reliably exhibit this issue.
