### ISSUE TITLE
Probe solutions for Policy Manual website in V3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7306]
# Story

As a web team, we would like to understand if existing functionality within v3 can meet the needs of the Policy Manual website so we have a better understanding if any custom development is necessary to transition this site.

# Additional Information

Current website - https://opsmanual.uiowa.edu

Some notable items related to the current site:
- Currently using red font and strikethrough to show changes to policies.
- Table of contents.
- Hierarchical structure of policy information
- Numbering of chapters, etc. seemed important to some larger internal audiences like Provost, HR, etc.
- Have a yearly archive that is produced in pdf format using Firefox as well as a library archive.
- Open to moving the department (e.g. Office of the General Counsel https://opsmanual.uiowa.edu/governance) to the chapter page rather than outputting below.
- Also seemed open to only displaying sub-chapters(?) as a link to separate page rather than both link and outputting info below (https://opsmanual.uiowa.edu/governance/board-regents).
- There is a lot of content and they lack content resources.

https://policy.clas.uiowa.edu/ is another policy type website that currently is on V3.

# Proposed solution

- Put together an example prototype with existing v3 functionality. Possibly portion of a table of contents and a few pages from a couple chapters.
- Handling of policy changes (Do we have a better way to handle this than allowing red font)?
- Keep in mind the possibility of having to migrate content from existing site and any concerns with that.

**Comment by joewhitsitt** [comment]
Given the recent struggles with memory on whitmanweb, we will have to be careful with scaling any solution here.

**Comment by briand44** [comment]
Grooming conversation.. Some concerns with book module as far as input vars, memory consumption, etc. based on large overview page. Also Sean mentioned some additional downsides with the book forward and back navigation.

From Max:
> PolicyTech is a 3rd party tool UI Health Care invested in to manage and store all of our patient care related policies “all…” “some” “most?”
> 
> I have no knowledge of the contract, or if this tool has potential for a broader university tooling. But happy to make a warm lead connection to the compliance team member I have connected with regarding PolicyTech instance to explore if desired…

https://grad.uiowa.edu/academics/manual may be similar as well.

**Comment by quamsta** [comment]
@briand44 poking my head in here to say I've had some experience working in PolicyTech and providing some solutions to the Department of Pathology over here for transitioning policy documents over from an older Intranet site to PolicyTech.

A couple of observations just from a purely technical standpoint re: PolicyTech:

- PolicyTech purely manages **document** files as far as I can tell. E.g., PDFs, Word Documents, Excel, etc. If the Ops Manual folks are okay transitioning to a purely document-based system instead of web/HTML documents for their manual, that could work, but they'd likely need to generate the new documents.
- Edit: the above documents are presented in an Office 365 webapp-like environment in the web browser though, they aren't just downloaded or something similar.
- It's difficult to generate canonical links to the "latest" version of a policy/document. URLs seem to expire as soon as a newer version of a document is uploaded. This has been a bit frustrating to work around, since we often want to link to the latest version of a policy/document, but they expire quickly if a modification has been made. There are some workarounds that I've developed specifically for the transition between locally stored documents -> PolicyTech, but they're a bit messy.

**Comment by mjoneill** [comment]
[like]  O'Neill, Michael J reacted to your message:
________________________________
From: Dustin Quam ***@***.***>
Sent: Wednesday, February 21, 2024 7:55:55 PM
To: uiowa/uiowa ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] Re: [uiowa/uiowa] Probe solutions for Policy Manual website in V3 (Issue #7306)


@briand44<https://github.com/briand44> poking my head in here to say I've had some experience working in PolicyTech and providing some solutions to the Department of Pathology over here for transitioning policy documents over from an older Intranet site to PolicyTech.

A couple of observations just from a purely technical standpoint re: PolicyTech:

  *   PolicyTech purely manages document files as far as I can tell. E.g., PDFs, Word Documents, Excel, etc. If the Ops Manual folks are okay transitioning to a purely document-based system instead of web/HTML documents for their manual, that could work, but they'd likely need to generate the new documents.
  *   It's difficult to generate canonical links to the "latest" version of a policy/document. URLs seem to expire as soon as a newer version of a document is uploaded. This has been a bit frustrating to work around, since we often want to link to the latest version of a policy/document, but they expire quickly if a modification has been made. There are some workarounds that I've developed specifically for the transition between locally stored documents -> PolicyTech, but they're a bit messy.

**Comment by quamsta** [comment]
Additionally, at the Division of Student Life before I left, we were utilizing the UI Libraries Special Collections and Archives department for a browsable set of archived policies on the Dean of Students website, after moving on from a custom solution in our previous platform:

https://dos.uiowa.edu/policies

**Comment by pyrello** [comment]
I'm going to take a look at this.

**Comment by pyrello** [comment]
Early look: https://sandbox.prod.drupal.uiowa.edu/policy-manual/table-contents

**Comment by pyrello** [comment]
A couple issues with the approach I've taken: 
- The current policy manual sometimes provides additional text below a link to a section. Using the menu to represent sections doesn't allow you to do this. We could potentially add a small customization that would allow using the Description field to be output, which could work if the text never needed to be formatted.
- The menu block is currently limited to showing 3 levels of links. We would need to expand this to 4 to show the last level that is currently not showing on https://sandbox.prod.drupal.uiowa.edu/policy-manual/table-contents

**Comment by briand44** [comment]
@pyrello regarding your first point, if I'm understanding what you are referring to, I think Policy Manual folks were open to that text moving to the section page rather than displaying under the link. @bspeare am I correct here?

**Comment by bspeare** [comment]
@briand44 Yes, they are open to that text appearing on the section page and not on the table of contents.

**Comment by pyrello** [comment]
I'm ready for another member of the team to review this.

**Comment by joewhitsitt** [comment]
>Have a yearly archive that is produced in pdf format using Firefox as well as a library archive.

Curious to know more about what this is and how we might solve for it.

**Comment by joewhitsitt** [comment]
I didn't mean to stop others from reviewing this with my comment above ;)

Generally I think this works based on my understanding of what is needed. Not sure how much work is involved with allowing 4 levels deep or why we limited it in the first place.

Editors will have to make sure the sorting stays as expected: https://sandbox.prod.drupal.uiowa.edu/policy-manual/ii-community-policies

I think this is worth putting in front of the customer as a low-tech solution to their content needs.

I wonder the difference in workflow. How much more work is it to establish these anchor/links compared to something like the Book module or is that something on the current website that is largely the same process? I assume the recommendation is to manually move the content. Just trying to get an idea of how big of an ask that will be.

[Still curious](https://github.com/uiowa/uiowa/issues/7306#issuecomment-1961508209) to know how we would approach some of their current functionality or if those are still needs to go live. Does something like entity print bring together multiple pages?

>Currently using red font and strikethrough to show changes to policies.

@pyrello did you think about how they would represent their changelog this time around? I think I had mentioned making sure `<mark>` was allowed in the WYSIWYG possibilty with the class support to designate different colors that meet contrast ratio requirements (warning, danger, etc.)

**Comment by pyrello** [comment]
> > Have a yearly archive that is produced in pdf format using Firefox as well as a library archive.
> 
> Curious to know more about what this is and how we might solve for it.

My understanding of this is that they are using a browser plugin (read: third-party tool) to generate their PDFs so was not considering that in scope.

**Comment by pyrello** [comment]
> Editors will have to make sure the sorting stays as expected: https://sandbox.prod.drupal.uiowa.edu/policy-manual/ii-community-policies

This is just my sloppiness in not moving the menu items to the correct spot. There should be no concern about things moving around if the menu is structured correctly.

**Comment by pyrello** [comment]
> Handling of policy changes (Do we have a better way to handle this than allowing red font)?

It appears that the `<s>` tag is allowed currently: https://sandbox.prod.drupal.uiowa.edu/policy-manual/ii-community-policies. Classes are not currently allowed for the `<s>` tag, so it would be necessary to add that to be able to change the color, if that is necessary. Alternately, a new pattern could be established using `<em>` to wrap newly added text to avoid having to add colors.

**Comment by pyrello** [comment]
As best as I can tell, here is the current structure on the Policy site:
- Headings - Just a number and a title
- Divisions - These denote major sections a level above chapters and consist of just a number and a title. They are not always used.
- Chapters - Reference a heading and optionally a division and consist of a title, number and optionally a sponsor.
- Sub-chapters - This is where all the content actually lives. References an article parent, which I think can be a chapter or sub-chapter. Consists of a number, title, optional sponsor, optional amended text, and the body.

Basic pages are used to build out the What's Changed page and the redlined versions of content changes (https://opsmanual.uiowa.edu/i-21-purpose-and-mission).

> Keep in mind the possibility of having to migrate content from existing site and any concerns with that.

It was indicated that the team that runs this website doesn't have a lot of capacity for migrating content or making content changes. I don't believe there is any scenario where we can make it easy or quick to manually migrate content. If we exactly recreate their existing content types, the manual migration process would be slow and take a long time based on how many pieces of content would have to be touched. If they switch to a version using basic pages, there is going to be some process of getting the old content appropriately cleaned up (read: stripped of unnecessary markup) before it can be put in. There would be dramatically fewer pages to create since a lot of the content items in the sub-chapters would be getting consolidated to fewer basic pages. The time-consuming aspect of the approach I have demonstrated is building out the menu using anchor links. My intuition is that this would take less time still than manually migrating content into the old format.

If we are looking at an automated migration, I believe it would be possible to build an automated process around this. I'm not sure if our process using the migration modules would work because there is not a one-to-one relationship between the old content and the new content. However, the sub-chapter content provides a structured outline of the whole policy content hierarchy, so I think we could utilize that for some type of migration solution.

> I wonder the difference in workflow. How much more work is it to establish these anchor/links compared to something like the Book module or is that something on the current website that is largely the same process? I assume the recommendation is to manually move the content. Just trying to get an idea of how big of an ask that will be.

Its hard to evaluate the difference in workflow between the book module and the proposed solution using existing functionality without investigating that specifically. I would consider that out of scope for this task.
