### ISSUE TITLE
Additional SiteNow Docs - Content Blocks

### ISSUE THREAD

**Issue by ethanstjohn** [uiowa/uiowa#732]
- [x] Update the content blocks available list.

- [x] Documentation for Carousel.
pro tip: You can have a full width carousel by setting the section width to large and the carousel column width to full.

- [x] Documentation for Card.

- [x] Docs for Accordion.

- [x] Docs for Webform.

**Comment by ethanstjohn** [comment]
I have added the above listed documentation. It would be great to hear some feedback on them :)
https://sitenow.uiowa.edu/documentation/content-blocks

**Comment by joewhitsitt** [comment]
A little feedback as I am going through these:

- "Paragraphs" are internal developer terminology and "Content Blocks" was what we decided should be the customer facing terminology when talking about them or providing documentation.
- Just because you can, doesn't mean you should breakup body content into multiple content blocks. Unless you need to break body content to provide unique ids for links or insert a blockquote, we should just start typing in the default body that is provided on node add.
- Personal opinion, the alternating background colors cause problems later when we want change block order or insert new blocks.
- Some of the language is redundant (content block settings) or inconsistent (break down of each field on one, but not the other). For these individual docs, we should be providing a brief intro of what it does and how it is different.

I think these points could actually be compiled into a wiki article about writing best practices, but that is for another day.
