### ISSUE TITLE
Whitman Web memory errors

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7335]
# Problem

Site editors get a temporary unavailable message when attempting to add pages. https://whitmanweb.iwp.uiowa.edu/node/add/page.

Site editors receiving AJAX errors when editing the main navigation block on this page: https://whitmanweb.iwp.uiowa.edu/node/3296/layout

Slack thread https://iowaweb.slack.com/archives/C0164FNN1PV/p1706806853636769

# Steps to reproduce

# Proposed solution

- ~~Increase memory limit for this site for the paths needed https://github.com/uiowa/uiowa/issues/7335#issuecomment-1932722859~~
- Dig to understand the issue better
- investigate Ben and Joes alternate solutions.
- May need to up memory temporarily in order to move forward with alternate solution
- https://github.com/uiowa/uiowa/issues/7335#issuecomment-1944481138

**Comment by briand44** [comment]
Mara suggested a possible change in menu structure in an email in its-web.

**Comment by joewhitsitt** [comment]
This is affecting deployments too... https://iowaweb.slack.com/archives/CSQA18BK4/p1707171150639339

**Comment by pyrello** [comment]
> This is affecting deployments too... https://iowaweb.slack.com/archives/CSQA18BK4/p1707171150639339

I was just reading this and wondering if maybe its related.

**Comment by joewhitsitt** [comment]
I was thinking that this will have to be brought down locally. If reproducible in the local environment, I'd start with breakpoints in menu_link_weight, menublock, menu_per_admin_menu. Perhaps trying to disable menu_link_weight and menu_per_admin_menu to see if that changes anything. We have a lot of extra layered on now that I have been thinking about it and I am sure all of these do additional access checks that add up. Otherwise getting some breakpoint to trigger early in a request (e.g. form_alter) and step into everything till the point it fails might help us zero in on what might be pushing it over the edge.

**Comment by briand44** [comment]
Grooming conversation... Increase memory limit for this site for the specific paths needed. Ben had tested setting memory limit to 256 and that solved the issue locally.

admin/structure/types/manage/page and node/*

**Comment by pyrello** [comment]
Pulling this in from the Slack thread for quicker reference:

> Here is the path to the site-specific file that I think exists on AC: /var/www/site-php/{$ah_group}/whitmanweb_iwp_uiowa_edu-settings.inc

My suggestion is that we could implement this change by editing that file.

**Comment by joewhitsitt** [comment]
Can we update this file instead and track it in git? https://github.com/uiowa/uiowa/blob/main/docroot/sites/whitmanweb.iwp.uiowa.edu/settings.php

**Comment by joewhitsitt** [comment]
Out of curiousity... 4858 and counting menu link content processed all at once without big menu.

Each one is called as part of buildOverviewForm in docroot/core/modules/menu_ui/src/MenuForm.php

"Form constructor to edit an entire menu tree at once."

**Comment by pyrello** [comment]
> Grooming conversation... Increase memory limit for this site for the specific paths needed. Ben had tested setting memory limit to 256 and that solved the issue locally.
> 
> admin/structure/types/manage/page and node/*

`admin/structure/types/manage/page` does seem to be affected, however this is not a page we should be accessing and making changes to in production since everything from it is stored in configuration. So I don't think we need to include this.

I'm not sure how we came up with those as the paths, but I think we actually need these:
- `node/add/page`
- `node/$nid/layout`

I'm also not encountering any issues with the `admin/structure/menu/manage/main` at 128 MB. I think this is because it is using big menu and it doesn't display the whole menu. This was the case even after I cleared cache and hit the page fresh.

Underscoring how the proposed solution is a temporary workaround, I wasn't able to clear the caches for the site with the memory limit set to `128M`. This makes me think that clearing caches is probably just regularly failing for this site. I'm guessing there is a way we could detect that we are in the context of a drush command being run and similarly change the memory limit, but I'm not sure how to do it off the top of my head.

**Comment by pyrello** [comment]
I was able to adjust the PHP `memory_limit` setting by setting up a custom DDEV include for PHP following the instructions at https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-php-configuration-phpini. I think we should probably include this file in the repo so that DDEV is running with the same amount of memory as the production application, so we can see these issues locally without having to adjust settings.

**Comment by joewhitsitt** [comment]
When you mentioned cache I started to wonder if there is a overwhelmed purge queue on the site. I know that in the past with significant menu changes, purge gets a huge list of paths it needs to clear. In d7 there was `ap_forget` which cleared the current queue. Curious if there is any issue surrounding that here.

**Comment by makurj** [comment]
IWP would like assurance that upping the memory will "permanently resolve" the menu issues, even when we add a new language with 52 children pages next spring.

**Comment by briand44** [comment]
Because we can’t assure a permanent fix, we will be looking into other possible long-term sustainable solutions..

Grooming conversation.... Ben did some probing of this previously and saw some options that could reduce amount of menu items. Also discussed that this may not be the last site with lots of menu items (Policy Manual perhaps) so trying to understand the issue a little better would be useful. Joe mentioned related content reference field similar to HR to reduce overall menu items.

- Dig to understand the issue better
- investigate Ben and Joes alternate solutions.
- May need to up memory temporarily in order to move forward with alternate solution

**Comment by bspeare** [comment]
# Alternative solution
For each translated page, like https://whitmanweb.iwp.uiowa.edu/song-myself/languages/deutsch-german/abschnitt-48
- In a related content field or the layout, add featured content list featuring all of the language overview pages (https://whitmanweb.iwp.uiowa.edu/song-myself/languages/espanol-spanish).
- Remove the translated page from the menu system
- Uncheck "generate url alias"
- Might need to clone and delete original to get breadcrumbs working
- The only items that need to be in the menu are the language overview pages https://whitmanweb.iwp.uiowa.edu/song-myself/languages/espanol-spanish.   All of the individual pages can use the same url structure like `song-myself/languages/espanol-spanish/seccion-15` and still have the correct breadcrumbs appear without being in the menu. 

<details>

<img width="483" alt="Screenshot 2024-02-14 at 1 59 14 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d11f0dc8-9a27-4004-b8c5-de6db8057b72">

![Screenshot 2024-02-06 at 16-26-43 Abschnitt 12](https://github.com/uiowa/uiowa/assets/1036433/4a9d3d9d-52ad-4020-b79c-73a06232854a)


</details>

**Comment by joewhitsitt** [comment]
Just to add a bit more detail, to the "related content reference field," this [was something originally added to HR](https://github.com/uiowa/uiowa/blob/main/config/sites/hr.uiowa.edu/field.field.node.page.field_related_content.yml) for them to use to essentially create non-menu call to action links for there content to items (page, article, etc.) that live elsewhere in there menu. By adding this field to the default, it would make HR's transition easier, but move items out of the menu system. The drag and drop order can be controlled by web editors and the field block could be made available for placement by layout builder users. The field block could be added to the default template similar to the active menu block.

I mentioned in grooming that with the field set to "unlimited" we need to be aware of how many items can be added to this and how it will be displayed on the page.

Obviously breadcrumbs would be lost with this solution, but being field based on the node, we are better positioned to create a reverse relationship to the child in the future (e.g. backlinks) if needed.

By adding this to the default, they would remain "standard"

**Comment by makurj** [comment]
Thanks all.

Regarding https://github.com/uiowa/uiowa/issues/7335#issuecomment-1944507369, is each link under "Other Available Languages" going to Section 12's translation in the other languages, or to the [language "table of contents"](https://whitmanweb.iwp.uiowa.edu/song-myself/languages/bahasa-melayu-malay) type page? They feel quite strongly about wanting each section having a way to see that exact section in other languages from the page.

**Comment by bspeare** [comment]
@makurj I was thinking the "table of contents" page, but if you were using a related content field or the featured content block you could set those links to be Section 12 specific.

**Comment by makurj** [comment]
Checked with IWP and a variation of the alternate solution will work (thanks @bspeare ), effectively eliminating the large menu issue. So if the site can be fixed to function again, we can work on implementing the solution.

**Comment by cory-skeers** [comment]
Poked a little at this debugging, and there are two separate points where I'm seeing it fail.

The first is in `Drupal\Core\Cache\DatabaseBackend`, line 172, it choking on trying to unserialize the later menu_link_item cache entity data.

When manually deleting that, it chokes on `/var/www/html/docroot/core/includes/form.inc on line 112`, in what looks like during the caching process in re-caching those menu link items, but I'm less clear on that part.

Edit: It's my inclination that it's not actually the caching that's the issue, but that this indicates an issue where it's (trying to) hold all menu items in data while it loads from / writes to cache, and eventually runs out of workable memory at around 4913 menu items. Which is what we were suspecting, but this might help direct to the more specific point of failure.

**Comment by joewhitsitt** [comment]
Taking a look at this as well. Not squatting

**Comment by joewhitsitt** [comment]
Ran into similar stops as Cory. Also docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.phpL548 while attempting a cache rebuild through the CLI. I imagine this is the same area that chokes during deployment. menu_link_content creates revisions which is necessary, but probably also taxing. Not sure if that gets auto cleaned up or not at any point.

Tried uninstalling menu_link_weight (errored of course) as I saw CSHS was processing during the Drupal\Core\Cache\DatabaseBackend calls. Either I was unable to successfully uninstall the module or it had no effect when trying to view the node/add/page

Same issues on ACN stage. Kubernetes does not magically save the day here. Factoid: PHP APCu is lower on ACN stage. Probably just a non-production env diff.

Just checked in on the memory requirements for Drupal:

>Typically 128 MB or 256 MB are found in production systems. Some installations may require much more, especially with media-rich implementations. If you are using a hosting service it is important to verify that your host can provide sufficient memory for the set of modules you are deploying or may deploy in the future. https://www.drupal.org/docs/getting-started/system-requirements/php-requirements#s-memory-requirements

Might want to get an explainer from Acquia on the feasibility of that for our hardware and our multisite situation.

Tried a random patch which didn't seem to help https://www.drupal.org/project/drupal/issues/3249147

**Comment by joewhitsitt** [comment]
Something I feel we have avoided talking about is the book module. Yes, it is officially on the way out of core and into contrib (just like aggregator), but it captures the hierarchy in smaller footprint than menu_link_content and might be what is necessary for policymanual similar to policy.clas.

**Comment by joewhitsitt** [comment]
I had forgotten we had already added this from HR for articles in the default. https://github.com/uiowa/uiowa/pull/5623

**Comment by joewhitsitt** [comment]
>Something I feel we have avoided talking about is the book module

Actually, this was previously investigated back when the site was going to use a different content structure. https://github.com/uiowa/uiowa/issues/3868

Just seeing the size of the content we are talking about now just makes me think it will be easier to maintain as book instead of using parent down relationship (related content field or featured content block)

Noticed that https://whitmanweb.iwp.uiowa.edu/song-myself/languages/english/section-2 type pages have their own next/previous navigation that would be automated as part of the book module. Additional concerns about navigation might be solved by https://www.drupal.org/project/custom_book_block

We could potentially automate the transition by establishing the top-level book nodes, looping through menu_link_content_data in tree order getting `link__url`, `weight`, loading `parent` then loading the entity node designating the parent, setting the weight and saving the node. A subsequent load can loop through and unset them from the menu.

**Comment by joewhitsitt** [comment]
After looking into it more, moving to book is not easy peasy and it won't all be roses in the end. The big win would be a separate/simpler db table with automatic navigation, but we will probably run into the same manage menu errors as each book has a drag/drop reorder/manage titles page and have to develop something like `big book menu`

<img width="906" alt="Screenshot 2024-02-19 at 3 31 24 PM" src="https://github.com/uiowa/uiowa/assets/4663676/e5a1ca33-c56f-42ab-9e6b-c0203e0afc8b">

Regardless, I do think that the section in other languages stuff should be "related" and not a menu entry. This seems to be the main problem. These alone add up quickly and will grow with new languages being added.

17 links (the other languages, minus the current one, plus a nolink parent link) x 52 sections for Song of Myself = 884 menu links.

3 links (the other languages, minus the current one, plus a nolink parent link) x 36 weeks for Civil War Writings = 324 menu links.

**Comment by joewhitsitt** [comment]
An issue I had not considered with related/featured content is that they are currently creating menu title overrides for these other languages links. `Español / Spanish` instead of the node title, `Sección 1` for example.

>They feel quite strongly about wanting each section having a way to see that exact section in other languages from the page.

So using the entity references through node field or featured content block will be linked as `Sección 1`, producing a list of links like:

...
Sección 1
Abschnitt 1
بخش:۱
Section 1
Section 1
...

To handle this out of the box, each section title per language would have to be updated to prefix with the language:

`Español / Spanish: Sección 1`

or

`Sección 1 - Español / Spanish`

Alternatively, we could do a display style option if they tag it with the language "Manually referenced content - Card list - title and tags". `Page title - tag1 tag2`

**Comment by joewhitsitt** [comment]
Before [^^](https://github.com/uiowa/uiowa/issues/7335#issuecomment-1953246502) my final suggestion after looking into this was going to be to mainly reduce the number of other languages links which will have a big impact on performance.

If we temporarily up their memory, they should be able to work with the website to resolve. We may want to confirm with Acquia how the memory limit works in our multisite setup which may inform if we should increase the limit based on Drupal's production recommendations.

Featured content block is available today, but styling options are currently limited and it is a weaker relationship to the content. The screenshot higher up is an HTML list vs what the featured content block outputs currently.

A related content field (base field exists in default for articles) could be added to the page content type and a manually referenced content option can be added to admin/config/sitenow/uiowa-pages similar to articles. From there we could [build a list/titles display option](https://github.com/uiowa/uiowa/issues/5575#issuecomment-1217026397). Placement would be set to the current bottom region.

**Comment by bspeare** [comment]
@joewhitsitt I like your suggestion of the related content option.

**Comment by makurj** [comment]
The way we decided to circumvent the menu issue based on Ben's alternative was to create a manual list on each section page linking to the other languages for that section but only list the language for the URL text and not "section X".

For example: https://iwp.prod.drupal.uiowa.edu/test

Let's assume this page is Section 1 in English. The first or third column will list all the languages that Section 1 has been translated into and the link text would be "Bahasa Melayu / Malay" but it would link to https://whitmanweb.iwp.uiowa.edu/song-myself/languages/bahasa-melayu-malay/bahagian-1, "Kurdî / Kurdish" would link to https://whitmanweb.iwp.uiowa.edu/song-myself/languages/kurdi-kurdish

**Comment by joewhitsitt** [comment]
Opened a ticket with Acquia to better understand the pros/cons of increasing the memory_limit for the prod environments.

**Comment by joewhitsitt** [comment]
Got some support articles back from the Acquia ticket. Key takeaways:

- The PHP memory limit is the maximum amount of RAM that a single PHP process can use. 
- The maximum setting is 1024 MB per process before you need to chat with Acquia and pay more.
- If you leave the PHP memory setting too high, you won’t be able to run more than a few PHP processes on a machine without running out of RAM.
- You can upsize your server(s) to gain additional memory and more PHP processes.
- More info about specific paths/processes limits: https://acquia.my.site.com/s/article/360004542293-Conditionally-increasing-memory-limits

So I interpret this as, bigger sites might need more memory per process. By increasing across the app env we can certainly do that, but it might come at a cost of not having enough processes per app. Given how stacked each app is with sites, unless we can continually upsize, we might want to be more cautious with just giving everyone a bump across the board.

Upping to 256M might be worth an experiment, but if it is solving in in some areas but introducing an issue elsewhere, we may want to go back down and be more specific.

Makur had pointed out https://www.drupal.org/project/memory_limit_policy in https://github.com/uiowa/uiowa/issues/1996#issuecomment-1424392485 which might be an easier config management way of handling this per site if needed.

**Comment by joewhitsitt** [comment]
Brian pointed me at the actual hardware limits we currently have. In stack metrics, for the current time range, we are using just under ~50% of our memory. Spikes can and will happen, but our Maximum PHP processes reached warnings metric for the same time range is generally below 5%.

After reviewing these metrics, I am probably more in favor of experimenting with 256M across the board in hopes that it will relieve us from the menu, lb blocks, views, find text, etc. memory spikes we typically see.

This is another reason though not to go too much in to the "sites behind authentication" business because caching is really helping us get the most out of our hardware.

I am interested in watching these metrics during and right after a deployment when cache rebuilds are triggered.

**Comment by pyrello** [comment]
> After reviewing these metrics, I am probably more in favor of experimenting with 256M across the board in hopes that it will relieve us from the menu, lb blocks, views, find text, etc. memory spikes we typically see.

This may just be a wording thing, but I don't understand how this is going to help us with memory spikes. We hit out of memory errors when the application exhausts the 128 MB of memory allotted to a particular PHP process thread. Upping our memory limit to 256 will result in more memory usage at times when we otherwise might have seen an out of memory error. This is good in that we prevented the error, but means that the amount of memory that can be used at a given point in time is actually higher and could result in larger spikes.

**Comment by joewhitsitt** [comment]
I'd be happy to huddle on this to clarify some points, but overall that is why I am suggesting the bump as an experiment in addition to whitmanweb finding a new home for the other languages menu items, whether that is developing the related content field for page or their idea of custom html lists.

Larger potential spikes, yes. Bigger ceiling than I originally thought, yes. Several processes beyond menus that need a bit more in a sea of processes that are just fine at/under the current 128M.

**Comment by joewhitsitt** [comment]
Had a huddle with Sean to clarify the current hardware ceiling for these processes.

For the 256M experiment, I was thinking we start with uiowa02 prod (whitmanweb.iwp). As we see issues with other sites we consider those apps as well.

Need to monitor deployments and if we see a rise in other memory exhaustion issues in areas we have not been seeing them.

For whitmanweb.iwp, if they want to try the custom HTML block solution first they might want to do a small slice before pausing and reflecting on what kind of gotchas/maintenance burden this solution might cause. Otherwise I think we could look at solving this with the related content field functionality and accounting for the content title issue raised in https://github.com/uiowa/uiowa/issues/7335#issuecomment-1953246502

**Comment by makurj** [comment]
Can you clarify what you mean by the custom HTML block solution? If the memory issue cannot be resolved by bumping it, the solution that we decided on with IWP is to utilize cards or text areas to implement https://github.com/uiowa/uiowa/issues/7335#issuecomment-1954394291, not featured content, due to page title issues.

**Comment by joewhitsitt** [comment]
@makurj, though we do plan to experiment with bumping up memory (with team approval), the current menu structure your site has for the other languages' links is unsustainable.

By custom HTML block, I meant your [solution](https://github.com/uiowa/uiowa/issues/7335#issuecomment-1954394291) of using a card/text area block with a unordered list. If you plan to go this way instead of waiting for an "related content" entity reference field solution, we suggest you proceed cautiously instead of going all-in at once in case the solution is not suitable for you and your group.

**Comment by makurj** [comment]
Thanks, @joewhitsitt . We will start experimenting with the custom HTML solution and report back.

**Comment by pyrello** [comment]
I did a little bit of investigating today to see what it would take to move to a solution using Drupal's built-in language handling capabilities. I think this has the potential to get around some of the memory issues we've encountered because the menu system would only be loading pages in the relevant language, so a fraction of the current menu structure would be loaded at the points in time where we are currently running out of memory. As an added benefit, there is a language switcher block built in that we could potentially leverage for switching between versions of a particular page.

So far, I have not found a way to make an existing node into a translation for another node. So, it might be necessary to write an update hook to transition the content that has been entered already so that it is not necessary to recreate thousands of pieces of content.

**Comment by joewhitsitt** [comment]
Team approved bump for memory_limit on uiowa02. This is now in place.

**Comment by pyrello** [comment]
I found this while investigating content translation: https://www.drupal.org/project/merge_translations

**Comment by pyrello** [comment]
Just found this: https://www.drupal.org/project/hierarchy_manager

**Comment by briand44** [comment]
Met with Makur and Mara about this and they plan to move forward with the custom html solution https://github.com/uiowa/uiowa/issues/7335#issuecomment-1954394291. Closing this as there isn't anything currently needed from us.

**Comment by joewhitsitt** [comment]
... but they plan to manually delete the other languages links themselves. if that is too troublesome, we might be able to craft the right kind of query to fetch and delete those.

parent links = select id from menu_link_content_data where title LIKE '%Other available languages%'

for each id from above select uuid from menu_link_content 

delete those now? ~~not sure if there is an easy entity_delete() for these.~~

```php
$menu_link_content = \Drupal::service('entity.repository')
            ->loadEntityByUuid('menu_link_content', $uuid);
$menu_link_content->delete();
```


child links are get all ids of menu_link_content_data where parent is one of the uuids in the form of menu_link_content:{uuid}

delete child links?
