### ISSUE TITLE
Probe adding logging back in since drush 12

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uiowa#7345]
[After updating to drush 12](https://github.com/uiowa/uiowa/pull/7310), we lost the ability to log things to splunk or DBlog with the logger instances changed there.

### Proposed experiment:

- Either: turn on DB logging locally or find where the drupal watchdog gets written locally in DDEV to monitor watchdog output.
- Find a core drush command that logs to Drupal watchdog.
- See if the core drush command is correctly logging to watchdog.

**Comment by joewhitsitt** [comment]
Not sure if this is related to our logging woes: https://github.com/drush-ops/drush/issues/5862

**Comment by joewhitsitt** [comment]
[Here is an example of where splunk was getting logs for these and now they are not ](https://splunk.its.uiowa.edu/en-US/app/search/search?earliest=%40mon&latest=now&q=search%20index%3Duiowa-acquia%20That%20is%20neat.&sid=1708719710.98499_EDED3979-0BD0-4DD8-A05C-4F129EBB094A&display.page.search.mode=smart&dispatch.sample_ratio=1)

**Comment by joewhitsitt** [comment]
Some of the loggers will need a `t()` wrapper to get the variables to work again: https://github.com/uiowa/uiowa/pull/7353/commits/d3286a5345c90c2d85958a4441649982ab045cec

**Comment by GaryRidgway** [comment]
- Is there something that we Need to learn from the issue joe mentioned?  
- we currently have terminal logging, but we do not have splunk logging.  
    - Ex: building imports were reporting to splunk, but they no longer are reporting since drush 12.  
- is there some way we can test this locally with a logfile to see if it is working? This would save us having to do DBlogging? there is probably something we can use in DDEV for this.
- Is this happening across the board with all drush commands? Is ALL stuff not working in logging like core and whatnot? Maybe the thing we did to fix it fixed command line stuff, but still not the correct way to do logging?
- Perhaps check drupal core to find examples of something that is being logged are doing stuff, and then replicating if it is working in logs.
- Probably a good idea to start with core.
    - Try using the log in event to see if it is getting logged to the log file?

Question to understand complexity:
Is it just us, or did all drush stuff stop outputting to logs?

After this, reassess direction.

**Comment by cory-skeers** [comment]
Doing a bit more digging, but so far it's looking like Drush commands aren't logging unless they're triggering another service that is logging, but moving from the Drush logger (eg `$this->logger()`) to calling the drupal logger directly (eg `\Drupal::logger()` -- would want to do dependency injection if we went this route though) gets things working.

**Comment by cory-skeers** [comment]
I'd thought https://www.drupal.org/project/scheduler/issues/3359998#comment-15048675 (messages not retrievable from php tests), but they've stated that the issue was resolved with a PR meant to address the previously pointed out https://github.com/drush-ops/drush/issues/5862. I've tried using that, and am not seeing any change in the behavior.

Drush commands that do end up showing up showing up in the log (like `imagecache-external:generate`) do so tangentially by calling methods that then use the base `\Drupal::logger()`, and not through the Drush `$this->logger()`. So an option would be to keep regular Drush logging in the Drush commands themselves, but add Drupal log interface logging within processes that are called from the Drush commands (like like `BuildingsProcessor::init()` and such).

So far I still feel like the preferred method would be logging through the Drush logger, that we are implementing it correctly (or at least, mostly correctly), and that there's something else going on and/or something that needs to be addressed upstream that may or may not have an issue attached to it, and so would like to spend a bit more time digging.

**Comment by joewhitsitt** [comment]
@cory-skeers not sure if this was what you were thinking, but I [pushed a commit](https://github.com/uiowa/uiowa/pull/7422/commits/866f51001a7af52e03410d71726b9334b95b149f) that handles both drush output and drupal logging for the command.

Originally I copy/pasta from brand_core and noticed it was doing double duty previously to achieve both:

https://github.com/uiowa/uiowa/pull/7310/files#diff-e5874d002f90bf5e986c180f88693f43fa4df503031c1d618ad8760d7d90d9d6

Happy to adjust it to something else if you discover another way.

**Comment by cory-skeers** [comment]
> @cory-skeers not sure if this was what you were thinking, but I [pushed a commit](https://github.com/uiowa/uiowa/pull/7422/commits/866f51001a7af52e03410d71726b9334b95b149f) that handles both drush output and drupal logging for the command.
> 
> Originally I copy/pasta from brand_core and noticed it was doing double duty previously to achieve both:
> 
> https://github.com/uiowa/uiowa/pull/7310/files#diff-e5874d002f90bf5e986c180f88693f43fa4df503031c1d618ad8760d7d90d9d6
> 
> Happy to adjust it to something else if you discover another way.

Either this or only using the `getLogger()->notice()` from the logger channel trait and avoiding the `DrushCommands` `logger` completely are the best approaches I've found so far.

As far as I can tell, the `DrushCommands` logger _should_ handle it all and has in the past, but currently isn't, and is where I've come up short finding out why or getting any updates to fix it. Using the logger trait and calling that seems to work fully for both.

I think with this we'll get doubled-up terminal output but only one db log entry, and if a drush update returns logging, then potentially doubling both in the future. We could get by with just relying on the logger channel trait and know we should only get one terminal output and dblog entry, but it'd be nice to be able to just use the built-in drush logger...

**Comment by joewhitsitt** [comment]
I am not getting double terminal output. I feel like that is why `getLogger()->notice()` was ripped out of brand_core in the first place.

**Comment by cory-skeers** [comment]
> I am not getting double terminal output.

Welp, I guess I understand this even less.

I pulled the branch down and also am only getting one terminal output, but when I've done that elsewhere, I get doubled terminal outputs. 🤷

**Comment by cory-skeers** [comment]
- Either: turn on DB logging locally or find where the drupal watchdog gets written locally in DDEV to monitor watchdog output.
  - The easiest way I found for this is to enable db logging and using something like `ddev drush @facilities.local watchdog-show --count=10` to see the tail of the log
- Find a core drush command that logs to Drupal watchdog.
  - The best example where logging worked was with `imagecache-external:generate`, and there it only works because the logging takes place within a module function using `\Drupal::logger()` instead of the `DrushCommands::logger`
- See if the core drush command is correctly logging to watchdog.
  - See above. I didn't find any instance of a drush command that used the `DrushCommands::logger` that successfully logged to watchdog
  
As best I can tell, the path forward is like what @joewhitsitt did at https://github.com/uiowa/uiowa/pull/7422/commits/866f51001a7af52e03410d71726b9334b95b149f. Sometimes this leads to double terminal output and sometimes not, and I'm not sure why. Another option would be to house any processing itself within the module and use the `\Drupal::logger()` directly, and to call that process from the drush command (as opposed to housing logging/processing/etc all within the command).

**Comment by joewhitsitt** [comment]
I've missed some EoD and a standup, but from today's standup it sounded like @cory-skeers had wrapped up investigating this. With a working solution in https://github.com/uiowa/uiowa/commit/866f51001a7af52e03410d71726b9334b95b149f I am fine with closing this and planning a new slice to repair existing commands.

After that, if we discover a better solution, we can plan another DX issue to refactor.

**Comment by cory-skeers** [comment]
Added a followup issue: #7444

Closing the probe as completed.
