### ISSUE TITLE
Spike: Add `console.log` statements to `media_linkit_library` to figure out why wrapping media items with a link doesn't work correctly

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7348]
Details: https://github.com/uiowa/uiowa/issues/7334#issuecomment-1932778598

**Comment by joewhitsitt** [comment]
I've learned three things so far:

- My JS debugging skills are lacking but I did do as the issue said and added a bunch of console.log statements in the JS to at least pretend to understand what was going on.
- I found that this is not an issue with our patch for linkit_media_library, but that there is a linkit issue here
  - https://www.drupal.org/project/linkit/issues/3396049
  - https://git.drupalcode.org/project/drupal/-/merge_requests/2909#note_257784
- editor_advanced_link is having the same issue: https://www.drupal.org/project/editor_advanced_link/issues/3349389

**Comment by joewhitsitt** [comment]
Made a similar comment on the patch issue. There has been a new commit to the patch since we last added it. Going to quickly evaluate it and see if we should run with it. Wonder if it is helpful towards this error I saw recently: https://iowaweb.slack.com/archives/CSQA18BK4/p1707144797306069

Update: not actually sure where that gets triggered to debug. Leaving as-is for now.

**Comment by joewhitsitt** [comment]
Unless there are other opinions, I feel like this spike is done. I have updated #7334 with some details from this issue.

**Comment by joewhitsitt** [comment]
In standup, it was suggested that a known issue be created and linked to #7334. Going to work on that now. ✅
