### ISSUE TITLE
Ability to send alert notifications via email on alert creation and update

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7350]
# Story 

As an ITS alert creator, I would like to be able to send an email communication about an alert so that folks subscribed to our email list can be notified right away.

# Additional Info

**Current email example**

![Image](https://github.com/uiowa/uiowa/assets/1017022/f735887e-863c-450e-9e03-d550c2723d07)

**Email info**
From: IT Service Alerts (IT-Service-Alerts@uiowa.edu)
To: IT-Service-Alerts-Members@iowa.uiowa.edu
BCC: e7199078.iowa.onmicrosoft.com@amer.teams.ms
Subject: [Alert Title]

Alert Start Date (https://github.com/uiowa/uiowa/issues/7122)
Alert title linked to alert node
Alert Description

Related Links:
IT Service Alerts page - https://its.uiowa.edu/alerts
Calendar view of alerts - https://its.uiowa.edu/alerts/calendar

**Current example with update that is closed**

<img width="1098" alt="Screenshot 2024-02-14 at 4 34 03 PM" src="https://github.com/uiowa/uiowa/assets/1017022/9a29f440-d2c5-44ed-ae4f-6b7ab5ebd295">

**Email info with update that is closed**

From: IT Service Alerts (IT-Service-Alerts@uiowa.edu)
To: IT-Service-Alerts-Members@iowa.uiowa.edu
BCC: e7199078.iowa.onmicrosoft.com@amer.teams.ms
Subject: "[Closed]" [Alert Title]

Alert Start Date (https://github.com/uiowa/uiowa/issues/7122)
Alert title linked to alert node

Update Info - latest first

Original Notice

Related Links:
IT Service Alerts page - https://its.uiowa.edu/alerts
Calendar view of alerts - https://its.uiowa.edu/alerts/calendar

**Future**

Daily digest email - Future Slice
Email logs?
Email notification to help desk?

# Proposed Solution

- Establish a boolean checkbox, "Send email on save" that is acted upon during node presave. The boolean is reset, but a email is triggered through the website with the alert node content similar to how it worked on the D7 site. See https://github.com/uiowa/uiowa/issues/7350#issuecomment-1942034243 for a more detailed description of the functionality.
- The email should be formatted similar, paying attention to the changes noted in https://github.com/uiowa/uiowa/issues/7350#issuecomment-1942129625
  - First send email and alert update email can be the same but with conditional logic to include closed information, updates/labelling the original alert descriptions.
- Keep in mind the future email digest slice as this functionality is developed.

**Comment by joewhitsitt** [comment]
Personal opinion - To improve their workflow from their current website and since our caching/alert updates have more to do with node save, I think there should be a checkbox on the node add/edit form that is "Send alert email on save" (visible only to certain roles) that triggers the email and unchecks itself before DB save. That way a revision is captured for accountability (align revision date with email date). If they need more accountability, a separate email log can be captured like before.

Moderation can be incorporated into this as well (transitioning to published/archived or already published) to prevent emails for draft/review states.

**Comment by joewhitsitt** [comment]
Grooming convo:

- Consider sending to BCC instead of To
- Date formats should match branding. See https://github.com/uiowa/uiowa/issues/7122
- Attempt to use a email "name" for the From instead of the email address.
- Link to node, should contain related links
- Doesn't _need_ branding for MVP. There are conversations going on elsewhere.
- If it is more work to keep the slices separate that can be adjusted (instant email, digest email, etc.)
- Needs some kind of logging accountability
- Biggest concern is getting the emails out immediately whereas facilities had different conditions. May want to confirm the proposed solution with them for how the email is triggered before starting.
- Reliability is a concern for dispatch and acquia mail.
- ITS is maintaining their own list of subscribers currently through Teams.
- Might not need a separate template/trigger for alert updates, but might keep it a separate slice to just focus on sending the email and not worrying about the conditionals/content associated with update/close emails.
- By using a separate email tab compared to https://github.com/uiowa/uiowa/issues/7350#issuecomment-1942034243, editors can give the published version a once over before sending an email. Alternatively, the could just save the alert, look at it and then save it again with the checkbox checked.

Possible customer questions:

- Are you okay with a node form based trigger? Do you recall the reasoning for the button on the node published?
- Acquia mail vs Dispatch?
- Do you ever want to schedule an alert email beyond just relying on the digest/instant?

Going to wait for customer response before putting together a proposed solution.

**Comment by joewhitsitt** [comment]
After meeting with Adrienne and James, they are okay with moving forward with node form based trigger (e.g. checkbox), acquia mail using revision history for email logging for now.

**Comment by joewhitsitt** [comment]
Initial questions:

- What should the replyto be? site email or the from address? - _using IT-Service-Alerts@uiowa.edu for now_
- What role(s) should the trigger be restricted to? Any updates on an additional role for this site? - _using `use editorial transition publish` for now_
- We had some debugging/production safe guards in place before, should add that in? At the very least, swap out the to/bcc for something else if not PROD? - _doing a PROD env check with a site-email fallback for now_
- Is it okay to hardcode related links for MVP? - _current site is hardcoded. doing the same for now_
- alert update timestamps also on brand? speaking of, any compromise on the "only some months are abbreviated"?

I had forgotten about the scheduling bit to this, but I think the previous presave work should cover what we need.
