### ISSUE TITLE
Update ctools and ctools views

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7395]
# Proposed Solution

- Update Ctools module to most recent version.
- Test to make sure there are no regressions with existing views blocks displays.
- Address any regressions found.

**Comment by pyrello** [comment]
While working on this and checking the custom functionality on UI Press, I noticed that a contributor to a book did not have the book listed on their page (https://uipress.uiowa.edu/people/guido-villa) despite them being listed as an illustrator for the book: https://uipress.uiowa.edu/books/walt-whitman. After some digging, I realized this was because the "Illustrator" person type had not been selected for Guido Villa and the view includes a filter for the person type of the contributor being selected. I can't remember why we did it this way, but it seems unnecessary to have that filter and an extra step for content editors to get view to show up correctly.

I think we could probably remove the person type filter (I tested it locally and didn't see any issues) from each of the view displays on that view. We could also potentially remove all the person types except Author (which we are using for this page: https://uipress.uiowa.edu/authors).

# Previous issues:
- #4329
- #4658
