### ISSUE TITLE
Authentication to BizHub/BuildUI Endpoints for v2/v3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7401]
# Story

As a web team, we need to authenticate to existing Facilities APIs so that we can continue to pull data from them once they deploy their basic authentication to production servers.

# Additional Info

Sending an email to its-web with credentials.

**Endpoints**
- All buildings api: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/buildings
- Individual building api (example): [https://bizhub- stage.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0013](https://bizhub-%20stage.facilities.uiowa.edu/bizhub/ext/building?bldgnumber=0013)
- Building Coordinators json response: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/bldgCoordinators
- All FM Staffs api: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/fmstaffs
- FM Latest News: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/fmlatestnews
- All Rooms Information: https://bizhub-stage.facilities.uiowa.edu/bizhub/ext/rooms

# Questions

Does this include projects endpoints (BuildUI)?

# Proposed Solution

- Separate BuildUI vs Bizhub calls. If this gets big it isn't a must do.
- implement basic authentication to these API calls

**Comment by joewhitsitt** [comment]
\Drupal\uiowa_facilities\FacilitiesAPI::request is the only place BASE_URL_1 (https://bizhub.facilities.uiowa.edu/bizhub/ext/) is called.

**Comment by joewhitsitt** [comment]
facilities and snp_map are the only calls to bizhub on v1 (701-703)

**Comment by briand44** [comment]
Grooming conversation... Consider a config option to enable authentication vs having authentication turned off? This would make working on it easier prior to requiring auth and would make it so we wouldn't need to have a deployment to enable this in coordination with API deployment. Maybe we should separate Bizhub vs BuildUI calls. Brian to check with Rakesh to verify authentication is only happening now for BizHub. Scope this to v2/v3 and have a separate slice for D7.

**Comment by briand44** [comment]
I just heard back from Rakesh and he said they have the same mechanism in place for BuildUI API's as well. I followed up asking for a stage url for testing.

**Comment by briand44** [comment]
Rakesh responded...

Here are the stage url related to the build UI endpoints for projects to test against.

https://bui-test.facilities.uiowa.edu/buildui/ext/projectinfo?projnumber=0897601
https://bui-test.facilities.uiowa.edu/buildui/ext/projects?bldgnumber=0025
https://bui-test.facilities.uiowa.edu/buildui/ext/capitalprojects
https://bui-test.facilities.uiowa.edu/buildui/ext/featuredprojects

Going to forward the email to our shared inbox because it contains credentials.

**Comment by joewhitsitt** [comment]
FYI, https://github.com/uiowa/uiowa/issues/7427#issuecomment-1997895760

**Comment by pyrello** [comment]
During the process of working through actually adding the basic auth to the API request and testing how it might work if the auth was missing or incorrect, I discovered that we don't currently have a mechanism to bounce out of the finishing the processing with our processor classes if there is a problem like this. Based on how the processors currently work (by comparing what is returned from the API/processing to the content that currently exists) the potential outcome if the API call wasn't working for whatever reason, I believe that all the content controlled by it (e.g. buildings or projects) would be deleted because it would be seen as not existing at the API source.

Based on this, I think we need to increase the scope of work to include refactoring to implement some graceful failure mechanism.

**Comment by briand44** [comment]
Grooming conversation... We discussed that it makes sense to add ^^ in scope for this issue but we don't necessarily need to be notified of the failure as part of this. Resized as a large to represent the overall size of this issue, medium amount left.
