### ISSUE TITLE
Filter by author on content overview

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7474]
# Story

As a SiteNow user with access to the content overview, I would like the ability to filter by author so that I can quickly find a particular piece of content I authored or was authored by a particular person.

# Additional Info

Requested by ITS but this seems like something that could be useful for the service.

# Proposed Solution

- take Seans work and see if we can address display possibly with patch to Claro

**Comment by pyrello** [comment]
I just did a very quick probe of this. Here is what I found:
- Adding an exposed filter for the "Authored by" field works as expected.
- The field is an autocomplete field without any clear way to change it to a drop-down, if that was desired.
- Without modification, it looks like this:
![Image](https://github.com/uiowa/uiowa/assets/709009/8bc352d2-f57a-4496-a291-8fd318f13c2b)

**Comment by pyrello** [comment]
I went ahead and exported the config change for this. At a minimum I think we should add some styling for the form so that it doesn't take up so much room.

**Comment by briand44** [comment]
Grooming conversation... Sean's probe has showed this is pretty straight forward. Worth noting the author is just the person who originally created the node and not necessarily the person who last edited or owns the content. Some styling likely still needed here. Possibly a Claro issue related to the display of filters and table being crowded. Potentially solved display with a patch. Joe mentioned media and fragments overviews but we decided those can be future issues if desired.

**Comment by bspeare** [comment]
I tightened the spacing up a bit.  There will still be overflow, but not as extreme as the original screenshot.   I looked for patches and found mostly issues discussing future improvement instead of immediate solutions:

- https://www.drupal.org/project/drupal/issues/3080994
- https://www.drupal.org/project/drupal/issues/3076820
- https://www.drupal.org/project/drupal/issues/3373303

And this interesting thread https://drupal.community/@joachim/111368755682570615. 

<img width="1290" alt="Screenshot 2024-03-22 at 3 32 32 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d0369cc3-32f0-49fe-805f-21cf1a9adb6e">
