### ISSUE TITLE
Migrate ITS services

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7479]
# Story

As an ITS site owner, I would like our services content from our current site to be migrated to our new site so that we don't have to manually copy all of that content over.

# Additional Info

Migrate all published D7 infocenters to D10 services ~182

**Mappings - D10 - D7**

- Title - title
- Summary - body summary
- Description - filtered html - body
- Aliases - multiple - field_ic_aliases
- Audience - multiple - taxonomy - field_audience
  - terms already exist on new site
  - new site missing "Staff" term. Not sure if that was by design?
  - **ITS considering not having Audience taxonomy**
- Category - single - taxonomy - field_ic_category
  - terms already exist on new site
  - new site missing "Artificial Intelligence".
- Related Services - multiple - entity reference - field_related_info_centers
- Website - field_ic_website - URL and Title
- Quick Links - multiple - migrating from both of the following fields into this field
  - field_ic_obtain - URL and Title
  - field_ic_commonactions - URL and Title
- Contact - filtered html - field_ic_contactinfo
- Fees - field_ic_fee_info
  - No Charge or Other. If Other then there should be Additional Fee Information
- Additional Fee Information - field_ic_fees
- Authored On date

# Questions

Did the staff audience get intentionally left off the new site? - They are trying to determine if they want to keep the audience taxonomy at all.

Does the Artificial Intelligence category need to be added to new site? - Yes

Url Alias - no need to map and migrate custom url aliases that have been set for services.
Redirects - they do want us to create redirects from the previous url alias to the content on the new site.

# Proposed Solution

- Create an `its_migrate` module in the its.uiowa.edu site directory following other site migration patterns (configuration held in `module/config/split/*`, `.install` file to load config, etc)
- Create a Services YAML migration definition including all fields defined above _except_ Related Services
- Create a Services migrate source class that extends `sitenow_migrate::BaseNodeSource`
- Preprocess as necessary (eg Category term mapping; see `now_migrate::NewsFeature` for an example that creates tags on the fly; this can be adjusted to only look up current tags, as all tags should exist in the site already)
- Add a Services Redirects migration YAML definition
- Add a Post Migration Event Listener or a second Services YAML migration definition for the related services field
  - If an event listener, include a boolean flag somewhere (likely the `$migration` object) that indicates when the listener has run, and skip if bool is there to avoid second firings of the listener, a previous problem with migration listeners
  - If a second migration, follow the redirects migration pattern (utilizing the `Services` migration class, the `migration_lookup` process, etc), and adjust to map only the Related Services field. This will technically be an update migration, so slightly different than our previous migrations

**Comment by cory-skeers** [comment]
> Related Services - multiple - entity reference - field_related_info_centers

Since this is a reference to content that's getting migrated as part of this, we'll need to do some form of post-migration update using the migration map to update the referenced node ids (using `sourceid1` and `destid1` columns from the `migrate_map_...` table, or the `node lookup` process, depending on the method).

Probably the standard way to do this would be in a post migration event listener. If we migrated the original reference IDs in the migration, this listener would go through and use the map table to update to the new ID. Or, if we didn't migrate data into the field, we'd grab both the data from the d7 database and the migrate map in the listener, lookup the correct value(s), and store it. 

If it's in a post migration event listener, the one added gotcha would be that the migrate event listeners will sometimes fire twice, and we'd need to account for that and prevent it making changes if/when it runs a second time.

Another option could be a second migration similar to our redirects migration that uses the node lookup process and updates  the one field for each of the nodes migrated in the first pass. It'd be a slightly different setup, as we don't normally do update migrations. I think in that case we'd want to not include the field values in the first migration, then include it in the second, and the migration would look at it as that field having updates available for each piece of content.

**Comment by briand44** [comment]
Grooming conversation... Related services seems to be the most complex piece of this. Cory mentioned he would probably use the post migration event listener to handle this as mentioned ^^. Not required for Cory to do this all himself. Discussed what to do about Audience taxonomy since they are considering doing away with this. Sounds like we can avoid this for now but we will need to do very similar work for the category mapping so may not require too much additional effort. Brian will try and push for an answer on this sooner than later. Noting that this may hang out in dev for awhile before we run in production. Scoped this to local migration and testing/review. Dev migration will be a separate slice.

**Comment by joewhitsitt** [comment]
Shower thought: Wasn't UIPress's migration similar to pull in related books? Or is that one the [migrations we should be cleaning up](https://github.com/uiowa/uiowa/issues/4994)?

**Comment by GaryRidgway** [comment]
[tasklist moved to here.](https://github.com/uiowa/uiowa/pull/7524)
