### ISSUE TITLE
Watchdog logging lost again for Facilities API

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7597]
# Problem

[A drush update and recent changes to the Facilities API](https://github.com/uiowa/uiowa/pull/7449) seem to have caused watchdog logging of the commands to stop being passed on to Splunk:
No new logs since 4/10: https://splunk.its.uiowa.edu/en-US/app/search/search?q=search%20index%3Duiowa-acquia%20%22That%20is%20neat.%22&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=%40mon&latest=now&sid=1713196218.42446_EDED3979-0BD0-4DD8-A05C-4F129EBB094A

**Comment by joewhitsitt** [comment]
Wonder if this is related to us getting logging back.

https://github.com/drush-ops/drush/pull/5980

**Comment by joewhitsitt** [comment]
The previous `use LoggerChannelTrait` `$this->getLogger('facilities_core')->notice()` seems to be working again for both watchdog and terminal output. Tried to reproduce the cache related symptoms of the past but haven't been able to.

https://github.com/uiowa/uiowa/pull/7310
https://github.com/uiowa/uiowa/pull/7472

**Comment by briand44** [comment]
Grooming conversation... Cory thinks we are now getting duplicate logging and we need to clean this up so we are only getting one set of logging. We can move stuff back to the class rather than the module function. Go back to using a channelTrait or dependency injection rather than calling the services directly.

**Comment by cory-skeers** [comment]
Specifically, the `$this->getLogger()->...` using the `LoggerChannelTrait` within the `DrushCommand` appears to be working for both the terminal and dblog, but not the `$this->logger->...` or `$this->logger()->...` methods.

No concern from me in this being the one that works, but noting because having at least 3 methods available and only 1 working in all places is confusing.
