### ISSUE TITLE
Grad - Updates to Degrees Offered

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7602]
# Problem

> One of the correct forms of a degree is not listed on this page: https://grad.uiowa.edu/programs/graduate-programs

>We also need the periods removed from degree names to follow the conventions here: https://catalog.registrar.uiowa.edu/graduate-college/#programstext and https://registrar.uiowa.edu/sites/registrar.uiowa.edu/files/2023-24_general_catalog.pdf.

# Background

>These are built off of fragments. For example, https://grad.uiowa.edu/fragment/781/edit?destination=/admin/content/fragments

# Proposed Solution

- Add `MPAff` to the options
docroot/modules/custom/grad_custom/grad_custom.module:grad_custom_degrees_offered_allowed_values()
- Adjust the human-readable option values to not include the periods. Check related functionality to make sure there are no assumptions on those values.
- Keep in mind that this is a shared module, and not necessarily used by the Graduate website only.

**Comment by briand44** [comment]
Grooming conversation... Do we know if this is used elsewhere? Probably need to look into that as part of this work. Grad_person_extended and thesis_defense feature splits have the grad custom module enabled. grad.uiowa.edu is the only site split with grad_custom listed.

**Comment by e-marie-w** [comment]
Summary:
Actual code changes were easy. I only changed the display name of the degrees at this time as I'm unsure if the machine names are being used in some way. 

Then I spent time investigating if this is used somewhere else. I started by searching for sites using thesis_defense and grad_person_extended since those feature splits use the grad_custom module. None were visible via a code search, but I knew and confirmed a few sites that were. So I switched tactics to checking the code of the feature splits, and found no usage. As far as I can tell the function with the degrees is only used by a field only found on the grad site split.

I went back to checking the changes on the local site. Fragments do not have a usage tab (but do have two revision tabs for some reason?) so I am fairly but not 100% certain they are not used anywhere else on the site. I was briefly confused why https://grad.uiowa.edu/programs/interdisciplinary-graduate-programs still had periods but quickly realized that page was manually created and so they'll need to manually update it.
