### ISSUE TITLE
v2 Articles and People column width settings offers a `-none-` option that does not apply width to the container

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7665]
# Problem
v2 Articles and People column width settings offers a `-none-` option that does not apply width to the container when the default of `Full` should be selected. 

<img width="226" alt="Screenshot 2024-05-09 at 3 05 18 PM" src="https://github.com/uiowa/uiowa/assets/1036433/5a77f2ab-74a3-4618-8e5f-2eb9664fc9f7">

# Steps to reproduce
https://pentacrestmuseums.uiowa.edu/about/staff-directory has `-none-` selected. 
<img width="1426" alt="Screenshot 2024-05-09 at 3 06 56 PM" src="https://github.com/uiowa/uiowa/assets/1036433/3b69d9df-9e9a-4739-9c25-fd32e69be88a">

# Proposed solution
- Remove `-none-` option and update hook to set as `Full`?

**Comment by briand44** [comment]
Grooming conversation... Not sure if we have an existing per paragraph item update hook to use as an example. Likely won't have to worry about temp store but should make sure. Will need to adjust all previous revisions so to avoid folks reverting to a previous version with this issue. Should run update in batches. Can we tie this to a v2 only module so it only runs on those sites (sitenow_paragraphs).

**Comment by GaryRidgway** [comment]
> Will need to adjust all previous revisions so to avoid folks reverting to a previous version with this issue.

I have been talking to @cory-skeers about this, I we think we will need to do database table manipulation if we are trying to fix all revisions as well. We can't edit and save the nodes, because that will create a revision itself. This will also mean we will have to insert database columns as well, so this greatly informs how we tackle the issue. 

Cory and I are going to pair later today and investigate this approach.
