### ISSUE TITLE
Update SiteNow v2/v3 so it can consume Hawk Alerts from new Emergency endpoint

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7687]
# Story

As a SiteNow v2/v3 service owner, we would like the SiteNow v2/v3 services to be able to consume Hawk Alerts from the new Emergency endpoint so that our visitors can be notified of any active Hawk Alerts.

# Additional Info

https://github.com/uiowa/uiowa/issues/7550#issuecomment-2098621468

> Removed the /api/active.xml endpoint option.
> We couldn't determine significant usage for this endpoint. Consumers are encouraged to switch to the JSON format.
> Changed the /api/active.json endpoint to /api/active
> It is still JSON but without the file extension. The endpoint won't resolve with .json appended.
> 
> The other changes are in order to follow the JSON 1.0 specification:
> The outside wrapper uihphawkalert becomes data.
> The inside wrapper hawkalert becomes attributes.
> date changes from UNIX timestamp to ISO-8601 YYYY-MM-DDThh:mm:ssTZD
> more_info_link has been updated to output the website URL with https:// prefix.
> Public Safety would like to deprecate use of e.uiowa.edu going forward.
> 

We don't want to deploy this until launch of the new endpoint.

Related to v2/v3, Sean mentioned maybe there is a way we can make the endpoint configurable so the new code could be deployed in advance of the Emergency site launch. At launch we could do some sort of `blt ume cset`.

**Comment by joewhitsitt** [comment]
Grooming convo:

- The main hiccups from the signage slice of this was date handling and the CORS.
- Given the recent `ume` snafu, we should confirm in advance that the command will run without issue.

**Comment by GaryRidgway** [comment]
When I was ssh'ed in, I was able to run `./vendor/bin/blt ume "image:flush --all"` to flush image caches. Throwing a command in quotes seems to allow you to run anything.

**Comment by cory-skeers** [comment]
Some notes:

Command to set the source config (and what would need to be run with `blt ume` with the updated endpoint alongside launch)
```
ddev drush @default.local cset uiowa_alerts.settings hawk_alert.source https://emergency.stage.drupal.uiowa.edu/api/active
```
We would also want to update it in `config/default/uiowa_alerts.settings` for new installs after that point.

`uiowa_alerts/es6/uiowa_alerts.es6` is the main source that needs to be updated (can also take this opportunity to move it to JS and dump the es6). There's some date formatting that needs to be accounted for, but mostly it's updating a few properties from `uiphawkalert` to `data` and `hawkalert` to `attributes`. 

I'd planned on having two libraries, and attaching one or the other in `uiowa_alerts/src/Plugin/Block/AlertsBlock.php` based on the config source endpoint, with the difference between the two being the updated JS, so that only one or the other would get loaded rather than including any logic in the JS itself.
