### ISSUE TITLE
Venue theming updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7706]
Josh got feedback from other stakeholders and is now asking for some changes to the Venues.

They would like links similar to the existing Events and Map link https://commencement.prod.drupal.uiowa.edu/venue/carver-hawkeye-arena for "Venue Info", "Parking", "Security" and "Accessibility".

They do not need both Events and Map links as they currently link to the same area of the page. They would be ok with removing Events since it is more for internal audience or combine into "Map & Events".

Josh said if he needed to follow a certain pattern when creating the unique ids, that is fine.

**Comment by joewhitsitt** [comment]
Grooming convo:

Content editors might have to create child links with anchor ids in order to make use of a placed horizontal menu. This is the ideal for handling the number of links in a responsive and accessible manner. Map & Events would be accounted for in this menu and removed from the header.

  - Venue could have hardcoded links regardless of whether or not the content is there.
  - Content editors might have to create child links with anchor ids in order to make use of a placed horizontal menu.
  - Handling the number of buttons/links could be a deciding factor.
  - Might want to confirm with Josh before implementing.

**Comment by bspeare** [comment]
Here's a preview of the proposed solution:




https://github.com/uiowa/uiowa/assets/1036433/f35e9880-49d4-42ee-af28-6856866d8af0
