### ISSUE TITLE
Identify v1 custom to v3 standard sites that haven't requested a v3 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7743]
# Story

As a web team, we would like to understand if there are any site that we identified as v1 custom that could move to v3 standard that missed the cutoff date of 5/31/24 to submit a site request so that we can understand if those sites can be removed or if they still want to continue with their web presence.

# Additional Info

As part of https://github.com/uiowa/uiowa/issues/7290, we communicated with v1 sites we believe can transition to v3 without any custom development. We told them they have untitl 5/31/2024 to submit a site request if they want to continue. We should audit the sites we communicated with to see if any have not met the deadline.

Link to existing spreadsheet - https://iowa.sharepoint.com/:x:/r/sites/CSI-Drupal2/_layouts/15/doc2.aspx?sourcedoc=%7BA3958AFA-FA30-492A-948E-0A3368521D3D%7D&file=Drupal%207%20Sites.xlsx&action=default&mobileredirect=true

# Proposed solution

Identify sites we communicated to.
Check spreadsheet/site requests to validate if they requested a site
Update spreadsheet if inaccurate.
Deliver list of sites that failed to meet deadline.
Create a card in PL to discuss next steps.

**Comment by briand44** [comment]
Grooming conversation... There are probably a few different approaches to tackle this work but left the proposed solution a little vague to allow developers to approach in a way that feels right to them. Deliverable is a list of SiteNow v1 sites that we identified can move to v3 without development (possibly with existing spreadsheet) that have failed to request a v3 site by the deadline.

**Comment by e-marie-w** [comment]
Summary of work so far:
I looked at the population of our last communication from https://github.com/uiowa/uiowa/issues/7484#issuecomment-2040300940 and got a list of 30 sites. Checked that against the spreadsheet. Spreadsheet had 28 but the two missing had launched or been removed so 28 remaining v1 custom to v3 standard is correct.

Of those 28 the spreadsheet listed 10 that had not yet requested a site. I double-checked the whole list and found three more that had requested a site but weren't listed as such in the spreadsheet. I updated two but left the third as-is since the site hasn't been provisioned yet (iowalionseyebank.org).

That leaves seven that have not yet requested a site:
- animal.research.uiowa.edu
- ehs.research.uiowa.edu
- hawkeyespaces.uiowa.edu
- portalpages.research.uiowa.edu
- report.hancher.uiowa.edu
- ris.research.uiowa.edu
- ubill.fo.uiowa.edu

I recall conversations around some of these so I plan to double-check the inbox and past issues as the next step.

**Comment by e-marie-w** [comment]
Further investigation:

According to an email from last month the plan is to use the v2 site billing.uiowa.edu to replace ubill.fo.uiowa.edu. billing.uiowa.edu is live but does not have any content besides a link on the homepage to ubill.fo.uiowa.edu. There is also an important redirect happening for billing.uiowa.edu/pay. Still, I think it might be better if we give them a v3 staging site instead of having them add content to v2 and then needing to convert it to v3.

portalpages.research.uiowa.edu just links to another site that is currently not loading for me so I wonder if this site is still necessary.

**Comment by joewhitsitt** [comment]
Thanks for digging into this. Sounds like we could update the spreadsheet to reflect the ubill.fo to billing plan. I know that Wendy M was previously asking which .fo sites still had to move and I missed this detail.

It seems like Modei and Jose were trying to dig into the analytics, but haven't given us a clear, "we don't need this anymore" so I would still group it as a part of this issue.

**Comment by joewhitsitt** [comment]
Just noting that we got an email today regarding billing/ubill.fo related to their conversion process and why they didn't fill out the request form.

**Comment by e-marie-w** [comment]
Closing as next steps are in #7793.
