### ISSUE TITLE
Banner block video in iOS 17 plays black screen

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7840]
# Problem
Banner block video in iOS 17 plays black screen

<img width="699" alt="Screenshot 2024-06-21 at 4 14 46 PM" src="https://github.com/uiowa/uiowa/assets/1036433/de1298ee-b49c-498a-a713-da5058936557">

# Steps to reproduce
Load https://dentistry.uiowa.edu/ on iPhone and click on the play/pause button. 

Related links: 
- https://stackoverflow.com/questions/78255334/ios-17-video-shows-a-black-screen-when-opening-in-full-screen-mode-with-a-post
- `https://github.com/cookpete/react-player/discussions/1785`
- [Webkit link](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&field0-0-0=product&field0-0-1=component&field0-0-2=alias&field0-0-3=short_desc&field0-0-4=status_whiteboard&field0-0-5=content&field1-0-0=product&field1-0-1=component&field1-0-2=alias&field1-0-3=short_desc&field1-0-4=status_whiteboard&field1-0-5=content&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&query_format=advanced&type0-0-0=substring&type0-0-1=substring&type0-0-2=substring&type0-0-3=substring&type0-0-4=substring&type0-0-5=matches&type1-0-0=substring&type1-0-1=substring&type1-0-2=substring&type1-0-3=substring&type1-0-4=substring&type1-0-5=matches&value0-0-0=video&value0-0-1=video&value0-0-2=video&value0-0-3=video&value0-0-4=video&value0-0-5=%22video%22&value1-0-0=poster&value1-0-1=poster&value1-0-2=poster&value1-0-3=poster&value1-0-4=poster&value1-0-5=%22poster%22)

# Proposed solution
- check safari bug tracker/issue queue as a first step.
- if an upstream issue we discussed just displaying the image and not allowing clicking in to view the video

**Comment by joewhitsitt** [comment]
regarding the proposed solution, would we be unsetting poster just for iOS or all the time? have we previously found an iOS indicator we can check against here?

**Comment by bspeare** [comment]
I haven't looked at it close enough.  I will update the proposed solution.

**Comment by briand44** [comment]
Grooming conversation... Should we even allow clicking on the image to see the banner since it is more decorative? Ben shared that this came from a research group who sees value in sharing their research through the banner video. If this is an upstream issue, we could fallback to just showing the image and not allowing linking off to the video until the upstream issue gets resolved.

**Comment by joewhitsitt** [comment]
i have an iOS device and a DEV env to push to. I will see what I can do here.

**Comment by joewhitsitt** [comment]
I have confirmed using BrowserStack to test locally that removing the poster attribute for iOS works, but then displays a blank placeholder until loaded. The `playsinline` attribute seemed to also work in my browserstack testing and IMO simplifies the UX since it is a decorative video. I'd like to push https://github.com/uiowa/uiowa/pull/7911 out to DEV for further testing.
