### ISSUE TITLE
frontend work for academic calendar list

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7854]
# Additional Info

Frontend work to create block display similar to prototype in https://github.com/uiowa/uiowa/issues/7851#issue-2373477052.

```[tasklist]
### Frontend tasks
- [x] display dates themed like prototype using recent UIDS date card stuff
- [x] implement search/filtering similar to prototype
- [x] Add loading spinner so user knows data is being loaded `<span class="fa-solid fa-spinner fa-spin"></span>`
- [x] Subsessions display with "group by month" unchecked is displaying Summer subessions after Fall
- [x] Swap out jQuery for standard JavaScript?
- [x] Lazyload in items to reduce page load time?
- [x] Sessions filter also seems buggy - Try filtering for "Fall 2024" with group by month checked
```

**Comment by briand44** [comment]
Do we need to have the session/month toggle public facing - Not required from Registrar, month used for academic calendar, session used for dates by session display. Should we be showing prior events from previous months if still part of current session - Brian to check on this but lets not plan on doing this unless they say they need it. In terms of accessibility, should we be switching focus after submit to the results? Do some voice over testing and other a11y testing.

**Comment by bspeare** [comment]
I moved the accessibility related work to a new issue at https://github.com/uiowa/uiowa/issues/7858 to try to reduce the size of this issue.  I still think this is a large.

**Comment by pyrello** [comment]
Since I was outvoted in making #7843 and #4943 priorities before this work, just noting here that the work we do in those issues may affect the eventual functionality of the JS being refactored/cleaned up in this work.

**Comment by pyrello** [comment]
This is looking good so far! No specific feedback yet, but a couple ideas for refactoring/optimizing:
- Look at core JS or JS from contrib modules by authors whose work you admire to see how they are organizing their JS code.
- Consider what pieces of this are specific to the Academic calendar (sort/parsing dates) and what might be generalizable (maybe we want to do more JS-based loading of a data set?). For generalizable parts, consider moving them to a separate library (JS file) or at least make sure they are encapsulated in a function call.

**Comment by joewhitsitt** [comment]
>Subsessions display with "group by month" unchecked is displaying Summer subessions after Fall

Can someone explain this a bit more?

**Comment by joewhitsitt** [comment]
> > Subsessions display with "group by month" unchecked is displaying Summer subessions after Fall
> 
> Can someone explain this a bit more?

Ben explained it to me and I believe it was resolved by https://github.com/uiowa/uiowa/pull/7890/commits/a872cb82f91cd1569392bcb5ade597ab780a3ddf

**Comment by pyrello** [comment]
In reviewing the code to prepare solutions for #7898 and discussing with Alan we noticed that the `fetch` JS function is called in 3 locations in the code (via the `fetchAndDisplayEvents()` function) both to initially load the page and then in response to changes to the filters. But based on the logic of our default display (when the page first loads) always including all events from the current session + 5, we start each page load with a complete list of every event that could possibly be shown. Additional calls to fetch results from the controller will only pull back a subset of that list or the complete list again. The subsequently fetched results shouldn't ever contain new events that were not previously included. Therefore, the additional AJAX fetches provide no new data and potentially are unnecessary. 

If our JS did the filtering that the controller is currently doing by parsing through the list of events that was originally loaded on page load, then we could eliminate those additional AJAX calls. The JS parsing is almost certainly going to be faster than an AJAX request, especially since the request has to do some amount of Drupal bootstrapping to either serve a cached result or to build a fresh result set and return it.

This has me toying with the idea of refactoring both the controller and the JS to move the filtering to the JS and to remove the additional `fetch` calls.

One potential complication would result from the possibility of a feature request to add the ability to pass in query string parameters to have the first page load reflect a particular state in terms of filters selected. In that case, it seems counterintuitive to load the full data set if some of the items will never be shown.

However, if we don't expect the full data set of events that could be shown on a single page to increase dramatically, I'd argue that it might be worth the trade off to eat that upfront cost of loading the full data set every time on first page load. I think most of the time cost of the AJAX request is eaten up by the overhead of bootstrapping Drupal rather than the size of the data set affecting it much. It probably isn't that much slower to always load the full data set. And any subsequent operations on the page are almost certainly going to be faster because JS manipulations can be very fast and we can avoid subsequent AJAX requests.

@GaryRidgway and I were planning on poking at this a bit tomorrow.
