### ISSUE TITLE
ITS alert requests

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7930]
- Next 7 days text on https://its.prod.drupal.uiowa.edu/alerts
  - If you scroll down to the bottom of the page and look at planned maintenance and service announcements, there is a slight difference between the two. Planned maintenance has the text "Services scheduled for maintenance over the next 7 days." We were hoping you could add this same text above the service announcements section please.
- All day check box on alert template
  - If you go into content and try to add an alert, there is a check box on the template under Dates Affected that says "All day". Can you please remove this check box? We cannot think of an instance where this check box would be used, we think it would cause confusion, and it would be best to just remove it.
- We want to train web editors on how to add an update to the alert using Drupal. We believe that the way things are set up now, the automatic email to helpdesk-notify@uiowa.edu is only triggered upon the creation of a new alert. Is it possible to make the automatic email get triggered by a new update to an existing alert?
  - If this is not possible, then we can just use our current method of having people email helpdesk-notify@uiowa.edu with updates.
- I was able to replicate the legend (https://its.prod.drupal.uiowa.edu/alerts) using a bulleted list with link titles to create the hovered text effect. I don't have access to the icons for the new alerts page, though.
  - Are you able to help me with this please?
- Asks in https://github.com/uiowa/uiowa/issues/7930#issuecomment-2248931573

**Comment by briand44** [comment]
Grooming conversation.. 

Text addition should be doable.

All day is part of smart date. Not sure if there is an option to remove or if we can hide with CSS or some fairly simple solution here. Cory mentioned as far as DB is concerned, pretty safe to hide or remove without downstream affects.

Legit request, let's see if we can accommodate.

Sean was able to get close with the legend icons but required wrapping the text in a link without the link taking you anywhere. Not sure on the best way to resolve that ask. Possibly add a custom block?

**Comment by pyrello** [comment]
Another request from ITS team:
- Can we allow editor roles to publish changes to service templates? Currently they cannot create or delete service pages, which is what we want. But if they have edits to an already established/published service, we'd like for the to be able to edit and publish instead of submitting their edits to review. This is similar to what we have with info centers and the third tier role on our current D7 site.
- Can we allow the editor role to replicate alerts. It looks like only publisher and webmaster role can replicate alerts and we'd like for editors to be able to as well. 

We discussed in EoD and agreed upon adding to the scope of this issue rather than adding a new issue.

**Comment by joewhitsitt** [comment]
>Can we allow editor roles to publish changes to service templates? Currently they cannot create or delete service pages, which is what we want. But if they have edits to an already established/published service, we'd like for the to be able to edit and publish instead of submitting their edits to review. This is similar to what we have with info centers and the third tier role on our current D7 site.

We can test this, but I believe it is setup that way:


![Image](https://github.com/user-attachments/assets/3228459d-f90e-465a-8822-de9131ee4416)


>Can we allow the editor role to replicate alerts. It looks like only publisher and webmaster role can replicate alerts and we'd like for editors to be able to as well.

This would be a ITS site-wide change (articles, page, etc.) as the replicate permission is not content type specific.

>Is it possible to make the automatic email get triggered by a new update to an existing alert?

I think to keep our sanity this would be any modification to the node (date change, service change, etc.), not just the addition of a new alert update ("this issue is closed").

**Comment by briand44** [comment]
>>Can we allow editor roles to publish changes to service templates? Currently they cannot create or delete service pages, which is what we want. But if they have edits to an already established/published service, we'd like for the to be able to edit and publish instead of submitting their edits to review. This is similar to what we have with info centers and the third tier role on our current D7 site.

>We can test this, but I believe it is setup that way

I think the issue here is an editor currently cannot publish the edits they make. I think it would be a change to the editorial workflow. Not sure if this would cause problems with articles, page, people content?

![Screenshot 2024-07-29 at 4 41 55 PM](https://github.com/user-attachments/assets/6f0a31cf-f23b-4638-82e7-362a8bc3590f)

**Comment by joewhitsitt** [comment]
Ah. Thanks for the clarification @briand44. So then would we just remove moderation for this content type as well?

**Comment by briand44** [comment]
Feedback from ITS... 

They are ok with us removing content moderation for services so editors can publish an edit to a service but not create new services.

They are ok if editors can replicate other types of content as long as they can't replicate and publish a new service. We should test replicating a service to make sure they can't publish.

They like the legend at the bottom but want us to include title text that gets pulled from the alert categories taxonomy description.
