### ISSUE TITLE
GPA Calculator branding and styling

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7933]
# Story

As a webteam, we would like to include some additional theming of the GPA calculator so that it uses University Branding and looks nice.

# Additional Information

https://registrar.prod.drupal.uiowa.edu/gpa-calculator - what is there now is still a deployment behind as of 8/20th.

We did minimal theming previously since this is a contrib module. We thought we likely should add some University Branding to this and otherwise clean up its appearance for display on the Registrar site.
```[tasklist]
### Tasks
- [x] Add new CSS file
- [x] Add new `registrar_core.libraries.yml` file to add an library item for the CSS file
```

**Comment by GaryRidgway** [comment]
I think it would be nice to try and collapse the form vertically to make sure there is not a lot of scrolling for the user who is using this calculator. I think it would be nice to remove some of the space between form fields, change the buttons to `bttn--small`, and perhaps even change the labels to be help text instead of labels above the form field.

**Comment by briand44** [comment]
Grooming conversation... Sean mentioned there is probably more work in general theming than actually brand related work. He also mentioned that the only thing probably critical is trying to get the inputs to display vertically inline with one another.

This should all be able to be handled within registrar unless we run into something we need to add to uids. Some conversation about this being a contrib module and there being possibility of it being used elsewhere. Could need a new library in uids base at some point.
