### ISSUE TITLE
Probe issue with umd command deleting wrong database

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7958]
# Story

As a webteam, we would like to understand why the wrong database was deleted while running `blt umd` so that we can understand if there are any additional tests or safegaurds that can be put in place to prevent this from happening in the future.

**Items mentioned in retro**
- Review our blt umd command to see if there are any bugs here? (BD)
   - Are files actually being deleted?! (Joe)
- Validate the theory about what went wrong (Sean)
- Potential future work to add tests/guards/warnings to prevent this from/alert us to this happening in the future (Sean)
- ~Document the path to success (Joe) - https://docs.prod.drupal.uiowa.edu/development-workflow/recovering-deleted-website~
- Get back to reviewing submissions and provision PRs more carefully (Joe)
- ~Make it known across the team that there is a weak link with converting special characters to underscores in our process (Joe) - https://docs.prod.drupal.uiowa.edu/acquia-cloud/note-about-databases-acquia-cloud~
- ~Meeting with the customer this afternoon to discuss and figure out next steps (Sean)~
```[tasklist]
### Proposed Solution
- [x] validate theory about what went wrong
- [x] Review blt umd command (check for bugs, check if files are actually being deleted)
- [ ] Identify any tests/safegaurds we should implement to prevent this from happening in the future.
- [ ] document any useful information for future
```

**Comment by briand44** [comment]
Grooming conversation... what files are we wondering about? `/mnt/gfs/app.env/sites`. When we deprovision a site the 'umd' command should delete that sites files. We should verify if that is actually happening/working. Could look at iowateacherintern.org since we just deprovisioned it.

How do we validate the theory of what went wrong. - By looking at the code and validating that what we think happened is possible/valid.

Scope to probing and understanding if any fixes are needed. If fix is easy, we can include here but not committing to that.

**Comment by joewhitsitt** [comment]
Capturing my slack comment here:

>Also created a note about databases on acquia cloud https://docs.prod.drupal.uiowa.edu/acquia-cloud/note-about-databases-acquia-cloud pointing out that the umd command does in fact loop through the applications and matches against the first human-readable for deletion: https://github.com/uiowa/uiowa/blob/508d9544d27e79dcd6758a395cd1a0933fa7f8b8/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L299 - https://iowaweb.slack.com/archives/C0164FNN1PV/p1722614087007409

**Comment by pyrello** [comment]
I think, based on the previous comment that we can consider the theory of what happened validated. First, the code loops through each application, `foreach ($this->getConfigValue('uiowa.applications') as $name => $uuid)`, and then loops through the databases on that application, `foreach ($databases->getAll($uuid) as $database)`. The applications are looped in the order that is specified in the `blt.yml` config file:
https://github.com/uiowa/uiowa/blob/508d9544d27e79dcd6758a395cd1a0933fa7f8b8/blt/blt.yml#L77-L85
The existing site happened to be on an older application and therefore its database was found first.

I don't see that we are loading the drush config in the command, but we could potentially do that to derive the specific application to avoid that outer loop. That wouldn't prevent this from happening again if both sites were on the same application, but it would make it less likely overall.

**Comment by pyrello** [comment]
Looking into this.

**Comment by pyrello** [comment]
Taking a look on `uiowa05` where `iowateacherintern.org` was recently de-provisioned, it looks like the files were removed as the code indicates. This means that the files directories themselves are not removed, but their contents are. There was still a config sync directory in `files` but everything else was gone. So it appears that it did work correctly.

I think the reason that the `michaelson.lab` files weren't deleted is that the method that actually deletes the files takes the application as an argument. Also, unlike the database name, the files path is unique for every site based on the fact that it contains the verbatim URL in the path. So, it was never a possibility that would delete the files. *whew*

**Comment by pyrello** [comment]
A test would be run after the provision command was completed, either locally (requiring a change to our process and significantly increasing the time provisions take) or via Travis, essentially checking that the code is good to go after the fact. But if the test revealed a problem, then it would be necessary to go back and make a change. That the test wouldn't prevent you from doing something that had to be changed later isn't great. **So, I don't think a test is the way to go here.**

Before we go any further in discussing a potential solution, though, I think we need to talk about what we want the outcome to be. **We could potentially solve the problem that we encountered before by adjusting the deletion command to use the information that is already known about the application the site lives on to ensure that the database is deleted from that application specifically.** 

Even with that fix, we could potentially still have an issue when attempting to provision two sites that have domains that get converted into the same database name on the same application. In that case, I think the provision command would probably fail, although possibly in a messy way.

While we would probably never want to allow a domain like `michaelson-lab.uiowa.edu` because it should instead use the `.lab.uiowa.edu` pattern, its hard to say with certainty that there couldn't be other overlapping domain => database situations that we would consider valid. I don't think that we should have domains name choices be constrained by the database name, since the database name can be any valid arbitrary string.

So, some possible solutions:
- Add the above fix to adjust the `umd` command to delete the database name on the specific application. We should do this no matter what else we do as this will help prevent the specific thing we encountered already and is a common sense improvement.
- Add a warning for when a domain would produce a duplicate database name. A developer would still need to decide what to do in that situation. Lightweight, but more potential for developer error.
- Change our database naming convention to use something like a UUID. This would be a fairly significant change requiring changes to how database config gets included, but would completely remove any constraint regarding domain name and destination application.

**Comment by joewhitsitt** [comment]
I'd lean towards a slice to make the `umd` more foolproof to ensure the site that was selected in the command is what is deleted. If that means the umd command needs to go beyond the human name and confirm the application and/or the database machine name by fetching more info about the site before deleting I think that would be good. We have worked hard to make deprovisions a JDI type task and I'd like to be confident we can continue treat them as such once all of the administrative checking is out of the way.

An optional additional slice would be to make sure the provision command would stop if the `$databases->create()` failed.

Though we have some validation on the request form our provisioning process still requires some human checking for issues. Like you said their could be a use-case for a particular near duplicate domain name and that we should just continue to take more than a glance at what we are moving forward with.

I personally would like to avoid changing up our database naming convention at this time.

**Comment by briand44** [comment]
Closing this but Brian going to put a follow up issue together to address the next slice.
