### ISSUE TITLE
Change filesystem structure for AFR

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7966]
Facilities and FO (others?) have been questioning our default filesystem structure of year month nesting which originated as the core default that we didn't change when we started v2.

https://www.drupal.org/project/drupal/issues/2128055

The idea at the time was that too many files in one directory can have performance issues and that the month year solution was set as a start point for the majority of websites using drupal to not run into an issue.

The original reasoning might be now dated:

https://serverfault.com/questions/59454/whats-the-maxium-number-of-files-a-unix-folder-can-hold/59458#59458

This is currently our default for file, audio, image, video: `file_directory: '[date:custom:Y]-[date:custom:m]'` and we have done custom paths for facilities building images and project reports.
```[tasklist]
### Proposed Solution
- [x] Establish site split for AFR
- [x] update config to change where file media type stored
- [x] Activate site split `ddev drush @foafr.prod config:import --source ../config/sites/afr.fo.uiowa.edu --partial -y && ddev drush @foafr.prod cim -y`
- [x] communicate with AFR so that they can remove files already added before rolling this out
```

**Comment by joewhitsitt** [comment]
I would imagine if we did this, it would be for new entities only and that we would not do a massive update hook. Also, this would be the general buckets. Any custom content type related media fields can be configured to a separate bucket to help reduce the chance of a large site putting too many eggs in one basket.

I also think that it would be helpful for remaining D7 sites so that when they manually download and upload files as part of their transition that the file paths should stay the same requiring less post-launch work in creating redirects for files based on analytics.

**Comment by briand44** [comment]
Grooming conversation... When a file is added it gets a url path with month and year and if the file gets updated yearly, it can be confusing to visitors because the url is showing a different date than the replaced file. Also, they would need to create lots of redirects because there are other apps with links to these files that they don't control. Going forward with media field references we can have those files be uploaded to a specific directory to avoid all files being in a single directory. Could we keep the files stored where they currently are but allow accessing them at a different path? That may add additional security benefits. May want to take a look at https://www.drupal.org/project/media_alias_display. Changing the file locations could cause issues down the road but not sure what those would be at this time. 

Discussed a probe to look into https://www.drupal.org/project/media_alias_display, reach out to Acquia to see if they have any guidance or limitations to how many files can live in a given directory. Goal of probe to determine if we should move forward with a change here and if so, are we changing the location of where the files are stored or how they are accessed. Probe sized as medium

**Comment by pyrello** [comment]
Noting this comment in the Server Fault article above that indicates potential scaling problems with filesystem operations as the number of files in a directory increases: https://serverfault.com/a/59456.

**Comment by joewhitsitt** [comment]
Brian asked me to make a comment here since I will be out. I think I recall Sean suggesting perhaps we just do a site specific solution for now so that we can learn more without going too far either way. I think I am coming around to that thought though I think Facilities (related people) will be asking for the same thing shortly after. If we are able to keep this fairly quiet for now, a site or feature split changing the file upload path for the media types from a date-based pattern to a media-type pattern sounds good to me. The other solution seems like a considerable investment to switch over to (just so a site can launch) and ultimately doesn't give us that filename.pdf type solution.

**Comment by briand44** [comment]
My understanding for AFR is that their preference for documents/files would be that they are stored in the same location as their D7 documents/files so that they are available at `sites/afr.fo.uiowa.edu/files/[filename]`.

**Comment by briand44** [comment]
Grooming conversation... Question came up about how many files. Our best estimate is currently 100-150. It was mentioned that AFR is ok with removing and re-adding the dozen files that currently exist on their new site so we likely can avoid an update hook here.

https://github.com/uiowa/uiowa/blob/main/config/default/field.field.media.file.field_media_file.yml#L28

Joe mentioned he would like to avoid files in the root for majority of sites so maybe a site split for AFR and others could be more media based.

When we communicate this we should make sure we communicate it in a way that reflects that it is ok for this site but may not be an option for other sites.

Decided to scope this to just address the file media type and storing those in the root files directory.

**Comment by briand44** [comment]
I reached out to AFR and let them know we plan to only address the file media type and that we do not plan to update any existing files they have added. I let them know that this is something we can do for the AFR site but may not be an appropriate path forward for other sites. They responded and don't have concerns with our plan.

**Comment by bspeare** [comment]
I have activated the site split and notified the AFR team.
