### ISSUE TITLE
Write parallel command output to log file and search it for errors instead of variable

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8016]
# Story

As a web team, we would like to write parallel command output to log file rather than variable and search it for errors so that we can have these logs around longer and possibly speed up the deployment.

# Additional Info

> 1. At the point where we invoke the parallel processing command, we could pipe that output to a log file just to have it since the AC task log doesn't stick around long enough to be useful a lot of the time. This could be done to provide a more robust feedback system regardless of whether we use those logs for further processing.
> 2. We could experiment with swapping out the method we are using for error-checking in parallel processing to use log file output instead of assigning the output to a variable. This might be both more performant and less susceptible to failure based on trying to assign to much data to a variable.

Grooming conversation - https://github.com/uiowa/uiowa/issues/8004#issuecomment-2310826574

**Comment by joewhitsitt** [comment]
Capturing some potential usable code for this issue and thoughts to consider:
https://github.com/uiowa/uiowa/issues/7800#issuecomment-2299134874
https://github.com/uiowa/uiowa/issues/7800#issuecomment-2299196276

**Comment by joewhitsitt** [comment]
In the meeting, Acquia made it sound like there might be an ACLI command that can fetch this log data for us, but that it might just mean we don't need to store it ourselves.

**Comment by joewhitsitt** [comment]
welp, I was hesitant at sharing this because it didn't fit the narrative of this task but i found a way to measure memory consumption of a function. here is the before and after. obviously it is local and with like 4 sites that have no updates, so Sean's concern about big variable storage might still be a thing. i like the solution in #8069 and still think we should roll with it so we can still inspect the logs beyond the time that Acquia Cloud UI allows.

log file:
Memory usage before execution: 2960040 bytes
Memory usage after execution: **3192680** bytes
Peak memory usage: 4194304 bytes

variable:
Memory usage before execution: 2960040 bytes
Memory usage after execution: **3189152** bytes
Peak memory usage: 4194304 bytes

Also, here is the nifty code I put in there:

```php
// Capture initial memory usage.
$initial_memory_usage = memory_get_usage();

// Capture peak memory usage before running through function.
$initial_peak_memory = memory_get_peak_usage(TRUE);

// Middle guts of the function.

// Capture memory usage after most of function.
$final_memory_usage = memory_get_usage();
$final_peak_memory = memory_get_peak_usage(TRUE);

// Output memory usage statistics.
$this->say('Before ' . $initial_memory_usage . ' bytes');
$this->say('After: ' . $final_memory_usage . ' bytes');
$this->say('Peak memory usage: ' . $final_peak_memory . ' bytes');

// throw exception code.
```
