### ISSUE TITLE
Investigate views xml backend for final exam schedule

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8024]
# Story

As a webteam we would like to investigate views xml backend so we can understand if it makes sense to invest in trying to use that module to implement the final exam schedule.

# Additional Info

While grooming https://github.com/uiowa/uiowa/issues/4967, we decided to investigate views_xml_backend to understand if it makes sense to try to move that module forward for use on the Registrar v3 site for the Final Exam Schedules.

It would be good to have an implementation plan for https://github.com/uiowa/uiowa/issues/4967 as a result of this investigation.

Grooming conversation - https://github.com/uiowa/uiowa/issues/4967#issuecomment-2315993677
Additional comments:
https://github.com/uiowa/uiowa/issues/4967#issuecomment-2316093450
https://github.com/uiowa/uiowa/issues/4967#issuecomment-2316156333

**Comment by bspeare** [comment]
Spent the day trying to update the merge request on https://www.drupal.org/project/views_xml_backend/issues/3369810#comment-15751700 to be D10 compatible.   There's still more testing to be done on it but it does work for outputting the schedule.  With that said, I definitely understand if we want to move faster and head towards Joe's suggestion at https://github.com/uiowa/uiowa/issues/4967#issuecomment-2316093450.

<img width="1421" alt="Screenshot 2024-08-30 at 4 50 35 PM" src="https://github.com/user-attachments/assets/2080b21a-beb5-4753-a638-0deba7ac0ace">

**Comment by joewhitsitt** [comment]
I wonder how difficult it would be to create a custom views query plugin that fetches/parses xml. Sean brought up a good point about the things we take for granted with Views. Maybe a profdev idea?! 🤔 

Generally, I still think that views_xml_backend is weak right now with a big issue queue, with an alpha over a year ago no real activity since. I don't like the idea of running with a patched alpha, but at the same time, it isn't the type of thing that will result in data loss if things were to go sour and we could pivot then.

Ultimately I still think a custom block, that takes in the legacycode value with similar JS filtering as we did for academic calendar would be the smallest slice and allow us to make the necessary a11y enhancements.

**Comment by joewhitsitt** [comment]
>I wonder how difficult it would be to create a custom views query plugin that fetches/parses xml. Sean brought up a good point about the things we take for granted with Views. Maybe a profdev idea?! 🤔

Poked at that idea a bit. Maybe not. It would essentially be developing our own version of views_xml_backend. Beyond the query, we would have to account for field, error, cache handling.

**Comment by joewhitsitt** [comment]
Going to try to summarize my thoughts from previous comments and capture some discussion Sean and I had in Slack:

- No strong feelings. Pros and cons to both. I was trying to convey that I was indecisive with this comment: https://github.com/uiowa/uiowa/issues/8024#issuecomment-2329365255
- Still think a custom block plugin sans views is the smallest slice. That is only my opinion though.
- I was impressed that Ben had a POC up and running and Sean brought up a good point about leveraging the rest of views once the data is in there is always nice. but it is how we handle taking in the legacyCode property where I feel like there are some unknowns. Relying on an patched alpha module as we try to stay up to date with Drupal core is another concern.
- Aggegator was brought up as an example of where we have blended blocks and views before, but that is a fielded block content type that does it's own wrangling outside of views. I am not aware of a block plugin that takes config/argument that we then pass into views. I think it would be possible but something new that will have bumps along the way.
- Up until this issue we have not relied on views_xml_backend or views_json_source for anything and instead built our own API fetchers and I think we have some decent past examples in our codebase to get moving with quickly.
- Both methods would need to fetch sessions from uiowa_maui? to obtain the legacycode.
- Sean had mentioned a small slice to start with the block plugin that gets the sessions/legacyCode as a way to further determine which way to go in the end. I'd be fine with that if the team doesn't want to pick one or the other to finish out this task.

**Comment by pyrello** [comment]
Noting that we have a previous API implementation that processes an XML response. However, this does not use our established pattern of extending ApiClientBase. A new implementation should follow that pattern, so the previous work might be of limited value for copy/pasting.

**Comment by joewhitsitt** [comment]
Both calls are to maui i think (sessions, exams). When thinking it would be a smaller slice, I wasn't thinking this would be the time to break from using uiowa_maui and use ApiClientBase which has json assumptions. The existing `getSessionsBounded` is what I thought would be used for sessions. If we did use ApiClientBase, i think it would get bigger in size.

**Comment by pyrello** [comment]
> Aggegator was brought up as an example of where we have blended blocks and views before, but that is a fielded block content type that does it's own wrangling outside of views. I am not aware of a block plugin that takes config/argument that we then pass into views. I think it would be possible but something new that will have bumps along the way.

I was grasping for an example of this and I may have said block plugin, but that was not the important part of what I was trying to say, which is that we have examples in our codebase of programmatically rendering a view:

https://github.com/uiowa/uiowa/blob/9b898285dbfcac41dd73e1a94a25f0bbaba52a54/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L549-L551

> Relying on an patched alpha module as we try to stay up to date with Drupal core is another concern.
I've honestly stopped paying much attention to the use of `alpha/beta/RC` for anything but core or contrib modules maintained by pros. My own experience of maintaining modules has been littered with examples of me doing things because I thought they were necessary or important but ultimately I didn't really understand what I was doing or why I was doing it. One person's `alpha` is another person's stable release. If the code does what its supposed to do and doesn't have any obvious defects in it, then I'd say its probably okay to use it.

The concern about keeping the module up-to-date so that we can move to the latest version of Drupal core is a valid concern. However, Drupal core is back to a two-year cycle for major version releases (after breaking that because of CKEditor 5 for D10), so we have a much longer window to be able to upgrade to D11 than we had for D10.

> Both calls are to maui i think (sessions, exams). When thinking it would be a smaller slice, I wasn't thinking this would be the time to break from using uiowa_maui and use ApiClientBase which has json assumptions. The existing getSessionsBounded is what I thought would be used for sessions. If we did use ApiClientBase, i think it would get bigger in size.

The `MauiApi` class is what `ApiClientBase` was originally based on and it also has JSON assumptions baked in. I'm okay with increasing the scope a little bit to clean up our API implementations a bit.

**Comment by joewhitsitt** [comment]
>we have examples in our codebase of programmatically rendering a view

You are right. I didn't look deep enough. Probably would want to look at this block plugin example then instead of those v2 paragraphs:
docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/ScholarshipsBlock.php
