### ISSUE TITLE
Probe exposed filters for local event list block

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8041]
# Story

As a web team, we would like to understand if exposing filters for the local event list block will be straight forward or if it is going to get complex so that we can determine the best way to solve for AFR event needs.

# Additional Info

Trying to decide between making enhancements to the page or enhancements to the list block. List block may add more value long term but could also be the more complex slice of work here.

Filters AFR would like:

- Search
- Category filter
- Date Range?

Scheduled a meeting with AFR to better understand how they intend to use and if the date range filter is necessary or nice to have here.

Team didn't think this would require much investment JDI/small type of task.

**Comment by briand44** [comment]
During our last meeting, AFR said the most important filter is the category filter. They could live without the search and the date range filter.

**Comment by bspeare** [comment]
Here's what the work in https://github.com/uiowa/uiowa/pull/8050 looks like. 

<img width="687" alt="Screenshot 2024-09-06 at 10 17 26 AM" src="https://github.com/user-attachments/assets/7ec4d18d-494b-4b8d-bd62-5ce01a7442be">


https://github.com/user-attachments/assets/1cbfe77b-3fad-45c7-ab85-427bc27d4594

- This uses the `date_popup` module to convert the exposed date field to a date input field. 
- Do we need a date range or can we just select a start date to minimize the amount of date inputs on the page?

**Comment by joewhitsitt** [comment]
I don't know if we have specifics about what they _need_ or _want_ specific to date filtering, and in fact I don't think we need to have that for their launch. They mentioned in the meeting that knowing it was showing upcoming by default and the old ones would fall off is nice. Their current site shows all so I think there was this idea that a user could limit the results and zero in on a specific period of time. It isn't clear to me or I wasn't paying attention on whether they would need the ability to see past events.

In terms of this probe (not necessarily afr.fo), I think it is more about what we can realistically offer for date filtering. Like if this is the start date filter on a upcoming events views block, so would it default to today? Something that occurred earlier in the day than now, are we still showing that? Should the date picker limit traversing back before today? Are we going to develop similar functionality as the uiowa events block for past/upcoming/date range? Does paging still work as expected based on what we do?

**Comment by bspeare** [comment]
Good questions! 

- Yes, the date input would show upcoming based on today's date and old ones would fall off.  Events earlier in the day would remain for the entire day. 
- The date input defaults to today, but can be set to default to any date in the block configuration. 
- I don't think we would want to limit the date range picker for past dates?  
- Paging still seems works as expected. 
- A "timeframe" feature would be useful if we want to avoid offering the date popup.  Or it could be a useful enhancement in the future if needed.

**Comment by briand44** [comment]
I asked Lauren previously if AFR needed to show past events:

>I believe the AFR team would not need to display event with a date in the past, since they have been rolling off events on their current site after they have past.

She asked Robert to confirm but I never got confirmation.

>Events earlier in the day would remain for the entire day.

Is this true? I noticed the other day that there was an event displaying on the event page that wasn't displaying on the list block. The event date was that day so I thought that there may be a granularity difference between the list block and the page (when date range filter disabled).

**Comment by bspeare** [comment]
> Is this true?

In local testing they are showing. 

The greater issue is probably handling the default date.    Since this value is exposed and set into the block config, this probably is fixed to whatever date is selected here?  Perhaps we might not want to expose this date field unless we want to hide the date popup input pictured here in the block config and override the default value and set it to load today's date.   

<img width="515" alt="Screenshot 2024-09-06 at 11 43 19 AM" src="https://github.com/user-attachments/assets/4f2d8114-6d1f-4803-b746-cfd02b3ee47b">

**Comment by bspeare** [comment]
<img width="1431" alt="Screenshot 2024-09-09 at 9 39 12 AM" src="https://github.com/user-attachments/assets/26957c19-c1bc-4327-93b8-8dbed912f37d">


It looks like the `date_popup` overrides the JQueryUIDatepicker in better exposed filters.   

The good news is that the native date input is keyboard accessible whereas the JQueryUIDatepicker has been removed from new versions of `bef` because it is not accessible at all. 

<img width="1361" alt="Screenshot 2024-09-09 at 9 39 18 AM" src="https://github.com/user-attachments/assets/f900b386-de21-480e-8f86-ad82d84a73df">

If we wanted to go that route, then we would need to add the label display back into our exposed filter display. 

<img width="969" alt="Screenshot 2024-09-09 at 9 46 48 AM" src="https://github.com/user-attachments/assets/1862db1d-8651-421e-9aa6-497de3ae94e9">

**Comment by bspeare** [comment]
# Summary

If we want to add the exposed date field on the local events list block we will need to use https://www.drupal.org/project/date_popup.  

Complications:
- Our current version of Better Exposed Filters still uses JQueryUIDatepicker.  We will need to turn off JQueryUIDatepicker on the local event feature to use the `date_popup` field. 
- Because the date input doesn't support placeholders (https://www.drupal.org/project/date_popup/issues/3424371), we will need to display the field labels which are currently visually hidden for screen readers. 

The result looks like this where items in a `<details>` do not display a label because the `<summary>` is always visible and there is no need for a duplicate label.  I don't mind how the `<details>` look without a label since those are a bit different from the other fields. 

<img width="1506" alt="Option4-open" src="https://github.com/user-attachments/assets/68b58601-3548-4f72-8637-1e37ea4ffa45">


### Additional notes:
- Better exposed filters removes JQueryUIDatepicker in the next version that we will use https://www.drupal.org/project/better_exposed_filters/issues/3210945. 
- Core is still working on adding the date field as a default in 11.x: https://www.drupal.org/project/drupal/issues/2648950. 

## Next steps

We could either

1. Move forward with https://github.com/uiowa/uiowa/pull/8050 which adds:
- Local event list block with exposed date, title, and category filter
- Local event page switches from JQueryUIDatepicker to date input
- Displays labels for all fields except `<details>`
- Contact customers with views exposed filter displays to let them know that the form labels will appear above fields except for `<details>`

Or

2. Move forward with:
- Local event list block with exposed title and category
- Delay https://github.com/uiowa/uiowa/pull/8050 and see if we can preprocess a label to appear above each `<details>`

My recommendation is option 1 because the work is mostly done and I don't see the label on the `<details>` as essential.

**Comment by joewhitsitt** [comment]
I think I am fine with option 1 as well but i'd be curious to know what changes once BEF comes out with a new stable release. Does date_popup stay? Core will always be working on date...

**Comment by bspeare** [comment]
@joewhitsitt BEF added a separate option called "Date Picker" that implements the date field.   Using "Default" here as an option uses date_popup. 

<img width="111" alt="Screenshot 2024-09-11 at 8 53 25 AM" src="https://github.com/user-attachments/assets/94a49e93-631b-4159-a8ac-c4d357e27095">
