### ISSUE TITLE
Investigate file structure change

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8064]
While grooming https://github.com/uiowa/uiowa/issues/7966, we discussed a probe could be helpful here.

Discussed a probe to look into https://www.drupal.org/project/media_alias_display, reach out to Acquia to see if they have any guidance or limitations to how many files can live in a given directory. Goal of probe to determine if we should move forward with a change here and if so, are we changing the location of where the files are stored or only how they are accessed?

https://github.com/uiowa/uiowa/issues/7966#issuecomment-2344444870

**Comment by joewhitsitt** [comment]
Going to start by opening a ticket with Acquia

**Comment by joewhitsitt** [comment]
Starting to look at the module and here are a couple observations so far:

- The current pattern set is media/[media:bundle:target_id]/[media:mid] which could change, but we ultimately probably want to avoid using the uploaded filename because of the media replace functionality already in place.
- Had to check the "standalone media URL" option under Media > Security config. This makes easier for spammers, etc. to guess and hit file paths by hitting media/file/117, media/file/118, etc.
- When referenced via media field/linkit_media_library the output URL is still the date based URL
- There seems to be a disconnect between existing files and new files. New files, hitting media/file/117 for example will trigger the save as of the browser. Old files will take me to the media entity route where the linked generic file is output.
- Re-saving an existing file causes something like media/file/117-0 to happen and still doesn't trigger the download properly.
- The save file as filename is the alias (e.g. 117, or a custom "my-file" instead of the filename stored on the server)
- There is a sub-module that "adds a media field to override media alias display on specific entities" which I think means for new files takes you to the media entity page instead of triggering download. Seems to have no effect on existing.
- We would have to remove our protection/fix in place surrounding the media alias (editors previously had the ability to change the alias which prevented them from getting to the edit route of the media entity) https://github.com/uiowa/uiowa/blob/3526f8284d4c486e684590c165e668dda846173b/docroot/profiles/custom/sitenow/sitenow.profile#L521

As it relates to afr.fo, this will give them non-date paths to access files directly, but won't prevent date-based paths from showing when referenced and by default won't match the URLs from the v1 site unless they set custom aliases (which as mentioned earlier could cause confusion/conflict with the replace functionality).

**Comment by joewhitsitt** [comment]
Didn't find anything in d8+ that made it seem like an editor could override a default directory setting and upload it elsewhere. It looks like file_paths might be the closest but at a glance I wasn't able to get it to work as I would expect it to.

[media_entity_download](https://www.drupal.org/project/media_entity_download) seems to be close but I think linkit_media_library might need to change to handle it properly. Without turning on the standalone media URL, you can have media/117/download type paths and that linkit can be updated to direct download them/reveal that path instead of the absolute date-based path that it is actually uploaded to.

**Comment by joewhitsitt** [comment]
Came across https://www.drupal.org/project/media_directories/issues/3045654 (which hints at the same single-directory concerns previously discussed) and https://www.drupal.org/project/media_directories/issues/3178219 (taxonomy driven upload organization, but it still needs work to deal with rename/move type operations). Still don't know how a "root" location work to mirror AFR's v1 file locations.

Trying to get [media_alias_display](https://www.drupal.org/project/media_alias_display) to _just work_ as expected with existing files though.

**Comment by joewhitsitt** [comment]
Brian brought up in EoD that SiteNow v1 was configured to use the root directory with a wysiwyg_uploads as well as other content type specific directories (e.g. profile photos) and there wasn't a problem before with that kind of less granular separation.

So with most sites having adopted v3 and funneled into these date specific folders already, then setting media type defaults file/annual_report.pdf, image/doe-john.jpg or featured-image/kinnick-field.jpg might be enough separation.

We could rely on other metadata to create separation as well that doesn't come off as a date. I've seen things like hashes suggested, but that makes it harder to track down if you ssh in to the server. unix timestamp for the first day of the month at 12:00:00 AM is shorter and is fairly easy to convert /1725148800/report.pdf

AFR would still need to rely on redirects for certain files if it wants to maintain that root level file path.

Ultimately, still waiting on Acquia's response about performance.

**Comment by joewhitsitt** [comment]
I was going to put together a POC for media_entity_download, but I think that linkit_media_library would need to be updated to insert media/mlid/download instead of media/mlid to work. default linkit works by changing a setting on the matcher config. not sure what the difference is, but it is probably a gap that linkit_media_library is not accounting for. When things work, it produces a URL like `https://foafr.uiowa.ddev.site/media/46/download?inline` and doesn't highjack the media entity edit form at media/46.

**Comment by joewhitsitt** [comment]
Figured out the issue with existing files. If the file doesn't exist, it sends does work. `--sync-public-files` solved the issue.

**Comment by joewhitsitt** [comment]
So I think to move forward with this, here is the remaining todo:

- Decide if we are changing the default media alias.
- Decide on whether we are updating existing links in WYSIWYG and other field/code instances to point to the canonical instead of the media entity file.
- Update hook to bulk delete media aliases and then programmatically save all media entities? This might need more probing.
- Update linkit_media_library to use canonical substitution instead of media.

This will allow date-based separation of files on the server but allow custom or non-date-based links to be used/viewed by visitors, reducing confusion about when the file was updated. I think redirects would still be needed unless the alias included the full filename with extension.

**Comment by joewhitsitt** [comment]
Heard back from Acquia:

>it is still recommended to split files up among multiple directories. It will still cause issues to have too many files in a directory.

**Comment by pyrello** [comment]
> The current pattern set is media/[media:bundle:target_id]/[media:mid] which could change, but we ultimately probably want to avoid using the uploaded filename because of the media replace functionality already in place.

I'm not sure I'm following this. I think the ideal scenario is that we would still provide a URL that looks like a file path. If people hover over a link and see the URL as a path that ends in `.pdf` or whatever, it communicates something about what to expect. Seeing a link like `/media/file/345` is potentially confusing and at a minimum it doesn't set them up for what to expect after they click the link.

With the file replace functionality, wouldn't the file name be the same between versions?

> Decide on whether we are updating existing links in WYSIWYG and other field/code instances to point to the canonical instead of the media entity file.

If existing links would continue to work, I'd be inclined to just leave them as is. Updating every single link across all sites because of a single request (or a few requests) seems like overkill to me.

**Comment by joewhitsitt** [comment]
Just stating that the media alias pattern is `media/[media:bundle:target_id]/[media:mid]`. It isn't set in stone and can be changed. Having it look like a filename path though is not what this module intends to do. You might be able to string together a pattern that would work like that `/[file:filename].[file:ext]` (not sure what is available) but with media_file_replace they can replace a .docx with a .pdf so I don't know if that would be a good pattern. They currently have the option to overwrite the existing filename or use the new replacement filename.

<img width="627" alt="Screenshot 2024-10-02 at 3 37 17 PM" src="https://github.com/user-attachments/assets/68603d69-5e8e-44f0-a444-38ad5973c827">

>If existing links would continue to work, I'd be inclined to just leave them as is. Updating every single link across all sites because of a single request (or a few requests) seems like overkill to me.

👍
