### ISSUE TITLE
ITS alerts not sending bcc email

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8106]
> Hi all, the alerts aren't going to the Teams IT Service Alerts channel. I've reviewed the settings and I have the teams address in the BCC line. Can you think of any reason the alerts aren't going to Teams?

---

Update: its-web email to the email team and Adrienne. they are looking through the logs. Brian added its-web to the bbc line and it didn't get an email either.

some detective work was done here: https://iowaweb.slack.com/archives/C0164FNN1PV/p1727362401769659

some options if it isn't an issue on the ITS email team side:

- refactor to send a separate email to the teams address (single value) either as a hotfix or with changes to the configuration form.
- create a similar but separate example on sitenow (site split) that we can test and figure out.
- debug the difference between webform bcc and ITS' alert email bcc.
- open a support ticket with Acquia regarding sendmail -t configuration and bcc handling/exposure.

**Comment by joewhitsitt** [comment]
The email team came back that they didn't see any activity related to those addresses being sent the emails.

**Comment by briand44** [comment]
Grooming conversation... Team felt that it is probably worth troubleshooting this a bit more before changing directions here. We need to be careful though so we don't send an email by accident.

If we aren't able to identify the issue or resolve the issue and need to refactor, let's adjust the config form as well.

Current code https://github.com/uiowa/uiowa/blob/main/docroot/sites/its.uiowa.edu/modules/its_core/src/Plugin/EmailBuilder/ITSAlertEmail.php#L37

also 
https://github.com/uiowa/uiowa/blob/main/docroot/sites/its.uiowa.edu/modules/its_core/its_core.module#L152

**Comment by bspeare** [comment]
Possible questions for Acquia:

- Does Acquia platform mail only support `-t` mode? Is `-bs ` a possibility?
  - https://docs.acquia.com/acquia-cloud-platform/manage-apps/platform-email/faq#section-what-are-the-flags-supported-by-platform-email-for-the-sendmail-command
  -  https://github.com/symfony/mailer/blob/v7.1.5/Transport/SendmailTransport.php#L46C31-L46C97
  - https://www.drupal.org/project/symfony_mailer/issues/3348345#comment-15346036
- Why does webform bcc work when symfony mailer does not?
  - Webform uses webform_php_mail instead of php_mail after running `ddev drush @sandbox.prod config-get system.mail` which might be why BCC is working with webform.

**Comment by bspeare** [comment]
Today I will update https://github.com/uiowa/uiowa/blob/main/docroot/sites/its.uiowa.edu/modules/its_core/src/Plugin/EmailBuilder/ITSAlertEmail.php to include a separate email for ITS using `$its_settings->get('single-alert-bcc')` field.  I will probably update the help text on the BCC field to remove mention of "Multiple emails should be separated by a comma" since we don't have the ability to bcc.  Or, are we looking to to restructure this config form further?  If so, what changes on the form do we want to implement?

**Comment by joewhitsitt** [comment]
This might be largely re-wording what you stated but i'd approach it like...

"We are getting reports that BCC addressed emails sent via Symfony Mailer are not being received through Acquia Platform Email but that Webform emails are." Illustrate you have looked at their docs a bit and ask if they happen to know why and if we can even achieve secure BCC given their documentation.

**Comment by joewhitsitt** [comment]
For the re-structure, if it isn't too much more, I'd go ahead and do an update hook to switch the config to something that isn't mentioning BCC so we don't get confused in the future.

**Comment by joewhitsitt** [comment]
Out of curiosity, I added myself as BCC on a resend email for the SiteNow Request form. Did not get it. So not all "webform" emails handle BCC.
