### ISSUE TITLE
Rotate Deploy Key

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8118]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1727791227606959

https://docs.prod.drupal.uiowa.edu/acquia-cloud/rotate-deploy-key

**Comment by briand44** [comment]
Grooming conversation... Follow the docs. There is a service account that gets emails that most of the team probably doesn't have access to or at least we don't have it setup. ui-acquia-github@uiowa.edu. Should be notes in our password manager for ui-acquia-github entries.

**Comment by briand44** [comment]
Just mentioning there is a reminder on the its-web calendar about this on 10/25/24. We should update that reminder for another year as part of this work.

**Comment by bspeare** [comment]
I have a question about step 8 on https://docs.prod.drupal.uiowa.edu/acquia-cloud/rotate-deploy-key regarding the personal access token.  Does anyone have experience with this?

**Comment by bspeare** [comment]
It looks like our personal access token (https://github.com/settings/tokens) in step 8 on https://docs.prod.drupal.uiowa.edu/acquia-cloud/rotate-deploy-key expired on 10/3/24 based on an email to ui-acquia-github@uiowa.edu.  We might want to wait to pair with Joe on this when he returns.   

Should we forward emails from ui-acquia-github@uiowa.edu to its-web so that we don't miss these notifications in the future?
<img width="513" alt="Screenshot 2024-10-17 at 9 09 47 AM" src="https://github.com/user-attachments/assets/c68c18ec-c708-4064-beae-718bf2c9572d">

**Comment by joewhitsitt** [comment]
>I have a question about step 8 on https://docs.prod.drupal.uiowa.edu/acquia-cloud/rotate-deploy-key regarding the personal access token.

Shoot. I might be able to answer.

>Should we forward emails from [ui-acquia-github@uiowa.edu](mailto:ui-acquia-github@uiowa.edu) to its-web so that we don't miss these notifications in the future?

I wouldn't be opposed to this. We rarely if ever send from this account. Could we do this for its-webservices too?

**Comment by bspeare** [comment]
@joewhitsitt the step 8 questions are:
- Since our token expired do we create a new Classic or Beta token?  Should we add some more instructions on what needs to be done if we let the token expire?

<img width="1005" alt="Screenshot 2024-10-24 at 9 12 42 AM" src="https://github.com/user-attachments/assets/f9965479-0c3e-4ea4-8dde-03ff6c6eff8a">

- Next question on "Follow [https://github.com/travis-ci/travis.rb#login](https://github.com/travis-ci/travis.rb) and [https://docs.travis-ci.com/user/github-oauth-scopes/#repositories-on-httpstravis-cicom-private-and-public](https://docs.travis-ci.com/user/github-oauth-scopes/). You will need to copy/paste this token further on, so keep it open."
  - I'm not sure what steps we need to incorporate from these links.  Could you provide further details?

**Comment by joewhitsitt** [comment]
- i'd go classic until we can't. if that were the options last time, i most likely went that way.
- step 8 is the set up for step 14 (using travis cli to create encrypted file using github authentication (personal access token))

It looks like the links are slightly broken though: https://github.com/travis-ci/travis.rb?tab=readme-ov-file#login, https://docs.travis-ci.com/user/github-oauth-scopes/#repositories-on-httpstravis-cicom-private-and-public

**Comment by joewhitsitt** [comment]
I can offer to work on this later and take another pass at the documentation as most other answers will come from fiddling with it and trying to move forward with it.

**Comment by joewhitsitt** [comment]
Okay. I updated the instructions here to try and make some things clearer: https://docs.prod.drupal.uiowa.edu/acquia-cloud/rotate-deploy-key

fyi - accidentally changed the github and shared email account passwords. should all be good and updated now in esaccess but still.

**Comment by joewhitsitt** [comment]
Will wait to close once this has been deployed all the way to prod. Then I will set up reminders and remove the old keys from acquia and github dedicated accounts.

**Comment by joewhitsitt** [comment]
Release with key going out. Recurring event reminder updated and old keys have been removed from acquia/github.
