### ISSUE TITLE
Probe workspaces

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8136]
# Story

As a webteam, we would like to understand if the workspaces functionality in core could be used within SiteNow to allow content editors to stage and deploy content changes.

# Additional Info

Clas is looking for a safe solution as they revamp some of their v3 websites that were launched prior to their existing content strategies.

> Is it possible to pull a copy of the sites we're working on down into a production environment where we can make our updates that then can be pushed back to live after we're done? 

Do we need to be on 10.3 before we can move forward with Workspaces if we want to?

**Comment by joewhitsitt** [comment]
Brian asked me to make a comment here since I will be out. I am all for probing this functionality, but I think we need to pay particular attention to what it does behind the scenes. database size and how it affects certain other layers of functionality (cron, cache/varnish, bulk operations, entity_usage, replicate, moderation, scheduler, revisions, prevent deletion (front/terms), etc.)

Ultimately, I don't see most sites using this, so keeping it a feature split makes the most sense to me if we move forward with it.

**Comment by briand44** [comment]
Grooming conversation... Sounds like since we are close to rolling out 10.3, we might as well wait until that rolls out. Can we keep this fairly simple and not require folks to create workspaces so usability doesn't become a problem. Want to be on the lookout for some of the concerns Joe mentioned in https://github.com/uiowa/uiowa/issues/8136#issuecomment-2411970039. Scope to understanding if we think this is a viable option for CLAS and potentially others to use in these circumstances. Sized as a medium to give us enough room to evaluate all the things mentioned in https://github.com/uiowa/uiowa/issues/8136#issuecomment-2411970039.

**Comment by briand44** [comment]
blocked until we roll with 10.3

**Comment by joewhitsitt** [comment]
The first thing i've come across is that instead of maintaining a copy of the db, workspaces are just revisions of content that are tied together (`workspace_association`). So our old practice of targeting the latest revsision id or something might need to be adjusted (p2lb, replicate, moderation behaviors, lb content updates)

**Comment by joewhitsitt** [comment]
So something like:

```php
$latest_revision_id = \Drupal::entityTypeManager()
  ->getStorage('node')
  ->getLatestRevisionId($node_id);
```

will need to be updated to something like:

```php
$live_workspace = \Drupal::service('workspace.manager')->getLiveWorkspace();
$storage = \Drupal::entityTypeManager()->getStorage('node');
$latest_live_revision = $storage->loadRevision($storage->getLatestRevisionId($node_id, $live_workspace->id()));
```

**Comment by joewhitsitt** [comment]
Same for things like entity queries I think:

```php
$workspace_manager = \Drupal::service('workspace.manager');
$current_workspace = $workspace_manager->getActiveWorkspace();

if ($current_workspace->id() === 'live') {
  // Do something only with the live environment.
}
```

**Comment by joewhitsitt** [comment]
ack!

Tried to use the stage workspace to delete demo content like when we are setting up the intranet feature:

```
The website encountered an unexpected error. Try again later.

Drupal\Core\Entity\EntityStorageException: This content item can only be deleted in the Live workspace. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->delete() (line 763 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
workspaces_entity_predelete(Object)
```

Update: There might be an issue with default content here.

**Comment by joewhitsitt** [comment]
Another weird thing is that I created a new page/published (e.g. node/7) in the stage workspace. The node because it needs to be revisionable is also created in the live version and is also published, but didn't have the url alias yet (e.g. /new-content) until I published the changes from the stage workspace. It is a page not found when using the alias path on the live site, but I can still get to it via node/7.

<img width="782" alt="Screenshot 2024-10-28 at 11 51 47 AM" src="https://github.com/user-attachments/assets/e19d9ce9-3eae-400b-ace6-b76ebcd668ee">

Update: trying to figure out the awkward relationship with content moderation

https://www.drupal.org/node/3087336

<img width="888" alt="Screenshot 2024-10-28 at 12 02 05 PM" src="https://github.com/user-attachments/assets/52df0b50-6015-43ca-adfd-5a86d1f36bf1">

Another example of this seems to be modifying an existing layout builder block like a card. if i change the text, even though i made the change in the stage workspace, in anonymous browser i see the change immediately.

**Comment by joewhitsitt** [comment]
- Certain forms can't be submitted outside the live workspace (e.g. revisions comparison)
- Adds further complexity to our revisioning setup. On the live environment I can delete the stage workspace revisions! Look ma! No revisions:

<img width="1074" alt="Screenshot 2024-10-28 at 2 14 54 PM" src="https://github.com/user-attachments/assets/e527eb39-96c1-4e91-8e58-be4b96513b65">

Update: Reminds me of https://github.com/uiowa/uiowa/issues/7753#issuecomment-2405560606. You can now create a revision of any taxonomy term edit (opt-in) and there is a UI. Masquerading as a webmaster, I can apparently see/interact with all this despite not having the necessary permissions..

**Comment by joewhitsitt** [comment]
I might need a second set of eyes poking at this, because it just doesn't seem to work as expected except for some basic modifications (node body edit but only before a layout builder edit overrides and publishes it).

Update: going to try a simpletestme instance to see what might be SiteNow specific and not just a compatibility issue with moderation.

Update: using a plain jane d10 install - workspaces without moderation worked as expected. adding in content moderation, any content marked as published in the staging environment is automatically published in the live environment.

**Comment by joewhitsitt** [comment]
Summary: I don't see an straight-forward solution that won't have gotchas or cause confusion between moderation and workspaces. Add to that, there are some items that probably need to be ironed out related to default content and node revision delete as well as generally thinking about revision strategy going forward for all of the content entities.

That said, I had troubles finding the original thread/ask of CLAS, but it seems like either bulk content moderation (existing functionality that they then track themselves) or staging content in STAGE/syncing seem like the best options we have available at this time.

**Comment by briand44** [comment]
Here is the original ask:

> We're working on making updates to all of the CLAS department websites—and a few program sites, too—that launched pre-my employment with CLAS in order to bring them all up to the same strategic approach as our more recently launched (the ones that launched in the last year and a half or so) CLAS department sites. While these are not as big of a lift as our D7 migrations were, there are definitely a lot of structural, content, taxonomy tagging, and imagery changes that need to be made, and the process for making these updates is definitely messier since we're working with live sites.
>  
> My question for you is—is it possible to pull a copy of the sites we're working on down into a production environment where we can make our updates that then can be pushed back to live after we're done? 
>  
> A few notes:
> We recognize we'd have to put a content freeze in place and we will coordinate that with the department, but may have some instances where they need to make high-priority/urgent updates on the live site, which we will then mirror on the prod site, in addition to our updates.
> We also will timebox our work and work in sprints (quasi-scrum/agile style) so that we can simplify the moving parts with sites moving into and out of prod environments.
>       ^^That's all to say this is even possible, and something your team is able and willing to do.
>  
> The sites included in this project are:
> [African American Studies](https://africanamericanstudies.uiowa.edu/)
> [American Studies](https://americanstudies.uiowa.edu/)
> [Native American and Indigenous Studies](https://nativeamericanstudies.uiowa.edu/)
> [Anthropology](https://anthropology.uiowa.edu/)
> [Cinematic Arts](https://cinematicarts.uiowa.edu/)
> [Classics](https://classics.uiowa.edu/)
> [Communication Sciences and Disorders](https://csd.uiowa.edu/)
> [Communication Studies](https://communicationstudies.uiowa.edu/)
> [Computer Science](https://cs.uiowa.edu/)
> [English](https://english.uiowa.edu/)
> [Ethics and Public Policy](https://ethicspublicpolicy.uiowa.edu/) (maybe — if not moving into philosophy)
> [History](https://history.uiowa.edu/)
> [Interdisciplinary Programs, Division of](https://interdisciplinaryprograms.uiowa.edu/)
> [Global Health Studies](https://globalhealthstudies.uiowa.edu/)
> [Interdepartmental Studies](https://interdepartmentalstudies.uiowa.edu/)
> [Latina/o/x/Studies](https://latinxstudies.uiowa.edu/)
> [Journalism and Mass Communication](https://journalism.uiowa.edu/)
> [Physics and Astronomy](https://physics.uiowa.edu/)
> [Political Science](https://politicalscience.uiowa.edu/)
> [Psychological and Brain Sciences](https://psychology.uiowa.edu/)
> [Social Work](https://socialwork.uiowa.edu/)
> [Sociology and Criminology](https://sociology.uiowa.edu/)
>  
> We are actively working on 10 of these sites (our public communication about this project, and the list of those 10 sites can be found on our [project page](https://resource.clas.uiowa.edu/marketing-communications/toolkit/websites/web-strategy-upgrades-project) on the CLAS Resource site) and will continue until they are all complete. We are at the point where we've figured out strategy for a couple (2-3ish) and are now working on figuring out our approach for build updates. Hence, my email as we're determining our options for coordinating these builds on live sites.

**Comment by pyrello** [comment]
> ack!
> 
> Tried to use the stage workspace to delete demo content like when we are setting up the intranet feature:
> 
> ```
> The website encountered an unexpected error. Try again later.
> 
> Drupal\Core\Entity\EntityStorageException: This content item can only be deleted in the Live workspace. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->delete() (line 763 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
> workspaces_entity_predelete(Object)
> ```
> 
> Update: There might be an issue with default content here.

Because the above produced an error, there is likely an issue with default content separately. However, it appears that the intended workflow is that content is only deleted from the live environment:

<img width="1401" alt="Screenshot 2024-10-31 at 10 21 01 AM" src="https://github.com/user-attachments/assets/3a1a3201-52a1-4001-ae14-8463e1611469">

That the system doesn't adjust all the actions/context menus to remove the delete option seems problematic. Seeming to give people the option to delete something only to tell them they can't seems like a really dumb UI. We could probably roll our own solution to this, but that would be extra work that doesn't provide the requested value.

This might matter less in a limited release of this feature set to just a subset of CLAS sites because we can just tell them this is a known issue, but this definitely is a blocker for rolling this out to the whole platform.

**Comment by pyrello** [comment]
> it seems like either bulk content moderation (existing functionality that they then track themselves) or staging content in STAGE/syncing seem like the best options we have available at this time.

@joewhitsitt Can you say more about how bulk content moderation could be used? Its not immediately obvious to me.

**Comment by joewhitsitt** [comment]
Just that they could make a bunch changes as draft/needs review state. Anything that comes up otherwise can be published immediately. when they are ready with their bunch-o-edits they can check all the items in the content overview and select publish latest revision (similar to p2lb). We could also update the moderation overview (admin/content/moderated) to include bulk operations and that specific operation allowing them to easily identify and select the content.

It would require tracking/auditing on their end to feel confident with blindly publishing in bulk.

**Comment by pyrello** [comment]
They would also need to be clear on a process for publishing urgent live edits to pages that have had edits made to a draft. There is still no way to keep those drafts changes in a draft state while publishing a new live version. I think it can be accomplished using the revision page and reverting to a previously published version, but we would probably want to test that workflow and provide clear guidance on how to do it successfully.

**Comment by joewhitsitt** [comment]
>There is still no way to keep those drafts changes in a draft state while publishing a new live version

That potential scenario/limitation might be where a "redesign" staging environment makes sense.

>We're working on making updates to all of the CLAS department websites—and a few program sites, too—that launched pre-my employment with CLAS in order to bring them all up to the same strategic approach as our more recently launched

In the potential future of SiteNow being upgraded in-place without migration (no d7->d8), eventually a lot of sites will go through a re-imagining/refresh similar to this. This happened within d7 quite a bit (rounds of development paired with content organization and a go-live). Though it wouldn't be the end of the world to do one-off syncing periodically, it would be nice to find a way to give site owners the tools to do this in-place if development work was not needed.

**Comment by pyrello** [comment]
> Though it wouldn't be the end of the world to do one-off syncing periodically, it would be nice to find a way to give site owners the tools to do this in-place if development work was not needed.

It sounds like there are potentially changes coming to workflow + workspaces that could make it a better solution down the road. If there are any situations we found to be confusing/not workable, it might be worth considering opening issues for them.

**Comment by joewhitsitt** [comment]
@mjoneill did Sean offer/setup a meeting with Maggie about this?

**Comment by joewhitsitt** [comment]
Sounds like Michael plans to talk with Maggie about this soon.

**Comment by briand44** [comment]
Closing this as the probe has been completed and I discussed the finding with Maggie and Brynne.
