### ISSUE TITLE
Unable to edit slider on default content home page

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#8214]
# Problem
If you clone https://medicinedermatology.prod.drupal.uiowa.edu's home page and try to add a slider to it.  The page cannot be edited. 

<img width="451" alt="Screenshot 2024-11-05 at 10 58 06 AM" src="https://github.com/user-attachments/assets/22bbca97-d485-4e7c-8207-2950a955e7e1">

# Steps to reproduce
- Clone https://medicinedermatology.prod.drupal.uiowa.edu's home page 
- Add Slider and save the page
- Edit the page and try updating the slider or any block on the page

# Proposed solution
- User reported that the error message is not displaying in Edge browser. 
- Possible upstream issue: https://www.drupal.org/project/drupal/issues/3416508.
- If you disable aggregation on prod, this error seems to go away.

**Comment by pyrello** [comment]
Users are now reporting this issue with the Edge browser.

**Comment by pyrello** [comment]
Mike from CLAS reported the same error occurring when editing an events block on the home page of https://stat.uiowa.edu/

**Comment by pyrello** [comment]
Seems related: https://www.drupal.org/project/drupal/issues/2755791

**Comment by briand44** [comment]
Grooming conversation.. May not be limited to the slider component as similar errors with events block https://github.com/uiowa/uiowa/issues/8214#issuecomment-2491889333. Could be related to aggregation. No reports yet for non-homepage pages that we are aware of.

**Comment by cory-skeers** [comment]
Patch from https://www.drupal.org/project/drupal/issues/2755791 does appear to work. The discussion on the issue is around how to approach this, as it adds `internal.jquery.form` as a core dependency, and core is actively working to deprecate and remove said dependency.

But it does get things working for now. Going to poke around and see if there's discussion anywhere else for a longer-term solution.
