### ISSUE TITLE
Reminder communication to SiteNow v1 custom sites that don't need custom development to migrate

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8240]
# Story

As a web team, we would like to remind SiteNow v1 custom sites that we believe don't need custom development that they should be working to transition their sites and they have a deadline of Aug 31st, 2025.

# Additional Info

As part of https://github.com/uiowa/uiowa/issues/7290, we identified sites and contacts and sent a communication (https://apps.its.uiowa.edu/dispatch/communications/1315926162) letting them know of the deadline they have to transition off of v1.

We should follow up with active v1 custom sites that we believe don't need development and provide a reminder to these folks of the deadline to transition.

```[tasklist]
### Proposed Solution?
- [x] use spreadsheet to identify active v1 custom sites that we don't believe need development
- [x] create communication
- [x] setup population and communication in Dispatch
- [x] send test to its-web
- [x] send to dispatch population
```

**Comment by briand44** [comment]
Maggie offered to help out with these comms.

**Comment by e-marie-w** [comment]
There were 30 sites in the last communication, we are now down to 20. (The spreadsheet shows 21, because while hso.research.uiowa.edu has launched on v3, the D7 site is still around. We have a reminder to check in with them in January.)

ubill.fo.uiowa.edu is in an odd situation. It will be replaced by billing.uiowa.edu, which has already launched. However, the homepage says under construction and links to ubill.fo.uiowa.edu, so I think we should still email them.

hawkeyespaces.uiowa.edu was in the original 30 that were contacted, but they are not in the remaining 20 as they plan to move their content to the main athletics website. I think it's worth sending a separate email to them checking in on if we can remove this yet, as the last spreadsheet update regarding the site was in June. 

Since all 20 remaining sites have requested a site, I'm thinking we can reuse most of the 'Finish transitioning your site' email we sent to the v1 standard sites previously.

**Comment by briand44** [comment]
@e-marie-w are sites like financialaid and law in your list of 20? Those have both launched as well but the v1 site still remains.

**Comment by e-marie-w** [comment]
> @e-marie-w are sites like financialaid and law in your list of 20? Those have both launched as well but the v1 site still remains.

Nope, it looks we started marking sites that were launched but not yet removed from D7 as 'Moved' for their D7 status. I can change hso.research.uiowa.edu to that. Do we want a list of those sites also? It looks like there's only about 6.

Edit: wait, we have more sites that have the v3 launched but d7 not yet removed and they are still marked as Active, should I change those to Moved as well or leave be?

**Comment by briand44** [comment]
Marie and I touched base on this and cleaned up the spreadsheet some more to get on the same page.

**Comment by e-marie-w** [comment]
We are down to 19 v1 custom->v3 standard sites:

- animal.research.uiowa.edu
- cgrer.uiowa.edu
- cmrf.research.uiowa.edu
- ehs.research.uiowa.edu
- fa.fo.uiowa.edu
- fmb.fo.uiowa.edu
- gao.fo.uiowa.edu
- govrel.uiowa.edu
- grantwood.uiowa.edu
- hawkeyecaucus.com
- intranet.pharmacy.uiowa.edu
- iowalionseyebank.org
- opsmanual.uiowa.edu (will launch at policy.uiowa.edu)
- tax.fo.uiowa.edu
- thelightbox.radiology.uiowa.edu
- treasury.fo.uiowa.edu
- ubill.fo.uiowa.edu
- vandervelde.studio.uiowa.edu
- worklife.uiowa.edu

**Comment by e-marie-w** [comment]
Population: https://apps.its.uiowa.edu/dispatch/populations/1375360573/configure. I copied the contacts from our original communication to this group and just removed the ones for launched/deprovisioned sites. I was going to cross-check with the spreadsheet list of contacts if I have the time, but I assume they should match.

**Comment by briand44** [comment]
@e-marie-w If I remember correctly, our original communication asked folks to request their v3 site. Now that they have, I am wondering if we should look at the users on the pre-production site and possibly include those in this comms if not already included. For example, fofa.prod.drupal.uiowa.edu, the Facilities team is helping transition these FO sites, so it may be good to include Lauren on these comms since she is the one transitioning the content. Thoughts?

**Comment by briand44** [comment]
Well fofa.prod.drupal.uiowa.edu was probably not a good example. Now that I look closer, I see Wendy is already included.

**Comment by briand44** [comment]
After reviewing the population more thoroughly, I feel pretty good about the existing contacts

**Comment by briand44** [comment]
I'd like to understand if there are any sites in this list that didn't get our previous communication. opsmanual possibly. Not sure if there are others but it would be good to understand

**Comment by e-marie-w** [comment]
> I'd like to understand if there are any sites in this list that didn't get our previous communication. opsmanual possibly. Not sure if there are others but it would be good to understand

Since I copied the list from that previous communication, I think they all should've gotten it. According to dispatch all the messages were delivered successfully.

**Comment by briand44** [comment]
>I was going to cross-check with the spreadsheet list of contacts if I have the time, but I assume they should match.

I did some cross checking with the spreadsheet and it checks out.

**Comment by mjoneill** [comment]
Yesterday when I read this it seemed fine.  

Then Acquia happened.

I am getting signals that Acquia is changing the terms of their D7 support commitment.  Curious if we should include some sort of language like, "Because we are on extended support, the longer into 2025 it takes to complete your migration, the more risk your site will face for outages, security vulnerabilities, etc..."

@briand44

**Comment by briand44** [comment]
I like the addition mentioned ^^

**Comment by cory-skeers** [comment]
> Yesterday when I read this it seemed fine.
> 
> Then Acquia happened.
> 
> I am getting signals that Acquia is changing the terms of their D7 support commitment. Curious if we should include some sort of language like, "Because we are on extended support, the longer into 2025 it takes to complete your migration, the more risk your site will face for outages, security vulnerabilities, etc..."

I like the addition of something like this. There have been responses in the past along the lines of "I looked at Drupal's website and support goes until XXXX," or with the recent file snafus requesting that we only upgrade D7 infrastructure if it's absolutely necessary in order to avoid service disruption, etc. I think the clearer it is that maintaining the old system is not guaranteed, easy, and without risk is good. There are definitely benefits to moving prior to the absolute last minute.

**Comment by e-marie-w** [comment]
Dispatch communication successfully sent!

**Comment by joewhitsitt** [comment]
@briand44 how do you want me to record responses from this email? Just update the notes in the Drupal 7 Sites spreadsheet?

**Comment by joewhitsitt** [comment]
I updated one of the contacts for a website (in the Drupal 7 Sites sheet) and replacing the individual in the dispatch population so they don't get another email later.

**Comment by briand44** [comment]
>how do you want me to record responses from this email? Just update the notes in the Drupal 7 Sites spreadsheet?

Yeah, that works if the responses are just "we plan to transition before the deadline". Obviously if they say they no longer plan to transition or we should be contacting someone else, there may be additional things that need to happen.
