### ISSUE TITLE
Intermittent issue with events block not being able to pull events

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#8255]
This was reported on https://uira.org.uiowa.edu/news-and-events/past-events-and-programs. I was able to observe the block displaying an error message of `Unable to fetch events at this time.`, which @joewhitsitt tells me is what happens when the timeout introduced in #8216 is triggered.

**Comment by pyrello** [comment]
Possibly related: #5618

**Comment by joewhitsitt** [comment]
Maybe related, maybe not, but Sean mentioned that the block didn't load the first time trying to open it. I had mentioned on the previous PR that I didn't touch the calls to the filters meaning they could also timeout and then the block doesn't like not having values. 

https://github.com/uiowa/uiowa/pull/8216#issuecomment-2462757345

>Unless we're hitting the point where the events DB is big enough that its slowing down queries just by its size - Sean

With the upgrade to ACN and keywords well over 2K on content hub I wonder if we are having issues we didn't originally.

**Comment by briand44** [comment]
Grooming conversation.... Currently there is a 10 second timeout. Is this something that should be increased? 20s? This particular events block is fetching past events which is an intense query. We've been resistant to making changes to Content Hub since it is being replaced but could make improvements on that end.

Splunk is showing some additional related errors https://splunk.its.uiowa.edu/en-US/app/search/search?earliest=%40w0&latest=now&q=search%20index%3Duiowa-acquia%20content.uiowa.edu%20%22Operation%20timed%20out%22&sid=1732047035.263840&display.page.search.mode=smart&dispatch.sample_ratio=1

It was mentioned we could revert the timeout and go back to how things were previously. There is some graceful fallbacks in place now as part of that though.

Sounds like we can start with testing increasing the timeout and do some local testing to see if that is helping eliminate most of the errors we are seeing in Splunk. If not we can try reverting the previous hotfix but keeping the graceful fallbacks.
