### ISSUE TITLE
file migration for instructional-resources.physics.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8285]
# Story

As a CLAS marketing team, we would like to have the files migrated from the D7 instructional-resources.physics.uiowa.edu website to the provisioned v3 website so that content editors can get this site transitioned quicker and do not have to spend time manually downloading and uploading their large assortment of media.

# Additional Info

>I am wondering if there is potential capacity to migrate the media between sites in a bulk way. I think they’d feel much less concerned about the timeline if they were able to focus on remaking pages rather than downloading and reuploading assets.

D7 site on UIClas - https://instructional-resources.physics.uiowa.edu/
v3 site on uiowa01 -https://physicsinstructional-resources.prod.drupal.uiowa.edu/

Not sure if we have migrated files for a site on the CLAS application. May run into some small bumps.

- doesn't look like that site is using media or file entity. Just core file enabled.

**Comment by cory-skeers** [comment]
Looks like the `d7_file` migration might "just work."

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/259fb6ce-dcf5-4e20-8bd1-7acc60da7755">

Caveat: There are 5420 files listed in the migration, and I ran it with a limit of 100, so there's plenty of space for failure down the line.

**Comment by cory-skeers** [comment]
> Looks like the `d7_file` migration might "just work."
> 
> <img alt="image" width="1315" src="https://private-user-images.githubusercontent.com/49074566/391709101-259fb6ce-dcf5-4e20-8bd1-7acc60da7755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNzM2MjQsIm5iZiI6MTczMzE3MzMyNCwicGF0aCI6Ii80OTA3NDU2Ni8zOTE3MDkxMDEtMjU5ZmI2Y2UtZGNmNS00ZTIwLThiZDEtN2FjYzYwZGE3NzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIxMDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNjQ3OWZiYTJhZjNmZmI4Njc5Y2NmMmM0YzE0YmQ4YTNhYmJjZjdlNjE5NzE2Mjk5YTNhMjcyYzIyNDM1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4igq6lCuMkRVdRp8Od8ssEA0jI8BRHxGGb1rnYokYlY">
> Caveat: There are 5420 files listed in the migration, and I ran it with a limit of 100, so there's plenty of space for failure down the line.

Ran the rest, and it was successful on 4747/5240 of the files. The 773 errored files were the result of 404 errors when attempting to retrieve the file.

**Comment by briand44** [comment]
Grooming conversation... Should be a Cloud Next to Cloud Next file migration (CLAS -> uiowa01) so hopefully no need to do the local option. Sounds like it would add value and not be too much additional work to provide files that errored as part of this. They may all be related as it appears it looks like they all have Maryland in the file name `University%20of%20Maryland%20QOTW%20Answer%20#363.pdf`. Was also mentioned that the errors could be bad encoding of `#`.

**Comment by cory-skeers** [comment]
> Edit: I think the quick and dirtyish solution here would be to add a line in `sitenow_migrate/src/Plugin/migrate/source/Files.php::prepareRow` like `    $row->setSourceProperty('uri', str_replace('#', '%23', $row->getSourceProperty('uri')[0]));`

> Edit2: https://www.drupal.org/project/drupal/issues/3259168

I poked at this a little bit more, and the first option here won't work. The regular url encoding happens after `prepareRow`, so if we process it to `%23` at that point, encoding further down the line processes the `%` and we end up getting `%2523` rather than the desired `%23`.

The second option looks like it'd work, and would require applying the patch and updating https://github.com/uiowa/uiowa/blob/main/config/features/sitenow_migrate/migrate_plus.migration.d7_file.yml prior to turning on the split for the site. I think we'd be fine committing this generally, but perhaps with that the quicker route for this task is to just apply the patch and make the change locally, run the migration, turn off the split, and sync up. (Though communication for a small freeze by the physics folks would need to made for this).

In either case, the general migration steps are
* `drush @physicsinstructional-resources.env config-split:activate sitenow_migrate`
* Update the form at /admin/config/sitenow/sitenow-migrate
* `drush @physicsinstructional-resources.env ms` see that the migration is registered and has 5k+ files ready to go
* `drush @physicsinstructional-resources.env mim d7_file`
* `drush @physicsinstrucitonal-resources.env config-split:deactivate sitenow_migrate`

**Comment by joewhitsitt** [comment]
i wish i could say this has gone swimmingly, but it seems to choke once added and only succeeds if I copy the difference to the uri process as well. going to do a gremlin check and try it again with just the `skip_hash_track: 1` change.

Update: oops. Bad copy/pasta i think.

**Comment by joewhitsitt** [comment]
Ran much better once I fixed the yaml file.. Sent an email to CLAS marcom to schedule a content freeze.

**Comment by joewhitsitt** [comment]
This migration was performed locally and synced up to production. Contacts have been notified. Waiting for review before closing.

**Comment by joewhitsitt** [comment]
Haven't heard of any issues.
