### ISSUE TITLE
Caching issues with Emergency endpoint

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8336]
With a focus on Signage, I believe similar to the CORS issue we ran into previously that is the new endpoint that is the problem. We should have probably compared this more to the old website, but I think we need to do more to adjust the cache related on this endpoint so that consumers hitting it must re-fetch.

`curl -I https://emergency.uiowa.edu/api/active`

I think we should test whether setting cache headers through an EventSubscriber or RouteSubscriber for this path has any effect and can make it through Varnish.

`$response->headers->set('Cache-Control', 'no-cache');`

I don't know if we could also inspect the varnish vcl file for uiowa702 to see if there were any special rules done for the v1 website.

ITS-ETS (osc-help) has offered to setup signage devices to test whether it is device/browser configuration with the signage install profile.

For reference:
https://github.com/uiowa/uiowa/pull/7698/files

**Comment by briand44** [comment]
>I don't know if we could also inspect the varnish vcl file for uiowa702 to see if there were any special rules done for the v1 website.

I'm pretty sure there were not.

**Comment by briand44** [comment]
Grooming conversation... It was reported that the Hawk Alert was showing up on Signage and had to reload uiowa.edu multiple times before showing. Also, Hawk Alert still showing on sites hours after closed. Suspected issue with the Emergency endpoint. We could try specific cache headers for endpoint path to get around Varnish. Old Emergency site has been deprovisioned but we think there is a backup if we needed to take a look. Something with the endpoint may be telling requests not to fetch. Based on previous CORS issue, we think endpoint is behind Varnish. Can we exclude this from Varnish?  Cache busting query parameters? Lets try and solve this issue as part of this slice.

**Comment by joewhitsitt** [comment]
Poking at this a bit more but hesitant to assign at this time as I will be out Mon/Tue of next week and this seems to be of high importance that it keeps moving.

From what I can tell the Purge/Acquia combo UI has changed quite a bit from D7 and doesn't provide any kind of mechanism to allow/deny list paths.

Since we want to first avoid a custom vcl file and we know from `curl -I https://emergency.uiowa.edu/api/active` that we get varnish cache hits, from what I've read we want to do some combination of the following:

- An EventSubscriber scoped to the path that sets `$response->headers->set('Cache-Control', 'max-age=30, public');`
  - My understanding is that this is the clearest message to Varnish not to cache this path too long.
  - Instead of no-cache because no-cache will really open us to DoS attacks on top of the fact that every SiteNow website and other websites are pinging this endpoint constantly. Apologies in advance if this change affects our views/loads pricing/costs with Acquia.
- Adding to that `$response->headers->set('Cache-Tags', '');` and `$response->headers->set('X-Drupal-Cache-Tags', '');` to make sure internally that Drupal isn't caching.
- Using a RouteSubscriber alterRoutes and set a no_cache on the JSON API route `$route->setOption('no_cache', TRUE);`
  - Similar to the cache-tags this is another attempt to prevent bubble down caching. 

We will want to test any changes we make in DEV where Varnish is setup, but like testing before, we shouldn't count on it being a mirrored experience to PROD. I've talked with Public Safety on the phone and they are okay with scheduling either a emergency website triggered alert or a rave cap (scoped to web) alert when the time comes to test.

**Comment by joewhitsitt** [comment]
Going to put together a PR with these ideas and send it out to DEV for some testing

**Comment by joewhitsitt** [comment]
Ack. Running out of time.

I think that https://github.com/uiowa/uiowa/pull/8340 is minimal enough to be sent out to PROD for more testing.

Originally I committed more, but I think we should start with the smallest amount and see if that is sufficient. The other commits could be re-added later if needed.

Communication with Public Safety and ITS-ETS has been happening in its-web. We can schedule a test with them to see if it changes anything.

**Comment by joewhitsitt** [comment]
I am realizing that while testing in production, it is necessary to curl with the https:// prepended. `curl -I https://emergency.uiowa.edu/api/active` otherwise our forced HTTPS redirect has a max-age of 1 year and is not properly clearing based on what we have pushed so far.

I am pretty sure Signage and SiteNow are both calling the endpoint with https:// but might explain some confusion from previous testing.

**Comment by joewhitsitt** [comment]
I hit the endpoint at the 28 second mark and there were over 400 cache hits. I am glad we have _some_ max-age on this otherwise the traffic would be a bigger issue.

**Comment by joewhitsitt** [comment]
Sent an email about scheduling a test

**Comment by joewhitsitt** [comment]
Another test, more mixed results. We got reports that it was showing on some signs. Haylee had to clear browser caches in order to get it to show. I had Brave and Chrome open. Leaving them open and untouched, Brave got the hawk alert on signage, chrome did not.

More Google searching is suggesting one of the following:

- Add `cache: false` to the ajax requests in Signage and SiteNow: https://stackoverflow.com/a/51511998
  - My understanding is that this is similar to a cache-busting timestamp at the end of the request path. 
- Add a `Last-Modified` header to the emergency.uiowa.edu code

My hope is that we can recreate the Chrome issue using DEV and make adjustments there instead of requesting another test right away.

**Comment by joewhitsitt** [comment]
Further reading suggests that ETag is more reliable than Last-Modified and that paired with max-age it should evaluate that before ETag leaving some kind of DoS buffer in place. Ultimately, to continue to keep the footprint small here, I wonder if the ajax cache false will be enough for now.

**Comment by joewhitsitt** [comment]
I still and may never have a good grasp of all of this, but because there were reports of different browsers having different results yesterday. I suspect that some users' browsers are still cached with the old headers and that is the issue with not fetching the alerts as they come up.

For example, the uiowa.edu homepage in my Chrome browser still reports a max-age of 1 month for the `active` call and is saying 200 OK (from disk cache). Where in Brave, it has the new cache header max-age of 30 and it slips between 200 OK (from disk cache) to just 200 OK with a reset age.

Even if it is temporary, we just need to make sure browsers aren't serving up stale data from before and fetching the new headers.

I just pushed out a change to develop that I think will work but I also think if we moved forward with cache and varnish clears on Signage and SiteNow, that should also solve the issue.

**Comment by joewhitsitt** [comment]
With the latest deployment, there was no change to Brian's browser window with a basic refresh, site/varnish clear, homepage save.

As I said to him, if the browser isn't aware of the 30-second max-age yet, it won't be seeing the must-revalidate just by that change alone, but we will be better positioned going forward.

Brian suggested instead of waiting things out that we think about the cache busting parameter, at least temporarily to the calls in signage/healthcare signage/v2 and 3. 

But because of the strict JSON api spec that is being followed, I think it needs to be something like `https://emergency.uiowa.edu/api/active?include=id`

At the same time I am playing around with recent purge module commands to see if they scratch deeper and it either cleared it for all apps or just browsers that had previously cached it on admissions because it also cleared the homepage for Brian in the same browser.. `cache:rebuild-external`

<img width="438" alt="Image" src="https://github.com/user-attachments/assets/07e79276-4781-40d0-a3de-ac845644f2f4" />

**Comment by joewhitsitt** [comment]
Replied to the thread in its-web that we are making progress but that could still be some stragglers and so in an effort to squash it all, that we would implement the cache busting parameters for signage/healthcare signage/v2 and 3.

I will work on putting those together.

**Comment by joewhitsitt** [comment]
Created `hawk_alert_endpoint_parameter` branches on Signage and Healthcare Signage with this change.

Pretty much mirrors the change in https://github.com/uiowa/uiowa/pull/8356

<img width="786" alt="Screenshot 2024-12-20 at 4 23 40 PM" src="https://github.com/user-attachments/assets/8fb4c8dd-1bb9-4826-9f6b-63638bb835cf" />

**Comment by joewhitsitt** [comment]
Sorry, adding a bit more detail to the why/what.

Certain browsers have a stored response with a max-age of 1 month. They don't see the max-age, must-revalidate and are not fetching new hawk alerts appropriately. We can wait out the old cache headers, but to do all that we can, this temporary endpoint change will force the scripts to fetch as new which will then get the max-age header from here on out. Because we don't know when those stubborn browsers might be used again, we should leave the tweak in place for the same amount of cache time before switching back to the bare endpoint.

As for detail about the endpoint change itself. The JSON API module follows a strict JSON spec and a random ?cachebusting parameter results in a 400 bad request. This alternative is just suggesting to include the ID property in the response if it isn't by default. No harm but on spec.

**Comment by joewhitsitt** [comment]
The temp endpoint tweaks rolled out today. Follow-up issue #8363 was created. I emailed the thread in its-web notifying them of the update. Suggested scheduling a periodic test to make sure things are still operating as expected. For now though, I think this issue can be closed.
