### ISSUE TITLE
XML sitemap using http://

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#835]
We should be using https:// for links for our sitemap.

**Comment by joewhitsitt** [comment]
Not 100% sure but this could be as easy as updating to the latest release:
https://www.drupal.org/project/simple_sitemap/releases/8.x-3.5

**Comment by richardbporter** [comment]
This is due to the fact that sitemaps are generated during cron runs and we do not pass the URI option during command execution.

https://github.com/uiowa/uiowa/blob/07931712ca7da769e7a3f319856ce82cbb0d2a75/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L47-L60

We could modify that but would need to test other functionality. Another option is to override the `simple_sitemap.settings.base_url` config similarly to the Acquia config override:

https://github.com/uiowa/uiowa/blob/fc1071363590f3cca7162051be60c4ce5ab57142/docroot/profiles/custom/sitenow/src/ConfigOverride/AcquiaConnectorOverride.php#L34-L47

We should figure out which is preferable. It may be the former.

**Comment by richardbporter** [comment]
BLT does pass the URI option automatically but without the scheme. I haven't seen any schemes included when using that option. I would vote for a config override.
