### ISSUE TITLE
Update SiteNow Migrate Uninstall?

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#836]
Is the sitenow_migrate_uninstall() still needed as is? Does it need to be updated based on the configuration moving to the profile config/sync directory?

I have updated the deprecated code in 53aeb880155f962a3ba4ac4e1addda6c64f406b4

@cory-skeers can you shed any light on this?

**Comment by cory-skeers** [comment]
@joewhitsitt tl;dr version: It needs to be updated to the new config location if we might use it as a base for custom migrations, otherwise it can be removed.


Once a migration group/entity gets registered with the core migrate module, to make any changes you need to remove the current config, uninstall the module, and reinstall with the new config.

It's not strictly needed anymore, but would be needed and updated based on the new config directory if the migrate module is used for a custom migration.

**Comment by cory-skeers** [comment]
There was also an effort to make migration definitions plugins instead of configs (largely https://www.drupal.org/project/migrate_tools/issues/2667368). From initial checking, looks like 1) migrations can be either configs or plugins but 2) migration_groups still need to be configs. If groups can be handled in plugins as well, then could get any of it needing to be in a config split.

**Comment by joewhitsitt** [comment]
This was removed: https://github.com/uiowa/uiowa/commit/1c8e17928ca1c53c9ced1c5807a89290881980fd#diff-6ddcd3967b6e0eed04c9a27513009f7e
