### ISSUE TITLE
Create pullquote block for LB use

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#943]

**Comment by pyrello** [comment]
Our current iteration of P2LB (#1976) converts pull quotes into text areas. If we truly want to pursue this as an option, we may want to consider doing it prior to launching the conversion tool, otherwise, we will likely lose the ability to know that something was intended to be a pull quote vs intended to be a text area.

**Comment by bspeare** [comment]
Closing in favor of https://github.com/uiowa/uiowa/issues/2881.
