### ISSUE TITLE
Differences between Rich text and Filtered HTML text formats??

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#970]
What are the differences (if any) between these formats? Do we need to add toolbar features to Rich text?

Here is what the Rich text format looks like in its current state:
![Screen Shot 2020-01-03 at 2 07 41 PM](https://user-images.githubusercontent.com/3067017/71747488-691eec00-2e35-11ea-8141-f36e05b22452.png)

Here is what the Filtered HTML format looks like in its current state:
![Screen Shot 2020-01-03 at 2 07 48 PM](https://user-images.githubusercontent.com/3067017/71747517-7936cb80-2e35-11ea-8b66-54b0c198dad1.png)

Also, the ability to embed Media is not allowed in Filtered HTML. Here is a screenshot of what Rich text allows for media embeds:
![Screen Shot 2020-01-03 at 2 23 08 PM](https://user-images.githubusercontent.com/3067017/71747405-2826d780-2e35-11ea-93f8-96182fa8029f.png)

**Comment by mark-bennett-uiowa** [comment]
@pyrello @bspeare @richardbporter @joewhitsitt 
I have updated the Filtered HTML and the Full HTML formats based off the latest update to Master. I have attached the two .yml files for these updates. It appears these files exist in multiple locations and I will defer to your expertise on how you want to handle this:
/config/<sitename>/filter.format.filtered_html.yml
/docroot/profiles/custom/collegiate/config/install/filter.format.filtered_html.yml
/docroot/profiles/custom/sitenow/config/sync/filter.format.filtered_html.yml
and the same as above for filter.format.full_html.yml.

[filter_formats.zip](https://github.com/uiowa/uiowa/files/4269476/filter_formats.zip)

I did end up removing the "Limit allowed HTML tags and correct faulty HTML" for the Full HTML format, but now Im second-guessing the choice.

Also, I wanted to recommend a few additional modules that we might want to add to the profiles:

- Editor Advanced Link (https://www.drupal.org/project/editor_advanced_link) - For additional link attributes, like Title, Class, Target, Rel, and ID.
- CKEditor Anchor Link (https://www.drupal.org/project/anchor_link) - Anchors are included by default like they were in D7.

Im sure there are things that need to be removed or tweaked, but this looked like a close, better version of what we setup for D7. For instance:

- I removed the ability to add figure, form, fieldset, input, button, video and iframe tags from one or both of the formats.
- Not 100% sure how we wanted to handle media uploads and display of media elements.
- How did we want to handle moving existing fields from Rich Text to Filtered HTML.

**Comment by pyrello** [comment]
Here is an attempt to update this issue, given recent changes.

The base filter formats that we are working off of are the formats from SiteNow:
* https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/config/sync/filter.format.filtered_html.yml
* https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/config/sync/filter.format.full_html.yml

Any suggestions for modifications should use those as a starting point. To see them in actual use, you can spin up a local version of https://demo.sitenow.uiowa.edu.

In the homepage project, we have made some modifications to the formats and their associated editor instances that allow us to incorporate some of the work we did in Collegiate. Specifically, they use the Media Library for media embeds, and use responsive images for image embeds.

SiteNow cannot immediately switch over to using the Media Library embed button because it uses a different embed tag: `<drupal-media>` instead of `<drupal-entity>`. For them to make that jump, they'll need some sort of update process.

You can see the overridden config files in uiowa.edu here: https://github.com/uiowa/uiowa/tree/master/config/uiowa.edu

SiteNow is already using Editor Advanced Link (for Filtered and Full formats). I would be up for adding the Anchor Link module, but we would want to seek input from the SiteNow team.

**Comment by pyrello** [comment]
I think that this issue can be closed. To summarize, we are moving forward on a path when the collegiate profile will be deprecated in favor of SiteNow + a Collegiate split (or some other as yet to be developed config split). Therefore any modifications to filter formats or editors should be made to either the SiteNow profile or one of the relevant splits.

Please reopen if you think this is still relevant.
