### ISSUE TITLE
Monthly articles archive in reverse order

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#987]
Monthly archive in reverse order ITI.Prod.drupal.uiowa.edu.

**Comment by joewhitsitt** [comment]
I think what happened was that I fixed the monthly archive view config for new sites, but old sites didn't get the fix since that view is ignored. It is ignored so that site owners can modify (hide the display, add/remove the feed icon, change title/path). Either an update hook is needed to update the sort config on the monthly archive block or we just fix in PROD them as we hear about them.

**Comment by joewhitsitt** [comment]
Going to confirm my fix is in the default and then update iti.prod

**Comment by joewhitsitt** [comment]
Fix is in the default and I update iti.prod https://iti.prod.drupal.uiowa.edu/news

I will create a known issue on the sitenow website, but all I did to resolve was turn on views ui, go to the articles view, click the block display (monthly archive), modify the contextual filter to sort as descending and save. turn off views ui. ??? profit!

**Comment by joewhitsitt** [comment]
https://sitenow.uiowa.edu/known-issues#uiowa-issues-987
